### ISSUE TITLE
MIGRACIÓ: Estudi situació actual migració de tràmits SISTRA1 a SISTRA2

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#1]
Analitzar la situació actual a nivell de tràmits suportats per SISTRA1:
- Tràmits actius
- Tràmits actius que no acaben en registre
- Tràmits amb circuit reduit
- Tràmits amb processament per part del backoffice
- Formularis de tràmits actius per versió de FORMS: v1, v2, ...
- Formularis de tràmits actius amb components avançats (arbres, llistes d'elements, cpatcha)

**Comment by amaciam-indra** [comment]
[Datos_Trámites_Producción.xlsx](https://github.com/GovernIB/sistra2/files/1686705/Datos_Tramites_Produccion.xlsx)

**Comment by sgelabert-dgtic** [comment]
Podeu afegir a la Issue les consultes SQL per generar l'Excel

**Comment by amaciam-indra** [comment]
[Consultes_migracio_SISTRA2.zip](https://github.com/GovernIB/sistra2/files/1736648/Consultes_migracio_SISTRA2.zip)
