### ISSUE TITLE
MIGRACIÓ: Definició d'estratègia de migració de formularis

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#10]
Completar document amb l'estratègia de migració de tràmits entre les plataformes SISTRA1 i SISTRA2. El document haurà de descriure:
- Anàlisi de la migració de formularis 
- Estudi de la viabilitat del mantenir el processament actual de tràmits.
- Estudi dels procediments que generen notificacions electròniques.
- Determinar abast de la nova zona personal.

**Comment by rsanz-indra** [comment]
Se ha actualizado documento según lo comentado en la reunión aunque falta por recibir el acta de la misma. Se han marcado los temas pendientes que quedarían por revisar.

**Comment by jsastre-dgtic** [comment]
Al document penjat a la Wiki "DGDT_Migracion_tramites_SISTRA1-SISTRA2", observam:
Pàg. 7- SISTRA1 se pondrá en funcionamiento con unas funcionalidades básicas por lo que algunos trámites deberán esperar a ser migrados conforme se vayan incorporando.  **-->On posa SISTA1 hauria de dir SISTRA2**
Pàg. 8- Revisión de trámites de tipo Bandeja que deberían ser de tipo Registro **--> Tots els PA, només poden obviar el registre Serveis.**
Pàg. 9- Se migrará la descripción del trámite. Esta descripción se usará a nivel interno dentro del Gestor de Trámites, a nivel del asistente se usará la descripción del trámite de Rolsac. **--> Tant a nivell de gestor com d’assistent, convé homogeneïtzar amb la mateixa descripció de rolsac. S’hauria de migrar com a comentari o camp auxiliar modificable. La descripció oficial a SISTRA2 ha de ser la mateixa que a rolsac.**
Pàg. 10- **No s’han de migrar les versions. Tot el que es migri a sistra2 serà v1 agafant només com a bona la darrera versió existent a sistra1.** 
Pàg 20 - “Identificación única de campo dentro del formulario” i “Migración de páginas de formulario” **Ok, però què passa si no tenim FORMS multipàgina?**

**Comment by amaciam-indra** [comment]
A continuació es contesten en negreta els diferents punts:
Pàg. 7- SISTRA1 se pondrá en funcionamiento con unas funcionalidades básicas por lo que algunos trámites deberán esperar a ser migrados conforme se vayan incorporando. -->On posa SISTA1 hauria de dir SISTRA2
**S'ha corregit aquest tema a la darrera versió comitada**

Pàg. 8- Revisión de trámites de tipo Bandeja que deberían ser de tipo Registro --> Tots els PA, només poden obviar el registre Serveis.
Se daba por supuesto ya que los de tipo servicio se iban a pasar como trámites personalizados,  pero se ha indicado explícitamente en el documento. 

Pàg. 9- Se migrará la descripción del trámite. Esta descripción se usará a nivel interno dentro del Gestor de Trámites, a nivel del asistente se usará la descripción del trámite de Rolsac. --> Tant a nivell de gestor com d’assistent, convé homogeneïtzar amb la mateixa descripció de rolsac. S’hauria de migrar com a comentari o camp auxiliar modificable. La descripció oficial a SISTRA2 ha de ser la mateixa que a rolsac.
**El mecanisme de migració és independent del catàleg de procediments de l'entitat (ROLSAC en cas CAIB), però a la darrera versió del document s'ha introduit una referència concreta a CAIB perquè en aquest cas es migri la dada**

Pàg. 10- No s’han de migrar les versions. Tot el que es migri a sistra2 serà v1 agafant només com a bona la darrera versió existent a sistra1.
**El procés de migració serà unitari per versió de tràmit, per tant s'haura de seleccionar de manera individual les versions de tràmits a migrar. No se planteja un procés conjunt de migració de tots els tràmits. Per tant, s'hauràn d'avaluar les versions de tràmits que es migran**

Pàg 20 - “Identificación única de campo dentro del formulario” i “Migración de páginas de formulario” Ok, però què passa si no tenim FORMS multipàgina?
**Com s'indica a la pàgina 3 del document, el procés de migració serà posterior a la posada en funcionament de SISTRA2, pel que s'assumeix que estaran disponibles les funcionalitats per poder dur a terme aquest procés.**

**Comment by jsastre-dgtic** [comment]
tot perfecte, però el darrer punt no l'acabam de veure clar... Comptant amb la unicitat dels camps preveieu migrar totes les pàgines a una? Quines funcionalitats exactament estaran disponibles?
