### ISSUE TITLE
STH: Funcionalitat de recerca d'esdeveniments i operativa ROLS 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#108]
1.- Si posam la data d'ahir no troba res:
![image](https://user-images.githubusercontent.com/18436867/53729198-d9a35800-3e74-11e9-9aa0-7d6befc48ca2.png)

2.- En canvi si ens remuntam a febrer si:
![image](https://user-images.githubusercontent.com/18436867/53729141-b9739900-3e74-11e9-9c62-3b40085dc2b0.png)
Necessitam que les columnes siguin clicables per ordenar per data, per exemple.

**Comment by jsastre-dgtic** [comment]
3.- TAMBÉ HEM OBSERVAT QUE AMB ELS ROLS:
![image](https://user-images.githubusercontent.com/18436867/53882609-14dd8c80-4017-11e9-8252-417717c976c5.png)
NO VEIEM L'ENTITAT NI L'ÀREA A LA CAPÇALERA. NO TOCARIA SORTIR?
![image](https://user-images.githubusercontent.com/18436867/53882670-448c9480-4017-11e9-8e3c-413ff822788f.png)

**Comment by jsastre-dgtic** [comment]
Amb els rols:
![image](https://user-images.githubusercontent.com/18436867/53882950-03e14b00-4018-11e9-8f98-c5f345ee3c71.png)

No veiem ni Entitat ni Àrea al mòdul de HELPDESCK
![image](https://user-images.githubusercontent.com/18436867/53882976-178cb180-4018-11e9-8050-5c56e6f1c990.png)

i a SISTRAGES ho tenim definit així:
![image](https://user-images.githubusercontent.com/18436867/53883009-2bd0ae80-4018-11e9-9112-deffa92e606d.png)

**Comment by rsanz-indra** [comment]
Hemos verificado el funcionamiento y sí que nos recupera los eventos asignando el role al área.
Lo que hay que tener precaución es que al asignar los roles en Seycon hay que esperar un rato (creo que por defecto estaba en 30 min) o bien reiniciar el servidor.  ¿Habéis vuelto a probar? 
Estaría bien que nos creaseis un usuario con rol STH_OPE y permisos sobre el área de Tests para poder probar en el entorno de desarrollo.

Por otro lado, revisando los correos acerca de roles he visto un role que no hemos contemplado. En uno de los correos se hablaba del role STH_SUP que permitía supervisar todas las áreas de una entidad (sería el equivalente para el STH al STG_ADM del STG). Revisad si es necesario para ver si hay que implementarlo (sería definir en la pantalla de definición de la entidad un nuevo role de supervisión tal como se define el role de administrador de entidad).

**Comment by rsanz-indra** [comment]
Se recibe confirmación por parte de la DGTIC de implementar el role STH_SUP.

**Comment by jsastre-dgtic** [comment]
Acabam de comprovar que passen coses molt misterioses: 
Tant amb firefox com en Chrome, la primera vegada que posam usu-pwd, falla i diu que no té rol. 
La segona vegada entra. 

Això només passa amb SISTRAHELP, amb SISTRAGES no ens passa.

**Comment by jsastre-dgtic** [comment]
Tot ok i comprovat
