### ISSUE TITLE
STT: Annexar doc firmat

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#109]
Hem intentat annexar un document firmat (amb autofirma: csig) i no va bé:
2019-03-04 13:22:10,258 ERROR [org.jboss.as.ejb3.invocation] (default task-38) WFLYEJB0034: Invocación EJB falló en el componente FlujoTramitacionServiceBean para el método public abstract es.caib.sistramit.core.api.model.flujo.DetalleTramite es.caib.sistramit.core.api.service.FlujoTramitacionService.obtenerDetalleTramite(java.lang.String): javax.ejb.EJBException: es.caib.sistramit.core.api.exception.FlujoInvalidoException: El flujo no es válido
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.handleExceptionInNoTx(CMTTxInterceptor.java:213)

**Comment by jsastre-dgtic** [comment]
Haurien de poder coexistir les 2 opcions, al final ens interessa un doc firmat... 
![image](https://user-images.githubusercontent.com/18436867/53733380-17a67900-3e81-11e9-87c1-2996a9258766.png)

**Comment by jsastre-dgtic** [comment]
Postposam la tasca.
Indra diu:
La validación de un documento anexo firmada todavía no está implementada, y de ahí que no se haya indicado que se validara esta funcionalidad. Pensad que estamos a la espera de la adaptación del plugin de validación de firma por parte de la Fundación Bit.

**Comment by jcerdar-indra** [comment]
- Se realizará un documento de análisis y estimación para esta tarea.

**Comment by jsastre-dgtic** [comment]
S'aprova el document d'anàlisi i es dóna llum verda per començar la tasca

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Cuando el trámite está configurado con las siguientes opciones de firma, aparece un mensaje si se intenta adjuntar un documento ya firmado y se firma con el asistente como hasta ahora.

![image](https://user-images.githubusercontent.com/67064375/206710048-32af8c92-4aee-4f36-8509-721890278527.png)
![image](https://user-images.githubusercontent.com/67064375/206710070-8aee3379-d0ab-425d-829f-72a2ba0b20ec.png)

Si se utiliza esta configuración muestra el mensaje para explicar la casuística de la firma y permite adjuntar documentos firmados (con sello de tiempo o sin él) y también permite firmar correctamente con el asistente si no se anexa documento firmado.

![imagen](https://user-images.githubusercontent.com/67064375/206853822-a92c7420-fc4e-4014-995a-1d3c07601581.png)
![imagen](https://user-images.githubusercontent.com/67064375/206853835-76fed6d3-702a-4f38-921a-8cc64e4e6ba5.png)
![imagen](https://user-images.githubusercontent.com/67064375/206853838-812f3c48-62e0-4458-89b5-b114bfeb454e.png)

Si se utiliza esta configuración muestra el mensaje para explicar la casuística de la firma y permite adjuntar documentos firmados (con sello de tiempo o sin él).

![imagen](https://user-images.githubusercontent.com/67064375/206853898-305e1dbb-1595-461f-bc07-fc43207a91f3.png)
![imagen](https://user-images.githubusercontent.com/67064375/206853885-2914d555-cde4-4d19-b12f-a64a98a9b4fa.png)
![imagen](https://user-images.githubusercontent.com/67064375/206853910-26a4c768-50e3-4d95-b0e1-4f3108e18fbf.png)

**Comment by jsastre-dgtic** [comment]
tindrà que fer-ho --> haurà de fer-ho

![image](https://user-images.githubusercontent.com/18436867/207251090-1b8ad7f7-9500-489d-93a9-4aa3a2d7db85.png)

**Comment by jsastre-dgtic** [comment]
Almenys heu de signar un usuari --> Almenys ha de signar un usuari
![image](https://user-images.githubusercontent.com/18436867/207254437-a5284814-7ad7-41c6-84ff-dc7d1d91f88b.png)

**Comment by jsastre-dgtic** [comment]
Tot i firmar amb el mateix dni que amb el que ens autenticam, falla la comprovació

![image](https://user-images.githubusercontent.com/18436867/207289134-e7367100-11f8-40e5-a743-0b092b08e285.png)

![image](https://user-images.githubusercontent.com/18436867/207289567-09a2701d-c8a5-4946-9f3d-f89989f2f5b2.png)

**Comment by jsastre-dgtic** [comment]
Aquesta és la configuració provada

![image](https://user-images.githubusercontent.com/18436867/207289778-7326204c-33cf-438b-9bc5-5c2b77b3ab19.png)

**Comment by jsastre-dgtic** [comment]
Solucionat el problema de firmar amb autofirma posant sistramit.anexos.anexoFirmado.PADES_LTV a false. No té sentit exigir al ciutadà segell de temps per als docs firmats que annexi.

**Comment by jsastre-dgtic** [comment]
A partir del desplegament urgent de la 1.4.1, el tipus documental del "Fitxer tècnic intern" que arriba a RW3 (el del Formulari Sistra2), va passar de ser Sol·liucitud a definir-se com a "Altres". Aquesta issue és la responsable. la reobrim.

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

**Comment by jsastre-dgtic** [comment]
No veim que funcioni res:

Posem el que posem aquí, no canvia STT (fins i tot hem provat de marcar els dos checks...)

![image](https://user-images.githubusercontent.com/18436867/217765853-3f2c5d30-131f-401d-8416-a1488dae1375.png)

Tot segueix com abans, quan s'havia de firmar, no annexar firmat.

![image](https://user-images.githubusercontent.com/18436867/217765595-5e45368a-3456-4f44-b5c8-ed8907c51529.png)

**Comment by jsastre-dgtic** [comment]
Tot comprovat, però:
Si s'intenta adjuntar un document sense firma, es podria detectar enlloc de pressuposar que la firma és errònia (quan en realitat no s'ha firmat)?
![image](https://user-images.githubusercontent.com/18436867/217808071-1de92b49-8f33-4729-8a76-fe93938bacb4.png)
