### ISSUE TITLE
STG: Millores desitjables a SISTRAGES 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#110]
1.- Possibilitat de fer "paste" als camps de les pantalles "disseny formulari"
![image](https://user-images.githubusercontent.com/18436867/53957007-85e77780-40dd-11e9-8d1b-d0de84bfae27.png)

2.-Incloure el botó de ping a la pantalla d'edició dels dominis:
![image](https://user-images.githubusercontent.com/18436867/53957085-bdeeba80-40dd-11e9-902c-52f8d03f625f.png)

3.- Al crear manualment una nova versió d'un tràmit, quedàs per defecte bloquejat per l'usuari que ha realitzat l'acció.
![image](https://user-images.githubusercontent.com/18436867/53957102-cd6e0380-40dd-11e9-9436-e64596b7d66b.png)

**Comment by rsanz-indra** [comment]
Por mantener una sola issue sobre mejoras de STG que no se consideran críticas, se puede consolidar todo en la #78 ?
En todo caso, podéis indicar las mejoras que se consideran más prioritarias. Se irán atendiendo en función de la disponibilidad y de la complejidad.

**Comment by jsastre-dgtic** [comment]
Tancam la 78 i obrim aquesta amb les dades actualitzades:

**4.- Afegir botó de refresc en la capçalera** per actualitzar la informació d'accés

**5.- En les finestres modals convindria canviar el títol en funció de l'acció.** 
Per exemple, si botó "Editar" --> "Edició d'Entitats", si botó "Nou" --> "Alta d'Entitat".

**6.- Permetre limitar l'accés a tràmits d'una àrea per al rol desenvolupador.** 

**7.-La molla de pa ha d'actuar sobre cada element:**
Quan s'entra en la pantalla de definició de versió ha de marcar l'opció per defecte "Propietats"
La versió del tràmit ha d'enllaçar a la pantalla de tràmits amb la versió seleccionada

**8.- Presentar proposta per traduir automàticament** català/castellà els camps de descripcions

**9.- No canviar el coloret del “Vist”** quan tenim seleccionada la fila. Ara canvia de blanc a groc. Deixar el blanc per evitar confusions del que vol dir. Aplicar-ho d'aquesta manera a tota l'aplicació.

**10.- Millores missatges emergents (growl).** 
"No té sentit treure un missatge emergent que desapareix abans de poder-lo llegir. Fent feina amb SISTRAGES, aquests missatges poden ser molestos perquè es posen damunt el botó que vols pitjar i has d'esperar a que se'n vagi l'emergent."

**11.-** Revisar totes les pantalles a nivell de **correcció lingüística** i el respectar l'opció d'idioma triada.

**12.- Establir signants:** 
Actualment el funcionament dels signats és que hauran de firmar tots els que es fixin per script. L'opció de fer que un document hagi de ser signat per un signat o altre no està contemplat. Contemplar-ho com a millora.
https://github.com/GovernIB/sistra2/issues/78#issuecomment-460927194

**13.- Revisió funcionalitat / ús de formatadors:**
**a.** A la pantalla "formatadors de formulari", un administrador de entitat podrà establir un dels formatadors existents com per defecte. A més s'establiran unes plantilles per defecte per al formatador.
**b.** S'habilitarà, a nivell de configuració importants, un check al formatador que indiqui si el formatador pot configurar-se a nivell de versió de tràmit. Amb aquest check s'evitarà que la configuració d'un formatador pugui personalitzar a nivell d'una versió de tràmit, mantenint així una configuració única a nivell d'entitat.

**Comment by jsastre-dgtic** [comment]
14.- Poder seleccionar múltiples camps (amb shift/crtl) per a canviar una propietat comuna (p.e. Obligatori) o per Copiar-los i aferrar-los a una altra secció/pàgina del Formulari.
![image](https://user-images.githubusercontent.com/18436867/54030281-6028a400-41ab-11e9-92f2-b0f8c9818552.png)

**Comment by jsastre-dgtic** [comment]
15.- Quan s'afegeix una línia nova on ja hem hagut de fer "scroll", torna a dalt de tot, fent que on es vol posar el nou camp desaparegui i obliga a tornar fer l'scroll.... Modificar aquest comportament
![image](https://user-images.githubusercontent.com/18436867/54030523-2b691c80-41ac-11e9-9ad3-b5d16c219f2b.png)

**Comment by jsastre-dgtic** [comment]
16.- Possibilitat de fer visible un camp dependent del valor d'un altre camp:
![image](https://user-images.githubusercontent.com/18436867/54109269-7d918400-43de-11e9-8f90-8b715ecc209d.png)

**Comment by jsastre-dgtic** [comment]
17.- Podríem fer una cosa així?
Detectar si ens posen un NIF i canviar obligatorietat del camp llinatge. Si ens posen DNI continua sent obligatori
![image](https://user-images.githubusercontent.com/18436867/54124379-86944c80-4402-11e9-8680-1aa58473b4bd.png)

**Comment by jsastre-dgtic** [comment]
18.- No veiem com canviar Actiu/No actiu:
![image](https://user-images.githubusercontent.com/18436867/54189495-38d71d00-44b2-11e9-8964-ef55deb44c94.png)

**Comment by jsastre-dgtic** [comment]
19.- Incloure botó "Bloquejar" a la pantalla de Definició de Versió:
![image](https://user-images.githubusercontent.com/18436867/54189682-97040000-44b2-11e9-91fb-b53c59c87af0.png)

**Comment by jsastre-dgtic** [comment]
Per noltros són prioritaris tots els punts esmentats llevat de:
5,8,11
Els punts 4 i 6 s'haurien d'aclarir què volen dir exactament abans de valorar-los.

**Comment by jsastre-dgtic** [comment]
Indra diu (comprovat): Se han llevado a cabo los cambios siguientes a nivel de lógica de servidor (puntos 2 y 3 del comentario https://github.com/GovernIB/sistra2/issues/110#issue-418286781): 

	- Al crear una versión, se bloquea automáticamente por el usuario que lo crea y además lo añade como una línea extra en el historial.
	- Se ha incluido botón de ping a la ventana de edición de dominios

**Comment by rsanz-indra** [comment]
Respecto a la aclaración de los puntos:
_4.- Afegir botó de refresc en la capçalera per actualitzar la informació d'accés_
Nos solicitastéis esta funcionalidad para refrescar la información de acceso (entidad, acceso áreas,...) en el STG. Esta información se cachea al inicio de sesión para optimizar. La idea era de meter una opción que permitiese refrescar esta información sin tener que reiniciar sesión.
_6.- Permetre limitar l'accés a tràmits d'una àrea per al rol desenvolupador._
No recordamos que nos pedisteis acerca de esto...

Parece que se ha quedado de indicar la mejora de "recordar" el perfil con el que se había accedido a STG (superadministrador, administrador entidad o desarrollador) para que la siguiente vez que se accediera a STG se iniciara con el último perfil. Esto venía bien cuando un usuario disponía de varios perfiles. Ya nos comentáis si consideráis necesario esta funcionalidad.

Como mejora adicional proponemos la introducción de un editor WYSGYG (como TinyMCE) para la edición de literales de tipo HTML (similar a lo que tiene ROLSAC para editar contenido HTML) que permita limitar y asistir el contenido HTML que se puede introducir.

**Comment by jsastre-dgtic** [comment]
19.- Importació-Exportació de tràmits: Implementar que des de la pantalla de verificació es pugui accedir a l'element en qüestió per modificar.

**Comment by jsastre-dgtic** [comment]
20.- "Recordar" el perfil amb el qual s'ha accedit a STG (superadministrador, administrador entitat o desenvolupador) perquè la següent vegada que s'accedeixi a STG s'iniciï amb l'últim perfil.

**Comment by jsastre-dgtic** [comment]
17.- Dividim la tasca en 2: En aquesta issue deixam "disposar de funcions de validació dels diferents documents identificatius". La resta (ampliació de dades de sessió a poder gestionar en els tràmits, mitjançant la recollida d'informació addicional de la resposta de Cl@ve), la passam al projecte LOGINIB ( https://github.com/GovernIB/LOGINIB/issues/8#issue-420877993 )

**Comment by jsastre-dgtic** [comment]
21.- Pantalla "Missatges d'Avís Entitat", fer  graella amb la llista de tràmits amb un botó d'afegir i treure.
En lloc que aparegui una llista de codis que aparegui una graella amb la llista de tràmits amb un botó d'afegir i treure (el botó afegir et mostraria un selector de versions amb un cercador). 
Té els avantatges que ofereix més informació visual (identificador i descripció tràmit) i també podríem aïllar davant canvis d'identificador dels tràmits.

**Comment by jsastre-dgtic** [comment]
22.- Introducció d'un editor WYSGYG (com TinyMCE) per a l'edició de literals de tipus HTML (similar al que té ROLSAC per editar contingut HTML) que permeti limitar i assistir el contingut HTML que es pot introduir.

**Comment by jsastre-dgtic** [comment]
https://github.com/GovernIB/sistra2/issues/110#issuecomment-472337171

Al crear una versión, se bloquea automáticamente por el usuario que lo crea y además lo añade como una línea extra en el historial.

Això és correcte, però hauria de quedar el desplegable de versions a la vista o quasi millor entrar en l'edició de la versió. El que no pot passar és tornar al punt de partida de la pantalla amb les versions de tots els tràmits ocultes i el focus a dalt de tot. Hauria d'obrir directament aquí:
![image](https://user-images.githubusercontent.com/18436867/54344497-47a00a00-4641-11e9-8942-f6383bbb30f9.png)

**Comment by jsastre-dgtic** [comment]
23.- Al modificar la  mida de la pantalla d'scripts, no hi surt la barra d'scroll, quedant els botons d'acceptar cancel·lar, esborrar i ajuda fora de la vista fins que es torna modificar mida de manera adient. Fer que sempre siguin visibles.
![image](https://user-images.githubusercontent.com/18436867/54600454-1d818a00-4a3d-11e9-8811-7404f76be151.png)

**Comment by jsastre-dgtic** [comment]
Els següents punts estan comprovats i funcionant:
1-2-3-4-7-11-13-18-19-20-21-22-23. Els que queden els passam a una nova issue per major claredat. 
Veure:
https://github.com/GovernIB/sistra2/issues/117#issue-422679728
