### ISSUE TITLE
STG: Adaptacions Diverses (1a FASE)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#113]
- Incloure funcionalitat de formatador per defecte per a l'entitat https://github.com/GovernIB/sistra2/issues/107#issuecomment-469575239
- Pantalla configuració entitat: desglossar configuració assistent en un pestanya
- Permetre esborrar literals opcions
- Controlar mida nom entitat a mostrar perquè no es desquadrament la capçalera https://github.com/GovernIB/sistra2/issues/107#issuecomment-469575239

**Comment by jsastre-dgtic** [comment]
Permitir borrar literales opciones: Que quedi dins la pantalla d'edició.

**Comment by jsastre-dgtic** [comment]
No funciona el formatador per defecte.

**Comment by jsastre-dgtic** [comment]
S'han d'incloure les plantilles en forma d'arxiu .properties al formatador. Ja hem comprovat que funciona.
Només quedaria quedar a la pantalla d'edició en esborrar "literals opcions".

**Comment by rsanz-indra** [comment]
Respecto a las 2 últimas incidencias entendemos que ya están resueltas:
- Ya se ha configurado el logo formateador en entorno CAIB
- Se ha explicado el funcionamiento del botón de borrar un literal (es para eliminar un literal, no para "vaciar" el contenido de los literales)
