### ISSUE TITLE
STG: Millores desitjables a SISTRAGES (FASE II)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#117]
**1.- No canviar el coloret del “Vist” quan tenim seleccionada la fila.** 
Ara canvia de blanc a groc. Deixar el blanc per evitar confusions del que vol dir. Aplicar-ho d'aquesta manera a tota l'aplicació.

**2.- Millores missatges emergents (growl).**
"No té sentit treure un missatge emergent que desapareix abans de poder-lo llegir. Fent feina amb SISTRAGES, aquests missatges poden ser molestos perquè es posen damunt el botó que vols pitjar i has d'esperar a que se'n vagi l'emergent."
_- Como primera aproximación se permite establecer por configuración el timeout y si desaparece automáticamente (punto 10 del comentario https://github.com/GovernIB/sistra2/issues/110#issuecomment-470893086)_

**3.- Establir signants:**
Actualment el funcionament dels signats és que hauran de firmar tots els que es fixin per script. L'opció de fer que un document hagi de ser signat per un signat o altre no està contemplat. Contemplar-ho com a millora.
https://github.com/GovernIB/sistra2/issues/78#issuecomment-460927194

**4.- Poder seleccionar múltiples camps (amb shift/crtl) per a canviar una propietat comuna** 
(p.e. Obligatori) o per Copiar-los i aferrar-los a una altra secció/pàgina del Formulari.
![image](https://user-images.githubusercontent.com/18436867/54602172-3ab85780-4a41-11e9-9d16-17623fb92543.png)

**5.- Comportament no desitjat relatiu al canvi de focus**
Quan s'afegeix una "línia nova" o un "nou camp" o "aplicar canvis" on ja hem hagut de fer "scroll", torna a dalt de tot i perd el focus, fent que on es vol posar el nou camp desaparegui i obliga a tornar fer l'scroll i tornar definir el focus.... Modificar aquest comportament
![image](https://user-images.githubusercontent.com/18436867/54602189-4ad03700-4a41-11e9-945a-fc4c4d9cf858.png)

 _Tenemos detectado un comportamiento indeseado relativo al cambio de foco al pasar por campos que desencadenan peticiones asíncronas. Dicho efecto hace que el foco se sitúe en el primer campo de formulario. Esperamos tenerlo solucionado en la próxima versión._

**6.- Possibilitat de fer visible/invisible un camp dependent del valor d'un altre camp.** 
Incloure tots els tipus, incloses les seccions:
![image](https://user-images.githubusercontent.com/18436867/54602260-76ebb800-4a41-11e9-8fb9-0c7579fdd29d.png)

**7.- Importació-Exportació de tràmits:** 
Implementar que des de la pantalla de verificació es pugui accedir a l'element en qüestió per modificar.

**8.- "Recordar" el perfil amb el qual s'ha accedit a STG** 
(superadministrador, administrador entitat o desenvolupador) perquè la següent vegada que s'accedeixi a STG s'iniciï amb l'últim perfil.

**9.- Disposar de funcions de validació dels diferents documents identificatius**

**10.- Pantalla "Missatges d'Avís Entitat", fer graella amb la llista de tràmits amb un botó d'afegir i treure.**
En lloc que aparegui una llista de codis que aparegui una graella amb la llista de tràmits amb un botó d'afegir i treure (el botó afegir et mostraria un selector de versions amb un cercador).
Té els avantatges que ofereix més informació visual (identificador i descripció tràmit) i també podríem aïllar davant canvis d'identificador dels tràmits.

**11.- Introducció d'un editor WYSGYG** 
(com TinyMCE) per a l'edició de literals de tipus HTML (similar al que té ROLSAC per editar contingut HTML) que permeti limitar i assistir el contingut HTML que es pot introduir.

**12.- Al modificar la mida de la pantalla d'scripts, no hi surt la barra d'scroll** 
Queden els botons d'acceptar cancel·lar, esborrar i ajuda fora de la vista fins que es torna modificar mida de manera adient. Fer que sempre siguin visibles.

**Comment by rsanz-indra** [comment]
Sobre "**2.- Millores missatges emergents (growl)**" :

- Además de controlar el timeout del mensaje y si desaparece o no, se ha modificado el estilo del mensaje para quitar la opacidad, permitiendo una mejor lectura.

- Se ha realizado pruebas para cambiar la localización del mensaje. En este sentido ha habido que habilitar un mecanismo para redirigir los mensajes del growl a través de la ventana principal, haciendo que en lugar que salgan los mensajes en las propias ventanas modales, salgan a nivel de ventana principal. Se adjuntan pantalla de como podría quedar cambiando la localización del mensaje abajo a la derecha. Hay que tener en cuenta que habría que modificar todas las pantallas modales para cambiar la forma de generar el mensaje.

![image](https://user-images.githubusercontent.com/17456494/54907780-a178bd80-4ee6-11e9-9a6a-541ba275e121.png)

**Comment by jsastre-dgtic** [comment]
**13.- Poder configurar a nivell dels camps (FORMULARIS) de textos si un camp ha d'estar en majúscula.**

**Comment by jsastre-dgtic** [comment]
14.-  STT: **Incloure num registre per pantalla a la secció de descàrrega del Justificant**
![image](https://user-images.githubusercontent.com/18436867/55936455-ace21d80-5c36-11e9-9bbc-460354e8f10d.png)

**Comment by jsastre-dgtic** [comment]
2.- Growl: Segueix "molestant" i segons on no ha canviat la opacitat
![image](https://user-images.githubusercontent.com/18436867/55953741-3278c400-5c5d-11e9-9d91-fa6c281333b5.png)

**Comment by jsastre-dgtic** [comment]
15.- Quan falla el ping a un domini, mantenir la pantalla de definició del domini, no tornar a l'inici
![image](https://user-images.githubusercontent.com/18436867/55954057-014cc380-5c5e-11e9-8f47-f874958ee060.png)


![image](https://user-images.githubusercontent.com/18436867/55954048-fb56e280-5c5d-11e9-83aa-5eb4d75716a8.png)

**Comment by jsastre-dgtic** [comment]
16.- No es presenta la molla de pa a totes les pantalles:
![image](https://user-images.githubusercontent.com/18436867/55954124-2ccfae00-5c5e-11e9-863e-1504407ae08f.png)

**Comment by jsastre-dgtic** [comment]
16.- Quan bóta error perd sessió i ja no podem veure errors:

![image](https://user-images.githubusercontent.com/18436867/55954440-fc3c4400-5c5e-11e9-9418-3f37646ce0a5.png)
![image](https://user-images.githubusercontent.com/18436867/55954463-0bbb8d00-5c5f-11e9-87be-65eeb98f79c8.png)

**Comment by jsastre-dgtic** [comment]
2.- Growl: Segueix "molestant" i segons on no ha canviat la opacitat--> S'ha trobat la manera de posar-ho a la part de baix a la pantalla pare. Es corregirà.

**Comment by jsastre-dgtic** [comment]
17.- Incorporar cercador a llista de tràmits (Avisos d'Entitat): https://github.com/GovernIB/sistra2/issues/112#issuecomment-472412502

**Comment by jsastre-dgtic** [comment]
18.- No fer scroll quan es fa "paste" d'un camp de formulari:
![image](https://user-images.githubusercontent.com/18436867/56788735-86101380-6800-11e9-8348-5424ae034724.png)

**Comment by jsastre-dgtic** [comment]
19.- Tal i com es va reflectir al document d'anàlisi del projecte, podríem canviar el comportament dels desplegables fent que filtràs segons es va introduint? Si cercam països i teclejam "es", no hauria d'anar al primer país començat en S, sinó al primer començat en "ES"... 
![image](https://user-images.githubusercontent.com/18436867/57218200-0569c800-6ff5-11e9-8c82-372c0dae5c41.png)

**Comment by jsastre-dgtic** [comment]
20.- No tancar la vista de versió quan la previsualitzam
![image](https://user-images.githubusercontent.com/18436867/57282002-71f3ce00-70ac-11e9-867d-0b9a6f033a12.png)

![image](https://user-images.githubusercontent.com/18436867/57282041-8a63e880-70ac-11e9-8516-3bb702a35534.png)

**Comment by rsanz-indra** [comment]
Revisando lista de tareas ya desarrolladas, los temas pendientes serían:

- _No canviar el coloret del “Vist” quan tenim seleccionada la fila. Ara canvia de blanc a groc. Deixar el blanc per evitar confusions del que vol dir. Aplicar-ho d'aquesta manera a tota l'aplicació._

- _Establir signants. Actualment el funcionament dels signats és que hauran de firmar tots els que es fixin per script. L'opció de fer que un document hagi de ser signat per un signat o altre no està contemplat. Contemplar-ho com a millora.  #78 (comment)_

- _Poder seleccionar múltiples camps (amb shift/crtl) per a canviar una propietat comuna (p.e. Obligatori)_ 

- _Tal i com es va reflectir al document d'anàlisi del projecte, podríem canviar el comportament dels desplegables fent que filtràs segons es va introduint? Si cercam països i teclejam "es", no hauria d'anar al primer país començat en S, sinó al primer començat en "ES"..._ Respecto a este punto el desplegable predictivo está contemplado como un nuevo tipo selector que está pendiente de implementar (no planificado)

Para una mejor legibilidad se propone cerrar esta entrada y abrir otra entrada con los temas pendientes.

**Comment by jsastre-dgtic** [comment]
Tancam aquesta i passam a:
STG: Millores desitjables a SISTRAGES (FASE III) #137
