### ISSUE TITLE
STG: Maquetació JSF finestres modals

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#12]
Implementació de les finestres modals del mòdul de gestor de tràmits. S'espera que en aquest cicle es finalitzi la gestió de totes les pantalles sense lògica

**Comment by sgelabert-dgtic** [comment]
Es sol·licita edemés efectuar els següents canvis ens el layout de l'aplicació:
-Adequació del backoffice als nous estils MIC
-Afegir a la capçalera títol del mòdul (Gestor de Tràmits)
-Afegir en el peu Codi d'aplicació, versió i enllaç al num. de revisió a GitHub.

**Comment by jmico-indra** [comment]
Hemos incorporado los ficheros de configuración de los proyectos además de incorporar algunas de las ventanas de dialogs.

En la creación de los dialogs hemos tenido serios problemas en la maquetación con los componentes de primefaces, principalmente cuando se introduce el componente primefaces datatable dentro de un componente primefaces datagrid. El problema produce la creación de columnas de más en el datatable además de un comportamiento bastante errático cuando se incluyen varios datatables. 

El problema fue notificado hace casi un año pero parece que hasta hace poco no han tenido claro como solucionarlo, por lo que está pendiente de subir una nueva versión de primefaces con el bug solucionado (la nueva versión no tiene fecha de publicación). Se puede solucionar con una propuesta que se realiza dentro de la issue pero generaba ciertos problemas d estilos. Al final hemos optado por utilizar el componente datagrid propio de jsf (y no el de primefaces) actualizando parte de la maquetación de los dialogs.

Issue de la incidencia: https://github.com/primefaces/primefaces/issues/2337

**Comment by rsanz-indra** [comment]
Esta versión incluye el diseño de las pantalla de dialogo del documento de mockups (queda pendiente las pantalla de tasas y de registro) y está el prototipo de la ventana de diseño de formularios para ver el montaje a nivel técnico.

**Comment by sgelabert-dgtic** [comment]
Comentaris sobre el layout de STG rol **SuperAdministrador**:
- En les finestres modals canviar botó "Aceptar" per "Desar" o "Guardar" segons l'idioma.
- En les finestres modals convindria canviar el títol en funció de l'acció. Per exemple, si botó "Editar" --> "Edició d'Entitats", si botó "Nou" --> "Alta d'Entitat". (_No prioritari. Valorar el seu cost_)
- Totes les opcions d'eliminació han de sol·licitar confirmació de l'acció (exemple gestió domini eliminació propietat)
- Per als botons que únicament tenen icona, afegir tootltip (exemple gestió de domini)
- **Gestió d'entitats**
  - Canviar missatge alert "Es va a eliminar la fila seleccionada, ¿vol continuar?" per "S'eliminarà la fila seleccionada, ¿vol continuar?"
- **Propietats globals**
  - Només apareix el botó d'edició. S'ha eliminat els botons "Nou" i "Esborrar" que figuren en el document de mockups i només permet edició del valor, perquè ?
  - Afegir al grid columna amb "Descripció de la propietat"
- **Plugin global**
  - Canviar literal "No es van trobar dades" per "No s'han trobat dades"
  - Afegir al grid columna amb "Descripció del plugin"
- **Gestió de domini**
  - Alineació superior de les labels (exemple "Descripcio", selector "Tipus" i "Paràmetres")
  - No demana confirmació alhora d'eliminar una propietat amb la toolbar vertical.
  - Presentar en el grid de paràmetres dues columnes "Codi" i "Valor"
  - En el tipus "Consulta remota" el finestra model per l'alta de paràmetres surt tallada.

**Comment by sgelabert-dgtic** [comment]
Amb la darrera versió commitada no em permet canviar al rol Administrador/Dsenvolupador. Entenc que no són estables

**Comment by rsanz-indra** [comment]
Respecto a los comentarios indicados se han realizado la mayoría de ellos.
En las propiedades globales no se permite el alta ni eliminación, porque las propiedades globales deberán ser propiedades preestablecidas en el sistema (precargadas mediante script de base de datos), por lo que sólo tendrá sentido su edición. De la misma forma, tenemos pendiente de estudiar si en la parte de plugins hacemos algo similar, ya que los valores a tratar son intrínsecamente asociados a la versión de Sistra.
Respecto a la tarea de maquetación JSF de las pantallas (sin lógica), damos por finalizada la tarea, ya que el objetivo de la misma era tener traspasados los mockups a JSF. De todas formas, una vez se tenga una primera versión completa de la versión inicial se pulirán temas como literales, aspectos menores a nivel de presentación, etc.
Hay que tener en cuenta que a partir del ciclo 3 ya se implementan la lógica de las pantallas y entre estas funcionalidades está la gestión de seguridad, por lo que la aplicación controlará que perfiles hay disponibles en base a los roles y permisos de acceso.
