### ISSUE TITLE
STG: Generació AJUDES i externalització d'aquestes

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#121]
1.- **IMPORTANT**: Totes les ajudes online (STG i STH) han d'anar a un directori del servidor en format html i fora del ear per tal de poder mantenir-la sense haver de desplegar l'ear cada vegada que es produeixi un petit canvi.

2.- Queden pendents la generació d'ajudes per a les pantalles de vista d'Administrador Entitat / Desenvolupador. (https://github.com/GovernIB/sistra2/issues/65#issuecomment-462331933)

**Comment by jsastre-dgtic** [comment]
Quan modificam la mida de la finestra d'ajuda no surten scrolls i només podem sortir tancant la finestra a la força sense saber si es guardarà o no. A més, l'ajuda fa referència a un camp que després no especifica (codProvincia)
![image](https://user-images.githubusercontent.com/18436867/56133036-cadbb500-5f8b-11e9-9d66-da7e62c9b021.png)

**Comment by jsastre-dgtic** [comment]
Queda pendent que cada mòdul tengui el seu directori d'ajuda (sistrages, sistrahelp) per separat.

**Comment by rsanz-indra** [comment]
La separación de directorios está incorporada en la última versión.

**Comment by jsastre-dgtic** [comment]
Actualitzar a: https://github.com/GovernIB/sistra2/tree/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda
