### ISSUE TITLE
STT: Desenvolupament de 4 tràmits candidats a implantar sobre SISTRA2 V0

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#126]
**AP0041PSAG** - Autorització per a la pesca marítima submarina al Parc natural de s'Albufera des Grau

**IN0015CINF** - Sol·licitud de l'informe preceptiu per a l'autorització dels plecs de prescripcions tècniques

**PT0004AVJO** - Preinscripció a les activitats d'estiu de l'IB-JOVE

**EH0059CERT** - Sol·licitud de certificat digital d'empleat públic

**Comment by rsanz-indra** [comment]
Se han llevado a cabo 3 trámites:
- Solicitud de certificado digital de empleado público
- Solicitud de tarjeta criptográfica
- Instancia genérica

Se prevé el desarrollo de los próximos trámites:
- [IN0026SIPR] - Solicitud de inicio de proyecto para el desarrollo de trámites telemáticos.
- [AP0041PSAG] - Autorización para la pesca marítima submarina en el Parc natural de s'Albufera des Grau.
- IN0015CINF - Sol·licitud de l'informe preceptiu per a l'autorització dels plecs de prescripcions tècniques
- Trámite plantilla

**Comment by jsastre-dgtic** [comment]
IN0026SIPR no funciona bé. S'envien detalls dels errors per correu.
AP0041PSAG no ens permet pagar. S'envien detalls dels errors per correu.
IN0015CINF no el tenim encara...

**Comment by jsastre-dgtic** [comment]
PT0004AVJO - Preinscripció a les activitats d'estiu de l'IB-JOVE no s'ha fet

**Comment by jsastre-dgtic** [comment]
**AP0041PSAG--> PESCA - AUT_SUB_ALB_GRAU:** no permet autenticació ni té scripts per emplenar camps en cas que es volgués autenticar

IN0015CINF --> MAD - INF_PPT: El desplegable de Conselleries és una llista de valors fixa. No hauria de ser així. Aquest tràmit no s'ha d'implementar per no estar llesta la integració amb Helium

PT0004AVJO --> No s'ha implementat

EH0059CERT --> No carrega les dades del certificat amb el que s'ha entrat

Sol·licitud de targeta criptogràfica --> MAD - TARGETA_CRIPTO: No carrega les Conselleries

Instancia genérica (#134) - SIMPL_DOC -INSTANCIA_GENERICA: OK

**Comment by jsastre-dgtic** [comment]
Tancam i passam a Migració de Tràmits #262
