### ISSUE TITLE
STT: Integració plugin de validació de signatura (servidor)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#128]
Pendent de la publicació, per part de la Fundació Bit, del connector de validació de signatures adaptat a versions actuals de CXF per poder realitzar la integració.

**Comment by rsanz-indra** [comment]
Integrado el plugin de firma. Quedaría realizar pruebas de funcionamiento.

**Comment by jsastre-dgtic** [comment]
Esperarem poder fer les proves per tancar issue.

**Comment by rsanz-indra** [comment]
Se ha finalizado la integración del plugin de validación de firma, pero queda pendiente que Portafib pueda gestionar varios tipos de firma para un mismo perfil. 
Por tanto queda pendiente de que se realicen las adaptaciones oportunas en Portafib.

**Comment by rsanz-indra** [comment]
Se ha instalado nueva versión de Portafib que maneja los perfiles de firma.
Se retoman las pruebas de validación de firmas.

**Comment by rsanz-indra** [comment]
Está fallando conexión con firmaweb (#44). Se espera a que se resuelva.

**Comment by rsanz-indra** [comment]
Ya funciona la firma: se ha probado a firmar un pdf (retornando pades) y un docx (retornando cades).
La validación de firma se ha realizado correctamente también.
