### ISSUE TITLE
STG: Implementació capa persistència JPA

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#13]
Incorporar al mòdul SISTRAGES la gestió de persistència JPA:
- Mapeig d'entitats JPA
- Generació dels scripts físics de dades a partir del model JPA

**Comment by rsanz-indra** [comment]
Se ha realizado el mapeo JPA de las entidades y realizado pruebas de operaciones con la BD.
Se ha comiteado con el mapeo deshabilitado porque queda pendiente trasladar los últimos cambios funcionales al modelo de base de datos detectados en la revisión de mockups, migración y preregistro.
En la siguiente versión a comitear se actualizará el modelo de datos y scripts con los últimos cambios para lanzar la creación de tablas en el entorno de desarrollo.

**Comment by rsanz-indra** [comment]
Esta tarea se puede dar como finalizada, teniendo en cuenta que el modelo de datos puede irse viendo afectado durante el proceso de desarrollo de la aplicación (cambios menores en el modelo de datos)
