### ISSUE TITLE
STT: Adaptació de l'esmena / lliurament presencial

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#131]
**Primera fase:** netejar operativa anterior de preregistre.
implementació frontal / JS
**Segona fase:** implementació sobre el flux de tramitació (s'estima que no es completarà en aquest cicle).
implementació de la lògica de negoci

**Comment by jsastre-dgtic** [comment]
- La planificació d'aquesta tasca dependrà de les adaptacions necessàries a realitzar per a la posada en producció de Sistra2v0

**Comment by rsanz-indra** [comment]
Se pospone tarea hasta terminar de cerrar Sistra2V0 para evitar tener que replicar cambios en diferentes ramas

**Comment by jsastre-dgtic** [comment]
Tancam i desglossam amb Milestone: Esmena i el lliurament presencial.
ESMENA - Anàlisi i proposta de solució #228
