### ISSUE TITLE
STG: 2 operatives diferenciades per a la incorporació de tràmits a SISTRA2

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#136]
s'ha redefinit l'operativa d'importar diferenciant 2 operatives diferenciades: promoció entre entorns (quadern de càrrega) i la importació en l'entorn de desenvolupament d'un tràmit provinent d'una altra instal·lació de Sistra2.

**Comment by jsastre-dgtic** [comment]
Es provarà en tenir l'entorn de PRE operatiu....

**Comment by jsastre-dgtic** [comment]
- Després d’importar hauria de seguir a la mateixa vista de l’àreades d'on s'ha fet.
![image](https://user-images.githubusercontent.com/18436867/64103539-c107f200-cd72-11e9-894f-fd939e837ce9.png)

**Comment by jsastre-dgtic** [comment]
Com es pot crear una versió si ja existeix? Sempre la reemplaçarà, no?
![image](https://user-images.githubusercontent.com/18436867/64103614-e7c62880-cd72-11e9-8028-686a60dd6b7e.png)

**Comment by rsanz-indra** [comment]
_Després d’importar hauria de seguir a la mateixa vista de l’àreades d'on s'ha fet._
Apuntamos como mejora

_Com es pot crear una versió si ja existeix? Sempre la reemplaçarà, no?_
Crear versión genera una nueva versión del trámite (correlativa)

**Comment by jsastre-dgtic** [comment]
Quedaria:
Després d’importar hauria de seguir a la mateixa vista de l’àreades d'on s'ha fet.
Apuntamos como mejora

**Comment by jparedes-indra** [comment]
Al importar se selecciona el trámite que se ha importado al igual que el área en el cual se ha importado. 
![#136](https://user-images.githubusercontent.com/67064375/147069327-38c9e45b-af4d-4008-a45b-42b7cb025dd4.gif)
