### ISSUE TITLE
STG: Millores desitjables a SISTRAGES (FASE III)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#137]
1.- No canviar el coloret del “Vist” quan tenim seleccionada la fila.
Ara canvia de blanc a groc. Deixar el blanc per evitar confusions del que vol dir. Aplicar-ho d'aquesta manera a tota l'aplicació.
2.- Millores missatges emergents (growl).
![image](https://user-images.githubusercontent.com/18436867/57675532-960e5c80-7622-11e9-8256-ceb4e1bd7efc.png)

Se ha realizado pruebas para cambiar la localización del mensaje. En este sentido ha habido que habilitar un mecanismo para redirigir los mensajes del growl a través de la ventana principal, haciendo que en lugar que salgan los mensajes en las propias ventanas modales, salgan a nivel de ventana principal. Se adjuntan pantalla de como podría quedar cambiando la localización del mensaje abajo a la derecha. Hay que tener en cuenta que habría que modificar todas las pantallas modales para cambiar la forma de generar el mensaje.

Encara surt malament:
![image](https://user-images.githubusercontent.com/18436867/57675543-9c9cd400-7622-11e9-94c9-431dfbb6ff76.png)

Growl: Segueix "molestant" i segons on no ha canviat la opacitat--> S'ha trobat la manera de posar-ho a la part de baix a la pantalla pare. Es corregirà.

3.- Establir signants:
Actualment el funcionament dels signats és que hauran de firmar tots els que es fixin per script. L'opció de fer que un document hagi de ser signat per un signat o altre no està contemplat. Contemplar-ho com a millora.
4.- Poder seleccionar múltiples camps (amb shift/crtl) per a canviar una propietat comuna
(p.e. Obligatori) o per Copiar-los i aferrar-los a una altra secció/pàgina del Formulari.
![image](https://user-images.githubusercontent.com/18436867/57675549-a1618800-7622-11e9-8f06-d0b088af3a9f.png)

5.- Comportament no desitjat relatiu al canvi de focus
Quan s'afegeix una "línia nova" o un "nou camp" o "aplicar canvis" on ja hem hagut de fer "scroll", torna a dalt de tot per tornar abaix de tot per tal de mantener el focus.... Es pot modificar aquest “efecte visual”?

![image](https://user-images.githubusercontent.com/18436867/57675558-a6263c00-7622-11e9-9bad-267716a2e6e7.png)

Encara tenim un comportament estrany amb el focus, revisar operativa:
No fer scroll quan es fa "paste" d'un camp de formulari:
![image](https://user-images.githubusercontent.com/18436867/57675568-aa525980-7622-11e9-87d7-cbc338c9a429.png)

6.- Possibilitat de fer visible/invisible un camp dependent del valor d'un altre camp.
Incloure tots els tipus, incloses les seccions:
![image](https://user-images.githubusercontent.com/18436867/57675574-ad4d4a00-7622-11e9-97d9-d5e04f5957ad.png)

7.- Al modificar la mida de la pantalla d'scripts, no hi surt la barra d'scroll
Queden els botons d'acceptar cancel·lar, esborrar i ajuda fora de la vista fins que es torna modificar mida de manera adient. Fer que sempre siguin visibles.

8.- STT: Incloure num registre per pantalla a la secció de descàrrega del Justificant
![image](https://user-images.githubusercontent.com/18436867/57675583-b2aa9480-7622-11e9-898a-dfa54ff71f39.png)

9.- Quan falla el ping a un domini, mantenir la pantalla de definició del domini, no tornar a l'inici
![image](https://user-images.githubusercontent.com/18436867/57675589-b5a58500-7622-11e9-99db-4a5f4e6a25b3.png)

![image](https://user-images.githubusercontent.com/18436867/57675600-b9d1a280-7622-11e9-98ae-337570077d51.png)

10.- Cercador dinàmic
Tal i com es va reflectir al document d'anàlisi del projecte, podríem canviar el comportament dels desplegables fent que filtràs segons es va introduint? Si cercam països i teclejam "es", no hauria d'anar al primer país començat en S, sinó al primer començat en "ES"...
![image](https://user-images.githubusercontent.com/18436867/57675612-bdfdc000-7622-11e9-8615-59cb79e0303e.png)

11.- No tancar la vista de versió quan la previsualitzam

![image](https://user-images.githubusercontent.com/18436867/57675620-c35b0a80-7622-11e9-8a02-489835a6d1ef.png)

![image](https://user-images.githubusercontent.com/18436867/57675635-ca821880-7622-11e9-8416-b803d7046856.png)

12.- Controlar en tots els botons de la pantalla d'edició de formularis si hi ha canvis pendents
13.- En els grids de propietats no va el dblclick per consultar / editar (p.e. en manteniment de connector les propietats del connector)

**Comment by rsanz-indra** [comment]
Actualizamos estado de algunas mejoras:

_2. Millores missatges emergents (growl)_

En principio en la última versión debería funcionar. Probad a borrar la caché del navegador.

_5. Comportament no desitjat relatiu al canvi de focus_
Este funcionamiento es debido a que se refresca el HTML de formulario cada vez que se produce un cambio por lo que el efecto que se ve es que se vuelve a colocar el foco en el campo. Se realiza el refresco completo del HTML para simplificar la lógica ya que la alternativa sería ir modificando parcialmente el HTML conforme se fuera modificando, solución que sería bastante más complicada.

_8.- STT: Incloure num registre per pantalla a la secció de descàrrega del Justificant_
Está incorporado en la última versión.

_9.- Quan falla el ping a un domini, mantenir la pantalla de definició del domini, no tornar a l'inici_
Está incorporado en la última versión.

**Comment by jsastre-dgtic** [comment]
Passam el punt 8 a: https://github.com/GovernIB/sistra2/issues/140

**Comment by jsastre-dgtic** [comment]
9.- Quan desbloquejam una versió, no contreure les versions associades al tràmit, quedar on som per defecte. Aquest és un vcomportament global de l'aplicació que s'hauria de modificar.
![image](https://user-images.githubusercontent.com/18436867/57753064-5cedef00-76eb-11e9-8053-ccf79bd8d891.png)

**Comment by jsastre-dgtic** [comment]
ok, ja no passa... la 9 resolta també!

**Comment by jsastre-dgtic** [comment]
10.- Possibilitat d'ordenació de les àrees alfabèticament
![image](https://user-images.githubusercontent.com/18436867/64232309-043c9f00-cef2-11e9-8603-a419a8a27b8e.png)

**Comment by rsanz-indra** [comment]
Se quedan pendientes las siguientes mejoras:
1.- No canviar el coloret del “Vist” quan tenim seleccionada la fila.
3.- Establir signants
4.- Poder seleccionar múltiples camps (amb shift/crtl) per a canviar una propietat comuna
5.- Comportament no desitjat relatiu al canvi de focus
6.- Possibilitat de fer visible/invisible un camp dependent del valor d'un altre camp.
10.- Cercador dinàmic

**Comment by jsastre-dgtic** [comment]
Ha quedat pendent això:
https://github.com/GovernIB/sistra2/issues/137#issuecomment-553883747

**Comment by jsastre-dgtic** [comment]
1.- La descartam
3.- Establir signants #458
4.- Es crearà un doc d'estimació
5.- Es crearà un doc d'anàlisi i estimació
6.-Possibilitat de fer visible/invisible un camp dependent del valor d'un altre camp. #459
10.- Es crearà un doc d'anàlisi i estimació
