### ISSUE TITLE
STT: Implementació de millores detectades durant el desenvolupament de tràmits candidats recomanables per a posada en producció de Sistra2-v0.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#138]
- Després d'executar una validació remota d'un camp no passa al següent camp.
- Millora gestió errors en mostrar justificant mitjançant redirecció.
- Permetre indicar en l'script de 'Validació de pàgina' el camp que està donant problemes.
- Permetre indicar en l'script de 'Paràmetres d'obertura de formulari' si hi ha camps que passen a configurar-se com sol lectura.
- En la generació de PDFs de formulari cal convertir les dates del format internacional (any / mes / dia), que és com s'emmagatzema en l'XML, al format europeu per a la presentació al PDF (any / mes / dia).
- Implementació full d'estils d'alt contrast per accessibilitat.

**Comment by rsanz-indra** [comment]
Se han desarrollado las mejoras identificadas así como otras que han ido surgiendo.
Queda pendiente el desarrollo de hojas de estilo de alto contraste que debe realizarse una vez se cierre finalmente la versión 0. Por ello se realizará la entrega de esta entrada y se solicita la creación de las hojas de estilo en una issue separada para poderla estimar y planificar de forma independiente.

**Comment by jsastre-dgtic** [comment]
ok
