### ISSUE TITLE
STT: Adaptació del flux de tramitació perquè no sigui obligatori el codi SIA.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#139]
Adaptació del flux de tramitació perquè no sigui obligatori el codi SIA.

**Comment by rsanz-indra** [comment]
Esta issue está duplicada (#130) y habría que descartarla.
Por error no se había indicado la issue en el documento de planificación.

**Comment by jsastre-dgtic** [comment]
tancam per duplicitat
