### ISSUE TITLE
STT: Anàlisi funcionalitat de pre-registre

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#14]
Anàlisi de la funcionalitat implementada per SISTRA1 relacionada amb pre-registre i estudi de la migració d'aquesta operativa a l'aplicació REGWEB3

**Comment by rsanz-indra** [comment]
Pendiente de revisión por parte de la DGDT y enviar dudas a BIT para plantear reunión.

**Comment by sgelabert-dgtic** [comment]
S'acorda reunió entre equip tècnic SISTRA2-REGWEB3 a fi de tancar la funcionalitat/establir contracte entre aplicacions.
Proposta DGDT:
- SISTRA2 emmagatzemarà temporalment el annexes i la sol·licitud, generarà un núm. de pre-registre i generarà el pdf a mode de justificant descarregable per al ciutadà . Aquest justificant no es signarà digitalment i no durà espai per la firma manuscrita.
- SISTRA2 implementarà un servei que permeti a REGWEB3 l'obtenció dels annexes i la sol·licitud
- REGWEB3 recuperarà els documents a partir del núm. de pre-registre, generarà l'assentament, el justificant de registre i ho passarà a distribució de RIPEA
-  SISTRA2 mantindrà un calendari de festius (multientitat) i calcularà la data màxima per la formalització del pre-registre (núm. màx. de dies especificat per propietat de sistema). Passada aquesta data es proposa purgar els documents de SISTRA2 i impedir la recuperació des de REGWEB3 del pre-registre (informant-ne del motiu)
- REGWEB3 digitalitzarà i signarà mitjançant un segell d'òrgan la documentació presencial a fi de convertir-a en còpia autèntica de document en paper. Cal veureu si s'han de segellar també els annexes a fi de poder-los emmagatzemar a l'arxiu i definir qui ho ha de fer.

Altres consideracions:
- A fi de complir amb la Llei 39/2015,  SISTRA2 sol·licitarà autenticació per a tot tràmit que formi part d'un procediment administratiu. En canvi es permetrà l'accés no autenticat per a Serveis Administratius.
- D'entrada no es preveu establir cap control/lligam entre l'autenticació i la posterior signatura del tràmit.
- L'accés al tràmit haurà de preveure l'autenticació de representants i funcionaris habilitats, per tant, s'haurà d'integrar amb RFH i REA
