### ISSUE TITLE
STT: Desenvolupament primer conjunt de tràmits a implantar sobre SISTRA2v0

### ISSUE THREAD

**Issue by fjcalderon-dgtic** [GovernIB/sistra2#143]

**Comment by fjcalderon-dgtic** [comment]
AS0007FRMI – ‘Fulla de notificació de risc i maltractament infantil en l'àmbit escolar’
OP0012PMAX – ‘Sol·licitud preu màxim’
AP0058PELM – ‘Autorització per a la pesca des d'embarcació en la Reserva Marina del Llevant de Mallorca’
AP0034AUTP – ‘Procediment on-line per a la sol·licitud d'autorització de pesca submarina en les reserves marines de Palma i del Migjorn de Mallorca’
PT0001SAIP – ‘Sol·licitud d'accés a la informació pública’
OP0029SAPP – ‘Sol·licitud animals potencialment perillosos’

**Comment by jsastre-dgtic** [comment]
Tancam i passam a Migració de Tràmits #262
