### ISSUE TITLE
Actualitzar a la documentació els contextos API d'aplicació

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#146]

**Comment by sgelabert-dgtic** [comment]
Els canvis efectuats no es reflecteixen sobre la documentació. Cal actualitzar-la.
- Document de disseny tècnic:
--> Secció 2 arquitectura tecnològica (descriure el mòdul sistracom)
--> Secció 9 contextos de l'aplicació (actualitzar)
--> Secció 10 infraestructura de suport (actualitzar nova arquitectura Jboss 7.2)
--> Secció (nova) descriure infraestructura d'autenticació (configuració empaquetat amb/sense domini de seguretat)
- Document d'anàlisi
-->Secció 2.6.4 (ampliar amb operacions plugin de firma)
-->Secció 2.6.7 (revisar operacions plugin de registre)

**Comment by rsanz-indra** [comment]
Se había actualizado solamente la documentación referente a la integración: 
- /sistramit/doc/SISTRAMIT_Manual_Integracio.odt
- /loginib/doc/LoginIB_Manual_Integracio.odt
- /paymentib/doc/PaymentIB_Manual_Integracio.odt

El resto de documentación del proyecto, requiere una revisión más completa (además de los puntos indicados). Esta revisión está planificada para noviembre.

**Comment by jsastre-dgtic** [comment]
No trobam això: 
https://github.com/GovernIB/sistra2/issues/146#issuecomment-513673288

**Comment by jcerdar-indra** [comment]
- Se ha actualizado la documentación requerida en https://github.com/GovernIB/sistra2/issues/146#issuecomment-513673288. 
- La documentación se ha enviado por correo a usuario sistra2 el 13/01 a las 8:33

**Comment by jsastre-dgtic** [comment]
Dia 13 enviau correu, dia 29 vos deim que no trobam el que esperàvem... S'arribà a validar?  S'ha pujat al Git?

**Comment by jparedes-indra** [comment]
Se vuelve a enviar la documentación por correo.

Enviado: mi. 04/01/2023 9:45
Asunto: RE: issues en revisió

**Comment by jsastre-dgtic** [comment]
I:\1. Serveis d'Administració Electrònica 2020-2024\01. Lot 1 Serveis electrònics per a la ciutadania\05. Àrea tramitació telemàtica\SISTRA2 - Documentació
