### ISSUE TITLE
STT: Desenvolupament segon conjunt de tràmits a implantar sobre SISTRA2v0

### ISSUE THREAD

**Issue by fjcalderon-dgtic** [GovernIB/sistra2#147]
TF0015OFOC - Oferta de empleo.
AP0035PESI - Solicitud de primera expedición o renovación de licencia de pesca recreativa (Inmediata).
SC0005RCLM - Reclamaciones a Consumo.
EB0002CERT - Solicitud de certificado de acción formativa.
EH0051EMPI - Escrito para empresarios individuales no inscritos en el Registro Mercantil.

**Comment by fjcalderon-dgtic** [comment]
Analizando vuestra lista de trámites candidatos (con las substituciones que habéis incluido), os doy mi parecer:

- OP0015PDOC - Presentación de documentación Plan estatal vivienda:  Lo veo bien, de entrada, es un trámite muy utilizado (cerca de 3000 solicitudes registradas en lo que va de año), no tiene pago de tasa,... pero he podido comprobar que es un trámite con una elevada carga documental, tiene definido cerca de 30 anexos, aunque casi todos dependen de un script, es decir de la información que se rellene en el formulario. Habría que analizar los tamaños de todos los anexos, porque con SISTRA2 tenemos que tener presente las limitaciones en cuanto a tamaño de anexos de REGWEB3 (impuesta a su vez por el proyecto SIR). Además, hay una integración con la aplicación Ajuviv.

- AP0037SCTP - Solicitud de cursos de Formación Básica en el ámbito marítim: Otro candidato que de entrada no veo mal, aunque este no es muy utilizado (cerca de 160 solicitudes registradas en lo que va de año), pero tiene un hándicap, dispone de tres anexos pero con un tamaño definido de 40 MB como máximo, lo cual supondría un impedimento a la hora de enviar esta solicitud a REGWEB para su posterior distribución . Habría que confirmar con los responsables de este trámite porque tienen esos tamaños definidos tan altos. No hay integración con ningún backoffice.

- CI0041TECO - Solicitud de certificación tienda de conveniencia: Trámite con una utilización muy baja (apenas 18 solicitudes registradas en lo que va de año), pero parece que es un trámite sencillo, sin pago ni anexos y no hay integración con ningún backoffice.

- AP0069FSEG - CURSO ACTUALIZACION FORMACION BASICA EN SEGURIDAD MARITIMA: Trámite con una utilización muy baja (apenas 33 solicitudes registradas en lo que va de año), pero parece que es un trámite sencillo, no hay pagos y sólo tres anexos, uno obligatorios y los otros dos no, y además, ninguno de ellos puede tener un tamaño superior a 1 MB.  No hay integración con ningún backoffice.

- IN0017GRAU - Reconocimiento de grado: Trámite con una utilización muy baja (apenas 45 solicitudes registradas en lo que va de año), además es un trámite interno, de tipo registro. Por lo demás, no parece complicado, sólo dispone de un sencillo formulario y no hay integración con ningún backoffice. 

- AP0038GMDS - Solicitud de cursos Operador restringido del sistema mundial de socorro y seguridad mundial: Trámite con una utilización  baja (apenas 67 solicitudes registradas en lo que va de año), pero parece que es un trámite sencillo, sin pago ni anexos y no hay integración con ningún backoffice.

- SC0014CEFA - COMUNICACIÓN DE BAJA DE FARMACÉUTICO ADJUNTO DE OFICINA DE FARMACIA: Trámite con una utilización  baja (apenas 82 solicitudes registradas en lo que va de año), pero parece que es un trámite sencillo, sin pago ni anexos y no hay integración con ningún backoffice.

- EB0008ENQ  - Encuesta conciliación familiar oposiciones y bolsines: se trata de un trámite con una alta utilización (cerca de 2000 solicitudes registradas en lo que va de año), además parece un trámite sencillo, sin pago ni anexos, pero hay dos aspectos a reseñar que pueden complicar la migración. Primero, se trata de un servicio, un trámite que no pasa por registro, y segundo, tiene configurada una integración en bantelback con la aplicación SISTRAEBAP, por lo que habría que analizar el coste de migrar esta integración. Como no es un trámite de un procedimiento reglado, que es un servicio desde el punto de vista de SIA, entiendo que no es necesario que pase por REGWEB. Lo que está por ver es si pasará por DISTRIBUCIO para tener presente la migración de la integración.


Resumiendo, entiendo que para estos procesos de migración iniciales, no prima tanto el uso del propio trámite, por lo que yo priorizaría todos los de la lista, salvo los dos primeros y el último (atendiendo a posibles problemas con número y tamaño de anexos, y las integraciones con backoffices)

**Comment by rsanz-indra** [comment]
Estado desarrollo a final proyecto:


(1.)	CI0041TECO - Solicitud de certificación tienda de conveniencia.:
Migrado. ENTREGADO 2019/09/02.
PROPUESTA DE MEJORA (que en SISTRA1 no existe): campo LL1_SOL se podría validar con script que sea obligatorio en caso de que campo NIF_SOL sea un NIF de persona física.

(2.)	AP0069FSEG - CURSO ACTUALIZACION FORMACION BASICA EN SEGURIDAD MARITIMA.:
Migrado. ENTREGADO: 2019/09/02.

(3.)  IN0017GRAU - Reconocimiento de grado.
Migrado. ENTREGADO: 2019/09/02.

En SISTRA1 aunque las dos plantillas PDF están diferenciadas en el nombre por el idioma, el contenido de ambas está únicamente en catalán. En SISTRA 2 se ha mantenido así.
PENDIENTE:
(a.) crear función .getFechaActual multiidioma (español, catalán, ...) con nuevo parámetro de idioma.
DATOS_VALORESINICIALES.setValor( 'CDATA', PLUGIN_UTILS.getFechaActual( "'a 'dd' de
(b.) PENDIENTE ¿crear fuente de datos IN_ORGANISMES particular para SOLO este trámite?
   Dominio: SELECT CODIGO, DESC_ES, DESC_CA FROM IN_ORGANISMES ORDER BY CODIGO
   DE MOMENTO se mete dominio genérico: GESCONSDIR3: LListat de conselleries amb codi DIR3

(4.)  AP0038GMDS - Solicitud de cursos Operador restringido del sistema mundial de socorro y seguridad mundial.

NO MIGRADO.

(5.)  SC0014CEFA - COMUNICACIÓN DE BAJA DE FARMACÉUTICO ADJUNTO DE OFICINA DE FARMACIA.

NO MIGRADO.

(6.)  OP0015PDOC - Presentación de documentación Plan estatal vivienda.

NO MIGRADO.

(7.)  AP0037SCTP - Solicitud de cursos de Formación Básica en el ámbito marítimo.

NO MIGRADO.

(8.)  EB0008ENQ - Encuesta conciliación familiar oposiciones y bolsines.

NO MIGRADO.

**Comment by jsastre-dgtic** [comment]
Tancam i passam a Migració de Tràmits #262
