### ISSUE TITLE
STH: Bug canvi de rol sistrahelp

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#148]
S'adjunta error al canvi de rol de Supervisor helpdesk a Operador helpdesk
http://tn.caib.es/ZCihgJVbOvhX

**Comment by rsanz-indra** [comment]
Se corrige error y se mejora el tratamiento de roles/entidades, ya que puede haber casos en los que según permisos / roles se superpongan permisos (p.e. role supervisor y role sobre una misma entidad se superponen)  o según que entidad deba mostrar o no cierto role.
