### ISSUE TITLE
STT: Desenvolupament layout de l'aplicació

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#15]
A partir dels mockups de l'assistent de tramitació #6 cal desenvolupar les següents funcionalitats:
- Maquetació de formularis. Evolucionar i millorar l'esbós js (http://caibter.indra.es/sistra2form/)
- Corregir els problemes js relacionats amb la presentació de dates. desplegables predictius, etc.
- Avaluar la inclusió d'utilitats js/jQuery per incorporar al frontal camps d'escriptura predictiva (https://jqueryui.com/autocomplete/)

**Comment by rsanz-indra** [comment]
Se publica en http://caibter.indra.es/sistra2form la maquetación HTML para la gestión de formularios en el asistente.
Se puede dar por concluida esta fase, durante la fase de desarrollo se irán ajustando funcionalidades.
