### ISSUE TITLE
STT: instruccions de tramitació (HTML)

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#161]
Realizar   la implementación de esta funcionalidad en el frontal, de tal manera que se permita visualizar el texto en la ventana de registro.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jsastre-dgtic** [comment]
ok
![image](https://user-images.githubusercontent.com/18436867/122741823-a3788500-d285-11eb-868c-8b25a2633400.png)
