### ISSUE TITLE
STG: Funcions data en els scripts: afegir camp format

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#163]
Crear nuevas funciones para permitir indicar en las funciones fecha un formato especifico. Modificar la ayuda para contemplar estas nuevas funciones.

**Comment by jparedes-indra** [comment]
Se resuelve en versión 1.2.0 y se despliega en caibter pero no en dev.

**Comment by jsastre-dgtic** [comment]
Pareix que funciona inversament al que diu l'ajuda
![image](https://user-images.githubusercontent.com/18436867/122742692-809aa080-d286-11eb-9489-01eb1b25a52f.png)

![image](https://user-images.githubusercontent.com/18436867/122742720-88f2db80-d286-11eb-9a5a-cd895b3c211f.png)

**Comment by jparedes-indra** [comment]
La función getFechaActual no funciona correctamente con un parámetro distinto a null y distinto a dd/MM/yyyy. 
![image](https://user-images.githubusercontent.com/67064375/124956648-7adbe380-e018-11eb-84be-4091c4d1f107.png)
![image](https://user-images.githubusercontent.com/67064375/124956665-7e6f6a80-e018-11eb-9d88-def13eff3250.png)
![image](https://user-images.githubusercontent.com/67064375/124956671-80d1c480-e018-11eb-9f10-5fe3db65d6fc.png)
![image](https://user-images.githubusercontent.com/67064375/124956678-83341e80-e018-11eb-87fc-f2364109884f.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/126142147-1aafee1d-bc34-42eb-bd9d-e4034c250a9c.png)

**Comment by avillen-dgtic** [comment]
La funció es relaciona amb la documentació com toca.

var date1= PLUGIN_UTILS.getFechaActual(null);
var date2 = PLUGIN_UTILS.getFechaActual('yyyy-MM-dd');
var date3 = PLUGIN_UTILS.getFechaActual('MM/dd/yyyy');

![image](https://user-images.githubusercontent.com/83401259/126754694-5d384355-2ae9-4ea4-8ab8-d36b61845cc4.png)
