### ISSUE TITLE
STT: Funcions data en els scripts: afegir camp format

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#164]
Crear nuevas funciones para permitir indicar en las funciones fecha un formato especifico. Modificar la ayuda para contemplar estas nuevas funciones.

**Comment by jparedes-indra** [comment]
Se resuelve en versión 1.2.0 y se despliega en caibter pero no en dev.

**Comment by jsastre-dgtic** [comment]
Informat a #163

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/126142252-0d490cf4-6977-4907-b372-393283fc567d.png)

**Comment by avillen-dgtic** [comment]
Informat a #163
