### ISSUE TITLE
STG: Permetre configurar mètodes autenticació

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#166]
Actualmente es posible configurar el QAA, y deberían poder configurarse además, los métodos de autenticación (USUARIO_PASSWORD, CERTIFICADO, ...).

**Comment by jsastre-dgtic** [comment]
ok
![image](https://user-images.githubusercontent.com/18436867/127855755-0a3297db-ecb7-44bb-a865-b94232604c0a.png)
