### ISSUE TITLE
STT: Permetre configurar mètodes autenticació

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#167]
Actualmente es posible configurar el QAA, y deberían poder configurarse además, los métodos de autenticación (USUARIO_PASSWORD, CERTIFICADO, ...).

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/127832152-6027b5ba-8a82-4535-8349-db1e374ccda1.png)
