### ISSUE TITLE
STG: Ajuda Online (propietat camp de formulari): permetre valor buit

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#168]
Actualmente se pueden añadir elementos de formulario sin texto en la propiedad "Ayuda on-line", pero si se accede a esa propiedad y no se introduce texto, se indica que es obligatorio. Debería permitirse dejarlo completamente vacío.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jsastre-dgtic** [comment]
ok
