### ISSUE TITLE
STG: Plantilla de correus de finalització de tràmit: externalitzar

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#169]
Actualmente la plantilla y los textos a usar pertenecen a la aplicación. Se debería externalizar.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (de3bcce), apadiendo la posibilidad de indicar la url de la sede electrónica en la configuración de entidad y añadiendo esa url en el correo que se envía al registrar.

![imagen](https://user-images.githubusercontent.com/67064375/125054857-ef5d6380-e0a6-11eb-85ef-36a1531ae29e.png)

**Comment by jsastre-dgtic** [comment]
Ens hauríeu d'explicar on es configura i com per a poder validar la issue.

**Comment by jparedes-indra** [comment]
La externalización de estas url se ha hecho de forma que desde la configuración de entidad se puede realizar. Por lo tanto, si vamos a configuración de entidad veremos esto: 
![image](https://user-images.githubusercontent.com/67064375/129153372-dd6eec04-228f-4d71-bc9b-59fc0f42ca08.png)
Aquí, se puede configurar la url de la sede electrónica. Como podemos ver, si utilizamos por ejemplo TEST-EMAIL para registrar y que se envíe un mail, el hipervínculo de la Sede Electrónica será el indicado en la configuración de entidad: 
![image](https://user-images.githubusercontent.com/67064375/129153984-b7cf8123-d9e1-4f4a-8f88-431b78471177.png)
![image](https://user-images.githubusercontent.com/67064375/129153993-fe295c95-f01b-4376-8ffb-e4f305190252.png)

**Comment by jsastre-dgtic** [comment]
El que diu la issue no és configurar la url de la seu electrònica. Aquesta issue demana externalitzar la plantilla del correu que ens arriba com a ciutadans quan realitzam un tràmit amb S2:
![image](https://user-images.githubusercontent.com/18436867/129329267-4a0f44e4-0e5c-452e-87ee-c5dfa09936b3.png)

El que necessitam és saber on és aquesta plantilla i si s'ha externalitzat per poder fer proves amb el format i contingut del correu automàtic.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
Para probar esta issue, en el pase que se ha realizado se han añadido dos plantillas de mail similares a las genéricas, las cuales tendréis que añadir en las entidades correspondientes en caso de querer utilizar plantillas. En caso de que no se utilicen, el mail que se enviará será el genérico utilizado hasta ahora.
Para añadir las plantillas, tenéis que ir a Configuración de Entidad-> Registro -> Plantilla para mail fin de registro
![image](https://user-images.githubusercontent.com/67064375/132844924-fed45bb9-0f8a-4ce6-87a7-b595b249d367.png)
Después, con TEST-EMAIL, se puede probar que funciona correctamente. Estas plantillas, admiten añadir placeholders, tal y como veréis en los ejemplos. Estos placeholders son los siguientes: 
	${NUMERO_REGISTRO}
	${URL_SEDE}
	${URL_CARPETA}
	${URL_LOGO}
Los podéis encontrar siempre en la ayuda de la configuración de entidad, y en las plantillas adjuntas veréis ejemplos de su uso.

**Comment by jsastre-dgtic** [comment]
Tenim un problema amb el logo, al STT i al correu no hauríen de coincidir amb el mateix arxiu, perquè a la capçalera de STT necessitam que sigui blanc i després al correu no es veu res perquè mostra blanc sobre blanc:

![image](https://user-images.githubusercontent.com/18436867/133061848-41196952-8c2b-43d4-89ef-86d57eec350c.png)

![image](https://user-images.githubusercontent.com/18436867/133061908-6567c786-c6b5-46d8-9455-cf59eb9fad8f.png)

**Comment by jsastre-dgtic** [comment]
No acabam de trobar sentit a que surtin 2 enllaços a la mateixa carpeta (els dos apunten a https://dev.caib.es/carpetafront/), podríen apuntar al registre concret tal i com es demanava a la issue 357?

![image](https://user-images.githubusercontent.com/18436867/133062464-e5d3977e-2082-4f72-a6f2-b4e70a9a14cc.png)

**Comment by jparedes-indra** [comment]
Se ha adjuntado la plantilla de correo tal y como se indica en la issue en el último pase de la versión 1.2.0. Ya redirige a la URL del registro concreto de Carpeta.

**Comment by jsastre-dgtic** [comment]
tot correcte
