### ISSUE TITLE
STG: Gestió de la seguretat

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#17]
Implementació de la gestió horitzontal de la seguretat d'accés a les pantalles segons rol

**Comment by rsanz-indra** [comment]
Ya está implementado el control de seguridad de acceso a ventanas y operativas según rol.
En las pantallas desarrolladas hasta ahora se ha incorporado el control. En las próximas se irá incorporando.
Por tanto hay que tener en cuenta que se han definir correctamente los roles tanto a nivel de aplicación como a nivel de seycon para poder acceder a pantallas/operativas.

**Comment by sgelabert-dgtic** [comment]
Una vegada autenticat només puc actuar com a perfil superAdministrador, és a dir, no em permet canviar el rol via aplicació. A continuació us pas còpia dels rols que tinc assignats sobre l'entorn de DES:
```
"UGR_CODGRU"
	"STG_ADM"
	"STG_ADM@web-des"
	"STG_ADM@weblogic-pre"
	"STG_DES"
	"STG_DES@web-des"
	"STG_DES@weblogic-pre"
	"STG_DES_SALUT"
	"STG_DES_SALUT@web-des"
	"STG_DES_SALUT@weblogic-pre"
	"STG_SUP"
	"STG_SUP@web-des"
	"STG_SUP@weblogic-pre"

```

**Comment by sgelabert-dgtic** [comment]
Ok.  Una cosa, tot i a tenir assignat el rol amb anterioritat a nivell seycon s'ha de sortir de la sessió i autenticar-se de nou perquè et permeti el canvi de perfil després d'assignar l'usuari a una entitat.
Entenc que és un problema menor, però podríem mirar d'evitar-ho ?

**Comment by rsanz-indra** [comment]
La lista de entidades accesibles se cachea a nivel de sesión por temas de rendimiento, ya que si no implicaría que a cada carga de una página se tendría que refrescar (carga de entidades, verificación de perfiles y control accesos por permisos/roles, etc.).
Como al asignar un role en JAAS (seycon) implica volver a hacer login, se estableció este cacheo (aunque no es el caso que se comenta, ya que como dices el role en seycon ya estaba dado).
Por tanto está implementado así por temas de rendimiento y para hacerlo "coherente" como funciona JAAS. Si se quiere "refrescar" la información de acceso a entidades sin salir de sesión, podemos poner algún botón a nivel de cabecera para ello, pero no complicaría demasiado la cosa y dejaría que ante un cambio de roles en seycon o acceso a entidad indicar que se deba reiniciar sesión.

**Comment by sgelabert-dgtic** [comment]
OK, ho passam al #22
