### ISSUE TITLE
STT: Plantilla de correus de finalització de tràmit: externalitzar

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#170]
Actualmente la plantilla y los textos a usar pertenecen a la aplicación. Se debería externalizar.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (de3bcce), apadiendo la posibilidad de indicar la url de la sede electrónica en la configuración de entidad y añadiendo esa url en el correo que se envía al registrar.

![imagen](https://user-images.githubusercontent.com/67064375/125056459-8c6ccc00-e0a8-11eb-86c3-33600a49b92d.png)

**Comment by jsastre-dgtic** [comment]
Pendent de STG: Plantilla de correus de finalització de tràmit: externalitzar #169

**Comment by jsastre-dgtic** [comment]
No s'especifica com validar aquesta issue.

**Comment by jparedes-indra** [comment]
Mirar #169

**Comment by jsastre-dgtic** [comment]
El que diu la issue no és configurar la url de la seu electrònica. Aquesta issue demana externalitzar la plantilla del correu que ens arriba com a ciutadans quan realitzam un tràmit amb S2:
![image](https://user-images.githubusercontent.com/18436867/129329267-4a0f44e4-0e5c-452e-87ee-c5dfa09936b3.png)

El que necessitam és saber on és aquesta plantilla i si s'ha externalitzat per poder fer proves amb el format i contingut del correu automàtic.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
Ver comentario de la #169

**Comment by jsastre-dgtic** [comment]
Veure comments: 
https://github.com/GovernIB/sistra2/issues/169#issuecomment-918024794
https://github.com/GovernIB/sistra2/issues/169#issuecomment-918018125

**Comment by jparedes-indra** [comment]
Ver comment #169: https://github.com/GovernIB/sistra2/issues/169#issuecomment-929228596

**Comment by jsastre-dgtic** [comment]
tot correcte
