### ISSUE TITLE
STT: Tràmits tipus esmena o aportació

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#173]
Montar trámites tipo subsanación o aportación, que en base al usuario autenticado o bien a un parámetro que identifique al expediente (lo da Carpeta o bien se pide al usuario que lo meta) se auto configure el trámite mediante los scripts. Trámites de instrucción (al menos emplenado plantilla genérica de instrucción) para todos los procedimentos.

**Comment by avillen-dgtic** [comment]
Es tanca aquesta tasca per canvis de l'organització i gestió d'aquest tipus de tràmits
