### ISSUE TITLE
STG: Visor de dades estadístiques de tramitació

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#179]
Es requereix un mòdul d’estadístiques per saber ús i volum de tramitació de cada procediment i tràmit per cada DIR3. SISTRA2 proporciona en el API Rest funciones para extraer estos datos y explotarlo aparte. 
Determinar si se ha de construir un módulo personalizado (tipo SISTRA1-Audita) o bien hay que usar alguna herramienta ya existente (tipo Pentaho).

**Comment by jsastre-dgtic** [comment]
Per ara ens centrarem en l'API que proporcioni les dades necessàries per estadística i es descarta cap eina ad hoc
