### ISSUE TITLE
STG: Processos automàtics

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#18]
Implementar un mecanisme que permeti a una sola instància autoconfigurar-se com a mestra, de manera que els processos automàtics s'executin de forma coordinada únicament per aquesta instància.

**Comment by rsanz-indra** [comment]
Se ha completado el desarrollo. Este mecanismo se podría replicar para los procesos automáticos necesarios en otros módulos (STT y STH).
