### ISSUE TITLE
STG: Firma no criptogràfica

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#180]
En SISTRA1 se impementó PERO no se llegó a emplear (quedó pendiente el cierre de aspectos legales y, a nivel técnico, realizar la reautenticación del ciudadano antes de dar el consentimiento de firma). Teniendo en cuenta que el componente horizontal LoginIB es el encargado de recoger las evidencias del ciudadano, la CAIB ha de decidir si se traslada esa firma al Portafirmas para que se consuma a través de Firmaweb.

**Comment by jsastre-dgtic** [comment]
Entenem qua hauria de ser un nou mètode de portafib

**Comment by jsastre-dgtic** [comment]
Descartam tasca per no pertànyer a Sistra
