### ISSUE TITLE
STT: Firma no criptogràfica

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#181]
En SISTRA1 se impementó PERO no se llegó a emplear (quedó pendiente el cierre de aspectos legales y, a nivel técnico, realizar la reautenticación del ciudadano antes de dar el consentimiento de firma). Teniendo en cuenta que el componente horizontal LoginIB es el encargado de recoger las evidencias del ciudadano, la CAIB ha de decidir si se traslada esa firma al Portafirmas para que se consuma a través de Firmaweb.

**Comment by jsastre-dgtic** [comment]
Entenem que hauria de ser un mètode més a portafib
