### ISSUE TITLE
STT: Pantalla de selecció de signatura: millorar

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#188]
Debería mostrar la mano desde el principio para realizar la selección directamente o indicarse mediante un icono giratorio que espere…

**Comment by jsastre-dgtic** [comment]
Ara mateix tenim la seqüència següent:
1.- La veim correcta:
![image](https://user-images.githubusercontent.com/18436867/149739543-a195b8ea-063c-43f5-8d78-fc08c1016fce.png)

2.- La pantalla popup és exageradament gran, fer-la responsive depenent de les opcions que torni pfib.
![image](https://user-images.githubusercontent.com/18436867/149739745-c1ac9872-9ed3-4667-9c55-b3ec5e4c324b.png)

3.- Reduir també la següent:
![image](https://user-images.githubusercontent.com/18436867/149739880-38e3dc13-87c7-4e4a-b446-3c8bea16c7c7.png)

4.- Ok
![image](https://user-images.githubusercontent.com/18436867/149740022-fd8bb8e4-4363-4026-b068-35c2fd0fc476.png)

5.-Ok
![image](https://user-images.githubusercontent.com/18436867/149740015-eb86b40c-435b-4011-87f7-c846730e288b.png)

6.- Ok
![image](https://user-images.githubusercontent.com/18436867/149740167-2306c4af-aaff-483f-a6f0-f01f6370e67f.png)

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

**Comment by aagudo-indra** [comment]
Con tal de poder personalizar el tamaño de la ventana emergente de firma, se han añadidodos propiedades globales en sistrages, las cuales permiten indicar el ancho y el alto de esta ventana. Estas propiedades son:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161063112-5ec125d7-5ef5-4244-86de-89575996ae99.png">

<img width="337" alt="image" src="https://user-images.githubusercontent.com/88820558/161063142-86cfb797-c8b8-4e1b-9cca-27a1f0019b2a.png">

**Comment by jsastre-dgtic** [comment]
Ha millorat prou. Aquestes lletres depenen de sistra2 o de pfib? Potser es podria reduir la mida?

![image](https://user-images.githubusercontent.com/18436867/161231130-6a04fe84-8b9a-4f5c-af58-4b4e852dcac2.png)

**Comment by aagudo-indra** [comment]
Les lletres depenen de pfib
