### ISSUE TITLE
STG: Implementació de la lògica de les pantalles II

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#19]
Es continua amb la implementació de la lògica de les pantalles iniciada en el tiquet #16:
- Mòdul d'Administrador d'Entitat / Desenvolupador:
    - Manteniment de versions 
    - Manteniment versió del tramit (passes de tramitació flux normalitzat)
    - Disseny de formulari 
    - Permetre moure un tràmit entre àrees

**Comment by rsanz-indra** [comment]
Al cierre del ciclo 4 el estado es el siguiente:

- Versiones trámite / Versión trámite (pasos tramitación): no se ha completado la tarea, queda pendiente de finalizar la edición de los pasos anexar, pagar y registrar.

- Diseño formulario: esta tarea sigue la planificación prevista y se prevé finalizarla durante este siguiente ciclo. Se ha contemplado a nivel de diseño la edición de varias páginas.

**Comment by rsanz-indra** [comment]
Se amplia el alcance de esta tarea para finalizar las tareas pendientes del anterior ciclo y las previstas para este ciclo.

**Comment by sgelabert-dgtic** [comment]
Tot i que la tasca està en desenvolupament, afegeix-ho alguns comentaris perquè es tinguin en compte;
- L'accés a la pantalla de definició de versions hauria de mostrar per defecte les "Propietats". Ara apareix en blanc.
- Segons l'anàlisi les pantalles d'scripts de personalització  i parametrització de tràmits haurien de tenir 3 bloc diferenciats (informació, eines i edició). En la implementació actual hi manca el bloc d'eines que permeti accedir als plugins, dominis, camps de formularis, etc.)
- En el control d'accés al tràmit no apareixen els botons "datepicker" i no permet especificar l'hora en els camps "Inici i "Fi" de Desactivació. S'hauria de mantenir la coherència amb la resta (veure Missatge d'avis d'entitat -- que per cert té un error pq l'única de manera de sortir es picar fora de la finestra--). 
Endemés cal invertir el concepte d'activació/desactivació, és a dir, un tràmit pot estar actiu o no i en cas d'estar actiu es poden establir dates d'inici i fi d'activitat (no obligatòries), fora d'aquest període es llança missatge configurat de tràmit no disponible.
A banda d'això es localitzen diverses errades que entenc que són pròpies de l'estat de desenvolupament de la tasca: "Missatge de desactivació", "Interval", etc.

**Comment by rsanz-indra** [comment]
- Modificamos funcionamiento para preseleccionar "Propiedades" al entrar en la ventana.
- Para la versión inicial de SISTRA2 está planificada una ventana de scripts "básica", sin el panel de herramientas lateral (plugins, dominios,...). Se ha ocultado en esta primera versión para no marear.
- En la funcionalidad de desactivación de un trámite, realmente nos hemos dado cuenta que tenemos la funcionalidad "duplicada": podemos desactivar temporalmente un trámite desde el Control de acceso y desde los Mensajes de aviso de entidad. Pensamos que lo mejor, sería dejar esta funcionalidad sólo en los Mensajes de aviso, ya que ofrece más versatilidad y estarían centralizados los bloqueos/avisos temporales que se realizan sobre los trámites (confirmarnos si realizamos este cambio). Respecto al funcionamiento del datepicker con hora, efectivamente la única forma de salir es clicando fuera del componente (este funcionamiento es propio del componente de Primefaces: https://www.primefaces.org/showcase/ui/input/calendar.xhtml).

**Comment by rsanz-indra** [comment]
Creo que esto ya lo hemos comentado anteriormente, el perfil de "gestor de área / administrador de área" no se contempló como tal en la fase de análisis y diseño. Lo que existe es un perfil "desarrollador" al que se le pueden asignar permisos sobre áreas.
Dicho esto, se podría hacer que para un perfil "desarrollador" con determinado permiso sobre ciertas áreas (p.e. "Alta/Baja) pueda mantener avisos sobre trámites específicos de esas áreas (serían avisos de tipo "Lista de trámites" y se debería comprobar que los trámites que se indiquen pertenecen a las áreas sobre las que se tiene permiso).  En este caso se podría renombrar el permiso "Alta/Baja" a "Administrar" para darle un sentido más genérico, ya que además de dar de alta trámites y dominios, podría gestionar avisos de la forma que se ha comentado.

Respecto al datepicker, lo revisamos.

**Comment by jsastre-dgtic** [comment]
Missatges d’avís d’entitat:
1.- Només ha de ser accesible pels Administradors d’Entitat.
2.- No queda clar què passa si emplenam les dates “in/fi” i res més. Queda desactivat? Activat? O simplement surt l’avís de l’Entitat definit? 
Consideram que:
-La pantalla “Missatges d’Entitat” hauria d’anomenar-se “Control d’Accés i Missatges d’Entitat”. 
- Hi manca un check ”Desactivar” al mateix nivel que el de “Bloquejat” (que s’hauria de dir “Bloquejar”)
- El camp de text lliure s’hauria de fer visible només en el cas de triar “Llista de tràmits” al desplegable. També seria millor ubicar-lo just davall el camp desplegable.
3.- Tampoc queda clar la diferencia que marca tenir activat el check de Bloquejat. Es desbloqueja automàticament en arribar a la Data fi o manualment?
	Consideram que hauria d’automatitzar-se tal i com ho hauria de fer el check nou de “Desactivar”
3.- Tampoc no ens queda clar quin tipus de control tendrem al camp de text lliure “Llista de tràmits”. Què passa si ens equivocam picant el Codi del/s tràmit/s?
4.- Entenem que la funcionalitat de desactivar un tràmit concret no l’hem d’eliminar, perquè és més pràctica si el que volem és desactivar un sol tràmit. Ha de ser accesible pels “Administradors d’Àrea”, que per noltros serán desenvolupadors amb el permís Alta/Baixa de tràmits atorgat. 
5.- Mantenint aquesta funcionalitat, demanam el que s’havia dit: https://github.com/GovernIB/sistra2/issues/19#issuecomment-394331400
-Cal invertir el concepte d'activació/desactivació, és a dir, un tràmit pot estar actiu o no i en cas d'estar actiu es poden establir dates d'inici i fi d'activitat (no obligatòries), fora d'aquest període es llança missatge configurat de tràmit no disponible.

**Comment by rsanz-indra** [comment]
Intentamos aclarar la funcionalidad de los avisos:
- La fecha de inicio/fin definen el plazo de "vigencia" del aviso, mientras esté vigente el aviso saldrá dicho aviso para el conjunto de trámites que aplique (teniendo en cuenta la lógica que se comentó respecto a si una fecha estaba rellenada o no).
- Respecto al concepto de "Bloquear", si está activado, significa que mientras esté vigente el aviso se bloquea el acceso al trámite, no se podrá iniciar la tramitación. Por tanto la gestión es automática respecto al plazo del aviso.
- El concepto de "activo" no aplica a nivel de aviso, es algo que se define a nivel de versión de trámite. Los avisos no se utilizan para indicar si una versión de trámite está activa o no, es algo propio de la versión de trámite. Los avisos se utilizan para realizar avisos temporales sobre un conjunto de trámites con opción a no dejar iniciar (bloquear).

Respecto a la forma de indicar la lista de trámites cuando es un aviso de tipo "Lista de trámites" ya se comentó que para una primera versión se realizaba esta solución simple y para una próxima versión se introduciría funcionalidad para poder buscar y seleccionar trámites. 
 
Realizamos el cambio de la opción "Mensajes de entidad" por "Control de acceso y mensajes de entidad" (vemos si no se desmonta el menú al ser tan largo) y mantenemos la funcionalidad de desactivación a nivel de trámite desde pantalla de Versión de Trámite (entendemos que un desarrollador por permiso "Alta/Baja" podrá mantener la pestaña de "Control de acceso" en pantalla de Versión de Trámite.

Respecto a esto no entendemos lo que queréis:
`Cal invertir el concepte d'activació/desactivació, és a dir, un tràmit pot estar actiu o no i en cas d'estar actiu es poden establir dates d'inici i fi d'activitat (no obligatòries), fora d'aquest període es llança missatge configurat de tràmit no disponible.`

El concepto de "activo" está pensado para marcar versiones de trámite que ya no se utilizan, es decir, tiene un significado temporal más definitivo.
El concepto de "desactivación" está pensado para paradas temporales programadas (p. ej.: tareas de mantenimiento sobre el trámite, paradas programadas, etc.). Es decir, sería equivalente a un aviso de entidad con la opción marcada de bloquear.
Hay que tener en cuenta que los plazos de un trámite se establecen en el Catálogo de procedimientos y servicios, no a nivel de Versión de Trámite.

**Comment by sgelabert-dgtic** [comment]
Traspàs aquí conclusions conversa telefònica respecte d'aquest tiquet:
- Es reserva el nom "bloqueig/desbloqueig" de tràmits per al backoffice, en el sentit de bloquejar el tràmit durant la configuració/manipulació d'aquest.
- Es lliga el nom "actiu" a la versió/versions del tràmit que estan operatives. A priori es considera que sobre l'entorn de producció no hauria de ser possible tenir més d'una versió activa del tràmit.
- El nom "deshabilitar accés" es relaciona amb la capacitat dels administradors d'entitat i desenvolupadors amb permisos de impedir l'accés al tràmit des del frontal. 
- A priori es considera útil que un desenvolupador amb permisos pugui deshabilitar l'accés a un tràmit des de la pantalla de de "Definició de versions" --> "Control d'accés".
- Es considera útil també que un administrador d'entitat pugui deshabilitar l'accés a tràmits de manera global des de l'opció "Control d'accés i missatges d'entitat". S'avaluarà si és possible que la pantalla reflecteixi els canvis fets des de la "Definició de versions"

**Comment by amaciam-indra** [comment]
A continuació s'adjunta alter parcial per upgrade a versió del commit 6c962be
[ALTER_STG.txt](https://github.com/GovernIB/sistra2/files/2133742/ALTER_STG.txt)

**Comment by amaciam-indra** [comment]
A continuació s'adjunta alter parcial per upgrade a versió del commit be114f3
[ALTER_STG.txt](https://github.com/GovernIB/sistra2/files/2155820/ALTER_STG.txt)

**Comment by rsanz-indra** [comment]
Queda pendiente el tema de la adaptación de cambios para mejorar la usabilidad. Están comiteado algunos  cambios (dobleclick y enlazar alta de formularios/anexos/tasas con la edición) y otros están a mitad (pantalla de trámites/versiones).

**Comment by amaciam-indra** [comment]
A continuació s'adjunta alter parcial per upgrade a versió del commit 07f4db4
[ALTER_STG.txt](https://github.com/GovernIB/sistra2/files/2176589/ALTER_STG.txt)

**Comment by sgelabert-dgtic** [comment]
Cal tenir en compte les recomancacions dels estandards de BBDD en quan al tipatge de camps VARCHAR2 (pàg. 9 - http://www.caib.es/sites/dgtic/ca/estandards_de_desenvolupament-7621/archivopub.do?ctrl=MCRST299ZI51195&id=51195). Per això s'ha d'afegir CHAR en la declaració del tipus.
![image](https://user-images.githubusercontent.com/17268396/42493709-58d30362-841e-11e8-9199-7876ae453673.png)

Quan pogueu feis una revisaió dels l'script generals sistrages_create_schema.sql i sistramit_create_schema.sql per evitar aquests errors.

**Comment by rsanz-indra** [comment]
Revisado script para ajustar a VARCHAR2(n CHAR)

**Comment by sgelabert-dgtic** [comment]
Adjuntem errades localitzades amb la versió https://github.com/GovernIB/sistra2/commit/07f4db4
- [Definició de versió] L'opció "propietats" no es editable, ni amb botó d'edició ni amb doble click
- [Definició de versió] El dominis emprats només apareixen en mode consulta. Revisar
- Bug molla de pa en la definició de les versions del tràmit. A vegades es fa referència al Codi de Tràmit i d'altres a la descripció del tràmit
- No trobam l'accés al Dissenyador de Formularis

Ens interessa sabre l'estat d'aquesta tasca a la finalització del 6è cicle. Les millores d'usabilitat es traslladen al tiquet #34

**Comment by rsanz-indra** [comment]
Revisamos el bug molla de pa.

Respecto al resto de cosas comentadas, ¿se ha bloqueado la versión del trámite para edición? Si no aparecerá en modo consulta. El acceso al diseñador de formularios se realiza desde las propiedades de un formulario.

**Comment by rsanz-indra** [comment]
Se corrige bug en la miga de pan

**Comment by rsanz-indra** [comment]
Precisamente para modificar una versión de trámite debe bloquearse para cambios.  El usuario que bloquea la versión es quién puede hacer cambios.
Hemos comprobado en vuestra instalación y efectivamente NO está bloqueada.

Para entrar en modo edición **hay que bloquear** la versión

**Comment by sgelabert-dgtic** [comment]
OK, el que embulla doncs és el "Control d'accés" sense bloquejar el tràmit:
- No accedeix a edició amb un doble click a l'edició per la desactivació.
- Per incorporar un nou "Missateg d'avís" s'ha de passar per un nou manteniment en una finestra addicional, quan els camps (Deshabilitar accés, Data inici, Data fi i Missatges d'avís) podrien ser directament editables. Es podria incorporar un nou check en desactivació per evitar haver d'esborrar tot els camps quan es vol eliminar un missatge.
- No es controla que la Data d'Inici sigui menor que la Data de Fi
- Canviar literal "Nre. tramitacions" per "Núm. tramitacions"
- El camp deshabilitar accés es marca com obligatori i no es comporta com a tal.
- La molla de pa ha d'actuar sobre cada element:
   - Quan s'entra en la pantalla de definició de versió ha de marcar l'opció per defecte "Propietats"
   - El codi d'àrea ha d'enllaçar a la pantalla de tràmits l'àrea seleccionada i mostrar tots els tràmist
   - El codi del tràmit ha d'enllaçar a la pantalla de tràmits amb el tràmit seleccionat
   - La versió del tràmit  ha d'enllaçar a la pantalla de tràmits amb la versió seleccionada
 - Amb els darrers canvis no veim com podem donar d'alta un tràmit nou en una àrea

**Comment by rsanz-indra** [comment]
Comentamos:

- _No accedeix a edició amb un doble click a l'edició per la desactivació._
¿Te refieres a Control de accceso en la pantalla de versión? Si hacemos dobleclick sí que nos abre la ventana.

- _Per incorporar un nou "Missateg d'avís" s'ha de passar per un nou manteniment en una finestra addicional, quan els camps (Deshabilitar accés, Data inici, Data fi i Missatges d'avís) podrien ser directament editables. Es podria incorporar un nou check en desactivació per evitar haver d'esborrar tot els camps quan es vol eliminar un missatge._
Está realizado así para reutilizar la pantalla de mensaje de aviso, de forma que se utiliza la misma tanto desde versión de trámite como desde 
Como es una operativa que no será habitual pensamos que es mejor que se quede así, reaprovechando la misma ventana.
En todo caso si se quiere que se cambie se podría poner como mejora pospuesta para no penalizar el retraso que estamos teniendo.

- _No es controla que la Data d'Inici sigui menor que la Data de Fi_
Implementamos validación

- _Canviar literal "Nre. tramitacions" per "Núm. tramitacions"_
Cambiamos literal

- El camp deshabilitar accés es marca com obligatori i no es comporta com a tal.
¿Te refieres al checkbox de "Deshabilitar acceso" en "Control de acceso"? Es un checkbox y por lo tanto siempre tendrá valor (activo o no activo). ¿A que se refiere de marcar como obligatorio y no se comporta como tal?

- _La molla de pa ha d'actuar sobre cada element:_
   - _Quan s'entra en la pantalla de definició de versió ha de marcar l'opció per defecte "Propietats"_
    Hemos tenido problemas con esto, no hemos podido hacer que se quede seleccionado en el árbol. Se puede apuntar como una mejora pospuesta.

   - _El codi d'àrea ha d'enllaçar a la pantalla de tràmits l'àrea seleccionada i mostrar tots els tràmist_
    Este comportamiento ya lo hace, muestra nueva ventana de áreas/trámites/versiones con el área seleccionada
   - _El codi del tràmit ha d'enllaçar a la pantalla de tràmits amb el tràmit seleccionat_
   - _La versió del tràmit  ha d'enllaçar a la pantalla de tràmits amb la versió seleccionada_
   Esto es un problema, ya que habría que ver si es factible. Implicaría poder seleccionar tanto en datatable padre como anidado teniendo en cuenta que las búsquedas están paginadas.
 Esto habría que dejarlo como una mejora pospuesta para no penalizar el retraso.

**Comment by rsanz-indra** [comment]
Ok. Si te parece pasamos el cambio del mensaje de aviso a la tarea #34 como mejora de usabilidad así podemos dar esta tarea por finalizada y no ampliarla más.

**Comment by sgelabert-dgtic** [comment]
Traslladat funcionalitat al tiquet #34
