### ISSUE TITLE
STG: Pantalla d'importació de tràmits: dimensionar

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#195]
La pantalla para importar versión es demasiado grande y para alcanzar los botones de control inferiores es necesario arrastrar la barra de título.
Hacer que aparezca un scroll para trabajar mejor con esa pantalla.

**Comment by jparedes-indra** [comment]
Se resuelve en versión 1.2.0 y despliega en CAIBter, pero no en DEV.

**Comment by jsastre-dgtic** [comment]
L'scroll només apareix a la secció del mig, fer que surti l'scroll a la pantalla sencera... 
![image](https://user-images.githubusercontent.com/18436867/122744593-6a8ddf80-d288-11eb-8599-287c1509d028.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (9030c09) y se despliega en CAIBter.

**Comment by avillen-dgtic** [comment]
![image](https://user-images.githubusercontent.com/83401259/124569988-c048b700-de46-11eb-8f70-deaaf29fc708.png)
L'scroll està desplaçat al costat dret com era d'esperar. Quan es fa un canvi en la proporció del diàleg el comportament és bo.
