### ISSUE TITLE
STT: Modificar l'apartat "annexar documentació"

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#199]
La frase «Podeu annexar 10 fitxers en aquesta passa d’Annexar. Les extensions permeses són: PDF,ODT,DOC,DOCX,JPG, PNG,ZIP,RAR. La mida màxima és de 10MB», aparece en la pantalla principal, debajo del cuadro «Annexar document», i también   cuando se abre el cuadro para adjuntar los documentos, por lo que puede eliminarse de la pantalla principal, al ser reiterativa.

**Comment by avillen-dgtic** [comment]
Tanquem.
