### ISSUE TITLE
MIGRACIÓ: Definició d'estrategia de migració de tràmits

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#2]
El·laborar document amb l'estratègia de migració de tràmits entre les plataformes SISTRA1 i SISTRA2. El document haurà de descriure:
- Període de coexistència i estratègia de manteniment de les plataformes.
- Selecció tràmits a migrar sobre SISTRA2
- Anàlisi de la viabilitat del manteniment de FORMS com a gestor de formularis externs.
- Estudi de la viabilitat del mantenir el processament actual de tràmits.
- Estudi dels procediments que generen notificacions electròniques.
- Determinar abast de la nova zona personal.

**Comment by rsanz-indra** [comment]
Esta tarea de análisis de migración se decidió realizar con más nivel de detalle, con lo que se comenzó con el estudio de los datos a migrar para trámites y formularios y su correspondencia entre SISTRA1 y SISTRA2. Se ha confeccionado un documento de correspondencia entre diferentes elementos que conforman los trámites activos en SISTRA1 (pendiente de revisar por DGDT). Queda pendiente la ampliación de este documento con la parte relativa a la migración de formularios.
Además de esta correspondencia de elementos, quedará determinar otros temas como procesamiento, etc.

**Comment by rsanz-indra** [comment]
Esta tarea se continua con la tarea #10

**Comment by rsanz-indra** [comment]
Esta tarea se continua y se da por finalizada en la tarea #10, por lo que se da por entregada.
