### ISSUE TITLE
STT: Assignar valor per defecte al camp selector

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#201]
En STT, el campo selector no tiene un valor por defecto seleccionado.

**Comment by jparedes-indra** [comment]
Al crear selectores con lista fija, si uno de los elementos de la lista se establece por defecto, es el que se carga al iniciar el formulario. 

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/e8930fc5-a47c-4493-9c0a-be2c1914141d)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/4263e888-aed7-45ef-8e4b-84101677a480)

Si no se establece ninguno por defecto, el componente no carga ningún valor y si se establece un valor en el script de Carga de Datos Iniciales, prevalece éste en lugar del marcado en la propia lista fija.

**Comment by jsastre-dgtic** [comment]
ok
