### ISSUE TITLE
STG: Millorar el dissenyador de formularis

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#203]
Poder cambiar el orden de las líneas y las secciones.
Si se añade un elemento y no cabe en la línea actual que cree una nueva línea a continuación de la que te encuentras y te inserte el elemento allí.

**Comment by jparedes-indra** [comment]
Si no hay espacio, se permite crear un componente en una nueva línea.
   
![imagen](https://github.com/GovernIB/sistra2/assets/67064375/4553c59a-aa0d-4953-abce-b97b25b893b3)

Además, ya se permitía mover líneas con los botones “Derecha” e “Izquierda”:
 
![imagen](https://github.com/GovernIB/sistra2/assets/67064375/cc1257f3-7f25-4755-a6c8-a42a7cfe5239)

**Comment by jsastre-dgtic** [comment]
ok
