### ISSUE TITLE
STG: Millorar el procés d'exportació de tràmits

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#205]
A la hora de exportar un trámite, estaría bien añadir un fichero de texto plano con toda la estructura y scripts en texto entendible, para permitir consultar toda la información (formularios, scripts, campos) algo que se pueda generar con un toString, que permita obtener toda la información para realizar el trámite a mano sin necesidad de importar el trámite. Esto permitiría una   comparación de 2 versiones de un trámite con un comparador de texto normal. (Este fichero no serviría para importar el trámite, simplemente es informativo en formato txt).

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

Ahora es posible extraer un resumen en formato txt del contenido del trámite y, además, al exportar aparecerá en el zip ese resumen.

![image](https://user-images.githubusercontent.com/67064375/217583418-59dfebb8-99b1-456a-9ccf-81c747b83a8f.png)

**Comment by jsastre-dgtic** [comment]
No veim cap utilitat en els camps que no podem editar o consultar amb STG. Per exempe, a la primera secció:

TramitVersio. 	 **Codi:1703**
	 NumeroVersio:5
	 **CodigoUsuariBloqueo:null
	 DadessUsuariBloqueo:null**
	 Release:34
	 Actiu:true
	 debug:false
	 Descripció:Prova simple HELIUM (Jaume Oleza)
	 **TipusTramit:T**
	 **IdTramit:66
	 IdArea:42**
	 IdentificadorArea:TESTS
	 TipusFlux:N
	 Autenticat:true
	 NoAutenticat:true
	 NivellQAA:2
	 IdiomasSoportats:es;ca
	 Persistencia:true
	 PersistenciaInfinita:true
	 PersistenciaDies:null
	 LimiteTramitacio:false
	 NumLimiteTramitacio:null
	 **IntLimiteTramitacio:null**
	 **Desactivacio:false
	 TerminiIniciDesactivacio:null
	 TerminiFiDesactivacio:null**

**Comment by jsastre-dgtic** [comment]
Consideram que en ser una funcionalitat que veuran tots els Administradors d'àrea, haurien de desaparèixer els camps esmentats i incloure una ajuda per tal d'explicar què fa aquest botó, per a què serveix i com interpretar el contingut del fitxer generat.

**Comment by jparedes-indra** [comment]
Resuelto en el TAG sistra2-1.4.2_1 (4e8b824).

Se ha añadido una ayuda para explicar las funciones de esa pantalla y el significado de algunos campos de un informe de ejemplo.
