### ISSUE TITLE
STG: Plugin de dominis remots

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#206]
Ese plugin no tiene sentido que esté a nivel de superadmin y debería estar a nivel de entidad, pero para eso habría que hacer que los dominios globales no puedan ser remotos, o distinguir 2 niveles de plugin remoto: global y entidad.
Estando a nivel de entidad sería equivalente al funcionamiento que se tiene en S1 para la gestión de usr/pwd de dominios, pero seguiría siendo a nivel de entidad. 
Otra cosa es que se plantee cambiar la gestión de los usr/pwd para gestionarlo por administradores de área.

**Comment by jsastre-dgtic** [comment]
Enviada proposta detallada a INDRA per email que implca un nou concepte de "variable de login":
![image](https://user-images.githubusercontent.com/18436867/107508555-80381d80-6ba1-11eb-9e49-0f1600b43917.png)

**Comment by jparedes-indra** [comment]
Se envia documento de análisis y estimación y se inicia desarrollo, cuyas issues relacionadas son las comprendidas entre la #291 y la #300.
[202103-SISTRA2_SecurizacionDominiosRemotos.pdf](https://github.com/GovernIB/sistra2/files/6439298/202103-SISTRA2_SecurizacionDominiosRemotos.pdf)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jsastre-dgtic** [comment]
A l'intentar configurar l'autenticació:
![image](https://user-images.githubusercontent.com/18436867/122746896-c3f70e00-d28a-11eb-819f-8f32dc82796d.png)

Dóna error:
![image](https://user-images.githubusercontent.com/18436867/122746774-a3c74f00-d28a-11eb-8dfc-e92ca079bd4e.png)

**Comment by jparedes-indra** [comment]
El error al 'Guardar' la configuración en la autenticación se produce utilizando el usuario dgmad2desa. Utilizando el usuario dgmad3desa no se produce este error, por lo que tiene que ser algo relacionado con los permiso7s y roles. Ambos son administradores de esta área, pero dgmad2desa no tienen el rol de desarrollador de área, cosa que el de dgmad3desa sí.

**Comment by jparedes-indra** [comment]
![err](https://user-images.githubusercontent.com/67064375/124267205-3d6ae800-db38-11eb-810b-b74080f8e656.gif)
![err1](https://user-images.githubusercontent.com/67064375/124267214-40fe6f00-db38-11eb-9d4a-f0466af1d96b.gif)

**Comment by jparedes-indra** [comment]
Este otro error se produce al abrir la pestaña 'Dominios' en la configuración de autenticación, seleccionar un dominio e intentar cerrat la ventana desplegable. Aquí falla con cualquier usuario.

**Comment by jparedes-indra** [comment]
Se ha resuelto el error al guardar la autenticación con un usuario con rol Desarrollador. 

![imagen](https://user-images.githubusercontent.com/67064375/124346440-1f0bf780-dbdf-11eb-93dd-8687a3037c7c.png)

Se ha resuelto el error al cerrar el popup de dominios asociados a una autenticación.

![imagen](https://user-images.githubusercontent.com/67064375/124346486-64c8c000-dbdf-11eb-8515-69c0219539bf.png)

**Comment by jparedes-indra** [comment]
Damos esta issue por resuelta y trataremos el problema del PING indicado en los correos, en la #298.

**Comment by jsastre-dgtic** [comment]
ok

**Comment by jparedes-indra** [comment]
Se resuelve un bug detectado al cerrar la pantalla de los formularios externos asociados a una autenticación, en el TAG 1.2.0 (913d950) y se despliega en CAIBter.
