### ISSUE TITLE
MULTIPÁGINA - Análisis

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#208]

**Comment by jsastre-dgtic** [comment]
Tasques necessàries per a la implementació de la funcionalitat de formulari multipàgina:

1.- Poder definir diverses pàgines per a un formulari, indicant un possible flux entre les pàgines mitjançant un script de navegació, que indicarà quina ha de ser la següent pàgina. D'aquesta manera, es permetrà definir diverses pàgines per a un formulari, però conforme sigui emplenat es podran mostrar unes pàgines o unes altres.

2.- Poder indicar si per a un formulari es permet guardar sense finalitzar el formulari. A l'introduir diverses pàgines en un formulari, es poden construir formularis més complexos en què pot ser interessant habilitar aquesta funcionalitat que permetrà a l'usuari omplir el formulari en diverses vegades.

Per donar suport a aquesta funcionalitat es veuen afectats els següents components:

- SISTRAGES (STG): s'ha de permetre introduir a nivell de formulari dels nous camps de configuració de script de navegació per una pàgina i si un formulari permet guardar sense finalitzar. Tot i que la primera versió de SISTRA2 permetia definir diverses pàgines a nivell de configuració de formulari, cal revisar aquest funcionament i adaptar-lo a la nova funcionalitat. S'haurà d'adaptar també l'API REST intern que utilitza STT per recuperar la configuració d'un tràmit.
- SISTRAMIT (STT): a partir de les noves opcions de configuració introduïdes, cal adaptar l'assistent en tots els nivells:

> o Frontal: és necessari adaptar la visualització i trucades AJAX amb la capa controladora web per contemplar les opcions de navegació entre pàgines i la nova operativa de guardar sense finalitzar.

> o Negoci: és la capa que requereix més adaptació ja que és la que conté la lògica:
 Recuperar noves propietats de configuració de la definició de l'tràmit des STG i adaptar lògica flux pas omplir per implementar els punts d'entrada de les operacions de navegació i guardar sense finalitzar.
 Adaptar gestor de formularis intern:
 Afegir a el motor de scripting el nou script de navegació entre pàgines.
 Implementar el control flux de pàgines: pila de pàgines de tipus LIFO (last-in-first-out) que permeti anar afegint / llevant pantalles completades.
 Ampliar el càlcul de dependències entre camps (estats, valors autorrellenables, valors possibles ...) per fer-lo funcionar entre diferents pàgines, contemplant la gestió d'inicialització o actualització de les mateixes conforme s'avanci o retrocedeixi de pàgina.
 Ha de permetre sortir guardant en qualsevol moment, si està habilitada la funcionalitat de guardar sense finalitzar, gestionant la persistència en aquest estat i permetent la càrrega posterior en aquest estat.
 A l'acabar D'el formulari s'ha d'adaptar la generació de l'XML i PDF que s'obtenen com a resultat, avaluant quines pàgines s'han emplenat.
