### ISSUE TITLE
STT: Desenvolupament layout de l'aplicació II

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#21]
Incorporació de funcionalitats generals al layout #5 :
- Gestió d'errors
- Login d'accés
- Seguretat

**Comment by rsanz-indra** [comment]
Se han desarrollado diversos aspectos generales de la aplicación: gestión y logs de errores, login anónimo y autenticado con Cl@ve (simulado), gestión de la sesión de tramitación,…

**Comment by sgelabert-dgtic** [comment]
Adjunt error de desplegament amb la darrera versió commitada [error_deploy_sistramit.txt](https://github.com/GovernIB/sistra2/files/1986589/error_deploy_sistramit.txt)

**Comment by rsanz-indra** [comment]
Parece que hay un problema de dependencias al desplegar STG y STT a la vez.
Lo revisamos.

**Comment by rsanz-indra** [comment]
Ya se despliegan correctamente las aplicaciones.
Se ha pasado la propiedad para especificar la ruta de almacenamiento al properties de la aplicación, ya que se requiere tenerla en el properties para definirla como recursos estáticos para mejorar rendimiento.

En el properties de sistrages y sistramit hay que añadir la propiedad: ficherosExternos.path con el path (hay ejemplo en el fichero de propiedades).
Quedaría borrar esta propiedad de la tabla de propiedades globales: 
DELETE FROM STG_CNFGLO WHERE CFG_PROP = 'ficherosExternos.path'

**Comment by sgelabert-dgtic** [comment]
Seguim tenint errors [server.log](https://github.com/GovernIB/sistra2/files/2021687/server.log).
Adjunt canvis en la configuració de l'entorn de DES:
- /app/jboss-7.0/server/jboss04/deploycaib
  - sistramit.properties --> es.caib.sistramit.properties.path=/app/caib/sistramit/sistramit.properties
  - sistrages.properties --> es.caib.sistrages.properties.path=/app/caib/sistrages/sistrages.properties
- /app/caib/sistramit/
  - sistramit.properties --> ficherosExternos.path=/app/caib/sistra2/files
- /app/caib/sistrages/
  - sistrages.properties --> ficherosExternos.path=/app/caib/sistra2/files
- Executat `DELETE FROM STG_CNFGLO WHERE CFG_PROP = 'ficherosExternos.path'`

**Comment by amaciam-indra** [comment]
Sembla que l'error es produeix perquè falta executar la sentencia següent de sistrages_create_data.sql:

Insert into STG_PROCES (PROC_IDENT,PROC_INSTAN,PROC_FECHA) values ('MAESTRO','NONE', sysdate);

**Comment by sgelabert-dgtic** [comment]
- Sentència insert executada.
- Adjunt error just després de l'autenticació [server.log](https://github.com/GovernIB/sistra2/files/2021968/server.log)

**Comment by amaciam-indra** [comment]
A la versió que estau provant ha hagut canvis al model de dades i per tant s'hauria de recrear l'esquema de SISTRAGES. Un altre opció és que feu els alters a partir dels canvis introduïts a la darrera versió de l'script de creació de l'esquema.

**Comment by sgelabert-dgtic** [comment]
OK, recreat esquema de BBDD, ara pareix que funciona.
Curiosament no m'ha donat l'error https://github.com/GovernIB/sistra2/issues/4#issuecomment-383468145.

**Comment by sgelabert-dgtic** [comment]
No veim com podem testejar el login (anònim i autenticat Cl@ve --simulat--) d'accés al frontal.

**Comment by rsanz-indra** [comment]
A nivel visual no se va a ver gran cosa, a nivel interno está montado la lógica para realizar la autenticación anónimo o la gestión de redirecciones cuando se conecte con Cl@ve (se pueden ver en modo debug del panel de red del navegador):

http://host:puerto/sistramitfront/asistente/iniciarTramite.html?tramite=x&version=1&idioma=es&idTramiteCatalogo=y
