### ISSUE TITLE
STG: Millores no critiques Sistema Gestor de Tràmits

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#22]
Llistat de millores detectades ordenades per prioritat:
1. #16 Dominis d'àrea / Fonts de dades
    - Afegir molla per poder identificar a quina àrea pertany el domini i endemés retornar a l'àrea de navegació"
2. #12 Gestió de domini global 
    - No demana confirmació alhora d'eliminar una propietat amb la toolbar vertical.
3. #16 Missatges d'Entitat [rol Adm/Des]
   - Implementar opció "Llista de tràmits" per especificar tràmits on actua el missatge
4. #17 Afegir botó de refresc en la capçalera per actualitzar la informació d'accés 
5. #12 Per als botons que únicament tenen icona, afegir tooltip (exemple gestió de domini)
6. #12 En les finestres modals convindria canviar el títol en funció de l'acció. Per exemple, si botó "Editar" --> "Edició d'Entitats", si botó "Nou" --> "Alta d'Entitat". 
7. #22 Permetre limitar l'accés a tràmits d'una àrea per al rol desenvolupador
8. #19 La molla de pa ha d'actuar sobre cada element:
       - Quan s'entra en la pantalla de definició de versió ha de marcar l'opció per defecte "Propietats"
       - El codi d'àrea ha d'enllaçar a la pantalla de tràmits l'àrea seleccionada i mostrar tots els tràmist
       - El codi del tràmit ha d'enllaçar a la pantalla de tràmits amb el tràmit seleccionat
       - La versió del tràmit ha d'enllaçar a la pantalla de tràmits amb la versió seleccionada

**Comment by rsanz-indra** [comment]
#16 Missatges d'Entitat [rol Adm/Des]
Implementar opció "Llista de tràmits" per especificar tràmits on actua el missatge

Implementado (Inicialmente de forma básica con una lista de códigos separados por ";". Más adelante se puede implementar de forma más asistida con listado de añadir/quitar con selector)

**Comment by rsanz-indra** [comment]
#12 Per als botons que únicament tenen icona, afegir tooltip (exemple gestió de domini)

Implementado

**Comment by jsastre-dgtic** [comment]
#34 Noves propostes a tenir en compte per a STG:
1.- Presentar proposta per traduir automàticament català/castellà
2.- No canviar el coloret del “Vist” quan tenim seleccionada la fila. Ara canvia de blanc a groc. Deixar el blanc per evitar confusions del que vol dir. Aplicar-ho d'aquesta manera a tota l'aplicació.

**Comment by jsastre-dgtic** [comment]
#35 Com a millora es podria modificar la finestra de selecció de dominis al formulari per tal que tregui primer els "Dominis emprats" i a més et donàs l'opció d'afegir un domini.

**Comment by jsastre-dgtic** [comment]
#78 Tancam aquesta i obrim la STG: Millores no crítiques pendents (Cicle12) #78 per deixar només les pendents.
