### ISSUE TITLE
Multipàgina - STT - Desenvolupament: Gestor intern: flux pàgines

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#220]

**Comment by jparedes-indra** [comment]
Se ha corregido en la versión 1.2.0 e instalado en CAIBter, pero no desplegado en DEV.

**Comment by jsastre-dgtic** [comment]
Veim que si modificam i anam envant i enrera, no s'actualitzen els valors així com tocaria: 
![image](https://user-images.githubusercontent.com/18436867/122909011-0b49d100-d355-11eb-85fd-b2474f3c0aa2.png)

![image](https://user-images.githubusercontent.com/18436867/122909054-1ac91a00-d355-11eb-9fa5-a1910494d021.png)

Potser afecta a més d'una issue...

**Comment by jsastre-dgtic** [comment]
Solucionat
