### ISSUE TITLE
Multipàgina - STT - Desenvolupament: Gestor intern: reprendre formulari

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#222]

**Comment by jparedes-indra** [comment]
Se ha corregido en la versión 1.2.0 e instalado en CAIBter, pero no desplegado en DEV.

**Comment by jsastre-dgtic** [comment]
A petició de J. Paredes tornam a l'estat de desenvolupament

**Comment by jparedes-indra** [comment]
Se ha de completar la funcionalidad de Multipágina, para permitir el guardado y reanudación a mitad de tramitación.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/126140522-0ce5e36a-714a-461a-859e-2333b6a9beec.png)

**Comment by avillen-dgtic** [comment]
El comportament és estrany, aquesta issue no està resolta. No guarda les dades quan teòricament "Guardar y salir"
![#222](https://user-images.githubusercontent.com/83401259/126461539-47041f67-e046-426f-ac0c-81150268bb7b.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(3f9c062) y se despliega y prueba en CAIBter.

**Comment by jparedes-indra** [comment]
https://user-images.githubusercontent.com/67064375/126994179-5b42e5bd-4a62-4601-8885-1a51fa015295.mp4

**Comment by avillen-dgtic** [comment]
El comportament és correcte.
