### ISSUE TITLE
Multipàgina - STT - Desenvolupament: Adaptació generació XML

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#223]

**Comment by jparedes-indra** [comment]
Se ha corregido en la versión 1.2.0 e instalado en CAIBter, pero no desplegado en DEV.

**Comment by jsastre-dgtic** [comment]
Es desestima aquesta tasca per fer un tractament idèntic al d'abans amb una pàgina. S'exigeix Id únic de camp per a tot el formulari independent de la pàgina on s'ubiqui.
