### ISSUE TITLE
Multipàgina - STT - Desenvolupament: Adaptació generació automàtica PDF

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#224]

**Comment by jparedes-indra** [comment]
Se ha corregido en la versión 1.2.0 e instalado en CAIBter, pero no desplegado en DEV.

**Comment by jsastre-dgtic** [comment]
Segueix pendent el tema del logo, el tractament multipàgina ens pareix correcte. tancam aquesta i mantenim #263
