### ISSUE TITLE
Multipàgina - Proves integració

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#226]

**Comment by jparedes-indra** [comment]
Se ha corregido en la versión 1.2.0 e instalado en CAIBter, pero no desplegado en DEV.

**Comment by jsastre-dgtic** [comment]
Es refereix no tant a integracions amb altres sistemes externs, sinó a la integració entre SISTRAGES i SISTRAMIT i dins d'SISTRAMIT, entre l'assistent (generació de passos) i el formulari (a nivell de scripts). S'han fet proves per veure que tot el tràmit funciona, tant amb formularis d'una pàgina com de diverses.
