### ISSUE TITLE
STG: Promoció de tràmits entre entorns

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#23]
Implementar la lògica i les pantalles associades als processos d'importació/exportació de tràmits entre entorns. Es preveu la implementació d'aquestes funcionalitats:
- Bloqueig/desbloqueig de tràmits
- Generació de quadern de càrrega
- Traçabilitat de versions (releases)
- Modificació de propietats d'accés al tràmit en els entorns de PREproducció i PROducció (activar/desactivar, termini, habilitar debug en cas de problemes, etc..)

**Comment by jsastre-dgtic** [comment]
Tenim un dubte: no ens queda clar amb el document d'anàlisi si un administrador d'Àrea podrà promocionar els seus tràmits entre entorns. Ho teniu contemplat?

**Comment by rsanz-indra** [comment]
No existe un perfil de Administrador de Área, existen los perfiles de Superadministrador, Administrador de Entidad y Desarrollador de trámites.
El Administrador de Entidad es el que puede promocionar los trámites entre entornos.
El Administrador de Entidad puede definir permisos en los roles para los Desarrolladores de trámites para asignar los permisos de:
- Alta: permitirá realizar el alta y baja de trámites y dominios
- Modificación: permitirá modificar trámites y dominios
- Consulta: permitirá consultar trámites y dominios
- HELPDESK: permitirá dar soporte en el HELPDESK a trámites realizados de esta área.

Esta especificado en el punto 2.4 del documento de análisis funcional.

**Comment by fjcalderon-dgtic** [comment]
Hola

En primer lugar, siento enviar este mensaje a estas alturas. Debería haberlo enviado antes, pero el tribunal de oposiciones me está quitando más tiempo del que yo preveía, además de la carga de trabajo del día a día de SISTRA1. No obstante, considero que, a pesar de las horas que ya hemos dedicado a revisar y debatir sobre los documentos de análisis, diseño y mockups, siempre habrá algunos detalles que saldrán a al luz, detalles que en su momento se nos escaparon y que suelen surgir cuando detallamos y profundizamos en  alguna funcionalidad concreta, como la que encabeza esta issue. 

Bien, me gustaría añadir unos comentarios sobre esta issue (promoción de trámites entre entornos) y otras cuestiones derivadas.


**a) ¿Qué significa promocionar?**
Primera cuestión, no me convence la palabra "promocionar". Me gustaría aclarar esta cuestión semántica en primer lugar porque creo que puede tener repercusiones importantes en los siguientes puntos. Desde mi punto de vista, promocionar viene a significar una especie de proceso "automático" que permite volcar información de un entorno a otro, esto eso, que por ejemplo un administrador pudiera pulsar un botoncito desde un entorno para indicar a SISTRA2 que coja un paquete de datos (versión de un trámite concreto) y lo copie y publique automáticamente en otro entorno. Entiendo que esta posibilidad se descartó en las primeras reuniones, por lo que considero más correcto hablar de procesos manuales de importación y exportación de, ¿de qué exactamente? entiendo que nos referimos exclusivamente a "versiones de trámites", no a trámites completos (con N posibles versiones). En otras palabras, entiendo que la idea era seguir el funcionamiento que tenemos ahora con SISTRA1, pero obviamente mejorando sustancialmente el proceso de importación y exportación actuales, permitiendo que, cuando alguien pulse el botón de "exportar" desde un entorno, la nueva plataforma genere un único fichero que empaquete toda la información y elementos que componen "una versión" de un trámite concreto. Ese fichero, posteriormente, será el parámetro de entrada cuando otro alguien pulse el botón de "importar versión" en otro entorno.

Entiendo además que para llevar a cabo estas operaciones de exportación e importación de versiones el bloqueo/desbloqueo de trámites no tiene sentido, porque lo que realmente bloqueamos son versiones, únicamente cuando nuestra intención sea modificar algún campo a mano o directamente borrar toda la versión. En el documento "SISTRA2_AnalisisFuncional.pdf", en la pág 15, comentáis qué vais a implementar una funcionalidad de check-in/check-out, para controlar la trazabilidad de las versiones. No me parece mal y entiendo que es a esto realmente a lo que vosotros llamáis bloqueo/desbloqueo en la operativa de importación y exportación de versiones de trámites, ¿estoy en lo cierto?


**b) Roles y permisos.**
Es obvio que tendremos que tener en cuenta el asunto de roles y permisos también en estas operaciones de importación y exportación de versiones de trámites. En la página 33 del documento "SISTRA2_AnalisisFuncional.pdf", se detallan estos roles propios de la aplicación SISTRA2 (superadmin, admin de entidad, desarrollador y operador de helpdesk), y el sistema para crear y designar otros roles, a nivel de ÁREA, con la ayuda de combinaciones de lo que llamamos permisos. En su momento, fijamos que sólo habría cuatro permisos: A/B, modificación, consulta y helpdesk. En más de una reunión, comentamos que haciendo uso de esta funcionalidad de crear roles por área y activando varios permisos, podíamos crear figuras como la del "administrador de área", que no dejaría de ser un desarrollador especial.

Respecto a a esta cuestión, creo que he encontrado una contradicción en el documento de análisis que es importante que aclaremos. En la página 34 del documento "SISTRA2_AnalisisFuncional.pdf", comentáis lo siguiente: 

_"La modificación de trámites sólo será permitida en el entorno de Desarrollo, por lo que el rol de Desarrollador de trámites, sólo se permitirá en dicho entorno. En los entornos de Preproducción y Producción sólo accederán el Superadministrador y Administrador de Entidad."_

Esta sentencia se contradice con otro párrafo, del mismo documento, en la página 14, sobre el entorno de producción:

_"Producción: entorno de explotación. No se permitirá modificar un trámite en este entorno, sólo se permitirá importar trámites exportados desde preproducción. Este entorno será accesible por superadministradores, administradores de entidad y desarrolladores con permisos de Alta/Baja y Modificación sobre un área, teniendo visibilidad únicamente sobre los elementos de dicha área."_

Desde nuestro punto de vista, consideramos que es esta última sentencia la opción acertada, porque nuestra intención era poder descentralizar en SISTRA2 los pases a producción de versiones de trámites, para que no recaigan estas tareas exclusivamente sobre los administradores de entidad. Por lo tanto, nuestra idea era otorgar roles de desarrollador en producción sólo para lo que nosotros llamaríamos "administradores de ÁREA". Esta idea es compatible con otra funcionalidad básica que hemos comentado en varias reuniones y que se reflejó en el documento de análisis, en concreto en la página 14, donde se especifica que los entornos de preproducción y producción estarán "capados" por seguridad, para que nadie pueda modificar a su gusto las entrañas de cualquier trámites, salvo contadas excepciones, como campos de: activar o desactivar trámite, mensaje de desactivación, fechas de inicio y fin, habilitar debug y poco más. Entiendo que para implementar este "capado" de determinados entornos, haréis uso de alguna propiedad global de la plataforma, con la oportuna modificación de la lógica (código) para lograr este objetivo. 


**c) Creación de trámites e importación/exportación de versiones**
Bien, aclarado el punto anterior, considero que debemos entrar en los detalles del proceso a seguir para llevar a cabo la importación y exportación de versiones de trámites, entre entornos. Para ello, considero primordial aclarar en primer lugar la operación de "nuevo trámite". Entiendo que antes de determinar dónde aparecerán los botones de importar y exportar, y quiénes podrán ver y usar tales acciones, debemos determinar si la operación de "crear nuevo trámite" es un paso previo indispensable, que debe realizarse de forma manual, en cualquiera de los tres entornos. Si estoy en lo cierto, si estamos ante ese escenario, entiendo que el proceso sería el siguiente:

1. Un administrador de entidad o un administrador de área (desarrollador con los permisos A/B, consulta y modificación), crean en el entorno de DESARROLLO un nuevo trámite  en un área concreta, al que llamaremos trámite con código PRUEBA.
2. Tenemos el trámite PRUEBA, con una versión implementada y chequeada (check-out o bloqueado) en el entorno de desarrollo
3. Un administrador de entidad, un administrador de área  o cualquier desarrollador de esa área (con permisos de consulta como mínimo), podrá ver el botón de "exportar versión", dentro esa versión chequeada del trámite PRUEBA.
4. Esa operación de exportación generará un único fichero comprimido con todos los datos y elementos de esa versión del trámite PRUEBA
5. Un administrador de entidad o un administrador de área en el entorno de PREPRODUCCIÓN (y entiendo que lo mismo si hablamos de PRODUCCIÓN) recibirán ese fichero comprimido y, en primer lugar, deberán crear manualmente el nuevo trámite PRUEBA (si no existe previamente) en ese entorno y en el área establecida. Una vez creado el trámite, cualquiera de ellos dispondrá del botón “importar versión”, que pedirá como parámetro de entrada ese fichero comprimido. La visibilidad de ese botón de importación debería estar asociada al permiso “A/B” de esa entidad en concreto. Durante ese proceso de importación, cabe la posibilidad de ofrecer una serie de ventanas al administrador de entidad o administrador de área para que ellos puedan adaptar algunos parámetros de la importación (estoy pensando principalmente en URLs, endpoints de ws) para que el proceso concluya de forma satisfactoria, sin necesidad posterior de tener que revisar algunos de esos parámetros que tiene una vinculación fuerte con el entorno en cuestión.
6. Una vez importada la versión, teniendo presente lo comentado anteriormente, ni el administrador de entidad ni el administrador de área podrían modificar manualmente cualquier campo de esa versión, exceptuando aquellos pocos campos que ya hemos enumerado. 
7. Si se produjera algún error con la importación, entonces tanto el administrador de entidad como el administrador de área, deberían primero bloquear y después eliminar la versión problemática, para repetir el proceso entero cuando se hubiera solventado el problema detectado (normalmente, tras realizar algunos cambios en el entorno de desarrollo).



**d) Vínculo de un trámite ROLSAC y SISTRA2.**
Un último apunte que me ha venido a la mente tras revisar toda la documentación sobre este proceso de importación y exportación. En el documento  “DGDT_MockPantallasSISTRA2,pdf”, en la página 22, disponemos de un mockup que muestra como se asignarán los roles y permisos por área. Ahí no veo problema, pero me preocupa en cambio lo que se muestra en la página 25, con el mockup de “Alta de tràmit”. No hay ni rastro de un campo en SISTRA2 que vincule ese trámite con un trámite y procedimiento de ROLSAC. 

Entiendo que es coherente con lo que se describe en el documento de análisis (“SISTRA2_AnalisisFuncional.pdf”), en la página 12, cuando se describe el proceso de “iniciar un trámite SISTRA2”, desde ROLSAC. Ese campo se pasará como parámetro en la url de llamada.  La idea es buena, de entrada, y puede resulta óptima si nos limitamos al punto de vista del asistente de tramitación SISTRAMIT, pero no lo veo tan claro si ampliamos los puntos de vista y tenemos en cuenta a otros actores de la plataforma, como administradores y operadores de helpdesk. Soy consciente de la funcionalidad que habéis añadido en la página 23 del documento de Mockups, a través del botón de “procedimiento”. Según vuestras propias palabras:

_El botón de “Procedimiento” incluido en la botonera de la sección “Llistat de tràmits” mostrará los procedimientos administrativos que hacen uso del trámite seleccionado. Este dato se obtendrá del catálogo de procedimientos a través del plugin correspondiente._

Sí, esta opción podría ayudar a los administradores, pero no lo veo realmente práctico e incluso tengo dudas de cuál será el rendimiento efectivo si, cada vez que pulsemos ese botón, SISTRA2 le solicitará a ROLSAC una búsqueda completa sobre todo el inventario de procedimientos, para que se compare en todas las fichas de trámites ROLSAC cuántas de ellas tienen establecido el código de trámite SISTRA2 en la formación de su URL para el acceso telemático. Desde mi punto de vista, en la mayoría de ocasiones, tanto si hablamos de trámites con flujo normalizado o personalizado, estaremos hablamos de trámites a medida, por lo que ese vínculo entre ROLSAC y SISTRA2 será uno a uno. Sólo cuando abordemos y implementemos completamente el concepto de “trámite plantilla” en SISTRA2, le vería más sentido a ese botón, porque entonces sí que estaríamos posiblemente ante un vínculo “N a uno”, dada la alta reutilización que se prevé en ese tipo de trámites plantilla. 

Además de lo expuesto hasta la fecha, creo que desde helpdesk también podría darse la necesidad de averiguar qué procedimiento ROLSAC está vinculado a un trámite SISTRA2 concreto, para solventar algunas dudas que puedan surgir ante determinadas incidencias. Por todo ello, creo que habría que considerar la posibilidad de introducir un campo adicional en SISTRA2 para que también se refleje de forma explícita el vínculo de ROLSAC hacia SISTRA2, es decir, poder conocer rápidamente qué procedimiento ROLSAC está vinculado con un trámite SISTRA2 a medida (disponga de flujo normalizado o perso

**Comment by rsanz-indra** [comment]
No hay problema en volver a analizar ciertas partes o cambiar requerimientos, pero habrá que tener en cuenta que podría tener un impacto en el alcance.

Pasamos a intentar aclarar las dudas planteadas. En todo caso, si no conseguimos aclararnos por aquí planteamos una reunión.

a) Cuando indicamos "promocionar" un trámite:
	- nos referimos exclusivamente a pasar una versión de un trámite de un entorno a otro (si no estáis cómodos con este término, podéis indicar otro)
	- en ningún momento indicamos para nada que sea automática, de hecho, en el análisis funcional se indica que la promoción se basa en realizar exportaciones e importaciones, es decir, de forma manual (Generar cuaderno e Importar en la aplicación).
	- el check-in/check-out, efectivamente se corresponde a Bloquear/Desbloquear en el prototipo (como indicas, no se bloquean/desbloquean trámites, se bloquean/desbloquean versiones tal como se aprecia en la aplicación). Cada vez que se Desbloquee se generará una release nueva, para tener controlados los cambios.  Por lo que he leído más adelante, no sé si se acaba de entender la funcionalidad de bloquear/desbloquear: un desarrollador bloquea una versión de trámite para hacer modificaciones sobre dicha versión y cuando termina de hacer los cambios la desbloquea indicando que cambios ha realizado (por tanto mientras una versión está bloqueada no se podrá promocionar a otro entorno, porque se está modificando). Esta funcionalidad de Bloquear/Desbloquear sólo estará disponible en Desarrollo que es donde se pueden modificar los trámites, tal como está especificado en el documento de análisis.

b) Efectivamente en la página 14 existe un error. Tal como se recoge en el análisis funcional solo los Superadministradores y Administradores de entidad pueden acceder a los entornos de Pre y Pro.
   Por lo que comentáis inferimos que queréis introducir un nuevo requisito para añadir un nuevo permiso "Promocionar trámites" (además de los que pedistéis de Alta, Modificación, Consulta y Helpdesk), que permita a un Desarrollador con este permiso acceder a entornos de Pre y Pro para promocionar trámites de las área para las que tengan dicho permiso y supongo que también debería poder modificar temas de activación, etc.. En todo caso, como comentas el término "Administrador de área" es algo "virtual", sería un Desarrollador con ciertos permisos sobre un área.
   
c) Respecto a la promoción de trámites entre entornos (exportación/importación), la idea es controlar que una versión de trámite se vaya promocionando de DESA a PRE y de PRE a PRO, para forzar a seguir todo el proceso (es decir, una versión de DESA sólo se podrá importar en PRE y una versión de PRE sólo se podrá importar en PRO). La idea es que al exportar se incluya toda la información necesaria para poder crear la versión, incluso se podría crear automáticamente el trámite si fuese necesario. Lo que igual sí debería estar creado en un principio debería ser el área (al menos si lo importa un Desarrollador porque los permisos se establecen por área, si lo exportara un Administrador de entidad se podría plantear que se diese de alta el área de forma automática. Respecto al tema de URLs que comentas de dominios, etc., efectivamente deberá formar parte del proceso de importación
	

d) Este tema ya se comentó varias veces con Salvador y se decidió evitar la doble asociación para evitar problemas, y que el punto más idóneo para establecer la relación debía ser Rolsac. También se vió que desde el punto de vista de realizar el diseño del trámite tampoco aportaba demasiado. Respecto al punto de vista de Helpdesk no hay ningún problema, ya que una vez iniciado el trámite ya se conoce el código de procedimiento Rolsac. De todas formas, si se quiere volver a tratar este tema podemos volver a hablarlo.

**Comment by sgelabert-dgtic** [comment]
Conclusió: 
- Podem estimar l'impacte d'incloure el permís perquè un desenvolupador d'àrea tingui un permís per importació tràmits?
- Podem assumir que la importació crearà el tràmit si no existeix, o "l'afegirà" si hi ha una versió prèvia?
- Respecte a ROLSAC i l'enllaç amb els tràmit:
    - Seguesc pensant que el doble enllaç exigeix mantenir la coherència de les actualitzacions en els ambdos sentits. 
   - Entenc que s'implementarà una "caché" a fi d'optimitzar les consultes de SISTRA a ROLSAC referides a l'inventari (tenim previst fer canvis a ROLSAC per normalitzar la informació de l'enllaç telemàtic al tràmit). 
   - Tot i això veig el problema que diu en Paco i així com està podríem donar d'alta tràmits sense associar-los a priori a cap procediment. Per tant, entenc que s'ha de controlar quan importam el tràmit entre entorns, és a dir, verificar en PRE/PRO que pertany com a mínim a un procediment ROLSAC i identificar els procediments afectats per la "promoció" del tràmit.

**Comment by rsanz-indra** [comment]
- Para que un desarrollador pueda exportar/importar trámites en PRE y PRO implicaría añadir un nuevo permiso y luego gestionar los permisos de acceso en PRE y PRO. 
- Como comentábamos se podría crear el trámite automáticamente. Un desarrollador no podría importar si el Administrador de entidad no ha creado el área en PRE y PRO, habiendo dado los permisos previamente. El proceso de exportación/importación deberá contemplar todos los elementos relacionados con un trámite y el proceso de importación será una especie de asistente que tendrá que ir verificando si existen o no elementos (p.e. dominios), ver si se deben crear, revisar su configuración (p.e. urls), etc. Para esto estamos preparando una maqueta antes de programar para ver como plantear el proceso de exportación/importación. Desde el punto de vista de importación por parte del desarrollador podría haber algunos elementos que pueden ser a nivel de entidad (p.e. dominios entidad) y habría que ver si el desarrollador podría manejarlos en la importación.
- Respecto a la optimización de las llamadas de Sistramit a Rolsac comentamos que se implementará una caché, de la misma forma que de Sistramit a Sistrages. Además respecto a la asociación de trámites del catálogo (Rolsac) a trámites electrónicos (Sistra) hay que tener en cuenta que lo más operativo posiblemente sería que Sistra apuntará a Rolsac de Producción ya que si no implicaría que para desarrollar un trámite electrónico se tuviese que ir replicando la información del procedimiento de Rolsac por los distintos entornos (para Sistra en Desarrollo y Preproducción se debería permitir la ejecución de trámites que todavía no fueran vigentes en el catálogo). Hay que tener en cuenta que los entornos de Sistra (Desa, Pre y Pro) realmente serían equiparables a entornos productivos ya que el entorno de Desa es donde los desarrolladores programan los trámites, en Pre donde se prueban y en Pro dónde se publican (por eso se llegó a plantear un cuarto entorno para pruebas de nuevas versiones de Sistra).

**Comment by rsanz-indra** [comment]
Podemos dar una aproximación en horas, pero tened en cuenta que estamos definiendo ahora el detalle de todo este proceso. La estimación podría ser una 40 horas.

**Comment by amaciam-indra** [comment]
Se han incluido las pantallas de promoción de versión de trámites en documento de mockups

**Comment by rsanz-indra** [comment]
Se está desarrollando la parte de importación e incluir las nuevas funcionalidades de promoción individual de dominios y revisión de los nuevos permisos.

**Comment by rsanz-indra** [comment]
Revisado script para ajustar a VARCHAR2(n CHAR)

**Comment by sgelabert-dgtic** [comment]
Comentaris sobre el document de disseny relacionats amb la promoció entre entorns:
- Pàgina 16 --> No s'indica com hauria de procedir un Administrador d'Entitat o un SuperAdministrador per promocionar dominis i fonts de dades globals o d'entitat. No veig que es prevegi l'exportació/importació per separat de dominis/fonts 

S'obre la incidència #35 per finalitzar las tasca

Ens interessa sabre l'estat d'aquesta tasca a la finalització del 6è cicle. Podeu indicar-nos si tota la funcionalitat indicada https://github.com/GovernIB/sistra2/issues/23#issue-323170145 està implementada

**Comment by rsanz-indra** [comment]
Se modifica documento de diseño técnico para indicar expresamente la importación/exportación de dominios.

Al cierre del 6º ciclo quedan por realizar las siguientes tareas:
- terminar proceso de importación de versión de trámite (parte de dominios y pruebas)
- revisión permisos según entorno según últimas especificaciones

Al crearse tarea #35 para finalizar los temas pendientes se pasa la tarea a entregada.
