### ISSUE TITLE
STT: Implementació capa persistència JPA

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#24]
Incorporar al mòdul SISTRAMIT la gestió de persistència JPA:
- Mapeig d'entitats JPA
- Generació dels scripts físics de dades a partir del model JPA

**Comment by rsanz-indra** [comment]
Se ha revisado modelo de STT y mapeado entidades

**Comment by sgelabert-dgtic** [comment]
En els commits relacionats a la issue no fan referència al mapejos d'entitats JPA. 
Si que hem pogut trobar aquest mapejos en el tiquet #25 commit https://github.com/GovernIB/sistra2/commit/1c1d2e3018b71a779c1d3eb7d5e05df493f785f6 
Per favor, ajustau els commits a l'objecte de la issue, si no és impossible fer-ne un seguiment i validar les hores imputades.

**Comment by rsanz-indra** [comment]
Nos hemos debido liar entre las 2 issues (24 y 25). Estaremos más atentos en próximos commits.
