### ISSUE TITLE
TPV - Anàlisi i proposta de solució

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#250]

**Comment by jsastre-dgtic** [comment]
[202010-PagoTPV.pdf](https://github.com/GovernIB/sistra2/files/5950892/202010-PagoTPV.pdf)

**Comment by jsastre-dgtic** [comment]
30/10/2020
S'analitza la integració amb la solució de pagaments TPV de Caixabank mitjançant la implementació d'un connector de passarel·la de pagaments en PaymentIB per poder realitzar pagaments des tràmits en SISTRA2.

Per a poder realitzar pagaments amb TPV des SISTRA2 cal implementar el connector de passarel·la de pagaments necessaris a PaymentIB.
PaymentIB permet definir diferents connectors de passarel·la de pagaments. Actualment està implementat el connector de passarel·la de pagament de l'ATIB i cal implementar un altre connector de passarel·la per TPV de Caixabank. A més, el plugin de passarel·la de TPV requereix la publicació d'una URL d'un notificador de pagaments perquè Caixabank notifica els pagaments.
La notificació de pagaments des Caixabank només es realitza una vegada, s'invocarà a NotificadorTPV i, si hi ha algun problema de comunicació, no ho reintenta. Per això és necessari poder confirmar el pagament manualment des PaymentIB (PAYMENTIBBACK) en cas d'haver-hi una incidència de pagament.
En cas que es vulgui habilitar per a aquest plugin que pugui gestionar el pagament presencial, cal gestionar des del propi connector la generació de la carta de pagament presencial.

Així desglossam les tasques de desenvolupament:
1.- Plugin passarel·la TPV
        o Mòdul connector TPV
        o Client TPV
        o Pagament electrònic
        o Pagament presencial
        o Notificador

2.- Confirmació manual pagaments
