### ISSUE TITLE
STG: Error BBDD en l'accés al backoffice

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#26]
Amb la versió https://github.com/GovernIB/sistra2/commit/15b0f6d2fc7566a99510a7fa0ca4abb2cd700f13 es produeix error de BBDD per la manca del camp RLA_PERPRO.  Adjunt log 
[log_sistrages.txt](https://github.com/GovernIB/sistra2/files/2093940/log_sistrages.txt)

Probablement falta actualitzar l'script d'schema de la BBDD SISTRAGES

**Comment by amaciam-indra** [comment]
Per error no s'havien commitat els canvis del model de dades de SISTRAGES

**Comment by sgelabert-dgtic** [comment]
Una vegada actualitzada la BBDD, apareix el seguent WARNING al accedir a l'aplicació: [log_sistrages-13062018.txt](https://github.com/GovernIB/sistra2/files/2096767/log_sistrages-13062018.txt)
Pareix que falten arxius CSS

**Comment by amaciam-indra** [comment]
He estat revisant aquest tema i sembla que els recursos són al projecte i per tant a l'aplicació. També hem comprovat que a les nostres instal·lacions no és produeix l'error.
Convindria per tant esborrar temporals del Jboss i reiniciar-lo. Esborrau també la memòria cau del navegador.

**Comment by sgelabert-dgtic** [comment]
Hem esborrat temporal del navegador i servidor i ja no apareix el WARNING.
