### ISSUE TITLE
STT: Bug amb la funcionalitat de FIRMA

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#264]
Des de SISTRA2 dins el camp que hi ha d'haver el NIF (administrationId) hi estavem posant un altre valor. 
Això a PRE no donava cap problema perquè segons la configuració que teníem, no es comprova el NIF del signant. Però quan ho hem provat a PRO, on sí es fa la comprovació, botava un error.

**Comment by jparedes-indra** [comment]
Se ha resuelto el bug con la versión de SISTRA2 1.1.4 (b89d923).
