### ISSUE TITLE
Crear un projecte a partir de l'arquetip del "projectebaseexemple"

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#265]
Seguir: https://github.com/GovernIB/projectebase
http://htmlpreview.github.io/?https://github.com/GovernIB/projectebase/blob/projectebase-1.0.8/generadordecomanda.html

**Comment by jsastre-dgtic** [comment]
L'objectiu és poder donar suport a desenvolupadors de tràmits que vulguin integrar el seu BO a l'esquema de l'AD.

**Comment by slromero-indra** [comment]
Buenas, donde queréis que subamos el proyecto? Nos generáis un proyecto nuevo en github para subir el desarrollo realizado?

**Comment by jsastre-dgtic** [comment]
Aquesta issue està pensada per a ús particular d'INDRA amb la idea de formar a INDRA amb les eines del Govern que generaran dubtes als desenvolupadors. L'objectiu és que INDRA sigui capaç de donar suport amb les integracions i res més. No fa falta ni desenvolupar res que surti del que ja té el "projectebaseexemple" ni s'ha de generar cap projecte nou a banda del que ja tenim. 
A banda d'això, quan es realitza una issue cal canviar l'etiqueta de "No iniciada" a "En entrega"

**Comment by jparedes-indra** [comment]
Tras crear el proyecto, se ha creado un trámite TEST-REMOTO en CAIBter, que permite probar la funcionalidad del gestor de formularios externos y del uso de dominios remotos. Damos la issue por finalizada.

**Comment by jsastre-dgtic** [comment]
Validat
