### ISSUE TITLE
DOC: Creació d'un document de versions explicatiu

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#266]
El document anirà acumulant un històric de les versions de SISTRA2, explicant les novetats i correccions de bugs que té cada versió.

**Comment by jparedes-indra** [comment]
El documento con las versiones de SISTRA2 se encuentra en https://github.com/GovernIB/sistra2/blob/sistra2-1.1/doc/SISTRA2-VERSIONES.docx.

**Comment by jsastre-dgtic** [comment]
Tancam issue, ara ja només es tracta d'anar mantenint el document actualitzat així com surtin versions.
