### ISSUE TITLE
STG: Comprovar a totes les pantalles "pop-up" que es redimendionin els camps interns a la pantalla

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#267]
![image](https://user-images.githubusercontent.com/18436867/110923005-b4c60300-8320-11eb-8e70-f6bc4038f752.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.2.0 (64208c6) y se despliega y prueba en CAIBter.

**Comment by jsastre-dgtic** [comment]
Segueix igual
![image](https://user-images.githubusercontent.com/18436867/124922257-9b487580-dff9-11eb-8418-0d2866fd9be6.png)

**Comment by jparedes-indra** [comment]
Se han revisado las pantallas que hemos visto mal, pero si detectais alguna más (aparte de la indicada), la revisaremos. No obstante, haremos un barrido para detectar otros popups con esta circunstancia.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(3f9c062) y se despliega y prueba en CAIBter.

**Comment by avillen-dgtic** [comment]
Segueix sense estar resolta aquesta issue.
![#267](https://user-images.githubusercontent.com/83401259/127111795-6cc65c96-08e1-4631-ba02-a69db926d225.gif)

**Comment by avillen-dgtic** [comment]
El comportament és l'esperat.
