### ISSUE TITLE
STG: Actualitzar el projecte (STG-STT-STH) per a que sigui compatible amb java 11

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#268]
Els actuals estàndards de desenvolupament del Govern de les Illes Balears (GOIB):
• OpenJDK 11 com a plataforma de desenvolupament (en substitució de JavaSE 7).

**Comment by rsanz-indra** [comment]
Detalle error:
         Sempre compilam sense problemes amb: "JAVA_HOME=C:\Program Files\Java\jdk1.8.0_231", si ho intentam amb "C:\Program Files\Java\jdk-11" falla. 

[INFO] sistrahelp-ear ..................................... SKIPPED 
[INFO] ------------------------------------------------------------------------ 
[INFO] BUILD FAILURE 
[INFO] ------------------------------------------------------------------------ 
[INFO] Total time:  6.257 s 
[INFO] Finished at: 2021-06-18T09:09:47+02:00 
[INFO] ------------------------------------------------------------------------ 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project sistracom-ws-utils: Compilation failure: Compilation failure: 
[ERROR] /C:/CAI/GitHub/sistra2-1.1.8/sistracom/sistracom-ws-utils/src/main/java/es/caib/sistra2/commons/ws/utils/WsClientUtil.java:[6,20] package javax.xml.ws does not exist 
[ERROR] /C:/CAI/GitHub/sistra2-1.1.8/sistracom/sistracom-ws-utils/src/main/java/es/caib/sistra2/commons/ws/utils/WsClientUtil.java:[23,48] cannot find symbol 
[ERROR]   symbol:   class BindingProvider 
[ERROR]   location: class es.caib.sistra2.commons.ws.utils.WsClientUtil 
[ERROR] /C:/CAI/GitHub/sistra2-1.1.8/sistracom/sistracom-ws-utils/src/main/java/es/caib/sistra2/commons/ws/utils/WsClientUtil.java:[52,62] cannot find symbol 
[ERROR]   symbol:   variable BindingProvider 
[ERROR]   location: class es.caib.sistra2.commons.ws.utils.WsClientUtil 
[ERROR] /C:/CAI/GitHub/sistra2-1.1.8/sistracom/sistracom-ws-utils/src/main/java/es/caib/sistra2/commons/ws/utils/WsClientUtil.java:[53,62] cannot find symbol 
[ERROR]   symbol:   variable BindingProvider 
[ERROR]   location: class es.caib.sistra2.commons.ws.utils.WsClientUtil 
[ERROR] -> [Help 1] 
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. 
[ERROR] Re-run Maven using the -X switch to enable full debug logging. 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles: 
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException 
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command 
[ERROR]   mvn <args> -rf :sistracom-ws-util

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

Para realizar la compilación de Sistra2, actualmente se requerirá de la versión de jdk11.
