### ISSUE TITLE
Migració tràmits de SISTRA1: actualització de situació en SISTRA1 d'explotació

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#271]
A partir d'querys a BD de SISTRA1 a l'entorn de producció, actualitzar l'Excel de situació detallada de cada tràmit susceptible de ser migrat a SISTRA2, en funció de la seva tipologia, components que empra, ...

**Comment by jparedes-indra** [comment]
Se ha de determinar si se migran los trámites con autenticación anónima.

**Comment by jparedes-indra** [comment]
Ya se entregó a la CAIB un listado de trámites a ser migrados.
