### ISSUE TITLE
Gestor de formularis externs: suport i documentació tècnica

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#272]
Crear documentació tècnica. PENDENT finalitzar suport a la migració de tràmits de la DG d'Educació.

**Comment by jparedes-indra** [comment]
Se adjunta documentación técnica que explica cómo configurar y utilizar el plugin del Gestor de Formularios Externos.

**Comment by jparedes-indra** [comment]
Se actualiza la documentación, para modificar el formato del ticket generado por el GFE.

[SISTRAMIT_Manual_Integracio_Aplicacions.pdf](https://github.com/GovernIB/sistra2/files/6221266/SISTRAMIT_Manual_Integracio_Aplicacions.pdf)

**Comment by jparedes-indra** [comment]
Se ha detectado un problema en el plugin del Gestor de Formularios Externos, por lo que se actualiza la rama 1.1 y se crea el TAG 1.1.5 (4ae97b4).

**Comment by jparedes-indra** [comment]
Puesto que ya se permite el tratamiento de lista de elementos en XML, se finaliza tanto la issue #329 como esta, según se acordó con la cAIB.
