### ISSUE TITLE
STG: Control de plantilla PDF per defecte

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#273]
Quan s'introdueix una plantilla PDF en un tràmit, el sistema no controla si hi ha una per defecte, el que provoca que aparegui un error en el moment de l'execució de l'tràmit. Es requereix que el STG indiqui que ha d'haver una plantilla per defecte abans de desar els canvis.

**Comment by jparedes-indra** [comment]
Se ha corregido en la versión 1.2.0 e instalado en CAIBter, pero no desplegado en DEV.

**Comment by jsastre-dgtic** [comment]
ok
![image](https://user-images.githubusercontent.com/18436867/122909360-6a0f4a80-d355-11eb-87d2-4941a420145e.png)
