### ISSUE TITLE
STG: Visualització de totes les àrees i tràmits en mode lectura

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#274]
Aprofitar la finestra ja existent per simplificar accés a l'usuari i reaprofitar funcionalitat (visualització, recerca, etc.)
 
A tenir en compte:
 
a. Introduir un check (ubicat al footer o al header) per indicar si es visualitzen només les àrees per a les quals es té permís o totes les àrees:
· Check deshabilitat (per defecte): només es visualitzaran les àrees per a les quals es tenguin permisos (funcionament actual d'aquesta finestra).
· Check habilitat: permetrà visualitzar totes les àrees.
b. Per a les àrees que no tengui permís:
· No apareixeran els botons associats a accions sobre aquesta àrea i els seus tràmits.
· Es permetrà accedir en mode lectura a la finestra emergent de detall de l'àrea (a aquest detall se li afegirà un camp per a la descripció de l'àrea).
· Es permetrà accedir en mode lectura a la finestra emergent de detall d'un tràmit.
· No es permetrà accedir al detall d'una versió.
c. A nivell de visualització es podria mirar de distingir visualment les àrees per als que no es tingui permís (p.e. introduir amb una icona de cadenat o un color de lletra diferent).

![image](https://user-images.githubusercontent.com/18436867/112105295-81029d00-8bac-11eb-8697-3c670e86faf7.png)

**Comment by jparedes-indra** [comment]
Se ha corregido en la versión 1.2.0 e instalado en CAIBter, pero no desplegado en DEV.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega en CAIBter, pero no en DEV.

**Comment by jsastre-dgtic** [comment]
Falla el punt:
· Es permetrà accedir en mode lectura a la finestra emergent de detall d'un tràmit.

**Comment by jsastre-dgtic** [comment]
A més a més, seria desitjable que funcioni la recerca de tràmits en àrees de només consulta, perquè ara mateix no funciona:
![image](https://user-images.githubusercontent.com/18436867/123060720-49a1c780-d40b-11eb-9098-114024f13cf4.png)

**Comment by jsastre-dgtic** [comment]
A més, quan desmarcam el check de visualitzar totes les àrees, no ens troba la nostra... imagin que pel fet de tenir emplenat el camp de recerca (entenc que l'hauria de mostrar, l'àrea nostra... ):
![image](https://user-images.githubusercontent.com/18436867/123061533-04ca6080-d40c-11eb-955d-a1ca26f539f3.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/126142674-fde63cd2-2580-40ce-a6ba-01fa7828468a.png)
![image](https://user-images.githubusercontent.com/67064375/126142703-4227a710-a90c-462d-9d3f-1e5b32d6a8e4.png)

**Comment by avillen-dgtic** [comment]
No podem comprovar el bon comportament d'aquesta issue per l’error que ens dona.
![#274](https://user-images.githubusercontent.com/83401259/126468682-a542cc98-6bee-45f1-878f-ab968b9d5d15.gif)

**Comment by avillen-dgtic** [comment]
El comportament és correcte.

**Comment by jparedes-indra** [comment]
Hemos añadido en esta issue el error que había al consultar los trámites de un área, que no dejaba abrir los trámites de dicha área. Actualmente, en la versión actualizada del tag ya permite el acceso a los trámites del área asociada al rol correspondiente en modo consulta.
