### ISSUE TITLE
STG: Scripts d'Autoemplenament

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#275]
Als scripts d'autoemplenament es tenen en compte les línies comentades per calcular les dependències d'altres camps.
De moment no es poden interpretar quines línies d'scripts estan comentades, ja que el càlcul de dependències es fa a mà. Caldrà veure on avisar d'aquest tema, per a que no es deixin línies comentades referenciant a camps, ja que es tindran en compte. A la finestra de script caldria ficar una ajuda de la pròpia finestra on s'expliqui el funcionament de la finestra i temes a tenir en compte en els scripts (entre ells aquest). PER TANT, s'ha de tenir en compte en la finestra d'ajuda. S'actualitzarà l'ajuda per indicar-ho.

**Comment by jparedes-indra** [comment]
Se resuelve en versión 1.2.0 y despliega en CAIBter, pero no en DEV.

**Comment by jsastre-dgtic** [comment]
ok
![image](https://user-images.githubusercontent.com/18436867/122922992-7d75e200-d364-11eb-83da-01d0ca2d7889.png)
