### ISSUE TITLE
STG: Fonts de dades en importació

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#276]
Caldria modificar els literals relatius a fonts de dades, ja que no queda clar quina és la que importes i quina l'existent (la de la instal·lació caldria posar-la com "Font de dades existent")

**Comment by jparedes-indra** [comment]
Estamos viendo que no existe el problema, ya que en DEV (1.1.8) ya se está mostrando la información correctamente.

![imagen](https://user-images.githubusercontent.com/67064375/124330711-49819480-db8e-11eb-9408-b07f5022e2b4.png)
