### ISSUE TITLE
STH: Finestra de detall en STH

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#277]
A les finestres de detall (diàlegs) en alguns casos s'incorpora scroll als grids havent espai suficient fins a la botonadura.

**Comment by jparedes-indra** [comment]
En las ventanas de detalle (diálogos) en algunos casos se incorpora scroll a los grids habiendo espacio suficiente hasta la botonadura (ver imagen).

![imagen](https://user-images.githubusercontent.com/67064375/113445138-94580880-93f5-11eb-8b1b-072352366b34.png)

**Comment by jparedes-indra** [comment]
Se ha resuelto en el TAG 1.2.0 (c147d32) y se ha desplegado en CAIBter.

**Comment by avillen-dgtic** [comment]
Desaparece el scroll del grill.
