### ISSUE TITLE
STG: Previsualitzar des del llistat de tràmits / versions

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#279]
A la finestra emergent de ‘Previsualització’ indicar nom de tràmit (en el títol o en pròpia finestra).

**Comment by jparedes-indra** [comment]
Se ha corregido en la versión 1.2.0 e instalado en CAIBter, pero no desplegado en DEV.

**Comment by jparedes-indra** [comment]
Se resuele en la versión 1.2.0 y se despliega en CAIBter, pero no en DEV.

**Comment by jsastre-dgtic** [comment]
Ok
![image](https://user-images.githubusercontent.com/18436867/122923930-7c918000-d365-11eb-969c-9893afe89aec.png)
