### ISSUE TITLE
STG: Especificació i implementació API Rest SISTRAGES

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#28]
Implementació de l'API Rest de serveis per SISTRAGES:
- Revisió del document de disseny tècnic i rols d'ús
- Especificació i implementació dels serveis de l'API
- Documentació de l'API des de l'inici amb el Framework Swagger

**Comment by rsanz-indra** [comment]
Comentamos las dudas:

- _Pàgina 11 --> No es queda clar si l'API interna de SISTRAGES també serà accedida per SISTRAHELP. Aniria bé afegir columna indicant des de quina aplicació (STG, STT o STH) es preveu que s'accedeixi a que aquestes operacions internes._
Se establece columna para indicar el módulo invocante

- _Pàgina 12 --> Definir conceptes d'auditoria d'esdeveniments, tràmits, fitxers de sessió i pagament (es sobreentén en alguns casos però millor que quedi definit)._ 
Modificamos documento para establecer descripción de los conceptos.

- Totes les API's Externes són exclusivament de consulta ?
En principio todas las operaciones analizadas son de consulta.

- _Pàgina 15 --> Vistes les operacions, millor separem les APIs d'accés internes i externes amb rols i contexts propis._
Ok. A falta de confirmarlo hemos establecido en el documento: STG_API / STG_APE y STT_API / STT_APE para distinguir los roles de acceso al api interno (_API) y externo (_APE).

- _Afegir secció en el document de disseny amb l'especificació dels contexts d'accés per aplicació  (SISTRAGES, SISTRAMIT, SISTAHELP), APIs internes i externes._
Añadida sección.

_Ens interessa sabre l'estat d'aquesta tasca a la finalització del 6è cicle: Nombre de serveis implementats de l'API interna i externa i Documentació de l'API de SISTRAGES amb Swagger._ 
A la finalización del 6º ciclo queda por finalizar los servicios de obtener definición versión trámite y resolver consulta fuente de datos, y la documentación con Swagger.

**Comment by rsanz-indra** [comment]
Se pasa a entrega esta issue para finalizarla en la #33

**Comment by sgelabert-dgtic** [comment]
Si vos pareix canviem el sufix dels rols, en lloc de _API, _APE, millor empram _API_INT, _API_EXT.
Quan pogueu actualitzeu el document de disseny.

**Comment by rsanz-indra** [comment]
Se corrige errata en documento Diseño Técnico
