### ISSUE TITLE
STG: Id del camp actual en Scripts

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#280]
A la finestra d'scripts d'un camp, no tens cap referència a l'id de el camp actual, i per donar-li un valor l'has d'emprar.
Estaria bé saber quin és.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega en CAIBter, pero no en DEV.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega en CAIBter, pero no en DEV.

**Comment by jsastre-dgtic** [comment]
ok
![image](https://user-images.githubusercontent.com/18436867/122924217-d2febe80-d365-11eb-9ec5-346c05d23538.png)
