### ISSUE TITLE
STT: Error al no estar disponible ROLSAC

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#281]
Controlar millor quan ROLSAC no està disponible. Ara, quan ROLSAC no està disponible està donant l'error:

service unavaible  Caused by: org.springframework.web.client.HttpServerErrorException: 503 Service Temporarily Unavailable at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:88) at ...

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega en CAIBter, pero no en DEV.

**Comment by jsastre-dgtic** [comment]
Funciona bé, només una petita qüestió lingüística. És "a l'accedir", no "al accedir". 
![image](https://user-images.githubusercontent.com/18436867/123601026-800a8880-d7f7-11eb-881a-8cf5d304af36.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (9030c09) y se despliega en CAIBter.

**Comment by avillen-dgtic** [comment]
![image](https://user-images.githubusercontent.com/83401259/124568456-3b10d280-de45-11eb-9ced-2536b621c5ee.png)

Es tanca la incidència.

**Comment by avillen-dgtic** [comment]
![image](https://user-images.githubusercontent.com/83401259/124568968-cd18db00-de45-11eb-9c3f-9c31eba0ab24.png)

Missatge canviat.
