### ISSUE TITLE
STT: Desplegable en domini

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#282]
El desplegable no permet seleccionar cap dels valors que mostra. Després revisar sembla que el problema és que el camp codi indicat per al selector difereix en una majúscula amb l'indicat en la query de la definició de l'domini.
Potser com a millora s'hauria de comprovar que no es pugui consignar un camp no retornat pel domini.

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/136549675-cd8fbb0a-df61-4fac-9c89-99c9c07a2b23.png)

**Comment by jparedes-indra** [comment]
Esto es muy difícil de realizar, ya que no vienen en la definición del dominio los campos que se van a devolver, por lo que no se puede saber si es correcto o no a priori. 
  
Los únicos campos que pueden proporcionar esa información son los parámetros que se definen en el contrato REST, pero las columnas que enviará cada dominio no. 
  
Por tanto, para que funcione correctamente deben indicarse los campos exactamente como vienen definidos en el dominio, haciendo coincidir mayúsculas y minúsculas, pero no es posible automatizar la comprobación a priori.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![#282](https://user-images.githubusercontent.com/67064375/140878782-ee5b226f-bf4a-45b7-b3bc-8c6cb762e8a0.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en la compilación 0ed040f y ahora, tanto las propiedades del dominio asociado al selector, como los campos que vienen del dominio son case NO sensitive.

**Comment by jsastre-dgtic** [comment]
ok:
![image](https://user-images.githubusercontent.com/18436867/145770354-9d2577bb-e58d-4149-a40f-8eaea7fac5b0.png)
