### ISSUE TITLE
Mostra dades de tràmits en CAIBpre i CAIBpro

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#283]
Al fer doble clic sobre un tràmit no s'obre la finestra emergent amb les seves dades i en els logs no es mostren errors. En CAIBdev funciona correctament.

**Comment by jparedes-indra** [comment]
Al hacer doble click sobre un trámite no se abre el popup con sus datos y en los logs no se muestran errores. En CAIBdev sí funciona correctamente, pero en PRE y PRO, se muestra como en la imagen.

![imagen](https://user-images.githubusercontent.com/67064375/113445331-fadd2680-93f5-11eb-8ae1-213ac5e3c1ba.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 (64208c6) y se prueba en CAIBter, simulando PRE y PRO.

**Comment by jsastre-dgtic** [comment]
Desplegat a DEV i pendent dels quaderns de càrrega per a desplegar a PRE
