### ISSUE TITLE
STT: Paràmetre @RequestBody

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#285]
En STT: ApiInternaRestController, el mètode de invalidació hauria de tenir un paràmetre per entrada '@RequestBody' com la resta de mètodes a la classe.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(c9b2299) y se despliega en CAIBter, pero no en DEV.

**Comment by jsastre-dgtic** [comment]
Ens hem pogut connectar i validar la funcionalitat amb el domini CICONIF, però amb un tràmit no ens va bé... Com introduim identificador (string, optional): Identificador según el tipo de invalidación: versión trámite (idtramite-version)?
Hem posat "TEST-REG-1"/"T" i no ens ha anat bé...

**Comment by jparedes-indra** [comment]
Se resuelve en CAIBter, en la versión 1.2.0(64208c6).
