### ISSUE TITLE
Mostra mètode d'autenticació a STH

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#286]
Mostra en STH el mètode d'autenticació amb el qual s'ha iniciat un tràmit.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega en CAIBter, pero no en DEV.

**Comment by avillen-dgtic** [comment]
La informació apareix.
![image](https://user-images.githubusercontent.com/83401259/122358522-018b2c80-cf55-11eb-8ccb-d6c1701f3a95.png)

**Comment by jparedes-indra** [comment]
En la versión 1.2.1 se han actualizado las siguientes ayudas: 

-       Se añade en PLUGIN_SESIONTRAMITACION el método getTramiteCP.
-       Se añade en PLUGIN_SESIONTRAMITACION el método getTramiteCP
-	También se modifica el índice de este para añadirlo. 
-	Se añade carpeta de DATOS_TRAMITECP con los métodos asociados e índice. 
-	Se añade carpeta de DATOS_PROCEDIMIENTOCP con los métodos asociados e índice. 
-	Los índices de DATOS_X se modifican para que al copiar el método en el portapapeles no se añadan incorrectamente algunas expresiones que estaban mal. (Se copiaba DATOS_USUARIO.getNombre())
-	PLUGIN_SESIONTRAMITACION.getParametroInicio: se modifica frase indicada sobre URL.
-	Index.html de PARAMETROS DOMINIO
-	Index.html VALORES DOMINIO
-	disenyoFormularioDialog.html, se añade frase indicando que los radiobuttons tienen que tener espacio en horizontal. 
-	definicionVersionAnexoDialog.html se cambia explicación del número de instancias. 

Por ello, en el directorio de ayudas externas debéis añadir/sobrescribir los siguientes archivos: 
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/definicionVersionAnexoDialog.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/disenyoFormularioDialog.html
Todos los docs de la carpeta: 
https://github.com/GovernIB/sistra2/tree/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/DATOS_PROCEDIMIENTOCP
Todos los docs de la carpeta: 
https://github.com/GovernIB/sistra2/tree/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/DATOS_TRAMITECP
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/DATOS_USUARIO/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/PARAMETROS_DOMINIO/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/PLUGIN_SESIONTRAMITACION/getParametroInicio.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/PLUGIN_SESIONTRAMITACION/getRepresentanteUsuario.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/PLUGIN_SESIONTRAMITACION/getTramiteCP.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/PLUGIN_SESIONTRAMITACION/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/VALORES_DOMINIO/index.html


Lo mismo para su versión en es: 
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/definicionVersionAnexoDialog.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/disenyoFormularioDialog.html
Todos los docs de la carpeta: 
https://github.com/GovernIB/sistra2/tree/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/DATOS_PROCEDIMIENTOCP
Todos los docs de la carpeta: 
https://github.com/GovernIB/sistra2/tree/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/DATOS_TRAMITECP
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/DATOS_USUARIO/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/PARAMETROS_DOMINIO/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/PLUGIN_SESIONTRAMITACION/getParametroInicio.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/PLUGIN_SESIONTRAMITACION/getRepresentanteUsuario.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/PLUGIN_SESIONTRAMITACION/getTramiteCP.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/PLUGIN_SESIONTRAMITACION/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/VALORES_DOMINIO/index.html
