### ISSUE TITLE
Esborrat en cascada d'àrea i els seus tràmits i versions associades

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#287]
Permetre que, mitjançant script o funcionalitat, es puguin eliminar tots els tràmits i versions d'una àrea, eliminar una àrea directament o un tràmit directament, eliminant en cascada seus objectes dependents (àrea, tràmit i versió). 
AQUESTA OPCIÓO NOMÉS HA D'ESTAR DISPONIBLE AMB EL ROL ADMINISTRADOR D'ENTITAT

**Comment by jparedes-indra** [comment]
Se resuelve en CAIBter, en la versión 1.2.0(64208c6).

**Comment by jsastre-dgtic** [comment]
Funciona ok, però seria desitjable un avís que ens informàs que s'esborrarà l'àrea seleccionada i tots els seus tràmits associats. Estau segurs de voler continuar?
En el cas que l'àrea no contengui cap tràmit, substituir fila per àrea, simplement.

![image](https://user-images.githubusercontent.com/18436867/124903128-ee173280-dfe3-11eb-9173-6db30a2c8175.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/126142877-cdb69ea6-15a0-49cf-8d12-7a40f9f519f8.png)

**Comment by avillen-dgtic** [comment]
Comportament correcte i es visualitza el missatge dels elements que s'esborraran.
