### ISSUE TITLE
Migració de l'tràmit "EH0069CEEP - Tràmit de renovació de certificats Electrònics"

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#288]
Revisar una primera versió de l'tràmit EH0059CERT que existeix en DEV i adaptar-lo a el nou EH0059CEEP.

**Comment by jparedes-indra** [comment]
Se finaliza el desarrollo del trámite y se mantiene en CAIBter hasta que se instale la versión 1.2.0 en DEV, ya que el trámite es multipágina.

**Comment by jsastre-dgtic** [comment]
No trobam el tràmit. 

![image](https://user-images.githubusercontent.com/18436867/122926155-e01cad00-d367-11eb-8689-aae48cf630bc.png)

**Comment by jparedes-indra** [comment]
En el área Z-AP teneís dos versiones. La 1 fué una prueba inicial, pero la 2 es el trámite migrado, que cuando se valide y pase a DEV, será la versión 1 del trámite que se cree.

**Comment by jsastre-dgtic** [comment]
https://github.com/GovernIB/sistra2/issues/274#issuecomment-866627231

**Comment by jparedes-indra** [comment]
Realmente esta issue está correcta, puesto que el trámite en si está migrado, independientemente de lo que sucede en la issue #274.

**Comment by jsastre-dgtic** [comment]
A l'àrea Z-AP(caibter) no trobam EH0069CEEP:

![image](https://user-images.githubusercontent.com/18436867/129190693-442a15cb-03b2-49a4-9851-a9e6108e254c.png)

Heu canviat el codi i és equivalent el EH0059CEEP?

**Comment by jsastre-dgtic** [comment]
A l'importar el tràmit eh0059ceep, tornam a detectar el problema del desplegable buit dels dominis
![image](https://user-images.githubusercontent.com/18436867/129339407-d2328e60-4b1e-4b00-9dc2-b3bac2b453b6.png)

**Comment by jsastre-dgtic** [comment]
I després falla
![image](https://user-images.githubusercontent.com/18436867/129339481-5476aff7-1bee-48d8-b275-9d4af5791af6.png)

**Comment by jparedes-indra** [comment]
Hemos realizado algunas pruebas ya que también nos estaba fallando la importación en nuestro local, y después de algunas modificaciones parece que ya funciona correctamente la importación del trámite. ¿Podéis probar a importar en DEV de nuevo?
![image](https://user-images.githubusercontent.com/67064375/129525409-1d914ff0-807e-453b-8a10-da168d771817.png)

**Comment by jsastre-dgtic** [comment]
La importació ha anat bé.
Això no quadra:
![image](https://user-images.githubusercontent.com/18436867/129532684-d37b4de5-95fe-4e6f-8539-878a89e10571.png)

**Comment by jsastre-dgtic** [comment]
Pareix que el que demana és el num de sol, més que l'adreça, perquè intent posar "Sant Pere, 8"  i no me deixa.
A més, demana l'extensió i espera un telèfon si o si

![image](https://user-images.githubusercontent.com/18436867/129533112-ff5dfd3d-af91-4d55-8713-018d27690134.png)

**Comment by jsastre-dgtic** [comment]
No aconseguesc activar aquest camp ni trobar-li utilitat... 
![image](https://user-images.githubusercontent.com/18436867/129533377-d736e565-5dbe-4151-b9a0-c09584c77113.png)

**Comment by jsastre-dgtic** [comment]
Potser hauríem de replantejar demanar la còpia del dni si hem entrat amb dnie o certificat digital.
Potser podríem plantejar PINBAL pel segon doc?

![image](https://user-images.githubusercontent.com/18436867/129533638-fc37e60e-13fb-424d-991f-d8cdc38e96d0.png)

**Comment by jparedes-indra** [comment]
> Pareix que el que demana és el num de sol, més que l'adreça, perquè intent posar "Sant Pere, 8" i no me deixa.
> A més, demana l'extensió i espera un telèfon si o si
> 
> ![image](https://user-images.githubusercontent.com/18436867/129533112-ff5dfd3d-af91-4d55-8713-018d27690134.png)

¿Cambiamos el nombre de este campo entonces? ¿Puede ir mejor 'Número de solicitud de la FNMT' tal y como indica la ayuda o nos indicáis vosotros el nombre? 

Para la validación del teléfono, al ser un campo teléfono no dejaba introducir más que campos de 9 dígitos. Por eso hemos cambiado la validación, que ahora pasa a ser mediante script de validación con el siguiente código: 
![image](https://user-images.githubusercontent.com/67064375/129570081-eda81531-776a-4070-aad5-45bfcbe23871.png)

Se valida si es un número de teléfono fijo o móvil y en caso de extensión si tiene 5 dígitos. Los mensajes de error en este campo aparecen con el siguiente texto, ¿estáis de acuerdo? 
![image](https://user-images.githubusercontent.com/67064375/129570264-ded506e6-66db-47d9-adca-b47120f3bf2b.png)

**Comment by jparedes-indra** [comment]
> No aconseguesc activar aquest camp ni trobar-li utilitat...
> ![image](https://user-images.githubusercontent.com/18436867/129533377-d736e565-5dbe-4151-b9a0-c09584c77113.png)

Nosotros tampoco le vemos mucho sentido a este campo, ¿lo eliminamos del trámite?

**Comment by jparedes-indra** [comment]
> Potser hauríem de replantejar demanar la còpia del dni si hem entrat amb dnie o certificat digital.
> Potser podríem plantejar PINBAL pel segon doc?
> 
> ![image](https://user-images.githubusercontent.com/18436867/129533638-fc37e60e-13fb-424d-991f-d8cdc38e96d0.png)

Al entrar con certificado digital tampoco le vemos mucho sentido a que pida la copia del DNI. ¿Eliminamos el anexo?

Referente a esto: "Potser podríem plantejar PINBAL pel segon doc?", no entendemos a que os referís. Si podéis especificarnos cual sería vuestra propuesta la valoramos.

**Comment by jsastre-dgtic** [comment]
L'objectiu hauria de ser que com a mínim, es presentàs amb les mateixes funcionalitats que l'actual:

Al EH0069CEEP (SISTRA1):

1.- El camp d'adreça funciona i l'ajuda és coherent
![image](https://user-images.githubusercontent.com/18436867/129681776-1f362c32-0c6e-43ba-8d97-ae215b815447.png)

2.- El camp d'informació "documentació a aportar" és dinàmic depenent de les opcions triades i funciona:

![image](https://user-images.githubusercontent.com/18436867/129682047-7837ed7e-9ff5-48af-af73-4a81b9f12bdd.png)

![image](https://user-images.githubusercontent.com/18436867/129682117-5a22b8e3-7ac5-4040-93c2-f47feba10403.png)

3.- Depenent del punt 2 la passa d'annexar demana un o dos docs:
![image](https://user-images.githubusercontent.com/18436867/129682207-41cf9b28-5bd4-4785-a313-5420c861ec48.png)

4.- El camp telèfon/extensió també admet extensió.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (003a482) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
El trámite está implementado con todas las funcionalidades que se pedían al igual que se puede encontrar en SISTRA1.

**Comment by jparedes-indra** [comment]
En cuanto al problema de la importación de trámites con scripts de navegación en alguna página, también se resuelve este error, así como el procesar cuadernos de carga desde PRE. 
![#288](https://user-images.githubusercontent.com/67064375/130779155-ac8b8f44-9837-4d71-a98e-4f2178b812dd.gif)

**Comment by avillen-dgtic** [comment]
La importació la fa correcta, però els dominis quan he importat el tràmit no funcionen a STT, en canvi el ping al domini al formulari és correcte.
![image](https://user-images.githubusercontent.com/83401259/130779923-63e6ad88-e8d1-4c8d-b8c5-6b613af7e767.png)

**Comment by jsastre-dgtic** [comment]
El num de sol·licitud FNMT ja no es demana. L'adreça de la Conselleria si... Cal comparar-lo amb l'actual a S1.

**Comment by avillen-dgtic** [comment]
El llistat de les conselleries no surt
![image](https://user-images.githubusercontent.com/83401259/193217988-4b07571c-9cc9-44a9-8110-9b7cfd3d930b.png)

En començar a picar l'adreça de correu electrònic ens dona un error el formulari
![image](https://user-images.githubusercontent.com/83401259/193218344-8c7dc532-ceb3-437c-9ba5-ba5fe7ad3694.png)
![image](https://user-images.githubusercontent.com/83401259/193218932-58d702b9-c1cb-40e1-9abf-8cf339e8b50d.png)

**Comment by avillen-dgtic** [comment]
![image](https://user-images.githubusercontent.com/83401259/209943334-e77c2408-8ce0-46f5-b2b0-851c67b8897d.png)

**Comment by avillen-dgtic** [comment]
👍
