### ISSUE TITLE
Solucionar problema Autoemplenat del camp data

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#289]
Si posam això a la càrrega de dades inicials funciona bé, però si ho posam directament a l'Autoemplenat del camp del formulari directament no: 

var ara = PLUGIN_UTILS.getFechaActual(null); 
DATOS_VALORESINICIALES.setValor('CDATA',ara); 

Aniria molt bé una altra funció que no implicàs haver de concatenar data/hora a través d'un camp ocult, i també seria molt útil poder triar si surten els segons.

Proposam introduir un paràmetre nou a la funció PLUGIN_UTILS.getFechaActual(); que ens permetri triar el nivell d'exactitud de l'1 al 3:
1.- només surt la data (19/03/2021)
2.- surt data+hora:minuts (19/03/2021 HH:mm)
3.- surt data+hora:minuts:segons (19/03/2021 HH:mm:ss)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(3f9c062) y se despliega y prueba en CAIBter.

**Comment by jparedes-indra** [comment]
La función getFechaActual ya retorna las opciones indicadas en la issue. Hemos añadido algunos ejemplos en la ayuda para poder sacar estos valores que se indican. 

![image](https://user-images.githubusercontent.com/67064375/126994806-26051e4b-2fb1-4b8e-a083-37688db4ea6f.png)

![image](https://user-images.githubusercontent.com/67064375/126994813-a27cec0a-d3e6-44b2-8df5-8aaa5b60e402.png)

**Comment by jsastre-dgtic** [comment]
Seguim amb el problema de l'autoemplenat:
Si posam això a la càrrega de dades inicials funciona bé, però si ho posam directament a l'Autoemplenat del camp del formulari directament no:
var ara = PLUGIN_UTILS.getFechaActual(null);
DATOS_VALORESINICIALES.setValor('CDATA',ara);

**Comment by jsastre-dgtic** [comment]
Així tampoc
var ara = PLUGIN_UTILS.getFechaActual(null);
DATOS_VALOR.setValor(ara);

**Comment by jparedes-indra** [comment]
La función del script 'Autoemplenat' no és la misma que la del script de 'Càrrega de dates incial', por lo que no va a funcionar igual. 

Este script esta pensado para lo que indica la ayuda que es esto: Permet indicar que un camp s'empleni a partir de valors d'altres camps (han de ser anteriors a aquest camp). 

Por lo que lo correcto y que sí esta funcionando sería añadir el valor en el script de carga de datos iniciales.

**Comment by jsastre-dgtic** [comment]
ok!

**Comment by jparedes-indra** [comment]
Al realizar varias pruebas, hemos observado lo siguiente. Vamos a añadir esta issue en planificación para su revisión: 
Cuando en el script de autorelleno de un campo de texto se le pasa este script, no aparece el valor de la fecha en STT:
![image](https://user-images.githubusercontent.com/67064375/129148854-ae51a15b-f157-497e-a5ed-3c811e4b5069.png)
![image](https://user-images.githubusercontent.com/67064375/129148858-8c237998-feb6-4c20-a963-49cc265cebe7.png)

En cambio, si se añade la función PLUGIN_DATOSFORMULARIO.getValor() al script, aunque la variable que se le pasa a DATOS_VALOR.setValor() no esté relacionada, este si se rellena automáticamente al hacer click encima del campo de texto: 
![image](https://user-images.githubusercontent.com/67064375/129148889-9ee7a2fd-7243-45f9-af82-590324c94a16.png)
https://user-images.githubusercontent.com/67064375/129150216-73f5fcc0-44a4-405d-8b03-931df0f93c16.mp4



Lo mismo pasa comentando PLUGIN_DATOSFORMULARIO.getValor(), por lo que este comportamiento serà revisado. 
![image](https://user-images.githubusercontent.com/67064375/129148954-5409ce52-75d0-4bd4-8d95-49ae0fef3c17.png)
https://user-images.githubusercontent.com/67064375/129150186-2338c5ae-7b5e-4dbb-8ca8-97bc39640e0b.mp4

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/140878695-2812a097-81cd-4f95-aeb3-098b66a8bf2c.png)

**Comment by jsastre-dgtic** [comment]
ok

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/141786642-1b7775fb-9c0d-480f-b740-2f81a966f833.png)
