### ISSUE TITLE
STT: Implementació del workflow de tramitació II 

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#29]
- Implementació de la lògica genèrica del workflow de les passes de tramitació i de la passa "Cal saber"
- Presentació de la passes en el frontal, enllaç amb la capa de negoci i accés a dades.

**Comment by amaciam-indra** [comment]
A continuació s'adjunta alter parcial per upgrade a versió del commit be114f3
[ALTER_STT.txt](https://github.com/GovernIB/sistra2/files/2155828/ALTER_STT.txt)

**Comment by sgelabert-dgtic** [comment]
Aplicats canvis sobre la BBDD de DES de SISTRAGES
Hauriem de canviar el nom del fitxer ALTER_STT.txt per ALTER_STG.txt

**Comment by sgelabert-dgtic** [comment]
Ups, tens raó Àlex... No sé com però el que he executat ha estat (cosa que entenc que també havia de fer):
```
/* 18/06/2018 - 22/06/2018 */
alter table STG_ENTIDA add ENT_LOPD  NUMBER(18);
comment on column STG_ENTIDA.ENT_LOPD is 'Texto respecto LOPD';

alter table STG_ENTIDA
   add constraint STG_ENTIDA_TRADUC_FK4 foreign key (ENT_LOPD)
      references STG_TRADUC (TRA_CODIGO);

update stg_entida set ENT_PRGDIA = 30;
commit;
alter table STG_ENTIDA modify  ENT_PRGDIA not null;

/* 25/06/2018 - 29/06/2018 */
alter table STG_ROLARE drop column RLA_PERPRO;
```
Em dec haver equivocat de fitxer...

**Comment by amaciam-indra** [comment]
Sí, aquest és l'alter que s'ha de fer damunt la BBDD de SISTRAGES i que s'ha adjuntat a la issue #19

**Comment by amaciam-indra** [comment]
A continuació s'adjunta alter parcial per upgrade a versió del commit 07f4db4
[ALTER_STT.txt](https://github.com/GovernIB/sistra2/files/2176594/ALTER_STT.txt)

**Comment by rsanz-indra** [comment]
Hemos detectado un problema al desplegar en el JBoss standalone que no se reproduce en desarrollo ni en el JBoss embedded ni en los test JUnit. Lo revisamos para solucionarlo.

**Comment by sgelabert-dgtic** [comment]
No disposam de frontal #30 per poder testejar la implementació de les passes de tramitació.
Sí que hem vist que s'executen tests maven per SISTRAMIT que recuperen informació estàtica del tràmit. Desconeixem però l'abast dels tests en relació amb l'objecte de la incidència. Ho podeu documentar ?

**Comment by rsanz-indra** [comment]
En la tarea #36 se comenta el tema de la documentación de los tests.
