### ISSUE TITLE
STG: SECURITZACIÓ DR/GFE - configuració autenticacions

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#291]

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.2.0 (de3bcce) y se despliega en CAIBter.

**Comment by jsastre-dgtic** [comment]
Seria més segur si una autenticació des del domini/GEF només es pogués seleccionar, després d'assegurar la seva existència i si no existeix, crear-la/editar-la/eliminar-la des de la pantalla de configuració d'autenticacions. 

D'aquesta manera evitariem canvis incoluntaris a una autenticació assignada a N tràmits.

**Comment by jparedes-indra** [comment]
Tras comentar con la CAIB, vamos a sustituir (en las pantallas de formulatio externo y dominio remoto) el botón + (crear autenticación), por un botón "Consultar", para que se abra un popup con los datos (en modo lectura) de la autenticacion seleccionada en el combo.

![imagen](https://user-images.githubusercontent.com/67064375/126759095-820f5de4-f292-4636-b648-7b9594201b19.png)

**Comment by jsastre-dgtic** [comment]
Comentar també que des de la pantalla de configuració d'autenticacions hauríem de tenir accés a testejar el bon funcionament d'un domini associat. Actualment només el tenim en mode lectura sense poder fer ping.

![image](https://user-images.githubusercontent.com/18436867/127853573-12106e36-2432-405b-860d-338c5f89eda0.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (003a482) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
El botón de Ping aparece correctamente al mirar los dominios asociados.
![image](https://user-images.githubusercontent.com/67064375/130778108-29c7a056-082a-4dc3-964a-e84f438c8454.png)

**Comment by jparedes-indra** [comment]
En las pantallas de dominios de área y de gestores externos, aparece el botón de consulta en vez del de crear autenticación. Solo se permite crear una autenticación desde la pantalla de configuración de autenticación. 
![image](https://user-images.githubusercontent.com/67064375/130778278-31c90b06-13e9-4ade-90ef-fa9f1648a832.png)
![image](https://user-images.githubusercontent.com/67064375/130778284-fe885067-d34a-4ceb-b992-e33e6229c661.png)

**Comment by avillen-dgtic** [comment]
Els canvis es veuen reflectits.
