### ISSUE TITLE
STG: SECURITZACIÓ DR/GFE - Adaptació gestors externs de Formularis

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#293]

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.2.0 (de3bcce) y se despliega en CAIBter.

**Comment by jsastre-dgtic** [comment]
Entenem desplegada a DEV CAIB, però necessitaríem definir un GFE per a poder validar-la...

**Comment by jparedes-indra** [comment]
En DEV vemos que habéis añadido en el área de TESTS el GFE de CAIBter. ¿Os basta para validar las issues relacionadas con GFE o necesitáis algo más?

**Comment by jsastre-dgtic** [comment]
Ens basta sempre i quan estigui operatiu el GFE de caibter. El vaig configurar a posteriori del comment...

**Comment by jparedes-indra** [comment]
Al tener el GFE, ¿faltaría alguna cosa más o se puede cerrar esta issue?

**Comment by jsastre-dgtic** [comment]
Per tot el referent a GFE/DR,  estam amb el desenvolupament d'un GFE i DR per a tenir en el nostre local un exemple d'on estirar.
