### ISSUE TITLE
STG: SECURITZACIÓ DR/GFE - Adaptació gestió placeholders

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#294]

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.2.0 (de3bcce) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (913d950) y se despliega en CAIBter.

De momento se puede probar mediante swagger, pero estamos securizando el trámite TEST-REMOTO para poder realizar pruebas de forma visual.

**Comment by jsastre-dgtic** [comment]
Restam a l'espera?

**Comment by jparedes-indra** [comment]
Con tal de probar los placeholders en un dominio remoto o en un gestor externo de formularios, se tienen que realizar las siguientes operaciones: 

1.- Indicamos en el fichero sistrages.system.properties el usuario y contraseña de la autenticación: 
sistrages/scripts/conf/sistrages.system.properties
 
![image](https://user-images.githubusercontent.com/67064375/126993494-95ab38a2-f72b-4632-a7eb-e649e3e4c86b.png)

2.- Una vez configurada la autenticación en este archivo, se configura en STG una autenticación utilizando los placeholders de esta forma: 
![image](https://user-images.githubusercontent.com/67064375/126993505-7010a6e9-a704-4619-aaae-287d2277cbdf.png)

 
3.- Para probar si se añaden correctamente los parámetros en un dominio, añadimos la autenticación a dicho dominio.
 
![image](https://user-images.githubusercontent.com/67064375/126993512-4e9b55fc-9668-4fc4-95f9-61bb935cdc24.png)

4.- Realizamos un ping a este dominio securizado y veremos que funciona correctamente ya que la configuración de autenticación se pasa correctamente. 


5.- Lo mismo para un GFE, seleccionamos la configuración de autenticación creada:
 
![image](https://user-images.githubusercontent.com/67064375/126993560-0b106d35-f7db-46f5-acd7-2d3067373eee.png)

6.- Y en un trámite que utilice un GFE securizado (como TEST-REMOTO), probamos de acceder al GFE y veremos como funciona correctamente. 

![image](https://user-images.githubusercontent.com/67064375/126993541-d02a6625-3042-40b0-b286-21d91abdf017.png)

**Comment by jsastre-dgtic** [comment]
Comprovat al domini d'àrea uo_pbe.
