### ISSUE TITLE
STG: SECURITZACIÓ DR/GFE - Adaptació procés importació

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#295]

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.2.0 (de3bcce) y se despliega en CAIBter.

**Comment by jsastre-dgtic** [comment]
Entenem desplegada a DEV CAIB, però necessitaríem definir un GFE per a poder validar-la...

**Comment by jparedes-indra** [comment]
Al tener el GFE de CAIBter, ¿faltaría alguna cosa más o se puede cerrar esta issue?

**Comment by jsastre-dgtic** [comment]
El procés d'importació no funciona encara pel tema de la securització que no es detecta. Depèn de la #369, quan tanquem podrem validar aquesta.

**Comment by jparedes-indra** [comment]
Se resuelve la issue #369

**Comment by avillen-dgtic** [comment]
La issue #369 està resolta. Donem aquesta també per tancada.
