### ISSUE TITLE
STG: SECURITZACIÓ DR/GFE - Adaptació capa REST

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#296]

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.2.0 (de3bcce) y se despliega en CAIBter.

**Comment by jsastre-dgtic** [comment]
Entenem desplegada a DEV CAIB, però necessitaríem definir un GFE per a poder validar-la...

**Comment by jparedes-indra** [comment]
Al tener el GFE de CAIBter, ¿faltaría alguna cosa más o se puede cerrar esta issue?

**Comment by jsastre-dgtic** [comment]
Per tot el referent a GFE/DR, estam amb el desenvolupament d'un GFE i DR per a tenir en el nostre local un exemple d'on estirar.

**Comment by avillen-dgtic** [comment]
La documentació s'adapta a la capa i el GFE generat funciona.
