### ISSUE TITLE
STT: SECURITZACIÓ DR/GFE - Adaptació gestió dominis

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#298]

**Comment by jparedes-indra** [comment]
Se resuelve en CAIBter, en la versión 1.2.0(64208c6).

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/124255923-fe826580-db2a-11eb-8459-276f6a4f7a47.png)

![image](https://user-images.githubusercontent.com/18436867/124255954-093cfa80-db2b-11eb-9455-d85c3f92ad51.png)

**Comment by jsastre-dgtic** [comment]
També es produeix error al desar la configuració d'autenticació:

![image](https://user-images.githubusercontent.com/18436867/124256552-b9aafe80-db2b-11eb-90f4-19169a912534.png)

![image](https://user-images.githubusercontent.com/18436867/124256566-be6fb280-db2b-11eb-87cb-1046391fad31.png)

**Comment by jparedes-indra** [comment]
Se ha resuelto el error al guardar la autenticación con un usuario con rol Desarrollador.

![imagen](https://user-images.githubusercontent.com/67064375/124346630-40b9ae80-dbe0-11eb-824d-cddfdb176bc7.png)

Se ha resuelto el error al cerrar el popup de dominios asociados a una autenticación.

![imagen](https://user-images.githubusercontent.com/67064375/124346652-562ed880-dbe0-11eb-992e-512bc859e4cc.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by avillen-dgtic** [comment]
Testejat i guarda sense mostrar cap classe d'error.
