### ISSUE TITLE
STT: SECURITZACIÓ DR/GFE - Adaptació gestió gestors externs formularis

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#299]

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.2.0 (de3bcce) y se despliega en CAIBter.

**Comment by jsastre-dgtic** [comment]
Entenem desplegada a DEV CAIB, però necessitaríem un GFE per a poder validar-la. Podríem disposar-ne d'un?

**Comment by jparedes-indra** [comment]
Al tener el GFE, ¿faltaría alguna cosa más o se puede cerrar esta issue?

**Comment by jsastre-dgtic** [comment]
Per tot el referent a GFE/DR, estam amb el desenvolupament d'un GFE i DR per a tenir en el nostre local un exemple d'on estirar.
