### ISSUE TITLE
STT: Frontal Assistent de Tramitació

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#30]
- Implementació  de la capa HTML/JS de l'Assistent de Tramitació i connexió amb la lògica del servidor.

**Comment by jsastre-dgtic** [comment]
Per provar la passa registrar necessitam saber com configurar el plugin de rw3 (STT: Frontal Assistent de Tramitació II #40)

**Comment by amaciam-indra** [comment]
Aquesta issue es correspon amb la implementació de la capa HTML/JS de l'Assistent de Tramitació, i no a la lògica de l'assistent. A SISTRAMIT es pot provar la implementació HTML/JS fins la passa a la que s'ha arribat fins ara en el desenvolupament del workflow de tramitació (passa Annexar).

**Comment by jsastre-dgtic** [comment]
Tenia entès que aquesta issue incloia la STT: Frontal Assistent de Tramitació II #40, on diu:
Es continua amb la implementació del frontal de tramitació de la tasca #30. Implementació fins a la passa Registrar
No és així?

**Comment by amaciam-indra** [comment]
Correcte, però torn a insistir en que aquestes issues fan referencia a la implementació HTML/JS. Per poder testejar l'HTML/JS fins al pas registrar primer s'ha de desenvolupar el workflow fins a aquest punt.
