### ISSUE TITLE
SECURITZACIÓ DR/GFE - Proves integració generals

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#300]

**Comment by jparedes-indra** [comment]
De momento se puede probar mediante swagger, pero estamos securizando el trámite TEST-REMOTO para poder realizar pruebas de forma visual. Finalizada esa tarea describiremos cómo hacerlas y entregaremos esta issue.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jparedes-indra** [comment]
Pasos para comprobar securización de dominio remoto - Probar en el dominio TDOMINIO-REMOTO-TEST una configuración de autenticación distinta a TEST-AUTENTICACION. Ocurre lo siguiente al hacer ping: 
![image](https://user-images.githubusercontent.com/67064375/126153440-6b5d8ba2-7836-4373-9d49-b0137b34c08e.png)
![image](https://user-images.githubusercontent.com/67064375/126153448-5cd4aa14-4fe3-4cc4-8a35-9be98b349611.png)

**Comment by jparedes-indra** [comment]
Pasos para comprobar securización de un formulario externo: ![image](https://user-images.githubusercontent.com/67064375/126154097-66ad048c-effe-4589-9d82-66408f22544b.png)Formulario:
![image](https://user-images.githubusercontent.com/67064375/126154034-226fac32-82a9-4834-92b7-28bee2802c86.png)
![image](https://user-images.githubusercontent.com/67064375/126154046-da7273ce-0ef7-4623-83c9-2381d763d3bc.png)
Accedemos en STT al Formulario Externo
![image](https://user-images.githubusercontent.com/67064375/126154118-90b103b5-c20e-4b9b-8d7d-723880840617.png)
Si cambiamos la autenticación por otra:
![image](https://user-images.githubusercontent.com/67064375/126154127-49764521-fc54-485b-8818-2d3757e6363a.png)
![image](https://user-images.githubusercontent.com/67064375/126154136-2e3a8eec-5e4b-4c86-a953-4eba649929cd.png)
En STH vemos el error: 
![image](https://user-images.githubusercontent.com/67064375/126154166-65d087ef-4c2f-49dc-9d8d-c7c099f61a70.png)

**Comment by jsastre-dgtic** [comment]
Sin autenticación --> Sense autenticació 
![image](https://user-images.githubusercontent.com/18436867/126946857-0ffe6ba1-1da6-45e0-a748-4ec12a679295.png)

**Comment by jsastre-dgtic** [comment]
Sense autenticació no hauria de funcionar el ping de domini

![image](https://user-images.githubusercontent.com/18436867/126949908-e1a39cd1-f06a-4c49-b6b0-51da24d8c4d0.png)

**Comment by jsastre-dgtic** [comment]
Ídem amb el Formulari Extern

![image](https://user-images.githubusercontent.com/18436867/126951475-5571b91e-3fb3-44a4-8a36-28a1fef63676.png)

![image](https://user-images.githubusercontent.com/18436867/126951307-15019ebf-40db-46e5-bf8a-ddafd0a7ac03.png)

**Comment by dmadronal-indra** [comment]
Buenas, 
El problema relacionado con la autenticación (acceder en modo sin autenticación) era problema del proyecto de ejemplo, ya está solventado.
queda pendiente revisar el tema del literal "Sin autenticación"

**Comment by jsastre-dgtic** [comment]
Quan estigui el literal  farem proves a dev caib per validar-ho. Mentrestant, ho deixam a revisió.

**Comment by jparedes-indra** [comment]
El literal ya se ha corregido, ¿se podría cerrar esta issue?
