### ISSUE TITLE
Noms dels documents annexos

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#302]
1.- Els noms dels documents annexos que s'inclouen no poden contenir els següents caràcters per a que REGWEB3 els pugui processar:
No es permet [>,%, *, &,:,;,,?, /, |,!, <, ¡, "

2.- Ara s'especifica el mimetype del document, però a un pdf no es posa el nom.pdf. Cal posar l'extensió per a que Arxiu/Alfresco els pugui mostrar després. Per tant, han d'arriba ra RW3 amb l'extensió al nom:

3.- fix per a detectar els caràcters no vàlids i els substitueixi per "_"
 
![REGISTRE_nomdoc](https://user-images.githubusercontent.com/18436867/112800362-d7218580-906f-11eb-8a7c-606c5b4abb40.jpg)

**Comment by jparedes-indra** [comment]
Se detecta que también han de eliminarse esos caracteres en el campo "Descripción"

![imagen](https://user-images.githubusercontent.com/67064375/116823961-d6f13a00-ab87-11eb-83e2-b4abf4be8c19.png)

**Comment by avillen-dgtic** [comment]
Caràcters testejats i el comportament és correcte.
