### ISSUE TITLE
STG: BUG al plugin GFE

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#303]
Falla "urlCallback":"https://dev.caib.es/sistramitfront/asistente/retornoGestorFormularioExterno.html" al PLUGIN de GFE

**Comment by jparedes-indra** [comment]
Se ha detectado un problema en el plugin del Gestor de Formularios Externos, por lo que se actualiza la rama 1.1 y se crea el TAG 1.1.5 (4ae97b4).

**Comment by jparedes-indra** [comment]
Se resuelve en rama 1.1 y TAG 1.1.5 (4ae97b4).
