### ISSUE TITLE
STG: No permetre simulació a la previsualització en entorns de PRE/PRO. Deshabilitar check. 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#304]
A PRE/PRO es permet SIMULACIÓ quan no s'hauria de permetre perquè si ho fas tanmateix falla: 

es.caib.sistramit.core.api.exception.CatalogoProcedimientosException: Simulación de catálogo procedimientos sólo disponible para entorno desarrollo 
        at deployment.sistramit.ear.sistramit-

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega en CAIBter, pero no en DEV.

**Comment by jsastre-dgtic** [comment]
Desplegat a DEV i pendent dels quaderns de càrrega per a desplegar a PRE

**Comment by jsastre-dgtic** [comment]
ok
