### ISSUE TITLE
Revisió de la integració amb Carpeta Ciutadana

### ISSUE THREAD

**Issue by fjcalderon-dgtic** [GovernIB/sistra2#306]

**Comment by jsastre-dgtic** [comment]
Comentar la qüestió de l'hora que arriba a Carpeta. Ara arriba el GMT+0 i hauria d'arribar GMT+1 (+horari estiu)= GMT+2
![image](https://user-images.githubusercontent.com/18436867/123916669-37cba180-d982-11eb-924d-702d9e20a680.png)

**Comment by jparedes-indra** [comment]
El formato retornado es correcto, y es el recomentado para las api rest. 

El problema es que en la aplicación de destino, en este caso carpeta, se debe aplicar el timezone que se desee, para mostrar la fecha en el formato deseado.

![imagen](https://user-images.githubusercontent.com/67064375/124960173-5550d900-e01c-11eb-8681-c03027b0690f.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (de3bcce) y se despliega en CAIBter.
