### ISSUE TITLE
STG: Eliminar tots els scripts d'una versió d'un tràmit

### ISSUE THREAD

**Issue by fjcalderon-dgtic** [GovernIB/sistra2#307]

**Comment by jparedes-indra** [comment]
Esta funcionalidad permite eliminar los scripts de una versión concreta de un trámite.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (913d950) y se despliega en CAIBter. Al seleccionar una versión, aparece una opción de menú que pemrmite eliminar los scripts de esa versión específica.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jparedes-indra** [comment]
Probado correcto funcionamiento
![image](https://user-images.githubusercontent.com/67064375/126141188-c4755158-4a96-4175-a41a-b18df45f3a0a.png)
![image](https://user-images.githubusercontent.com/67064375/126141196-64a701c1-70a8-401c-a6f5-12f6a583bc01.png)

**Comment by avillen-dgtic** [comment]
Testejat. Elimina els scripts correctament.
