### ISSUE TITLE
Millora del tràmit TEST-FUNC

### ISSUE THREAD

**Issue by fjcalderon-dgtic** [GovernIB/sistra2#309]

**Comment by jsastre-dgtic** [comment]
Actualment el tràmit TEST-FUNC inclou les següents funcionalitats:

· Tots els mètodes d'autenticació i accés anònim, persistència sense límit i script de paràmetres inicials.
· FORM-1: Formulari obligatori amb scripts "Càrrega de dades inicials", "Paràmetres d'obertura de l'formulari" i "Postguardar formulari". Components i camps: Línia, Secció, Text, Selector i checkbox, cadascun amb diferents scripts de autocompletat, estat, validació i valors possibles, així com propietats d'obligatorietat, només lectura, tipus i altres.
· FORM-2: Formulari opcional amb camps avís i autorrellenados de formulari anterior.
· FORM-3: Formulari dependent amb script "Establir dependència").
· FORM-4: Formulari opcional amb script "Càrrega de dades inicials" i camps d'avís i text amb scripts d'estat i validació, de diversos tipus "Identificació".
· ANE-1: Annex dependent amb script "Establir dependència" i amb extensions pdf i odt.
· ANE-2: Annex obligatori i amb extensions pdf i doc.
· ANE-XML: Annex obligatori, amb extensió xml i script de validació.
· ANE-PDF: Annex obligatori i fitxer i script de validació.
· PAG-1: Pagament obligatori amb passarel·la "ATIB".

A nivell de formulari faltaria:
· Revisar límit de text i opció multilínia en camp text.
 
A nivell de tràmit / versió faltaria:
· multipàgina
· Annexos dinàmics
· Camps dependents (similar a TRAMITE_MULTIPLE)

**Comment by jparedes-indra** [comment]
Se añaden funcionalidades nuevas al trámite, tales como multipágina, anexos dinámicos y campos dependientes (TRÁMITE_MÚLTIPLE). Se mantiene en CAIBter al integrar multipágina y no estar desplegada la versión 1.2.0 en DEV.

**Comment by jsastre-dgtic** [comment]
https://github.com/GovernIB/sistra2/issues/220#issuecomment-865863548

**Comment by jparedes-indra** [comment]
Ya se aclaró el funcionamiento de la multipágina y se resolvió en la issue #220.

**Comment by jsastre-dgtic** [comment]
ok
