### ISSUE TITLE
PLG: Component horitzontal d'autenticació LoginIB

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#31]
- Creació del component horitzontal d'autenticació CAIB que integrarà d'inici l'autenticació per Cl@ve i anònima.
- Definició del plugin d'integració

**Comment by sgelabert-dgtic** [comment]
Es sol·licita implementació de sobre el Cl@ve2

**Comment by rsanz-indra** [comment]
No vemos en el espacio de CAIB (https://github.com/GovernIB) la aplicación LOGINIB.
Podéis crearlo?

**Comment by sgelabert-dgtic** [comment]
Acabem de crear el repositori https://github.com/GovernIB/pluginsib-loginib
He assignats al usuaris @rsanz-indra , @amaciam-indra , @gcorullon-indra , @jmico-indra al projecte

**Comment by rsanz-indra** [comment]
Hemos subido los fuentes al proyecto pluginsib-loginib.
Esta issue debería pasarse al proyecto pluginsib-loginib para que se queden reflejados los commits.
También necesitaremos que se incluyan los jars propios de Cl@ve en el repositorio maven CAIB (una vez los hayamos generado los pasaremos).

**Comment by rsanz-indra** [comment]
Se ha implementado toda la operativa sobre Cl@ve 1. Para Cl@ve 2 hay problemas de conexión, se ha puesto consulta al CAID

**Comment by ftrias-dgtic** [comment]
Quan executam el .bat des de la consola, per genear els .ear, es produeix aquest error: 

[ERROR] Failed to execute goal on project sistracom-plugins-mock: Could not resolve dependencies for project es.caib.sistra2:sistracom-plugins-mock:jar:0.0.1-SNAPSHOT: Failure to find es.caib.loginib:loginib-rest-api:jar:0.0.1-SNAPSHOT in https://governIB.github.io/maven/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of governIB has elapsed or updates are forced

**Comment by sgelabert-dgtic** [comment]
Ho farem així per provar-ho, però lo seu és que es faci un deploy del jar sobre el repositori de Maven de GitHub incorporant al POM el codi per fer l'upload:
```
<plugin>
  <groupId>com.github.github</groupId>
 <artifactId>site-maven-plugin</artifactId>
 <version>0.12</version> 
 <configuration>
           <!-- git commit message -->
           <message>Maven artifacts for ${project.version}</message> 
           <outputDirectory>${project.build.directory}/mvn-repo</outputDirectory> 
           <noJekyll>true</noJekyll>   
           <!-- remote branch name -->
           <branch>refs/heads/gh-pages</branch> 
           <includes>
	             <include>**/*</include>
           </includes>
           <path>maven</path>
           <!-- github repo name -->
           <repositoryName>maven</repositoryName>      
           <!-- github username or organization  -->
           <repositoryOwner>GovernIB</repositoryOwner>    
           <server>github_governib_maven</server>
           <merge>true</merge>
           <dryRun>false</dryRun>
           </configuration>
           <executions>
	           <execution>
 	             <goals>
  	               <goal>site</goal>
	             </goals>
	             <phase>deploy</phase>
	          </execution>
	     </executions>
</plugin>
		 		 
 </plugins>
	 </build>
	 <distributionManagement>
         <repository>
	       <id>github_governib_maven</id>
	       <name>GitHub GovernIB Maven Repository</name>
	       <url>file://${project.build.directory}/mvn-repo</url>
	     </repository>
  </distributionManagement>
```

**Comment by rsanz-indra** [comment]
Sí, es la idea, tal como se hace p.e. con el api de Solr. También existen unos jars de Cl@ve2.0 que están incluidos en el propio proyecto que están en un repositorio interno al proyecto que estaría bien subirlos al repo CAIB.
Pero hasta que no tengamos algo más estable no vale la pena.

Aclarado el tema, volvemos a pasar la entrada a desarrollo.

**Comment by rsanz-indra** [comment]
Pasamos esta entrada a entregada ya que existen entradas propias en el repositorio de LoginIB
