### ISSUE TITLE
FORMACIÓ: El·laboració del Curs de Formació Avançada de SISTRA2

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#311]
BLOC 1: (ens encarregarem a la DGMAD del contingut). 
1.1.- Procés per sol·licitar un nou tràmit telemàtic. Si s’implementa amb  SISTRA2, quins són els permisos necessaris a ROLSAC, SISTRA2 i DISTRIBUCIÓ (visió del gestor), així com el paper de CARPETA (visió de l'ciutadà). 
1.2.- Amb els permisos establerts, la pràctica consistirà en realitzar la configuració de nova fitxa ROLSAC per provar el seu acoblament amb un tràmit SISTRA2 i realitzar una comprovació, des de DISTRIBUCIÓ, per tal de visualitzar el contingut d'una sol·licitud registrada de prova.

BLOC 2: Exemple avançat de tramitació (s'encarrega l'equip d'INDRA)

2.1.- Exemple de tramitació avançada amb SISTRA2. Desenvolupament des de zero d'un tràmit que faci ús d'un formulari més complex, amb l'ús de tots els components actuals disponibles al gestor de formulari de SISTRAGES
2.2.- Capacitats que ofereix el motor de scripting, també per a l'apartat d'annexos , per exemple, ensenyar com flexibilitzar aquest apartat i crear annexos dependents. 
2.3.- Informació sobre el pas de pagament de taxa, ampliant en aquesta ocasió la seva configuració a les dues passarel·les de pagament ja disponibles

BLOC 3: Migració (s'encarrega l'equip d'INDRA)

3.1.- Exemple de migració d'un tràmit d'SISTRA1 i SISTRA2.  Encara que no estigui disponible per a un perfil de "administrador d'àrea", convé que en tenguin una visió àmplia. En aquest procés es recalcarà en el no automatisme del procés i que presenta algunes limitacions actuals, motivades en part perquè no disposem encara de la funcionalitat "formulari multi-pàgina".

BLOC 4: Dominis remots  (ens encarregarem a la DGMAD del contingut)

4.1.- Exemple pràctic de configuració de domini remot amb SISTRA2, fent ús del projecte base. 

BLOC5: Integració amb un GFE (s'encarrega l'equip d'INDRA)

5.1.- Exemple de formulari extern amb SISTRA2. Exemple d’Educació.

BLOC 6: Què passa quan es registra un tràmit amb SISTRA2?  (ens encarregarem a la DGMAD del contingut)

6.1.- Configuració de DISTRIBUCIÓ 
6.2.- Integració amb backoffice per recuperar el contingut de les sol·licituds finalitzades de SISTRA2 i crear un expedient dins una Sèrie Documental definitiva d’Arxiu. (RIPEA, HELIUM, PBE)

**Comment by jparedes-indra** [comment]
Se envía correo el 20/08 con enlace de descarga de la formación correspondiente a Indra
