### ISSUE TITLE
Refrescar canvis formulari ajuda

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#312]
Quan hi ha canvis a la pestanya d'ajuda de sistrages, tot i desar/refrescar M.Cau, no es reflecteix a sistramit (entorn PRO)

![image](https://user-images.githubusercontent.com/18436867/115018065-b05caf00-9eb7-11eb-8717-bb4473a455f2.png)

![image](https://user-images.githubusercontent.com/18436867/115018080-b5b9f980-9eb7-11eb-9360-f0226d26120c.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jsastre-dgtic** [comment]
ok
