### ISSUE TITLE
STT: Dades de tramitació persistent

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#313]
Emmagatzemar un conjunt mínim d'informació de tramitació de manera persistent i servir-la via API de SISTRAMIT. 
Proposam d'entrada els camps següients:
codSIA, nom del tràmit, data de tramitació, DNI, numero de registre d'entrada, estat (finalitzat, inacabat, pendent de personació).
Modificació de l'api STT perquè serveixi la informació per rang de dates i de manera paginada.

**Comment by jparedes-indra** [comment]
Se resuelve esta incidencia en el TAG 1.2.0 (de3bcce) y se muestran los datos solicitados en SISTRAHELP.

![imagen](https://user-images.githubusercontent.com/67064375/124576508-aa3df500-de4c-11eb-8421-5eba5fafe2cb.png)

**Comment by jsastre-dgtic** [comment]
No veiem nom del tràmit, només id.

**Comment by jparedes-indra** [comment]
Añadiremos el nombre de trámite.

**Comment by avillen-dgtic** [comment]
A caibter i a dev es veu aquesta informació.
![image](https://user-images.githubusercontent.com/83401259/127632482-8c692b83-de4c-42ff-9861-90c2c4f17089.png)
