### ISSUE TITLE
STH: incloure al detall de l'error les dades inicials NIF/NOM

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#314]
A SISTRAHELP hauríem de poder seleccionar i copiar el NIF (i el nom) de la columna d'esdeveniments per tal de posar-la al filtre, i tampoc surt al detall i hi hauria de sortir. 
![image](https://user-images.githubusercontent.com/18436867/115851545-59ab2400-a427-11eb-804d-6653afdb49f6.png)

![image](https://user-images.githubusercontent.com/18436867/115851765-99720b80-a427-11eb-805e-257cfae84d90.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(b84bea7) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jsastre-dgtic** [comment]
ok
