### ISSUE TITLE
STT: Controlar la mida màxima de la descripció dels annexos

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#315]
(SQLException: ORA-12899: el valor es demasiado grande para la columna "SISTRAMIT"."STT_DOCPTR"."DTP_ANEDES" (real: 104, máximo: 100))

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by avillen-dgtic** [comment]
Accepta 200 caràcters.
![image](https://user-images.githubusercontent.com/83401259/122045799-71c37200-cdde-11eb-9af0-ee7d04c21012.png)
