### ISSUE TITLE
STT: Millorar l'estructura del correu a través del Formulari d'incidències

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#316]
Que el correu vengui sense tipificar ni cap informació estructurada no és el desitjat (hauria de sortir com a SISTRA1): 

        Incidència tramitació - Dubtes funcionals - TF0009CMOB 
        
Tràmit 	Sol·licitud de primera expedició o renovació de llicència de pesca recreativa (Immediata) 
Id Tràmit 	AP0035PESI 
Id Procediment	AP0035PESI 
Data creació	20/04/2021 20:31:26 
Id persistència 	NR0LKWDY-MCNKGDT8-T8USX7K2 
Nivell d'autenticació	Sense autenticació 
NIF	18233959L 
Nom	Javier 
Telèfon	649989870 
Adreça electrònica	jamarnu@hotmail.com 
Horari de contacte	08:00- 20:00 
Tipus de problema	Problemes a l'accedir o per firmar un tràmit amb certificat 
Descripció del problema 	Hola, fa uns quant mesos faig fer la sol·licitud de llicència de pesca recreativa i no lhe rebuda. Neccesitaria infromació sobre el seguiment de la sol·licitud. Gràcies

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jsastre-dgtic** [comment]
Pendents de solucionar un problema amb el nostre servidor de correu

**Comment by jsastre-dgtic** [comment]
Caldria direccionar a una adreça nostra el formulari d'incidències caibter per a poder validar

**Comment by jsastre-dgtic** [comment]
No ens arriba el correu. Relacionat amb el CAI- 2141222...

**Comment by jsastre-dgtic** [comment]
Format aconseguit. Ara tenim altres errors en issue Errors al Formulari d'incidències #358
