### ISSUE TITLE
Completar la doc tècnica amb explicacions de SISTRAHELP

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#317]
A la documentació tècnica no hi ha cap referència als rols del mòdul SISTRAHELP, ni STH_SUP ni STH_OPE. Cal afegir-ho

**Comment by jparedes-indra** [comment]
Se actualiza el documento en la rama 1.2, con URL: https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrahelp/doc/SISTRAHELP_Manual_Instalacio.odt.

**Comment by avillen-dgtic** [comment]
A la documentació ja hi figuren les referències als rols.

**Comment by jparedes-indra** [comment]
Se resuelve en CAIBter, en la versión 1.2.0(64208c6).
