### ISSUE TITLE
STH poder fer "paste" a tràmit/cod PA?

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#318]
BUG STH per fer "paste" a tràmit/cod PA

![image](https://user-images.githubusercontent.com/18436867/116679635-1282dd00-a9ab-11eb-9ac5-60a827bc06ac.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(b84bea7) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jsastre-dgtic** [comment]
ok
