### ISSUE TITLE
STT: Gestionar tipus de document a l'autenticació

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#319]
Per a NIE s'hauria enviar el tipus de document "E" i s'està passant "N".

![image](https://user-images.githubusercontent.com/18436867/116849442-0ab37a80-abef-11eb-9639-3c950ce456a3.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución. También se resuelve en la 1.1.6.

**Comment by jsastre-dgtic** [comment]
Segueix demanant el llinatge del representant a la IG

![image](https://user-images.githubusercontent.com/18436867/127831011-e8fa540a-78d1-4298-880c-6465e3b83531.png)

![image](https://user-images.githubusercontent.com/18436867/127831045-93a6d3fd-7052-46a0-87a6-0671173b1b44.png)

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/127831875-de7bd29f-1036-4d45-bffa-a0296f3b4c1a.png)

**Comment by jsastre-dgtic** [comment]
Cal que faceu les proves a DEV CAIB, s'hauria de comprovar que parlam de la mateixa versió alineada. Comprovat això hauríeu de fer la prova amb el mateix certificat de representant, que ja vos passàrem per aquest motiu.

**Comment by dmadronal-indra** [comment]
Buenas, 
No entendemos muy bien cuál es exactamente la problemática. ¿nos podéis detallar que estáis rellenando en los diferentes campos del trámite de IG para tratar de replicarlo? también necesitaríamos que nos facilitarais de nuevo el certificado para poder testearlo.

En cualquier caso, el problema que se muestra en los pantallazos,
![imagen](https://user-images.githubusercontent.com/17270582/129897229-13a3db31-9170-4fc7-96ef-ae4fa83dba11.png)
Viene dado debido a que el nif 99999973K es un nif de persona Física, y en estos casos debería venir informado el primer apellido, el hecho de que no venga informado hace pensar que es un error del certificado.

**Comment by jsastre-dgtic** [comment]
Si és un error del certificat hauríem de veure quin exactament, perquè a la informació del certificat, teniu un Surname= Ficticio Activo, i aquesta és la info que no es detecta

Vos pas el certificat de proves una altra vegada per correu... 

CN = 99999973K REPRESENTANTE FICTICIO (R: A01111111)
G = REPRESENTANTE
SN = FICTICIO ACTIVO
SERIALNUMBER = 99999973K
O = IZENPE S.A.
OU = Ordezkari ziurtagiria - Certificado de representante
2.5.4.97 = VATES-A01111111
Description = Reg:Gasteiz /Hoja:B-166472 /Tomo:37393 /Seccion:8 /Libro:1 /Folio:20 /Fecha:10-02-1974 /Inscripción:1
C = ES

**Comment by dmadronal-indra** [comment]
Buenas, 
tal como se ha comentado por correo el problema es que en el certificado no llegan los datos de apellido1 y apellido 2 desglosados, (vienen juntos en un único campo) por eso no es posible por ahora mostrarlos en la aplicación.

**Comment by jsastre-dgtic** [comment]
En aquest correu restavem pendents de l'anàlisi que ens havíeu d'enviar...
" la solución pasa por añadir la funcionalidad de permitir desglosar los datos, y almacenar esa información de apellidos desglosados en loginIB. Realizaremos un pre-análisis para ver qué implicaciones tiene y os enviaremos un documento con los detalles."
