### ISSUE TITLE
STG:  Warning JSF

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#32]
Adjunt warning quan s'accedeix  a SISTRAGES  [warning-jsf.txt](https://github.com/GovernIB/sistra2/files/2179891/warning-jsf.txt)

**Comment by sgelabert-dgtic** [comment]
Pareix que era un problema de temporals... No s'ha tornat a reproduir

**Comment by sgelabert-dgtic** [comment]
Nou warning al accedir [log_sistrages20180711.txt](https://github.com/GovernIB/sistra2/files/2183244/log_sistrages20180711.txt)

**Comment by rsanz-indra** [comment]
A nosotros nos ha llegado a pasar a uno de nosotros durante un tiempo de forma aleatoria que con un siguiente redespliegue se corregía. En todo caso la aplicación funciona correctamente, no vimos que causaba ningún efecto. Habéis notado algún efecto en la aplicación?

**Comment by sgelabert-dgtic** [comment]
De moment no hem notat cap defecte funcional en l'aplicació. Amb la versió que tenim desplegada el warning bota de manera aleatoria.

**Comment by sgelabert-dgtic** [comment]
Segueix apareixent el warning:
```
2018-08-24 12:04:00,473 WARNING [javax.enterprise.resource.webcontainer.jsf.application] (default task-39) JSF1064: no se encuentra o sirve el recurso, jquery/jquery-plugins.js, desde la biblioteca, primefaces.
2018-08-24 12:04:00,473 WARNING [javax.enterprise.resource.webcontainer.jsf.application] (default task-39) : java.io.IOException: TuberÃ­a rota
```

**Comment by jsastre-dgtic** [comment]
Passam a la tasca #81
