### ISSUE TITLE
STT: Canviar el literal "Ajuda"

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#322]
Canviar el literal "Ajuda" per: "Ajuda tècnica en la tramitació telemàtica"
![image](https://user-images.githubusercontent.com/18436867/117260580-86136700-ae4f-11eb-86d1-664f57b0543b.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by avillen-dgtic** [comment]
Aquest canvi ha fet desaparèixer el telèfon de contacte. 
![image](https://user-images.githubusercontent.com/83401259/122022457-e5598500-cdc6-11eb-9073-9814e9796943.png)

**Comment by avillen-dgtic** [comment]
El canvi s'ha fet.
![image](https://user-images.githubusercontent.com/83401259/122043975-3fb11080-cddc-11eb-8199-a6fa049e5803.png)
