### ISSUE TITLE
STG: Mantenir checks autenticació al promocionar

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#323]
Al generar el quadern a dev i processar-lo a PRE (release 26), no ens manté els canvis a l'autenticació. A més ens surt un error amb les dades de registre... 

![image](https://user-images.githubusercontent.com/18436867/117262896-033fdb80-ae52-11eb-8d6a-f0d556e8ffb3.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jsastre-dgtic** [comment]
Desplegat a DEV i pendent dels quaderns de càrrega per a desplegar a PRE

**Comment by jsastre-dgtic** [comment]
Ok
