### ISSUE TITLE
STT: tractament dades de representant

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#324]
modificar SISTRA2 per a que per defecte tracti les dades de representant tal com ho fa per a les dades del presentador, per no controlar-lo a nivell de tràmit.

**Comment by jsastre-dgtic** [comment]
Cal avaluar si modificam LOGINIB per a que ens proporcioni totes les dades del certificat (que detecti els de tipus 11-12) i després a SISTRA2, triar el representant a l'autenticació. ( https://github.com/GovernIB/LOGINIB/issues/16 )

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
La validación de firma con certificado de representante ya funciona entre PFIB y SISTRA2. 
Para ello hay que tener instalada en los entornos la última versión de PFIB (v2.0.20) y activar la validación de firma y DNI en todas las configuraciones del perfil de firma que corresponda.

**Comment by jsastre-dgtic** [comment]
desplegada la versió S2 1.2.1 a caib dev i atacant la 2.0.21als entorns caib, comprovam que funciona bé.
