### ISSUE TITLE
STG: els camps de text multilínia no pinten a SISTRAMIT les línies establertes a SISTRAGES

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#325]
![image](https://user-images.githubusercontent.com/18436867/118448900-d5308600-b6f2-11eb-9b19-514241840aa8.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(c9b2299) y se despliega en CAIBter, pero no en DEV.

**Comment by avillen-dgtic** [comment]
A sistramit el comportament és l'esperat. Et notifica si has passat de les 20 línies.
