### ISSUE TITLE
STG: Control número caràcters a l'editor tiny

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#327]
Revisar que no se superi el número 4000 de caràcters a l'editor tiny dels avisos al disseny de formularis i estabilitzar el comportament a l'hora de guardar, per evitar que es produeixi errors.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by avillen-dgtic** [comment]
S'introdueix un text aleatori, de 3999 caràcters i surt el missatge
![image](https://user-images.githubusercontent.com/83401259/122018408-1e8ff600-cdc3-11eb-8b4a-31642cfbbda1.png)

**Comment by jparedes-indra** [comment]
Se ha mejorado el mensaje para explicar mejor la circunstancia del tamaño permitido.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (9030c09) y se despliega en CAIBter.

**Comment by avillen-dgtic** [comment]
Revisada la funcionalitat i es tanca la incidència.
