### ISSUE TITLE
Crear un mecanisme que ens permeti conèixer la versió dels 3 entorns de  SISTRAMIT, SISTRAHELP, LOGINIB i PAYMENTIB.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#328]
Crear un mecanisme que ens permeti conèixer la versió instal·lada a cada entorn, tant en SISTRAMIT, LOGINIB i PAYMENTIB.

Una possible solució seria mitjançant HTML ocult (STT i LIB)
SISTRAHELP i PAYMENTIB entenc que són fronts intern i es pot visualitzar al peu de pantalla, tal i com es mostra a la imatge (img02).
Aprofitant aquest canvi, vos demanam normalitzar al català l'etiqueta de l'entorn de tots els mòduls (img01).
producción=producció
preproducción=preproducció
desarrollo=desenvolupament

img01:
![image](https://user-images.githubusercontent.com/18436867/119320110-826b4700-bc7b-11eb-83a8-12697c72bca0.png)

img02
![image](https://user-images.githubusercontent.com/18436867/119320120-85663780-bc7b-11eb-91dd-8ef06c8e5293.png)

**Comment by jparedes-indra** [comment]
Se actualiza SISTRA 2 rama 1.2(de3bcce), LOGINIB TAG 2.3.2(d423c2a) y PAYMENTIB TAG1.1.1(338b0ae) para permitir ver la versión y compilación al pulsar botón derecho sobre la interface y acceder al código de la página. La información de versión y compilación aparece en la parte inferior.

**Comment by jsastre-dgtic** [comment]
No veim que s'hagi fet la segona part de la petició:
Aprofitant aquest canvi, vos demanam normalitzar al català l'etiqueta de l'entorn de tots els mòduls (img01).
producción=producció
preproducción=preproducció
desarrollo=desenvolupament

**Comment by avillen-dgtic** [comment]
Fent la revisió de la versió 1.2.0 encara veiem que no està feta aquesta issue.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (9030c09) y se despliega en CAIBter.

**Comment by avillen-dgtic** [comment]
![image](https://user-images.githubusercontent.com/83401259/124577314-70b9b980-de4d-11eb-9114-ef0ee4cef460.png)

Encara no podem identificar les versions, revisat tant a STG com a STH.

**Comment by jsastre-dgtic** [comment]
A STT:
![image](https://user-images.githubusercontent.com/18436867/124592922-4d4b3a80-de5e-11eb-9f47-402a94b353d4.png)

A STG:
![image](https://user-images.githubusercontent.com/18436867/124592954-56d4a280-de5e-11eb-86a7-13936c58d71a.png)

A STH: No és correcte Desarrollo--> Desenvolupament (igual que a STG)
![image](https://user-images.githubusercontent.com/18436867/124593042-766bcb00-de5e-11eb-8a7b-0422eb8cccf1.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

En paymentIB, se ha indicado en el commit FIX: #298 erróneamente. En realidad, el commit de paymentIB soluciona esta issue, que es la #328.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/126152501-8cb2738e-b064-40bb-9b11-1254ac9c452a.png)
![image](https://user-images.githubusercontent.com/67064375/126152512-140c845b-473c-43ec-b7ae-77f8554e4ea5.png)
![image](https://user-images.githubusercontent.com/67064375/126152520-f88e9cf3-39b6-4e3e-8859-0e9dfca776e5.png)
![image](https://user-images.githubusercontent.com/67064375/126152532-d5d66760-d776-4936-b863-2a38382f5e4b.png)
![image](https://user-images.githubusercontent.com/67064375/126152548-d915d261-37ab-4724-b344-2ee24825936f.png)
![image](https://user-images.githubusercontent.com/67064375/126152558-5941d91a-1657-45f1-aad1-d6a47e1edd88.png)

**Comment by avillen-dgtic** [comment]
Els canvis s'han comprovat i són correctes.
