### ISSUE TITLE
STG: Implementació API Rest SISTRAGES

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#33]
Es continua amb la implementació de l'API interna el tiquet #28 :
- Documentació de l'API amb Swagger
- Implementació dels serveis interns : [descripció]

**Comment by sgelabert-dgtic** [comment]
D'acord amb el document de disseny tècnic el context d'accés a l'API interna és: /sistrages/api/rest/interna i veig que en el web.xml està securitzat amb el rol STG_API_INT i que funciona correctament si s'empra l'usuari de WS $sistramit_sistrages,  però quin seria el context d'accés a la documentació amb al swagger-editor?

**Comment by sgelabert-dgtic** [comment]
En quan a l'API interna de SISTRAGES:
> /sistrages/api/rest/interna/entidad/{id}

- El backoffice i l'API retornen com "identificador" de l'entitat el codi DIR3, però l'operació de consulta empra l'identificador intern (ENT_CODIGO) de BBDD. A través del backoffice, no podem consultar l'id de l'entitat en cap lloc (aniria bé que es presentés com a camp protegit).  El JSON de retorn, tampoc figura l'id intern de l'entitat.

> /sistrages/api/rest/interna/entidad/{id}/avisos

- No funciona, retorna sempre una llista buida d'avisos, quan el backoffice n'hi ha de definits. 
- Els avisos són multi-idioma, per tant, entenc que faltaria el paràmetre idioma sistrages/api/rest/interna/entidad/{id}/avisos/{idioma}
- Segurament hauríem de poder treure els avisos d'una versió de tràmit concreta sistrages/api/rest/interna/tramite/{idTramite}/{version}/avisos/{idioma}, no?

> /sistrages/api/rest/interna/dominioFuenteDatos/{idDominio}

- Desconec l'estructura del JSON amb el paràmetres per fer petició POST. Pendent de provar-ho amb swagger

> /sistrages/api/rest/interna/entidad/1/permisosHelpdesk
- Dóna un 404

Entenc que l'API s'anirà completant en funció de les necessitats dels altres mòduls. A priori hagués definit altres operacions que no figuren a l'API.
A més cal veure si la granularitat d'operacions com /rest/interna/tramite/{idTramite}/{version}/{idioma} és adequada o ens convé segmentar-ho afegint un paràmetre de pas de tramitació, per exemple.

**Comment by sgelabert-dgtic** [comment]
El commit https://github.com/GovernIB/sistra2/commit/e6568716435705d44e11e4dc7dbb6ad5022f044e relacionat amb el tiquet #29 "Implementació del workflow de tramitació II" conté codi d'implementació de l'API SISTRAGES. Per favor, intentau relacionar els commits amb les incidències, si no és molt difícil dur-ne el seguiment.

**Comment by rsanz-indra** [comment]
Por error se comiteo asociado a la issue que no tocaba. Todos esos cambios son de esta issue.

**Comment by jsastre-dgtic** [comment]
No ens funciona:
**http://sdevapplin5.caib.es:48080/sistrages/api/rest/interna/dominioFuenteDatos/CIUTATS**
<html>
    <head>
        <title>Error</title>
    </head>
    <body>Request method 'GET' not supported</body>
</html>

**http://sdevapplin5.caib.es:48080/sistrages/api/rest/interna/emtidad/A04003003/permisosHelpdesk**
**http://sdevapplin5.caib.es:48080/sistrages/api/rest/externa/tramite**
<html>
    <head>
        <title>Error</title>
    </head>
    <body>Forbidden</body>
</html>

**Comment by jsastre-dgtic** [comment]
1.- Ok, ara el problema és que no aconseguim crear una Font de Dades:
![image](https://user-images.githubusercontent.com/18436867/46522924-7ccf5180-c884-11e8-8008-05aa4e056c64.png)
![image](https://user-images.githubusercontent.com/18436867/46522938-85278c80-c884-11e8-9eda-8a1ea6c2cf58.png)

**Comment by dmadronal-indra** [comment]
Buenas, 
Antes de crear un dominio que consuma una fuente de datos, es necesario crear la fuente de datos, y al crear el dominio es necesario indicar la fuente, en este caso al no existir ninguna no puede seleccionar una por defecto. Este error parece darse solo si no se ha creado ninguna fuente de datos, añadiremos un control para evitarlo. Si probáis creando primero la fuente de datos debería ir bien. ¿lo podéis verificar?

**Comment by jsastre-dgtic** [comment]
Creant abans la Font de Dades si ens deixa. Però el servei dóna error... <html>
    <head>
        <title>Error</title>
    </head>
    <body>Internal Server Error</body>
</html>

**Comment by jsastre-dgtic** [comment]
Al document: 
[](https://github.com/GovernIB/sistra2/blob/sistra2-1.0/doc/pdf/SISTRA2_DisenyoTecnico.pdf)
A la pàgina 12: http://sdevapplin5.caib.es:48080/sistrages/api/rest/interna/entidad/A04003003/permisosHelpdesk

I a la pàgina 14:
http://sdevapplin5.caib.es:48080/sistrages/api/rest/externa/tramite

(Si posam "http://sdevapplin5.caib.es:48080/sistrages/api/rest/interna/tramite/SA001/1/ca", funciona bé)

**Comment by dmadronal-indra** [comment]
Referente a la consulta del error al consultar la fuente de datos, el dominio dado de alta no incluye ninguna consulta por lo que, segun parece, es normal que no retorne resultados, si se incluye una consulta valida debería funcionar.

Referente a las funcionalidades indicadas del API Interna de STT sólo están implementados los servicios necesarios para la integración dº (STT--> STG), que es la integración que se ha puesto en marcha. En este ciclo se ha definido el  módulo API Rest para STT, se han implementado las funciones necesarias y se ha puesto en marcha la integración con STG. Cuando se comience con el STH se implementarán dichos servicios.
Respecto al API Externa tampoco está planificada todavía la implementación.

**Comment by jsastre-dgtic** [comment]
1. Amb una QUERY= SELECT ID, DESC FROM CIUTATS, seguim obtenint error. Tampoc podem fer un ping, ni estam segurs del pseudollenguatge.... ens comentau com fer-ho?

<html>
    <head>
        <title>Error</title>
    </head>
    <body>Internal Server Error</body>
</html>

2.- Ok
3.- Ok

**Comment by amaciam-indra** [comment]
Hola,

Amb la URL http://sdevapplin5.caib.es:48080/sistrages/api/rest/interna/dominioFuenteDatos/DOMINICIUTATS sí que obtenim una reposta:

{
    "datos": [
        {
            "ID": "01",
            "DESC": "Palma"
        },
        {
            "ID": "02",
            "DESC": "Inca"
        }
    ],
    "error": false,
    "codigoError": null,
    "descripcionError": null,
    "numeroFilas": 2,
    "nombreColumnas": [
        "ID",
        "DESC"
    ]
}

Respecte al ping, aquesta funcionalitat encara no està implementada, tal i com indica la propia aplicació amb un alert.

**Comment by jsastre-dgtic** [comment]
Qualque cosa tenc jo malament idò:
![image](https://user-images.githubusercontent.com/18436867/46597944-82c26e00-cae2-11e8-9d73-4ea968b96bb7.png)

**Comment by jsastre-dgtic** [comment]
OK, ja me funciona! Gràcies

**Comment by jsastre-dgtic** [comment]
En poder compilar acabam de provar el nou control per a crear font de dades...

**Comment by jsastre-dgtic** [comment]
ok, si no vos queda res pendent de consulta podem tancar la issue... ens ho confirmau?

**Comment by amaciam-indra** [comment]
confirmat, podeu tancar
