### ISSUE TITLE
millorar el missatge informatiu d'un error d'script

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#330]
Quan falla l'script, si no s'ha indicat un missatge d'error en l'script, s'indicaria que falta.

No és evitar aquest error, sinó que en lloc de donar un error no controlat (nullpointer) es generi un error controlat que indiqui clarament el motiu (throw new ErrorConfiguracionException ( "No existeix missatge error amb codi" + pCodigoMensajeError);)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0 y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jsastre-dgtic** [comment]
Ok
![image](https://user-images.githubusercontent.com/18436867/122902953-39c4ad80-d34f-11eb-8de1-2a903a604a9d.png)
