### ISSUE TITLE
Verificar el funcionament de la funció SetDatosContacto a l'enviar país, província o municipis sense valor.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#331]
Verificar el funcionament de la funció SetDatosContacto a l'enviar país, província o municipis sense valor.

**Comment by dmadronal-indra** [comment]
Buenas,
Vamos a añadir una serie de medidas en las ramas 1.1 y 1.2 para tratar de evitar el error.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (64208c6) y se despliega en CAIBter.

**Comment by jsastre-dgtic** [comment]
Comprovat registrant això:
![image](https://user-images.githubusercontent.com/18436867/124278447-92155f80-db46-11eb-9549-2eb9939cc561.png)
