### ISSUE TITLE
Funcionalitat caché SISTRA2-ROLSAC

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#332]
Implementar la funcionalitat de cache entre SISTRA2-ROLSAC

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/126143037-fbfc70ed-63f6-4513-96fc-6b0e3212fcb3.png)
Resultado cache correcta: 
![image](https://user-images.githubusercontent.com/67064375/126143089-be33317b-2cd7-494b-bbd3-4fd077a77fc0.png)

**Comment by jparedes-indra** [comment]
Inicio:
 
![image](https://user-images.githubusercontent.com/67064375/126143192-cea35e07-9e99-4201-b87b-519f8bacd446.png)

Se cambia por esto:

![image](https://user-images.githubusercontent.com/67064375/126143222-c9952074-bb19-47ad-b63f-c00fd131ee3c.png)

Resultado cache correcta: 

![image](https://user-images.githubusercontent.com/67064375/126143268-4de1a038-548b-482a-96d9-addc044c0f9e.png)

**Comment by avillen-dgtic** [comment]
Comprovat que els canvis fets a ROLSAC són reflectits a STG i STT
