### ISSUE TITLE
Escriure al XML els formularis els camps de data amb el mateix format que al formulari (dd/mm/aaaa). 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#333]
Ara el pdf surt així però l'xml surt com a "aaa/mm/dd". Helium només té un format de data dd/mm/aaaa

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jparedes-indra** [comment]
Probado correcto funcionamiento. 
![image](https://user-images.githubusercontent.com/67064375/126140921-fe1adcdb-250b-403a-98e2-9fc4ee110d94.png)
![image](https://user-images.githubusercontent.com/67064375/126140942-7bffe1e3-56df-4282-a17a-c4c6b67abb4a.png)

**Comment by jsastre-dgtic** [comment]
Correcte
<CAMPO id="CDATA" tipo="simple"><VALOR>23/07/2021</VALOR>
