### ISSUE TITLE
STG: Actualitzar dominis emprats per tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#334]
Si substituïm un domini per un altre, queda la informació dels dos, amb la consegüent problemàtica migratòria
![image](https://user-images.githubusercontent.com/18436867/122728114-1418a500-d278-11eb-826e-45c61ebbc3cb.png)

**Comment by jparedes-indra** [comment]
Hemos intentado replicar el error pero no terminamos de entender la casuística. ¿Podéis detallar lo que está pasando para poder entenderlo y solucionarlo?

**Comment by jsastre-dgtic** [comment]
Els dos dominis mostrats a la imatge fan el mateix. Quan vaig canviar a un desplegable que enlloc d'estirar d'un estiràs de l'altre, a l'hora de promocionar me sortiren l'antic i el nou, quan en realitat només s'emprava el nou, al tràmit en qüestió.

**Comment by jsastre-dgtic** [comment]
Cal millorar la validació de versió perquè intenti detectar dominis no usats i afegir un warning per revisar-los

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
![#334](https://user-images.githubusercontent.com/67064375/135093457-c75b3a53-dc07-41e0-8306-5ad6e8203a87.gif)

**Comment by jsastre-dgtic** [comment]
Així com s'actualitza automàticament la llista de dominis emprats quan el cridam a un formulari, el que es pretenia era actualitzar aquesta llista automàticament. Podeu valorar-ho?

**Comment by jsastre-dgtic** [comment]
Es renuncia a https://github.com/GovernIB/sistra2/issues/334#issuecomment-933190105 per ser massa complicat si la crida es realitza des dels scripts.
En el seu lloc, s'accepta la validació amb els warnings pertinents:

![image](https://user-images.githubusercontent.com/18436867/142394625-c49eff4b-3fe7-468c-b49a-bc6926a307d7.png)

![image](https://user-images.githubusercontent.com/18436867/142394711-e1590bf2-4f65-419b-b8b2-b40be2206914.png)
