### ISSUE TITLE
STG: Molla de pa normalitzada

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#335]
Surt version enlloc de versió:
![image](https://user-images.githubusercontent.com/18436867/123052782-7f42b280-d403-11eb-8850-871d4e33a40a.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (4a1501f) y se despliega en CAIBter.

**Comment by avillen-dgtic** [comment]
Canvi present
