### ISSUE TITLE
STT: Al checkbox per acceptar la protecció de dades canviar accepte per accepto

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#337]
![image](https://user-images.githubusercontent.com/18436867/123058657-56252080-d409-11eb-88d3-861a13950efc.png)

**Comment by avillen-dgtic** [comment]
.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/126140257-dd3cffbc-af86-44c0-abc5-2aaefe36dc90.png)

**Comment by avillen-dgtic** [comment]
Apareix el canvi
