### ISSUE TITLE
STG: Desar domini SQL al fer PING

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#338]
Quan fas ping sense desar abans, te demana si vols desar però no ho desa... 

![image](https://user-images.githubusercontent.com/18436867/123403373-00877a00-d5a9-11eb-8977-9cf26e1c7795.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(4aed129) y se despliega y prueba en CAIBter. Está pendiente que la CAIB despliegue en DEV para validar la resolución.

**Comment by jparedes-indra** [comment]
Prueba realizada y correcto funcionamiento. 

![image](https://user-images.githubusercontent.com/67064375/126139975-f43b3132-da70-4654-9d79-d304010808ab.png)

![image](https://user-images.githubusercontent.com/67064375/126140013-9555b16c-21fa-47aa-9917-d0afd41c1980.png)

**Comment by avillen-dgtic** [comment]
Funcionament correcte.
