### ISSUE TITLE
STG: Afegir fitxers d'ajuda als annexes com administrador d'àrea

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#339]
![image](https://user-images.githubusercontent.com/18436867/123937972-fd203400-d996-11eb-9118-3e1971ebb2ad.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (003a482) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
Al entrar con un usuario administrador de área, funciona correctamente ya.

**Comment by avillen-dgtic** [comment]
Apareix l'ajuda als annexos com a rol administrador.
