### ISSUE TITLE
 Exigir l'existència d'almenys un formulari a cada versió de tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#340]

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (4a1501f) y se despliega en CAIBter. 

Al validar un trámite, si no existe formulario aparece el aviso en la pantalla:

![imagen](https://user-images.githubusercontent.com/67064375/126560178-0f6b2afd-50f4-4a22-8434-82d58df7b463.png)

**Comment by avillen-dgtic** [comment]
El missatge apareix i resol la incidència.
