### ISSUE TITLE
STG: Definició del camps tipus import per a que accepti negatius i decimals

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#341]
![image](https://user-images.githubusercontent.com/18436867/124245124-f5d86200-db1f-11eb-82e8-23bf74c7bf04.png)

**Comment by jparedes-indra** [comment]
Se permite añadir números negativos y decimales en el rango de un campo de texto de tipo Número.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/e1948144-0888-4d66-b92c-92228cc8ba5c)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/9539c46a-ff2b-47fb-882e-c111764b90b6)

**Comment by jsastre-dgtic** [comment]
Si s'introdueix un negatiu al rang, s'hauria de marcar automàticament el "permetre negatius"

![image](https://github.com/GovernIB/sistra2/assets/18436867/4402580b-64ca-4fae-83b9-18bcde83d2c7)

**Comment by jparedes-indra** [comment]
Se marca y desmarca el check “Permite negativos”, en función de si los números del rango son negativos o no.
 
![PruebaNumeroNegativo](https://github.com/user-attachments/assets/769af143-a4bd-48cc-816d-f6fab3719f7d)

**Comment by jsastre-dgtic** [comment]
No funciona...

![image](https://github.com/user-attachments/assets/e9599880-8afd-4815-bce0-089b4e83c346)

![image](https://github.com/user-attachments/assets/5a94a6f5-ce54-4201-bb1f-4d02c104e506)

**Comment by jparedes-indra** [comment]
Se rellena la precisión entera de forma automática al marcar la opción de permitir rango y se valida que no quede vacía.

![341importeNegativoError1](https://github.com/user-attachments/assets/875aed6c-c50e-4ce9-91a3-ac517784317d)

![341importeNegativoError2](https://github.com/user-attachments/assets/5078e021-1685-48a2-b090-30583ede6f57)

**Comment by jsastre-dgtic** [comment]
![Image](https://github.com/user-attachments/assets/6476f076-9623-45e2-8052-2158129ba5fa)
![Image](https://github.com/user-attachments/assets/3ad1f5d9-406c-4067-a562-1c9f60f3072c)

**Comment by jsastre-dgtic** [comment]
Comprovat i correcte

![image](https://github.com/user-attachments/assets/325823a8-8e27-44cc-b5db-28140fdd4f06)
