### ISSUE TITLE
STT: Millora formatador justificant pagament

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#342]
![image](https://user-images.githubusercontent.com/18436867/124277932-ebc95a00-db45-11eb-8a04-9b865bd8a65b.png)

**Comment by jparedes-indra** [comment]
Indicar que, más que mejorar el formateador justificante pago, se va a ampliar el formateador pdf para añadir las funcionalidades requeridas para mostrar el justificante simulado de esa manera.

**Comment by jsastre-dgtic** [comment]
Perquè es canvia de formatador depenent de si és un justificant de pagament real o un de pagament simulat? 
Com es resol el justificant de pagament si es tria la via del TPV de La Caixa?

**Comment by jparedes-indra** [comment]
Esta pregunta se respondió en un correo el 08/07 a las 20:27 explicando que el justificante de pago simulado no tiene relación con los justificantes que se van a emitir reales. Aún así, ¿queréis que hagamos las modificaciones de alinear el título PAGAMENT SIMULAT a la izquierda y no tan junto a la tabla?

**Comment by jsastre-dgtic** [comment]
Si, però canviant només tasa per taxa. Entenc que això no té cap implicació en la resta de clases.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/135089436-1ad0f997-8a88-4dc0-8660-e496fb993a2b.png)

**Comment by jsastre-dgtic** [comment]
Tot correcte, ara només demanaríem que el nom de l'arxiu fos justificant.pdf (enlloc de justificante)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/140878010-0c78a099-adfd-49ac-ace9-ca449009920b.png)

**Comment by jsastre-dgtic** [comment]
comprovat
