### ISSUE TITLE
No pendre SIMULAT si el Check està desactivat

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#344]
Al copiar la url de la previsualització ens surt simulat quan el check està inactiu

https://dev.caib.es/sistramitfront/asistente/iniciarTramite.html?tramite=TEST-REGISTRE&version=5&idioma=ca&servicioCatalogo=false&idTramiteCatalogo=$--SIMULADO--$

![image](https://user-images.githubusercontent.com/18436867/124724426-47ac2e00-df0c-11eb-96b8-251f6e6d907d.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (966f47b) y se despliega en CAIBter.

**Comment by avillen-dgtic** [comment]
Tràmit sense el check & copiant URL
http://caibter.indra.es/sistramitfront/asistente/iniciarTramite.html?tramite=TEST_330&version=3&idioma=ca&servicioCatalogo=false&idTramiteCatalogo=2848219

Tràmit amb check & copiant URL
http://caibter.indra.es/sistramitfront/asistente/iniciarTramite.html?tramite=TEST_330&version=3&idioma=ca&servicioCatalogo=false&idTramiteCatalogo=$--SIMULADO--$
