### ISSUE TITLE
STH: Controlar l'error de l'esdeveniment Enviar Tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#345]
Al acceder al evento "Enviar trámite" aparece un error.

![image](https://user-images.githubusercontent.com/18436867/124753596-74227300-df29-11eb-8212-d719ec01f747.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.2.0 (c9e1606) y se despliega en CAIBter.

**Comment by avillen-dgtic** [comment]
L'error ja no es produeix.
