### ISSUE TITLE
STG: A l'intentar duplicar un tràmit i dur-lo a una nova àrea, falla 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#346]
![image](https://user-images.githubusercontent.com/18436867/125040667-37c15500-e098-11eb-9654-e49a82b64c6f.png)

**Comment by jparedes-indra** [comment]
Parece ser que es un problema de fichero, pero necesitamos más información sobre como se produce el error para poder solucionarlo. ¿Podéis explicarnos qué trámite es el que duplicáis y a qué área lo movéis?

**Comment by avillen-dgtic** [comment]
No només en canviar d'àrea, també dintre de la mateixa àrea.
![image](https://user-images.githubusercontent.com/83401259/127457974-a098baf6-405d-4a62-a398-694b966303d9.png)

**Comment by jparedes-indra** [comment]
Hemos comprobado que este error se debía a un problema de configuración en CAIBter. Ya está resuelto y comprobado que no se reproduce.

**Comment by avillen-dgtic** [comment]
La clonació des d’una àrea o des d'un tràmit funciona correctament.
