### ISSUE TITLE
 Aparició d'un camp sense funció en aquesta pantalla... 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#347]
![image](https://user-images.githubusercontent.com/18436867/125040919-748d4c00-e098-11eb-9d04-1df3e7fa1cba.png)

**Comment by jsastre-dgtic** [comment]
ok
![image](https://user-images.githubusercontent.com/18436867/130777232-05aea6a1-9fc2-4286-bfb0-7a147c364ac6.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (003a482) y se despliega en CAIBter
