### ISSUE TITLE
STG: Control·lar l'error: Falla la connexió a la BBDD de Sistra1

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#348]
Aquesta millora ha de controlar els missatges d'error quan es vol intentar connectar a la base de dades de Sistra1 o qualsevol altra base de dades.

**Comment by jparedes-indra** [comment]
Cuando falla la conexión a la BBDD de SISTRA1, de la cual se nutre el desplegable de Trámites de SISTRA1, mostrar error en misma pantalla y no en pantalla completa:
![image](https://user-images.githubusercontent.com/67064375/126948613-4427274e-a001-421f-822d-113cb265d27a.png)
![image](https://user-images.githubusercontent.com/67064375/126948656-5c7e0730-6fd5-4fa3-b926-0d48423f69bd.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (003a482) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
En caso de que falle la conexión con la BBDD de S1 en la pantalla de migración, ahora el error aparece de la siguiente forma: 
![image](https://user-images.githubusercontent.com/67064375/130777218-5cda14d5-ef42-4b88-85b1-e21b184cfc68.png)

**Comment by jsastre-dgtic** [comment]
ok
