### ISSUE TITLE
STH: Fer més gran la finestra de la traça d'error

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#349]
A petició vostra hem obert aquesta issue. 
Com a suggeriment i evitar futures issues d'aquest tipus, podríeu fer d'aquestes finestres que siguin redimensionable per l'usuari a voluntat.
![image](https://user-images.githubusercontent.com/83401259/126121992-b5b14f21-87e0-44d7-bc6b-766f6041f4a0.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (966f47b) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
Traza redimensionable y más grande. 
![image](https://user-images.githubusercontent.com/67064375/126644455-2cd1584b-4d5a-4c8f-9dbd-2b1897a60717.png)

**Comment by avillen-dgtic** [comment]
El que no arribo a entendre és perquè el text no és redimensionable quan modifiquem la resolució. Tinc entès que l'aplicació ha de ser totalment responsive.
![image](https://user-images.githubusercontent.com/83401259/126758904-0ddffe18-2262-4862-b69f-63dce356b1e1.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(3f9c062) y se despliega y prueba en CAIBter.

**Comment by avillen-dgtic** [comment]
El diàleg de les traces s'ajusta a la finestra.
