### ISSUE TITLE
STG: Multipàgina - pàgines fantasmes

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#351]
Quan elimines les pàgines i ten vas a la navegació de les existents hi apareixen les "esborrades". 
![#new](https://user-images.githubusercontent.com/83401259/126602438-d3c7b856-209c-4a85-ac11-e33a76910dec.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (003a482) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
Ahora al eliminar una página y darle a Editar a otra, primero detecta que se han realizado cambios y pide si se quieren guardar o no. En caso afirmativo, ya aparecen correctamente las páginas: 
![#351](https://user-images.githubusercontent.com/67064375/130776945-b27a3589-5c23-41db-bd3b-9c923f55e1cc.gif)

**Comment by jsastre-dgtic** [comment]
S'hauria de permetre desar la pàg 1 i la 4 com a finals?
![image](https://user-images.githubusercontent.com/18436867/130779310-7e4fe8cc-502e-41e6-a1b8-15f71d8db54b.png)

**Comment by jsastre-dgtic** [comment]
Ok
