### ISSUE TITLE
STG: Dominis - Canvi del text de confirmació

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#352]
Al text de confirmació s'ha de fer interrogatiu a la pregunta.

![image](https://user-images.githubusercontent.com/83401259/126602977-6da9453a-914d-4acb-820d-4dd9fb77c112.png)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/130775418-cd458542-a37d-43c9-b795-db0e22ce9504.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.2.0 (003a482) y se despliega en CAIBter.

**Comment by jsastre-dgtic** [comment]
"amb el guardat" no és correcte. S'hauria de canviar per "segur que vol desar els canvis?"

**Comment by jparedes-indra** [comment]
Cambiado
![image](https://user-images.githubusercontent.com/67064375/132842350-21747ec1-7d4e-43f1-8c31-02536b84c3d5.png)
