### ISSUE TITLE
STG: Validació de tràmits abans previsualitzar o alhora de crear URL

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#353]
Ens hem trobat amb molts de casos errors a STT per un error al tràmit, com a exemple la no existència d'un formulari. Aquests errors es detecten mitjançant la funció de validació que hi ha amagat al menú.

La proposta és validar el tràmit abans de previsualitzar-lo mostrant un diàleg amb els problemes o suggeriments, si és que existeixen.

**Comment by jparedes-indra** [comment]
Para poder aclarar esta issue necesitamos más información. La propuesta que sería, ¿que se validase la issue al darle al botón de previsualizar? 

¿Qué tipo de errores queréis que se controlen en esta validación a parte de la no existencia de un formulario, que ya se está controlando? ¿Por ejemplo el control de errores en los scripts del trámite?

**Comment by avillen-dgtic** [comment]
El que es proposa és evitar els errors una vegada s'està previsualitzant un tràmit. Sigui un error dels scripts o si no existeix un formulari.

**Comment by jparedes-indra** [comment]
Al hacer click en el botón de previsualizar versión, antes de previsualizarse el trámite en STT, valida que no haya errores en el trámite de cualquier tipo: 
![#353](https://user-images.githubusercontent.com/67064375/130775186-62812942-c18f-46a4-9755-229cecfaeea2.gif)

**Comment by jsastre-dgtic** [comment]
ok, però ens podeu explicar quins tipus d'errors ens podem trobar? Perquè la manca de formulari és un error de registre?
![image](https://user-images.githubusercontent.com/18436867/130780555-881f852e-26d0-42d0-acbf-833bc6634ba9.png)

**Comment by jsastre-dgtic** [comment]
Indra diu al correu: En la validación se pueden encontrar este tipo de errores: Literales, Literales HTML, Scripts, Dominios, Formateador, Datos Registro.  En el caso de errores relacionados con literales, el error ya se controla antes de llegar a validar completamente el trámite. Pero en otros, puede ocurrir que podamos previsualizar el trámite sin tener en cuenta estos errores y es por ello que ahora al pulsar el botón de previsualizar se valida el trámite. 
El error de la falta de un formulario es un error de "Datos Registro" porque este tipo de error "es el que se lanza al validar el paso de registrar un formulario". 
- Consideram que el que es registra no és un formulari, sinó tot el tràmit. Es podria llençar un error més específic en el cas que no existís formulari?

Ejemplos de validación de un trámite con errores: 

![image](https://user-images.githubusercontent.com/18436867/144560876-263701fd-84f1-4c30-a8e0-8ef1a05af4a9.png)
![image](https://user-images.githubusercontent.com/18436867/144560922-9b7fc63b-dc65-4764-9630-2a901ce037c6.png)

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0

**Comment by jcerdar-indra** [comment]
- Ahora, al no tener formulario un trámite, al validar se lanza un error más específico: 

![image](https://user-images.githubusercontent.com/96287364/149172198-207cd7b7-c172-4f86-b991-10f0183f7e9b.png)

**Comment by avillen-dgtic** [comment]
👍
