### ISSUE TITLE
STG: Ordre alfabètic als desplegables

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#354]
![image](https://user-images.githubusercontent.com/18436867/127153268-fe904c69-898a-4f53-b7c8-27443375fed7.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
Se ordenan correctamente los desplegables:
![image](https://user-images.githubusercontent.com/67064375/135088005-38ae330d-1715-446e-9ce8-e34be1b05b39.png)

**Comment by avillen-dgtic** [comment]
L'ordre dels desplegables és correcte.
