### ISSUE TITLE
 STG: càrrega paginada de la pantalla àrees / tràmits / versions 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#356]
Actualment, la pàgina principal de veure àrees / tràmits / versions carrega tota la informació disponible (/sistragesback/secure/app/viewTramites.xhtml), fent que la càrrega vagi perdent velocitat a mesura que s'afegeixen tràmits i versions.
Canviar aquesta forma de càrrega per una càrrega que es realitzi de forma paginada en la qual només es carregui la nova informació de tràmits i versions quan s'avanci en les pàgines de navegació.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
Esta issue se va a notar a nivel cualitativo al mejorar la velocidad en la carga de información de las áreas, trámites y versiones de la página principal
