### ISSUE TITLE
STT:  apuntar al detall del registre recentment registrat des de l'enllaç a Carpeta

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#357]
El botó de CARPETA que es mostra a la captura hauria de poder apuntar al detall del registre recentment registrat. Seria una URL semblant a: https://dev.caib.es/carpetafront/#/moduls/registres/p/GOIBE2448/2021 

Per ventura que es pugui modificar via properties? apuntaria a això: https://dev.caib.es/carpetafront/#/moduls/registres/p/ i s'afegiria dinàmicament el núm de registre

![image](https://user-images.githubusercontent.com/18436867/127446093-864cb5e5-ff4a-4d26-ade0-37cc41d48b27.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/132843918-cd25e75c-6d5b-4681-995c-0348e2b6ddb5.png)

La url al pulsar en Carpeta se crea correctamente como nos indicastéis

https://dev.caib.es/carpetafront/#/moduls/registres/p/GOIBE3009/2021

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/133063469-45cdfa97-afec-477b-8bb7-2b2d53417ca1.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
Para resolver esta issue hay que añadir una propiedad en el plugin de registro con los siguientes valores: 
     - Código: justificanteURL
     - Valor: /#/moduls/registres/p/${NUMERO_REGISTRO_B64URLSAFE}
![image](https://user-images.githubusercontent.com/67064375/135094045-8fccd233-b066-49a8-aba9-4966a34cbd8d.png)
