### ISSUE TITLE
Errors al Formulari d'incidències

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#358]
no arriben dels documents adjunts 
no funciona quan pren el responsable de rolsac

**Comment by jparedes-indra** [comment]
¿A qué os referís cuando decís que no funciona cuando coge el responsable de ROLSAC? 

¿Es que no funciona cuando el tipo de destinatario que se indica es Responsable de incidencias? 
![image](https://user-images.githubusercontent.com/67064375/128994159-d3f41d7b-b01e-4e72-bb93-5f6a36f7eb4a.png)

**Comment by jsastre-dgtic** [comment]
Respecte al correu que arriba (només si posam un email directe, no arriba si triam responsables) des del formulari d'incidències: 

1.- No ens arriba el document PDF adjunt que hem pujat al formulari d'incidències 
2.- A l'assumpte del correu hauríem de tenir la mateixa informació que a SISTRA1: "Incidència tramitació - Problemes a l'accedir o per firmar un tràmit amb certificat - MO0006NAUM" 
3.- El que a SISTRA1 era IdProcediment a SISTRA2 hauria de ser Codi SIA del PA 
4.- El que a SISTRA1 era Nivell Autenticació a SISTRA2 hauria de ser QAA/Mètode Cl@ve (distingir entre cert/cl@vepin/Cl@vepermanente) 
  
Exemple S1: 
![image](https://user-images.githubusercontent.com/18436867/129720163-aba00596-2bf0-4080-9a3b-70cbd4ebfae5.png)

**Comment by jparedes-indra** [comment]
Se resuelve el punto 1  en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
Se resuelven el resto de puntos en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/144590222-c7e4229f-5df3-420b-80b4-33fac60d6daf.png)

**Comment by avillen-dgtic** [comment]
Aquesta issue presenta dues falles.

1. Els correus associats a les ajudes. El separador ";" no funciona. Només s'envia el correu al primer d'ells.
2. Comprovació de les dades introduïdes. DNI i Nom. No hi ha cap mena de limitació encara que sigui amb un tràmit que té autenticació. Hauria de quedar limitar l'edició d'aquests dos camps.
![image](https://user-images.githubusercontent.com/83401259/145377836-1c5ce1db-ff1a-4884-a2b3-19612f235ef7.png)

**Comment by jsastre-dgtic** [comment]
Quan el tràmit és "anònim" hi hauria d'haver una validació del camp NIF/DNI/NIE/NSS com a mínim.

No sabem què vol dir "Altres", s'hauria d'explicar a l'ajuda de STG:
![image](https://user-images.githubusercontent.com/18436867/145387250-1e75d1f0-7a7c-42a4-aab1-a0bde5730ebe.png)

**Comment by jparedes-indra** [comment]
El check "Altres" hace referencia a los tipos de NIF de persona física (tipos K, L y M). Lo documentaremos en la ayuda.

**Comment by jcerdar-indra** [comment]
- Se resuelven los distintos puntos mencionados: 
    - Los separadores (;) para listas de correo.
    - Se pone en modo lectura los campos de Nombre y DNI en los formularios de incidencias cuando se accede con autenticación. 
![image](https://user-images.githubusercontent.com/96287364/149172629-9227595b-ef83-42ec-b533-e6d927fa1edd.png)
    - Se añade validación de NIF cuando se accede a un trámite sin autenticación:
![image](https://user-images.githubusercontent.com/96287364/149172753-55b89bbd-4e52-42a0-8d2f-abfd879d08f1.png)
    
    - Se actualizan las ayudas para explicar el significado del check 'Altres'

**Comment by avillen-dgtic** [comment]
Donat que tot el formulari té eines per comprovar el contingut dels inputs, també cal revisar el telèfon.
![image](https://user-images.githubusercontent.com/83401259/149299718-c158be08-ac0c-429c-837b-1f8b0dc51752.png)

**Comment by jcerdar-indra** [comment]
- Se soluciona en el TAG 1.2.2_1(807f0a5)

**Comment by jcerdar-indra** [comment]
![image](https://user-images.githubusercontent.com/96287364/151118826-e8159d09-62a4-4c6b-bf89-2990d8244ec5.png)

**Comment by avillen-dgtic** [comment]
👌
