### ISSUE TITLE
STG: Exportació i importació de dominis d'entitats

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#359]
L’exportació i importació de dominis no funcionen. 
De CAIBTER vull fer una exportació del domini CAIB_DOMINI_FIXO cap a DEV i no és possible.

**Comment by jsastre-dgtic** [comment]
L'exportació pareix que funciona bé.
A l'importar accedim a una pantalla amb un desplegable buit:
![image](https://user-images.githubusercontent.com/18436867/129317471-0487a660-8e57-41dd-8b3f-c9ffa811e9aa.png)

![image](https://user-images.githubusercontent.com/18436867/129317556-d5cda537-2cc1-4496-89ce-8391bea64097.png)

Pel que fa la importació, ha funcionat correctament. Mantenim la issue oberta pel tema del desplegable buit.

**Comment by jsastre-dgtic** [comment]
Tancam i obrim una nova issue:
A l'importar un domini d'entitat accedim a una pantalla amb un desplegable buit #366
