### ISSUE TITLE
STT: Implementació del workflow de tramitació III

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#36]
- Implementació de la lògica genèrica del workflow de les passes de tramitació i de la passa "Emplenar"
- Presentació de la passes en el frontal, enllaç amb la capa de negoci i accés a dades.

**Comment by sgelabert-dgtic** [comment]
No disposam de frontal #30 per poder testejar la implementació de les passes de tramitació.
Sí que hem vist que s'executen tests maven per SISTRAMIT que recuperen informació estàtica del tràmit. Desconeixem però l'abast dels tests en relació amb l'objecte de la incidència. Ho podeu documentar ?

**Comment by rsanz-indra** [comment]
Se ha ampliado los comentarios existentes en los tests de Maven y adicionalmente se ha añadido un punto en el documento de Diseño técnico para indicar los tests implementados para el motor de tramitación.
Además de los tests unitarios del motor de tramitación se puede ir validando el frontal (hasta paso Rellenar). Se puede acceder mediante:
http://localhost:8080/sistramitfront/asistente/iniciarTramite.html?tramite=x&version=1&idioma=es&idTramiteCatalogo=y
En el paso Rellenar para simular el rellenado del formulario hay que utilizar la siguiente url para meter directamente el xml del formulario:
http://localhost:8080/sistramitfront/asistente/rf/simularRellenarFormulario.html?idPaso=RF1&idFormulario=F1

**Comment by jsastre-dgtic** [comment]
http://sdevapplin5.caib.es:48080/sistramitfront/asistente/rf/simularRellenarFormulario.html?idPaso=RF1&idFormulario=SALUT001FORM no ens funciona, però pareix que ja ho heu integrat, perquè desde l'assistent ens surt:
![image](https://user-images.githubusercontent.com/18436867/46527724-4ef10980-c892-11e8-9c3f-85753e788381.png)

**Comment by jsastre-dgtic** [comment]
Observacions al sistramit.

[Observacions a STT.pdf](https://github.com/GovernIB/sistra2/files/2449778/Observacions.a.STT.pdf)

**Comment by rsanz-indra** [comment]
Comentamos las observaciones:
- 1) Los literales del asistente de momento no están traducidos. Los traduciremos una vez esté ya más avanzado. Por tanto habría que posponer los errores de traducción para más adelante. El idioma es un parámetro de inicio del trámite.
- 2) El logo sale así en base al diseño que se nos propuso (se hizo más compacta la cabecera). El logo oficial es ese por lo que si ese es el tamaño de cabecera que se quiere no se puede hacer más. En todo caso vemos que no se ha cargado el logo en blanco que resalta más.
- 3) Revisamos para dar más espacio. Incluimos esta mejora para la revisión del asistente en el próximo ciclo.
- 4) Se da por supuesto que existirá al menos una red social. Si consideráis que puede ser un caso real que no haya ninguna, pues modificamos para que no salga nada.  Si no es un caso real, sirve de "chivato" de que falta meterla.
- 5,6,7) Como hemos comentado en el punto 1 los textos están por revisar, básicamente se ha copiado lo que había en el portal. Más adelante revisaremos bien los textos. No obstante, podéis ir sugiriendo cosas.

**Comment by jsastre-dgtic** [comment]
1,3,5,6,7: Ok
2.- On es configura el logo a mostrar al STT?
4.- Ja ens pareix bé...

**Comment by amaciam-indra** [comment]
Respecte al punt 2 del comentari https://github.com/GovernIB/sistra2/issues/36#issuecomment-427738234, el logo de l'assistent es configura a nivell de propietats d'entitat segons s'indica a la pantallada següent:

![imagen](https://user-images.githubusercontent.com/17268599/46618587-38f87880-cb20-11e8-97d6-d749bdbc1aa6.png)

**Comment by amaciam-indra** [comment]
confirmat, podeu tancar
