### ISSUE TITLE
STG: Maquetació del modals

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#360]
Trobem un altre modal amb problemes de canvis de dimensió.

![image](https://user-images.githubusercontent.com/83401259/127866762-80dd840a-045b-4a30-b203-c4cad9ed6198.png)

**Comment by avillen-dgtic** [comment]
També a les ajudes
![image](https://user-images.githubusercontent.com/83401259/127867464-655dba74-cb4c-4b71-948b-9c9db12e670e.png)

**Comment by alejandrovillen** [comment]
......

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/132842172-5e354dc5-ea5f-4081-b574-0e21bd6d9d8f.png)

**Comment by jsastre-dgtic** [comment]
A l'ajuda apareix un scroll bar que no té gaire sentit

![image](https://user-images.githubusercontent.com/18436867/133074037-0fcd2a1d-b652-4d03-8fc7-618d9ec14829.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
Ya no aparece el doble scroll en las ayudas. 
![image](https://user-images.githubusercontent.com/67064375/135093519-16db525b-6595-47e5-a980-85a29508c42b.png)

**Comment by avillen-dgtic** [comment]
Si el modal creix verticalment, hauria de desaparèixer l'scroll
![image](https://user-images.githubusercontent.com/83401259/135221806-3e6095ec-e627-4ab1-9438-0a395659b2d4.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![#360](https://user-images.githubusercontent.com/67064375/140877939-62903530-9f1c-4247-bd7a-ad5fae83e208.gif)

**Comment by jsastre-dgtic** [comment]
comprovat
