### ISSUE TITLE
Cal millorar el tema de l'usabilitat

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#365]
Fer feina amb un portàtil és complicat, queden tallades les pantalles sense barres que desplacin per veure tota la informació.
La finestra de les àrees queda molt petita i la informació de tràmits no és completa
![image](https://user-images.githubusercontent.com/18436867/129316877-f269822d-48f9-4bb6-b9f2-b03f0c0e72b5.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (6f221bb) y se despliega en CAIBter

**Comment by avillen-dgtic** [comment]
Es veu bé a partir d'una resolució de 1280x960.
Amb una resolució 1024x768 la paginació desapareix i els textos es veuen tallats.
![image](https://user-images.githubusercontent.com/83401259/135054005-0126db5d-05c3-4c33-ad28-3b99c6d8084b.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/140877815-fe553bc3-14f8-446d-9b6a-57204cda65ad.png)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/140877835-57dbaa92-03da-4c10-a140-dfbad19892b1.png)

**Comment by jsastre-dgtic** [comment]
ok, ha millorat. Si surten més coses ja veiem

**Comment by jsastre-dgtic** [comment]
Accedim a l'àrea de test i no veim ni scroll ni la paginació a baix. No podem visualitzar els tràmits existents a l'àrea, tot i que si el cercam, existeix.

![err_scroll](https://user-images.githubusercontent.com/18436867/142585667-11e32c30-f63e-41e1-a3ab-47d5891a65d6.gif)

**Comment by jsastre-dgtic** [comment]
tancam #404 , no dóna error, però la pantalla surt malament, no mostra tota la barra de baix ni s'adapta a un portàtil... tancam aquesta i documentam això aquí:
![err_scroll2](https://user-images.githubusercontent.com/18436867/142586742-ababa982-5629-4edc-9242-7fc4d29ab544.gif)
:

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
El scroll ahora funciona en toda la pantalla de edición de scripts. 

Antes:
![image](https://user-images.githubusercontent.com/67064375/144592127-77e8886b-6df3-485f-a0e5-24c264b710d3.png)

Ahora: 
![image](https://user-images.githubusercontent.com/67064375/144592164-52191de3-296e-46e3-8cb9-1a7aea9c0a4a.png)

**Comment by jparedes-indra** [comment]
Respecto al recuadro que se indica en la imagen, indicar que el editor de scripts tiene componentes complejos de primefaces y que no permite algunas de las funcionalidades, lo que genera que cuando se disminuye el tamaño la barra quede cortada.  Podemos ver como solucionarlo, pero implicaría una cantidad elevada de horas y creemos que no es necesario debido a que sigue cumpliendo la funcionalidad, solo es un aspecto visual cuando se disminuye el tamaño de esa ventana. De todas formas, si consideráis que se ha de solucionar, vemos como hacerlo y lo solucionamos.

  
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/67064375/144592416-c9d4bc64-728b-48b3-8df5-a99bf35d43a5.png)

**Comment by avillen-dgtic** [comment]
Correcte,
