### ISSUE TITLE
No té sentit check de visualitzar totes les àrees si el perfil és adm ent

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#367]
![image](https://user-images.githubusercontent.com/18436867/129333027-5151e49f-8a62-4bde-8a88-24fe43ee2ed2.png)

**Comment by jparedes-indra** [comment]
Esta issue está duplicada ya que la #376 es igual. ¿Podéis cerrar esta?

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/132843430-b0d2f332-1947-4b47-8af4-f000fe4d8e71.png)
