### ISSUE TITLE
Botó editar Formulari no té cap efecte

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#368]
![image](https://user-images.githubusercontent.com/18436867/129334043-757ed362-443b-4899-958a-11dde8df87fd.png)

**Comment by jparedes-indra** [comment]
En CAIBter, al darle al botón de Editar aparece la edición del formulario. ¿No está apareciendo en DEV esta ventana desplegable? 
![image](https://user-images.githubusercontent.com/67064375/129345823-7a9587ba-9d93-499b-baf3-9824e8f03975.png)

**Comment by avillen-dgtic** [comment]
Apareix els diàlegs.

**Comment by jsastre-dgtic** [comment]
no apareixia, ara si... devia ser un tema puntual
