### ISSUE TITLE
A l'importar versió no detecta La configuració associada al gestor extern de formulari 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#369]
![image](https://user-images.githubusercontent.com/18436867/129337124-5557ad8c-5096-4f32-93ef-17e18de07a51.png)

I quan revisam surt el desplegable en castellà, cal canviar-lo a català:

![image](https://user-images.githubusercontent.com/18436867/129337411-6d693889-5ab4-4642-b993-1700bbdcea96.png)

El fet és que existeix una autenticació amb el mateix nom exacte i no el detecta:
![image](https://user-images.githubusercontent.com/18436867/129337608-e9475077-8eea-4149-a19f-6daccd47f09d.png)

**Comment by jparedes-indra** [comment]
El desplegable de las configuraciones ya aparece en el idioma correspondiente: 
![image](https://user-images.githubusercontent.com/67064375/130773568-93da0f56-d159-4df5-b47a-1edfb0c255bd.png)
![image](https://user-images.githubusercontent.com/67064375/130773636-84fdb8fa-499c-40f1-9cef-34b8c06bb165.png)

**Comment by jparedes-indra** [comment]
Además, las autenticaciones también se detectan correctamente tanto en la importación de dominios como de GFEs. 
![image](https://user-images.githubusercontent.com/67064375/130773841-4fda02e4-3192-46c7-8eb5-6bfe697199f8.png)

También se ha solucionado el mismo problema al procesar cuadernos de carga entre entornos de desarrollo y preproducción: 
![image](https://user-images.githubusercontent.com/67064375/130774061-d878ed05-0132-482c-adec-43c7728e3e25.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (003a482) y se despliega en CAIBter

**Comment by jsastre-dgtic** [comment]
La idea no és llevar el control, és controlar si existeix l'autenticació i si no existeix, crear-la, com en la resta d'elements de la importació.
Hem provat de canviar el nom a l'autenticació associada al GFE i no hi ha cap control a l'autenticació. Conseqüentment falla. 

![image](https://user-images.githubusercontent.com/18436867/130783474-b810c222-1a2e-492f-aa30-220861381eee.png)

![image](https://user-images.githubusercontent.com/18436867/130784394-457dfa07-aaa0-4837-8371-7ae5426e99d7.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/132843232-5741237c-e5b9-4066-b50e-c5f4592c60c4.png)

**Comment by avillen-dgtic** [comment]
Es resol la incidència.

**Comment by jsastre-dgtic** [comment]
Al promocionar CCPRE-TRA-TEST-REGISTRE-9-3-des.zip no funciona el botó "Processar", tot i que sí ens ha permès crear l'autenticació inexistent associada al GFE extern. Quan l'hem creada li he canviat el nom, a l'autenticació

![image](https://user-images.githubusercontent.com/18436867/133782027-26c44615-83bd-4cae-87c3-d8a2d5f79791.png)


![image](https://user-images.githubusercontent.com/18436867/133781846-58fdfe55-4e7f-4127-ab4e-6721db4902e1.png)

**Comment by jsastre-dgtic** [comment]
Hem confirmat que la importació funciona bé important la versió 9 mateixa. El que no funciona és la promoció de dev a pre.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
![#369](https://user-images.githubusercontent.com/67064375/135096175-3f07de5e-be41-4aaf-8950-b356fd6ab087.gif)

**Comment by jsastre-dgtic** [comment]
la validarem en passar a pre

**Comment by jsastre-dgtic** [comment]
Generam el quadern de la v9 de test-registre, però a l'intentar Processar Quadern a PRE:
![image](https://user-images.githubusercontent.com/18436867/135612268-302fa7ab-40f1-4eae-ac5a-f1ff04efa463.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jsastre-dgtic** [comment]
Entenem que necessitam desplegar a pre la versió S2 per a provar-ho. Queda pendent la validació per aquest motiu.

**Comment by avillen-dgtic** [comment]
No funciona el processament de quaderns.
![image](https://user-images.githubusercontent.com/83401259/148913764-2cc1929b-bc57-4bc2-90f2-f06d1b3a8dd9.png)

![#000](https://user-images.githubusercontent.com/83401259/148914526-a94bedd2-db0c-4982-8a14-7817190f4507.gif)

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0 (49d5485)

**Comment by jcerdar-indra** [comment]
![#369](https://user-images.githubusercontent.com/96287364/149183831-afa25bfc-6a9a-4c9b-8d9f-5e07a639ee67.gif)

**Comment by avillen-dgtic** [comment]
Ajornada la comprovació d'aquesta issue fins a passar a PRE.

**Comment by avillen-dgtic** [comment]
👍
