### ISSUE TITLE
STG: Revisió i proves de l'aplicació

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#37]
Realitzar una revisió global i proves funcionals de l'aplicació:
- Revisió de literals multiidioma
- Revisió i implementació de funcionalitats pendents (ping a dominis, refresc de caches,..)

**Comment by rsanz-indra** [comment]
Se han revisado las pantallas de la aplicación y además al comenzar a integrar con SISTRAMIT para la ejecución de trámites han surgido errores que se han tenido que ir corrigiendo, por lo que esta tarea ha tenido un alcance superior al estimado inicialmente

**Comment by jsastre-dgtic** [comment]
Falta revisió i implementació de funcionalitats pendents (ping a dominis, refresc de caches,..)
