### ISSUE TITLE
STG: SECURITZACIÓ DR/GFE - Visualització dels tramits associats

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#370]
Seguint el mateix comportament que als dominis remots, els GFE haurien de tenir un llistat dels tràmits que l'estan fent servir. Aquesta funcionalitat ajudarà a trobar els tràmits des d'un GFE.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/135093617-af8760e1-ce95-45ff-87f6-08e6a4d43d36.png)
