### ISSUE TITLE
Pàgina d'ajuda no trobada

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#371]
No es troba la pàgina d'ajuda a la secció de GFE
![image](https://user-images.githubusercontent.com/83401259/129692054-d2a9a7d2-f3f9-4ad8-aae4-5838881368f4.png)

**Comment by dmadronal-indra** [comment]
buenas, 
esto es debido a que no habéis actualizado la ayuda en los directorios correspondientes, para evitar problemas, lo ideal sería eliminar esas propiedades, para que se acceda directamente a las propias de la aplicación, y solo usar esas propiedades en el caso de que sea necesario realizar una actualización de la ayuda y no se desee actualizar la aplicación


![imagen](https://user-images.githubusercontent.com/17270582/130223505-349a9feb-7770-4b43-8794-63025e6f93b3.png)

**Comment by jsastre-dgtic** [comment]
No interessa dependre de les pròpies de l'aplicació. De fet, no haurien d'existir, perquè hi ha una issue tancada que demana externalitzar les ajudes, no fer-ne una còpia externa. Si s'actualitzen les ajudes, s'haurien d'haver passat els fitxers html corresponents quan es pujà la versió a DEV, cosa que féreu voltros.

**Comment by jsastre-dgtic** [comment]
STG: Generació AJUDES i externalització d'aquestes #121
