### ISSUE TITLE
Generar fitxers PDF formatejats a partir d'un GFE

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#373]
Amb relació a la issue #372 ha sorgit aquesta tasca.

Arribat a aquest punt, on la responsabilitat del formulari queda fora de la plataforma de Sistra2 i per tant la generació del fitxer XML, una vegada que aquestes dades arriben a la plataforma queda per determinar com es pot fer per aplicar una plantilla a aquest fitxer. 
Als formularis interns tenim a les propietats del formulari les plantilles de visualització de PDF i els scripts associats.
![image](https://user-images.githubusercontent.com/83401259/129708241-dee6397c-e986-4358-888f-9b913278b18e.png)

En canvi, als formularis externs no tenim cap classe de propietat que ens pugui donar aquesta funcionalitat, només se’ns permet seleccionar el formulari i l'identificador. 
![image](https://user-images.githubusercontent.com/83401259/129708730-3806ff64-9baf-4df7-bbb2-5bfc62015530.png)

**Comment by dmadronal-indra** [comment]
Buenas tardes,
La responsabilidad de generar la plantilla del formulario es del propio GFE. 
En la respuesta del GFE se incluyen 2 campos, uno para el XML y otro para el PDF.
Actualmente la generación de este PDF queda fuera de la plataforma SISTRA2. Si no lo veis adecuado habrá que replantear la solución actual.
En este caso en ambos campos se está enviando el mismo fichero (el XML), por lo que revisaremos el proyecto de ejemplo para que retorne correctamente un pdf de ejemplo.

**Comment by dmadronal-indra** [comment]
Buenas ya hemos actualizado el GFE para que retorne un PDF de ejemplo.

![imagen](https://user-images.githubusercontent.com/17270582/129894949-3aa8e5e5-c847-4b50-aab3-015a576d20df.png)

**Comment by avillen-dgtic** [comment]
El comportament de STT ara és el correcte.
