### ISSUE TITLE
Missatge d'error no controlat.

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#375]
Fent un ping a un DR sense connexió genera el següent error, cosa que està bé, però no el text que mostra. A més a la plataforma de sistrahelp no apareix aquest error.

- [ ] Canviar el text a un orientat a l’usuari. 
- [ ] Afegir aquests esdeveniments a la plataforma de Sistrahelp.

![image](https://user-images.githubusercontent.com/83401259/130056675-59f1a7ac-eb62-4867-8878-b77f3ff44ca7.png)

**Comment by dmadronal-indra** [comment]
Buenas,
Referente a los errores en sistrahelp, hay que tener en cuenta que sistrahelp solo muestra los errores ocurridos en sistramit, los ocurridos en sistrages se muestran en el log de sistrages.
Es decir, si el pin se ejecuta en sistramit (ejecución de un trámite), al ocurrir un error se verá en sistrahelp, pero si el ping se ejecuta desde sistrages el error aparece en el fichero de log y se muestra al usuario el mensaje correspondiente.

Revisaremos el error que se le muestra al usuario.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
En caso de error en el ping, aparece la traza en la ventana y se indica que hay un error:
![image](https://user-images.githubusercontent.com/67064375/135088490-3a2cffb5-ed87-4c69-94c6-8759b55f5777.png)

**Comment by avillen-dgtic** [comment]
Me pareix bona sol·lució.
