### ISSUE TITLE
Navegació incorrecta a les pantalles Dominis Àrea/GFE/Conf Aut

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#377]
Quan accedim als dominis de l'àrea test, hauríem de poder tornar a l'àrea test, que és la pantalla des d'on venim. Ens obliga a tornar a visualitzar totes les àrees, cercar la nostra i accedir una altra  vegada al tràmit de l'àrea que ens interessa. 

La pantalla hauria d'especificar de quina àrea són els dominis i tornar a la pantalla de tràmits de la mateixa àrea d'on venim

![image](https://user-images.githubusercontent.com/18436867/130574555-0c7de9b4-5188-414f-95e6-c61577725b6c.png)

**Comment by jsastre-dgtic** [comment]
Ídem a la GFE
![image](https://user-images.githubusercontent.com/18436867/130575112-db5a32ea-8ea2-4a1b-ab6f-3c7a51531146.png)

**Comment by jsastre-dgtic** [comment]
Ídem a la pantalla Configuració Autenticació 

![image](https://user-images.githubusercontent.com/18436867/130575263-ad4c6693-3dd4-4c6e-b91b-d01c53f4bcec.png)

**Comment by jparedes-indra** [comment]
En las pantallas de Dominis Àrea/GFE/Conf Aut se añade miga de pan. Cuando se pulsa vuelve a la pantalla inicial manteniendo seleccionada el Área y los tramites. 

![imagen](https://user-images.githubusercontent.com/67064375/132755245-e2a119bf-545b-4174-9521-017b89308ea7.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/132842517-a728a080-db8e-44b0-b25b-c31a0e6d6aa0.png)
