### ISSUE TITLE
Fer clicable tota la molla de pa

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#378]
L'enquadrat no és clicable.

![image](https://user-images.githubusercontent.com/18436867/130780211-492a9f60-32dc-440d-ad0f-46013b22d4e8.png)

**Comment by jsastre-dgtic** [comment]
2a casuística: Quan es clica a la versió 5 ha de tornar a la versió 5 i torna al llistat de tràmits de l'àrea

![image](https://user-images.githubusercontent.com/18436867/131335422-cb08607b-236d-44c2-be37-3dd4ba6eb4d6.png)

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/131335481-c7746d90-01da-4c6b-9f81-68497d73d52c.png)

**Comment by jparedes-indra** [comment]
Cuando se hace click sobre un elemento de la miga se actualiza la miga, el árbol y el contenido.

![imagen](https://user-images.githubusercontent.com/67064375/132755935-7eaebc60-d941-4100-9453-f61833d3de9a.png)

![imagen](https://user-images.githubusercontent.com/67064375/132755944-25a2d7e2-8557-479e-8932-90a6947cdb1e.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by avillen-dgtic** [comment]
La segona part d'aquesta issue no s'ha resolt. 
Quan piques damunt la versió t'hauria de dur al llistat dels tràmits a la pàgina on estan les versions.
![#378](https://user-images.githubusercontent.com/83401259/133055473-c21ce130-9a46-4d8d-9c0f-79a46cbdb621.gif)

**Comment by jsastre-dgtic** [comment]
Quan cliques damunt la versió en realitat va a l'àrea

![image](https://user-images.githubusercontent.com/18436867/133419569-fabe0e1a-ecce-48c2-aba1-2e36cf5ea46a.png)

Accedim aquí, i només quan tornam clicar damunt la versió 8 ens mostra el menu de versió enlloc del d'àrea:

![image](https://user-images.githubusercontent.com/18436867/133419750-47b0fa51-784a-46d9-b3d5-4a76872c1989.png)


![image](https://user-images.githubusercontent.com/18436867/133419884-d2b24deb-22f3-447f-9ada-3c3d7c65068d.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
![#378](https://user-images.githubusercontent.com/67064375/135089291-b3736f9f-bd3e-4a2a-984b-56bdea1b82bf.gif)

**Comment by jparedes-indra** [comment]
![#378_1](https://user-images.githubusercontent.com/67064375/135089304-e75911ae-c531-4233-b5ac-5cffaf73fca1.gif)
