### ISSUE TITLE
Error no controlat al ping de dominis no accesibles

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#379]
Quan el servei que dona un domini no és accessible, el missatge que et retorna és l'stack de java.
![image](https://user-images.githubusercontent.com/83401259/130781486-62212585-6c44-49a0-ae1f-0c08c269ebf1.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
En caso de error en el ping, aparece la traza en la ventana y se indica que hay un error. 
![image](https://user-images.githubusercontent.com/67064375/135088352-cdd6e840-af62-41e6-9f6b-504e47424294.png)
