### ISSUE TITLE
STG: Integració amb SISTRAMIT

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#38]
- Integració amb el frontal de tramitació SISTRAMIT (refresc de caches)

**Comment by jmico-indra** [comment]
Los cambios del commit de hace 3 días (3523427) pertenecen a la issue #42

**Comment by sgelabert-dgtic** [comment]
Es detecta error en el refrescar caché de la versió d'un tràmit.
Adjunt log servidor d'aplicacions [log_refresc_cache.txt](https://github.com/GovernIB/sistra2/files/2463412/log_refresc_cache.txt)

**Comment by rsanz-indra** [comment]
Este error es debido a una mejora en los procesos automáticos que introducimos el viernes a última hora y falla sobre un tema de permisos. Miramos de subir ese cambio en particular al git.

**Comment by rsanz-indra** [comment]
Ya está subido el bug del proceso automático.

**Comment by rsanz-indra** [comment]
Se puede probar fácilmente cambiando en la pantalla de Configuración de entidad alguna propiedad (p.e. enlace redes sociales) y darle al botón Refrescar caché. Tras 1 min se debería ver el cambio en el asistente (sistrafront)
En instalación CAIB hay que configurar bien el usr/pwd de acceso al STT en la pantalla de Propiedades globales (verificar también que el usuario creado tiene el role adecuado STT_API_INT). 
Se puede probar también en caibter.
