### ISSUE TITLE
Al fer doble click hauria d'entrar al domini  en mode consulta

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#380]
![image](https://user-images.githubusercontent.com/18436867/131120478-7204d20f-6311-4503-a637-29b5d601c75f.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/132842751-7854df51-0e3f-4dbe-87cc-d7fde5088917.png)

**Comment by avillen-dgtic** [comment]
Es resol la incidència
