### ISSUE TITLE
Independitzar cada entitat i els seus tràmits

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#381]
Quan intentam crear un tràmit ens diu que ja existeix tot i que el tràmit existeix en una altra entitat.

**Comment by jsastre-dgtic** [comment]
Permetre la creació d'àrees amb mateix identificador en diferents entitats (ve de la #381)

**Comment by jsastre-dgtic** [comment]
Cal definir la unicitat d'elements a nivell d'àrea (els elements a nivell d'àrea podran repetir identificador en diferents àrees de la mateixa entitat). 
· DOMINIOS GLOBALES: GLOBAL#[ID-DOMINIO] · ENTIDAD: Id funcional (“GOIB”, ”APB”, …) o DOMINIO ENTIDAD: [ID-ENTIDAD]#[ID-DOMINIO] o FUENTE DATOS ENTIDAD: [ID-ENTIDAD]#[ID-FUENTEDATOS] o AREA: [ID-ENTIDAD]#[ID-AREA] § TRAMITE: [ID-ENTIDAD]#[ID-AREA]#[ID-TRAMITE] § DOMINIO ÁREA: [ID-ENTIDAD]#[ID-AREA]#[ID-DOMINIO] § FUENTE DATOS ÁREA: [ID-ENTIDAD]#[ID-AREA]#[ID-FUENTEDATOS] § GESTOR FORMULARIO EXT: [ID-ENTIDAD]#[ID-AREA]#[ID-FUENTEDATOS] § CONF. AUTENTICACIÓN: [ID-ENTIDAD]#[ID-AREA]#[ID-CONFAUT]

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

Tal y como se indiacc en el documento de estimación se ha modificado la unicidad de los identificadores de los componentes de Sistra2 para que esta sea a nivel de área.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/88820558/161064210-7034f23a-601c-4d43-8093-657af9eeb14c.png)

**Comment by jsastre-dgtic** [comment]
I com quedaria la crida des de rolsac/SEU/CARPETA?
![image](https://user-images.githubusercontent.com/18436867/161237149-2f16ccfe-0cdb-44d0-9696-1fe46a43c63b.png)

**Comment by jsastre-dgtic** [comment]
A partir de la versió 1.3.0 (per ara només és a SE), a rolsac haurem de posar ENTITAT.ÀREA.CODI_TRÀMIT (abans només posàvem Codi_Tràmit)

Exemple: CAIB.DEPENDENCIA.TRA_SOLICITUD (L'entitat sempre serà CAIB)
