### ISSUE TITLE
Revisió del procés de migració amb multipàgina

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#383]
- L'error apareix a l'ésser necessari generar un identificador de cada pàgina per defecte en migrar.

- S'ha de revisar que la multipàgina funciona en migrar un tràmit.

- Caldria revisar si, per exemple, algun script no es migra correctament com el script de navegació.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
![#383](https://user-images.githubusercontent.com/67064375/132843371-81eeafe6-2170-48d0-a879-7702755de240.gif)
