### ISSUE TITLE
Eliminar el límit del núm de versions i mostrar-les totes

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#384]
si un tràmit té més de 10 versions, es mostren les 10 darreres.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
![#384](https://user-images.githubusercontent.com/67064375/132843176-540dc66a-8758-4477-a4e8-f364556cb7c9.gif)

**Comment by avillen-dgtic** [comment]
No es pot accedir a les versions. No hi ha un scroll vertical que et permeti mostrar totes.

![image](https://user-images.githubusercontent.com/83401259/133073860-dee27e88-bc88-4762-b7a4-633f4028b997.png)

**Comment by avillen-dgtic** [comment]
![#384](https://user-images.githubusercontent.com/83401259/133209523-6ada9aab-c59a-4033-9fcb-5f027cb31806.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
![#384](https://user-images.githubusercontent.com/67064375/135096675-07d74969-b118-4cad-8b4c-f7e6962b857e.gif)

**Comment by avillen-dgtic** [comment]
El comportament és correcte.
