### ISSUE TITLE
Error en el procés d'importació d'un domini remot

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#385]
error en el procés d'importació d'un domini de consulta remota que tingui una configuració d'autenticació enllaçada.

![image](https://user-images.githubusercontent.com/18436867/131481945-38b3afd6-393c-44d3-a07a-84da352ebeec.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
![#385](https://user-images.githubusercontent.com/67064375/132843305-4ca0e084-4944-4f10-9be1-29e1ee2722e0.gif)

**Comment by avillen-dgtic** [comment]
La importació funciona correctament.
