### ISSUE TITLE
Actualitzar continguts de l'ajuda

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#386]
Actualitzar l'ajuda amb les dades que arribaran a REGISTRE segons la configuració a sistrages (extracte, òrgan destí, oficina, llibre...) i amb altres continguts.

**Comment by jparedes-indra** [comment]
En la versión 1.2.1 se han actualizado las siguientes ayudas: 

-	También se modifica el índice de este para añadirlo. 
-	Se añade carpeta de DATOS_TRAMITECP con los métodos asociados e índice. 
-	Se añade carpeta de DATOS_PROCEDIMIENTOCP con los métodos asociados e índice. 
-	Los índices de DATOS_X se modifican para que al copiar el método en el portapapeles no se añadan incorrectamente algunas expresiones que estaban mal. (Se copiaba DATOS_USUARIO.getNombre())
-	PLUGIN_SESIONTRAMITACION.getParametroInicio: se modifica frase indicada sobre URL.
-	Index.html de PARAMETROS DOMINIO
-	Index.html VALORES DOMINIO
-	disenyoFormularioDialog.html, se añade frase indicando que los radiobuttons tienen que tener espacio en horizontal. 
-	definicionVersionAnexoDialog.html se cambia explicación del número de instancias. 
-      Método getTramiteCP en PLUGIN_SESIONTRAMITACION.

Por ello, en el directorio de ayudas externas debéis añadir/sobrescribir los siguientes archivos: 
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/definicionVersionAnexoDialog.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/disenyoFormularioDialog.html
Todos los docs de la carpeta: 
https://github.com/GovernIB/sistra2/tree/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/DATOS_PROCEDIMIENTOCP

Todos los docs de la carpeta: 
https://github.com/GovernIB/sistra2/tree/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/DATOS_TRAMITECP

https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/DATOS_USUARIO/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/PARAMETROS_DOMINIO/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/PLUGIN_SESIONTRAMITACION/getParametroInicio.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/PLUGIN_SESIONTRAMITACION/getRepresentanteUsuario.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/PLUGIN_SESIONTRAMITACION/getTramiteCP.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/PLUGIN_SESIONTRAMITACION/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/VALORES_DOMINIO/index.html


Lo mismo para su versión en es: 
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/definicionVersionAnexoDialog.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/disenyoFormularioDialog.html
Todos los docs de la carpeta: 
https://github.com/GovernIB/sistra2/tree/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/DATOS_PROCEDIMIENTOCP

Todos los docs de la carpeta: 
https://github.com/GovernIB/sistra2/tree/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/DATOS_TRAMITECP

https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/DATOS_USUARIO/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/PARAMETROS_DOMINIO/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/PLUGIN_SESIONTRAMITACION/getParametroInicio.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/PLUGIN_SESIONTRAMITACION/getRepresentanteUsuario.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/PLUGIN_SESIONTRAMITACION/getTramiteCP.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/PLUGIN_SESIONTRAMITACION/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/VALORES_DOMINIO/index.html

**Comment by jparedes-indra** [comment]
Relacionado con la issue #433 y la nueva propiedad en DATOS_ANEXOSDINAMICOS, se han de añadir las siguientes ayudas: 

En CA: 
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/DATOS_ANEXOSDINAMICOS/addAnexo.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/DATOS_ANEXOSDINAMICOS/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/plugins/DATOS_ANEXOSDINAMICOS/setPrecedenciaSobreAnexosFijos.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/ca/definicionVersionAnexarDocumentos.html

En ES:
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/definicionVersionAnexarDocumentos.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/DATOS_ANEXOSDINAMICOS/index.html
https://github.com/GovernIB/sistra2/blob/sistra2-1.2/sistrages/sistrages-frontend/src/main/webapp/ayuda/es/plugins/DATOS_ANEXOSDINAMICOS/setPrecedenciaSobreAnexosFijos.html

**Comment by jsastre-dgtic** [comment]
Necessitam que formin part del quadern de càrrega tots els fitxers html modificats.

**Comment by jparedes-indra** [comment]
Se modifican las ayudas siguientes en el pase de la versión 1.2.1_1. Los ficheros correspondientes se encuentran en el pase. 

Ayuda 'Paso Registrar': 
![image](https://user-images.githubusercontent.com/67064375/144591514-a54a901c-54f8-4e09-aa3a-cccd3edd0c79.png)

Si se hace click en el hipervínculo que se muestra, aparece la siguiente tabla: 
![image](https://user-images.githubusercontent.com/67064375/144591598-0375dc56-81de-42fa-8510-82508e645c45.png)
