### ISSUE TITLE
Optimitzar finestra Esdeveniment

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#387]
No pareix que tengui molt de sentit la mida dels camps quedant informació sense visualitzar quan tenim tot l'espai per a poder-ho fer:

![image](https://user-images.githubusercontent.com/18436867/131801637-643b3aa0-98ef-4adf-b66d-62886818925c.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/132844410-fbef1d60-8441-43c0-af39-1c2b166348e3.png)

**Comment by avillen-dgtic** [comment]
Corregit.
