### ISSUE TITLE
Mantenir preferències a la sessió dels resultats per pàgina

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#388]
El valor dels tràmits mostrats per pàgina s'haurien de mantenir segons la sessió. Actualment es perd aquesta preferència sempre que es surt de la pantalla tràmits:

![image](https://user-images.githubusercontent.com/18436867/131813040-0f5db912-e084-4f86-9285-4030b851707a.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
![#388](https://user-images.githubusercontent.com/67064375/144592534-e4541229-c842-4eb2-8527-32ee46a49970.gif)

**Comment by avillen-dgtic** [comment]
Es manté 👍
