### ISSUE TITLE
Poder donar d'alta una configuració d'autenticació que no hi hagi en el procés d'importació.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#389]
Ara mateix si ve amb una autenticació amb Id=PBE i no la troba (perquè he canviat l'Id a PBE2) el que fa és donar a triar quina autenticació donada d'alta volem triar. El que es demanava a la issue era la possibilitat d'importar l'autenticació d'origen amb una revisió manual.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/132844481-2e8e37c1-b14a-4216-b0fe-fb9228a9c4e1.png)
![image](https://user-images.githubusercontent.com/67064375/132844490-4c169093-f120-4e4c-9a13-2b48d7dd2148.png)

**Comment by avillen-dgtic** [comment]
El funcionament es correcte.

**Comment by jsastre-dgtic** [comment]
Seria més clar si visualitzam el nom del domini a la pantalla de revisió de domini:

![image](https://user-images.githubusercontent.com/18436867/133420676-57d33fe4-0582-4e8a-9959-f277bca14dc6.png)

**Comment by jsastre-dgtic** [comment]
No existeix la configuració d'autenticació i me crea el DR al PBE sense fer la validació:
![image](https://user-images.githubusercontent.com/18436867/133420898-bd20f7f3-46a8-417a-8465-21afd0a7529b.png)
Curiosament funciona i agafa l'autenticació PBE2, quan s'ha exportat amb PBE, no PBE2... 
![image](https://user-images.githubusercontent.com/18436867/133421399-233d3f14-7376-4ec1-9f4f-876896905a55.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/135089355-fcb65a43-455e-4f26-a463-4e78bc1f56fe.png)
