### ISSUE TITLE
STT: Implementació del workflow de tramitació IV

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#39]
- Implementació de la lògica genèrica del workflow de les passes de tramitació i de la passa "Annexar"
- Presentació de la passes en el frontal, enllaç amb la capa de negoci i accés a dades.

**Comment by rsanz-indra** [comment]
Se recomienda recrear el esquema de sistrages y sistramit para tener los datos "limpios" ya que ahora se necesitan tener los datos bien porque se comienzan a integrar los módulos entre sí.
