### ISSUE TITLE
Tractament del "case sensitive" als paràmetres de DOMINI tipus camp.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#390]
En el cas que tenguem un paràmetre de tipus camp, implementar un upper() tal com es fa amb l'Id dels Camps automàticament. Considerar també que surti a l'ajuda el fet de case sensitive.

**Comment by jsastre-dgtic** [comment]
Els paràmetres de dominis són case sensitive i pot dur a confussions, atès que els noms dels camps al formulari automàticament es transformen en majúscules (upper()), però no així les seves referències als paràmetres de domini.
L'exemple és referenciar qualsevol paràmetre de domini remot  tipus camp amb el nom del camp en minúscules, quan al formulari el nom del camp és en majúscules.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/140877685-1579969b-e9c4-4440-b78e-df857c02560e.png)
![image](https://user-images.githubusercontent.com/67064375/140877695-5c738844-b6f6-4a9c-8dbe-b1939e82b7d5.png)

**Comment by jsastre-dgtic** [comment]
Comprovat
