### ISSUE TITLE
error al formatador tipus PLANTILLA que fan servir diversos tràmits migrats de SISTRA1

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#392]
L'error es genera a l'haver camps tipus data en un formulari que es passarà a PDF amb aquest formatador. Indica que la data no és vàlida ja que espera aquests dos tipus de format (yyyy-MM-dd o yyyy / MM / dd) i en canvi els camps tipus 'Data' envien aquest altre: dd / MM / yyyy, que no es contempla i llança l'excepció

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1 (ee80509) y se despliega en CAIBter.

**Comment by jparedes-indra** [comment]
Se puede probar previsualizando un trámite del área de migración que utilice formateadores tipo plantilla y tenga un campo tipo fecha en el formulario. Por ejemplo AUT_SUB_ALB_GRAU.
