### ISSUE TITLE
Fer que quan es desmarca el Check d'Autenticat es desmarquin els tipus d'Autenticació.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#393]
Per defecte, quan es desmarca check de 'Autenticat', els checks de el tipus d'autenticació es marquen. Hauria de ser a l'inrevés.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![#393](https://user-images.githubusercontent.com/67064375/140877613-b0b93ec5-74eb-436f-83da-cdb7ddc86ca3.gif)

**Comment by jsastre-dgtic** [comment]
ok
