### ISSUE TITLE
Llistat de tràmits duplicats

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#394]
En cancel·lar la importació d'una versió, el llistat dels tràmits s'ha duplicat.
![#new](https://user-images.githubusercontent.com/83401259/133045987-2f3132da-19b3-4872-b16d-ed0c9135043d.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
La problemática de duplicado de trámites sucedía cuando se realizaba alguna de las siguientes acciones:
Control acceso
Borrar scripts
Duplicar versión
Importar versión
Cambiar tamaño ventana

**Comment by jparedes-indra** [comment]
Control acceso: 
![394-control_de_acceso](https://user-images.githubusercontent.com/67064375/135089873-bddc0578-2985-40d8-b26e-40610c79c842.gif)

**Comment by jparedes-indra** [comment]
Borrar scripts: 
![394-borrar_script](https://user-images.githubusercontent.com/67064375/135089904-4da10dc1-e140-4b45-b8a3-192c88cd58f9.gif)

**Comment by jparedes-indra** [comment]
Duplicar versión: 
![394-duplicar_version](https://user-images.githubusercontent.com/67064375/135089938-864f91a6-0c90-4a1d-a2ba-56c3649894d1.gif)

**Comment by jparedes-indra** [comment]
Importar versión: 
![394-importar_version](https://user-images.githubusercontent.com/67064375/135090056-35e7c79e-74dc-40fc-816b-d9e911c9f239.gif)

**Comment by jparedes-indra** [comment]
Cambiar tamaño: 
![#394_CambiarTam](https://user-images.githubusercontent.com/67064375/135090304-136712c9-adb3-4b16-aa30-ce46a7823f25.gif)
