### ISSUE TITLE
Fallen les mides dels components

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#395]
Es mostren barres de desplaçament havent-hi espai per a créixer.
![image](https://user-images.githubusercontent.com/83401259/133046517-972354e4-e6a7-4cc5-a1c7-bea5ac4250ea.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (6f221bb) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
Antes como se veía:
![image](https://user-images.githubusercontent.com/67064375/135043976-60507356-0a98-478e-9e66-4e3845d67e49.png)

Ahora: 
![image](https://user-images.githubusercontent.com/67064375/135044024-a7d1eb2b-c3c3-455d-8459-7281635802a5.png)
