### ISSUE TITLE
L'estil del breadcrumb no té fin

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#396]
![image](https://user-images.githubusercontent.com/83401259/133054100-11885db3-01e8-4f53-ad3a-f847e6a6ddcf.png)

**Comment by avillen-dgtic** [comment]
#377

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/140877531-a29df407-066a-41c4-9d70-7905f1bfcfa1.png)
![image](https://user-images.githubusercontent.com/67064375/140877541-9163b194-cc85-4146-954d-4187eb8c61bd.png)
![image](https://user-images.githubusercontent.com/67064375/140877547-acd0752a-3c62-4520-98ad-db0a9fb2d34d.png)

**Comment by jsastre-dgtic** [comment]
ok
