### ISSUE TITLE
Mostrar un error controlat a STT quan falla una connexió a DR

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#397]
![image](https://user-images.githubusercontent.com/18436867/133056802-18904a05-e118-44aa-bcb4-bc4714105dfa.png)

Podríem mostrar més informació concreta de l'error?

![image](https://user-images.githubusercontent.com/18436867/133056607-97d2e570-c1e7-4494-9399-554888bbe278.png)

**Comment by jparedes-indra** [comment]
En la reunión mantenida el 16/11, se acordó añadir algunos datos mínimos (sin comprometer la seguridad del sistema ni caer en malas prácticas de seguridad) que permitan y faciliten la búsqueda del error en SISTRAHELP.

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

<img width="391" alt="image" src="https://user-images.githubusercontent.com/88820558/161067262-47930ebc-9dd6-4883-a302-80f73e138f26.png">

**Comment by jsastre-dgtic** [comment]
A STT:
![image](https://user-images.githubusercontent.com/18436867/164200758-3fcff00e-f4eb-4fff-8f99-6b067473f5f4.png)

A STG:
![image](https://user-images.githubusercontent.com/18436867/164200827-57e2c2c3-08a0-4f34-9e79-678b5dfe3815.png)


A STH:
![image](https://user-images.githubusercontent.com/18436867/164200883-2f090e61-9449-43c5-8706-ebedfd9bce5d.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.0_2 (a8ddb58). 

En STH los errores relacionados con dominios remotos lanzan una excepción más específica DominioErrorException:
![image](https://user-images.githubusercontent.com/96287364/167799557-068d66d8-881e-4c02-bfcd-3c39ee958542.png)

**Comment by jsastre-dgtic** [comment]
A l'intentar obrir el formulari:
![image](https://user-images.githubusercontent.com/18436867/168235387-92a11e97-1c92-48fd-bda0-3b855db64aa0.png)
A STH:
![image](https://user-images.githubusercontent.com/18436867/168235524-40a59a10-6f44-41fa-a814-e98a2a659619.png)
