### ISSUE TITLE
La botonera de les versions no apareix. 

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#398]
Arran de la issue #378 apareix un bug. Al llistat de les versions apareix que ja hi ha una marcada, però no apareixen els botons associats a aquesta acció.
![image](https://user-images.githubusercontent.com/83401259/133056824-9c6b807a-2695-4ac5-b751-34403ace8a9c.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
![398](https://user-images.githubusercontent.com/67064375/135090407-45f6a5c2-af67-458f-8123-ba4ef5e2a199.gif)
