### ISSUE TITLE
Errades textos Pantalla Configuració d'entitat

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#399]
registro --> registre
pas guardar --> passa desar? No ens queda molt clar això què és ni amb l'ajuda. No existeix una "passa desar" ni a STG ni a STT... 
"Plantilla per a mail fi de registre"-->  "Plantilla correu finalitzar tràmit"

![image](https://user-images.githubusercontent.com/18436867/133206916-fa02ad53-6652-4aab-92e0-aab098061951.png)

![image](https://user-images.githubusercontent.com/18436867/133206906-7e5a7fd0-e538-41c5-a9ed-3e0d70a2074c.png)

Passes de tramitació:
![image](https://user-images.githubusercontent.com/18436867/133207050-a2bf863e-2f7e-4c7b-8c16-c33c4c8d70ad.png)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/135088845-e8274d35-aa5e-4846-ba9c-07f8f275773f.png)
