### ISSUE TITLE
STG: Definició model de dades

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#4]
Definició del model de dades del mòdul de Gestor de Tràmits:
- Disseny físic de dades.
- Documentació del model de dades.
- Scripts de creació de l'esquema físic de dades.

**Comment by amaciam-indra** [comment]
Creada documentació de model de dades i scripts de creació de l'esquema físic de dades. El commit associat és el c9b8192.

**Comment by rsanz-indra** [comment]
Pendiente de revisar por si se modifican funcionalidades al revisar mockups.

**Comment by sgelabert-dgtic** [comment]
Tenint en compte que es poden produir canvis substancials en el disseny físic de dades (per exemple fins que no es tanquin requeriments de pre-registre #14 o de migració #10 ) i que les dades introduïdes són simples proves, es proposa:
- Incorporar script DDL per l'esborrat complet dels objectes de la BBDD
- Incorporar script DML per incorporar aquelles dades de configuració bàsiques de l'aplicació.

**Comment by sgelabert-dgtic** [comment]
He passat script DDL sobre la BBDD de DES, localitzant les següents errades. Adjunt log [LOG_DDL_SISTRAGES.txt](https://github.com/GovernIB/sistra2/files/1879684/LOG_DDL_SISTRAGES.txt):
- El fitxers haurien d'estar amb UTF-8. Tenim problemes amb els accents dels comentaris, pareix que estan amb ANSI.
- Els noms del tablespaces són :
  - SISTRAGES (per dades i indexos, al no haver-hi distinció entre ells s'utilitza per defecte SISTRAGES)
  - SISTRAGES_LOB (per objectes LOB)
  Això fa que hi hagi una errada al crear l'objecte STG_SCRIPT
- Hi ha una errada al crear l'objecte SGT_FICEXT

**Comment by rsanz-indra** [comment]
Subiremos los ficheros adaptados en la próxima actualización con los nuevos cambios introducidos en el modelo de datos (antes se deberá lanzar el drop del schema de la actual versión).

Respecto al error de STG_SCRIPT, ¿podéis indicarnos que tablespace no está correcto en la sentencia?
En principio está como tenemos definido otros LOBs (p.e. en Rolsac)
El error lo da porque ya existe "algo" con ese nombre (Error SQL: ORA-00955: este nombre ya lo está utilizando otro objeto existente)

La sentencia es:

create table STG_SCRIPT 
(
   SCR_CODIGO           NUMBER(18)           not null,
   SCR_SCRIPT           CLOB
)
TABLESPACE SISTRAGES
   LOB (SCR_SCRIPT) STORE AS STG_SCRIPT_SCRIPT_LOB
	 (TABLESPACE SISTRAGES_LOB
	 INDEX STG_SCRIPT_SCRIPT_LOB_I);


P.e. en Rolsac esta así y no vemos diferencias:

create table RSC_SIAJOB  (
   SIJ_ID number(19,0) not null,
   SIJ_FECINI date,
   SIJ_FECFIN date,
   SIJ_DESBRE clob,
   SIJ_DESCRI clob,
   SIJ_ESTADO number(1,0),
   primary key (SIJ_ID)
)
TABLESPACE rolsac 
                LOB (SIJ_DESBRE) STORE AS RSC_SIAJOB_DESBRE_LOB 
                     (TABLESPACE ROLSAC_LOB
                         INDEX RSC_SIAJOB_DESBRE_LOB_I)
                 LOB (SIJ_DESCRI) STORE AS RSC_SIAJOB_DESCRI_LOB 
                     (TABLESPACE ROLSAC_LOB
                          INDEX RSC_SIAJOB_DESCRI_LOB_I);

**Comment by sgelabert-dgtic** [comment]
Respecte a STG_SCRIPT la sentència es correcte perquè jo l'he corregida (disculpau). Si mirau el fitxer commitat trobareu aquesta altra:
```
create table STG_SCRIPT 
(
   SCR_CODIGO           NUMBER(18)           not null,
   SCR_SCRIPT           CLOB
)
TABLESPACE **SISTRAGES_DADES**
   LOB (SCR_SCRIPT) STORE AS STG_SCRIPT_SCRIPT_LOB
	 (TABLESPACE SISTRAGES_LOB
	 INDEX STG_SCRIPT_SCRIPT_LOB_I);
```

**Comment by rsanz-indra** [comment]
Ok, corregido.

**Comment by sgelabert-dgtic** [comment]
Amb el darrer commit ha desaparegut el contingut del fitxer "sistrages_drop_schema.sql"

**Comment by amaciam-indra** [comment]
Es preveu que durant el desenvolupament hi hagi ajustos de taules i camps al model de dades

**Comment by rsanz-indra** [comment]
Proponemos dar por terminada esta tarea ya que su objetivo era fijar el modelo inicial de BBDD de SISTRAGES. Durante el proceso de desarrollo pueden surgir pequeños ajustes sobre el modelo de datos que serán asumidos en las tareas específicas de desarrollo.

**Comment by sgelabert-dgtic** [comment]
Adjunt log de l'execució dels scripts [log_sistrages_20180417.txt](https://github.com/GovernIB/sistra2/files/1918365/log_sistrages_20180417.txt):
```
@\SISTRA2\sistrages\scripts\bbdd\1.0\oracle\sistrages_drop_schema.sql
@\SISTRA2\sistrages\scripts\bbdd\1.0\oracle\sistrages_create_schema.sql
@\SISTRA2\sistrages\scripts\bbdd\1.0\oracle\sistrages_create_data.sql

```
Apareix un error al recrear la taula STG_SCRIPT:
```
Error que empieza en la línea 2.091 del comando:
create table STG_SCRIPT 
(
   SCR_CODIGO           NUMBER(18)           not null,
   SCR_SCRIPT           CLOB
)
TABLESPACE SISTRAGES
   LOB (SCR_SCRIPT) STORE AS STG_SCRIPT_SCRIPT_LOB
	 (TABLESPACE SISTRAGES_LOB
	 INDEX STG_SCRIPT_SCRIPT_LOB_I)
Informe de error:
Error SQL: ORA-00955: este nombre ya lo está utilizando otro objeto existente
00955. 00000 -  "name is already used by an existing object"
```

**Comment by rsanz-indra** [comment]
Falla la creación de la tabla por la configuración del almacenamiento del LOB. Es el único LOB que existe en este esquema.
En principio, el script sigue las indicaciones que nos pasasteis para almacenamiento de LOBs y está dando un error de que algo está usando (podría ser el index STG_SCRIPT_SCRIPT_LOB_I que se ha creado para el LOB)   ¿Podéis verificarlo con la gente de BBDD?

**Comment by rsanz-indra** [comment]
Entiendo que habéis desplegado ya la aplicación, ¿habéis resuelto este tema?

**Comment by sgelabert-dgtic** [comment]
Sí, hem obert consulta amb Oracle:
> Si es así, parece ser que estáis sufriendo el Bug:7831817. En la nota de MOS Doc. ID 1925773.1 podréis encontrar el detalle. 
> Junto con la aplicación del parche correspondiente, en la nota se explica el siguiente workaround:
>  1.  Deshabilitar la papelera de reciclaje a nivel de sesión:
> ` ALTER SESSION SET RECYCLEBIN = OFF;`
> 2. Borrar la tabla con la opción PURGE
> ` DROP TABLE STG_SCRIPT PURGE;`
> 3. Vaciar la SHARED POOL
> ` ALTER SYSTEM FLUSH SHARED_POOL;`
> 4.  Lanzar de nuevo el CREATE TABLE
> ` CREATE TABLE STG_SCRIPT …`

Adjunt log [spool_log.txt](https://github.com/GovernIB/sistra2/files/1936901/spool_log.txt)
Em resta confirmar amb el DBA l'aplicació del parche. Mantinc el tiquet obert fins rebre resposta.

**Comment by rsanz-indra** [comment]
Se indica en el documento de diseño técnico. 
Queda pendiente revisar la tarea de Maven para generar el script de BD de forma dinámica a partir del modelo JPA.

**Comment by rsanz-indra** [comment]
Se generan los scripts al lanzar la tarea Maven. 
En el pom principal se establecen las props para establecer la BD destino:
<schema.generate.databaseProductName>Oracle</schema.generate.databaseProductName>
<schema.generate.databaseVersion>12</schema.generate.databaseVersion>
Los scripts se generan en target/generated-schema

**Comment by rsanz-indra** [comment]
Se modifica documento de Diseño Técnico para indicar detalles de la generación automática del schema.

Para la generación del schema se está usando por debajo JPA 2.1 (Persistence.generateSchema() ). El plugin utilizado simplemente es un recubrimiento sobre esto para poder usarlo desde Maven. 
Respecto al tema de la precisión de los campos, la propiedad 'precision' en la anotación 'Column' solo aplica en la generación del schema para campos de tipo decimal (para campos de tipo long o int se genera el schema con la configuración estándar). Esto ya es un tema de JPA 2.1, no del plugin.
