### ISSUE TITLE
STT: Frontal Assistent de Tramitació II

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#40]
- Es continua amb la implementació del frontal de tramitació de la tasca #30. Implementació fins a la passa Registrar

**Comment by jsastre-dgtic** [comment]
Per provar la passa registrar necessitam saber com configurar el plugin de rw3

**Comment by jsastre-dgtic** [comment]
No converteix a pdf...
![image](https://user-images.githubusercontent.com/18436867/46665115-2be09580-cbc3-11e8-8b47-317669ca3509.png)

![image](https://user-images.githubusercontent.com/18436867/46665092-1a978900-cbc3-11e8-8c06-6e2fca550ee4.png)

**Comment by amaciam-indra** [comment]
En resposta al comentari https://github.com/GovernIB/sistra2/issues/40#issuecomment-428142790:
aplica el mateix que s'ha indicat al comentari https://github.com/GovernIB/sistra2/issues/30#issuecomment-428163799

**Comment by amaciam-indra** [comment]
Resposta a comentari https://github.com/GovernIB/sistra2/issues/40#issuecomment-428149823:

El plugin de conversió a PDF encara no està implementat, de fet està planificat pel ciclo 9 de desenvolupament.
