### ISSUE TITLE
Error quan eliminen un GFE

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#400]
![#new](https://user-images.githubusercontent.com/83401259/133409874-d510e676-ae83-451e-948f-5a9122e4b7e1.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![#400](https://user-images.githubusercontent.com/67064375/140877480-c7b00bc5-6cf2-41ff-b4c3-ecab3c1ad430.gif)

**Comment by jsastre-dgtic** [comment]
ok, comprovat
