### ISSUE TITLE
Error duplicant DR

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#402]
Quan canviem d'àrea, el camp identificador es canvia tot sol. Aquest comportament seria més lògic si el camp identificador estigués davall del selector d'àrea o directament que no canviés.
Aquest error pot donar problemes i confusió als usuaris.

![#new](https://user-images.githubusercontent.com/83401259/133410896-82e1a93f-a5a6-441e-b123-e7fe02745d07.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
![#402](https://user-images.githubusercontent.com/67064375/144592613-4d5d9edd-d531-4c49-99bb-fc85a59d35cc.gif)

**Comment by avillen-dgtic** [comment]
👍
