### ISSUE TITLE
Afegir camp descripcó a una versió

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#403]
Amb la creació i proves de tantes versions per a un mateix tràmit, ens hem trobat que seria interessant incloure el camp de descripció a aquestes versions. Així, a la graella on apareixen les versions, podríem visualitzar l'estat de la versió. 
Aquesta millora no ha de tenir cap repercussió a STT, només és un camp d'informació que ajuda a l’usuari que gestiona els tràmits.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/144592677-85d1707c-2961-4e15-89f0-b6b24dcdf869.png)
![image](https://user-images.githubusercontent.com/67064375/144592695-a6a74086-99f9-4176-98d8-f1b71b18106e.png)

**Comment by avillen-dgtic** [comment]
Perfecte pel comentari, però hi ha un fallo quan s'excedeix del nombre de caràcters.

![image](https://user-images.githubusercontent.com/83401259/144599486-66e03aa0-b532-42f0-9373-aa7dd6bb294d.png)


Afegint un maxlength amb el nombre de caràcters que tenim limitar per bbdd s'arregla.

**Comment by jparedes-indra** [comment]
Se resuelve en la compilación 0ed040f y se añade un tooltip que permite ver toda la longitud de la descripción.

![imagen](https://user-images.githubusercontent.com/67064375/145765964-9051f75a-e3a2-4418-acb3-b91e89c9b52c.png)

**Comment by jsastre-dgtic** [comment]
Ara no falla, però podria aprofitar-se més l'espai mostrar el màxim d'info?
![image](https://user-images.githubusercontent.com/18436867/145770626-7dade525-38cf-4348-9e65-b065d89069b3.png)
