### ISSUE TITLE
Error quan s'edita un script d'un formulari

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#404]
Es genera un error quan piquem a l'edició d'un script.

![#new](https://user-images.githubusercontent.com/83401259/133427431-8e63274c-ed8f-4485-9c47-df03fb13cebf.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![#404](https://user-images.githubusercontent.com/67064375/140877174-b074c6fc-faa4-4aa6-b349-ab10986c8adc.gif)

**Comment by jsastre-dgtic** [comment]
no dóna error, però la pantalla surt malament, no mostra tota la barra de baix ni s'adapta a un portàtil... tancam aquesta i documentam això a la #365
