### ISSUE TITLE
Eliminar opció simulació a PRODUCCIÓ

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#405]
Atès que preproducció no és públic, i és l'entorn de validacions funcionals, pot convenir mantenir la simulació de pagament a PRE, però hauria de desaparèixer a PRO
PRE
![image](https://user-images.githubusercontent.com/18436867/133562068-31342d04-2d2e-4a81-9999-ac4210f3d144.png)

PRO
![image](https://user-images.githubusercontent.com/18436867/133562653-11bc0bfc-1cef-4e16-9c0d-95d0c7b3661e.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/140876779-cac521c1-f22b-4916-8589-3be77bdb7d0b.png)

**Comment by avillen-dgtic** [comment]
👍

**Comment by jsastre-dgtic** [comment]
Quan es promociona de dev a pre, ja canviar el valor de simular=false

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.1_0 ( https://github.com/GovernIB/sistra2/commit/b1380dff3750d3222705cb0d4fbbf980f0a0dfea)

![image](https://user-images.githubusercontent.com/96287364/177781064-5dcae623-e522-4751-ad85-041431458896.png)

**Comment by jsastre-dgtic** [comment]
Ara a PRE surt l'opció. Com queda al final això?

![imatge](https://user-images.githubusercontent.com/18436867/183024125-c4f5bc49-56a1-4bed-a23e-de7bfd2c83eb.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.2_1 (https://github.com/GovernIB/sistra2/commit/b308a01a1b1260bd6364486f0d4e26991fdd2093).

**Comment by jcerdar-indra** [comment]
Se ha quitado la visualización de este check en PREPRODUCCIÓN ya que ahora al generar cuadernos de carga no se permite generar un cuaderno en caso de que esté marcado el check.

**Comment by jsastre-dgtic** [comment]
Ok

![image](https://user-images.githubusercontent.com/18436867/193542468-e029adc3-a1d8-490b-88c0-419e604d3e60.png)

**Comment by jsastre-dgtic** [comment]
Comprovat, ok
