### ISSUE TITLE
Fase de confirmació a la  pantalla Gestió Dominis

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#408]
Canviar:
El domini està relacionat amb altres tràmits, segur que vol desar els canvis?

Per
El Domini està relacionat amb un o més tràmits, segur que vol desar els canvis?

![image](https://user-images.githubusercontent.com/18436867/133770663-c725d57d-44ab-4c37-9a53-47c8c25e21de.png)

**Comment by avillen-dgtic** [comment]
👍
