### ISSUE TITLE
canviar el text sobre protecció de dades

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#409]
Canviar el text “He llegit i accepto la política de privacitat” per “He llegit i accept la informació sobre protecció de dades”

![image](https://user-images.githubusercontent.com/18436867/133773255-f01fcea8-e2b8-413e-b1c0-f071c98a0434.png)

**Comment by jparedes-indra** [comment]
Para ganar en cohesión, vamos a cambiar el literal también en el popup que aparece si no se marca el check.

![imagen](https://user-images.githubusercontent.com/67064375/134883221-023ecaeb-b5fe-4fb0-a225-0a742e07e844.png)

**Comment by jparedes-indra** [comment]
Este es el resultado tras el cambio realizado.

![imagen](https://user-images.githubusercontent.com/67064375/134940672-0739ffe7-3b62-4d0e-86f6-5c06be14773f.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/135088936-cddffd9b-ee60-4b23-ad43-ecc6180639b8.png)
