### ISSUE TITLE
Canvis al Formatador Genèric

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#410]
Logotip més gran.
Títol del procediment en majúscula versalitas.
Codi SIA (text + codi) més gran.
Marca d’aigua del govern

![image](https://user-images.githubusercontent.com/18436867/133774860-585bbc41-4013-4e4b-b493-77fccecf8090.png)

![image](https://user-images.githubusercontent.com/18436867/133774912-8da7a746-82fe-405d-9651-c84bc83cb7ec.png)

**Comment by jparedes-indra** [comment]
En el pase realizado, se ha adjuntado un archivo en la carpeta PROPERTIES FORMATEADOR GENERICO. Este es el archivo properties que usa el formateador de tipo genérico y en el cual se pueden modificar algunas características mediante este archivo. 

En este archivo se han añadido algunas propiedades nuevas para poder modificar por ejemplo el tamaño del logo del documento o escoger si el título debe estar en mayúsculas o no. En caso de querer configurarlo indicar que desde este archivo de properties se podrían modificar estos atributos. 

![image](https://user-images.githubusercontent.com/67064375/135091412-d76e6a56-3aef-4b08-a1e4-3752371f61b7.png)

**Comment by jparedes-indra** [comment]
Con las propiedades mostradas en el comentario anterior, el documento quedaría de la siguiente forma:

![image](https://user-images.githubusercontent.com/67064375/135091653-a85faa94-ebab-4db2-bc16-d43cab3c2603.png)

**Comment by jsastre-dgtic** [comment]
Restam pendents de "Se resuelven los puntos menos el tipo de letra Versalitas para el título y la marca de agua del documento que se añadirá en versiones posteriores"

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf) el punto de la marca de agua. Quedaría por analizar el tipo de letra Versalitas.

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/140876729-8b2a7baa-e024-4a03-b007-5ada6063d199.png)

**Comment by jsastre-dgtic** [comment]
Queda pendent el tema versalites segons indicau https://github.com/GovernIB/sistra2/issues/410#issuecomment-963866356
