### ISSUE TITLE
Controlar validació obligatorietat en camps multilínia

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#411]
Problema en la validació d'obligatorietat dels camps de text multilínia. 
El problema és que si s'indica que aquest camp és obligatori i és multilínia, bota un error si no s'introdueix text en ells en el formulari que els conté, en lloc de mostrar un missatge indicant que s'han d'omplir.

![image](https://user-images.githubusercontent.com/18436867/133777045-4a426270-bf1a-4262-a5b5-2bcb75581fcf.png)

![imagen](https://user-images.githubusercontent.com/67064375/133799263-70fd23a6-810b-4506-bb31-adb1055b2fa2.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/135090483-d45cc810-5386-43f0-aebb-b89ef192266f.png)
