### ISSUE TITLE
La paginació i la molla de pa

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#414]
No funciona la molla de pa quan els tràmits es troben a una paginació fora de la primera
![#000](https://user-images.githubusercontent.com/83401259/135220479-8f4b3b78-8e01-414f-b2c9-ac694cde8919.gif)
.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![#414](https://user-images.githubusercontent.com/67064375/140876567-295dcd6f-b3c6-4836-9ec1-d4229a337688.gif)

**Comment by jparedes-indra** [comment]
Se ha detectado una casuística en la que sigue fallando la paginación con la 'molla de pa'. Al realizar una búsqueda de un trámite que se encuentra en una página que no sea la principal y clickar en la versión de la molla de pa, no recupera correctamente la página y no realiza correctamente la paginación.
![MollaPa](https://user-images.githubusercontent.com/67064375/141765146-2ae7d297-ab71-43f0-bc4e-3cf2828f10ef.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
![#414](https://user-images.githubusercontent.com/67064375/144593077-bc15642e-62ba-46f4-9d53-126764a4c42b.gif)

**Comment by avillen-dgtic** [comment]
No la podem testejar per la issue #455

**Comment by avillen-dgtic** [comment]
👍
