### ISSUE TITLE
Operacions a nivell de versions

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#415]
Quan es fa una operació damunt una versió, sigui per exemple desbloquejar, el llistat és recarregar i com a conseqüència es perd el punt
![#000](https://user-images.githubusercontent.com/83401259/135223192-df4a015d-85b7-4511-b16a-61fa43d9249c.gif)
.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![#415](https://user-images.githubusercontent.com/67064375/140876518-a5d81c03-a9ef-442a-894f-47867aa7fdff.gif)

**Comment by avillen-dgtic** [comment]
Perfecte!
