### ISSUE TITLE
Botonera al modal d'errors de validació

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#416]
Els botons de Corregir i Validar al modal d'error de validació pareix no tenir cap efecte
![#000](https://user-images.githubusercontent.com/83401259/135224572-7ae74150-9244-407a-bd55-a86758d5fdd9.gif)
.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![#416](https://user-images.githubusercontent.com/67064375/140876468-25ce5755-8c08-4a21-8ab3-0fdf65f21716.gif)

**Comment by avillen-dgtic** [comment]
![#000](https://user-images.githubusercontent.com/83401259/142607828-ff3bc8b4-e377-497b-ba2b-769c0da7cf02.gif)

Ara no ens surt els botons de validació i correcció.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
Los botones de corregir y validar aparecerán al validar cuando el trámite esté bloqueado y sólo aparecerán para el usuario que lo tenga bloqueado, siguiendo la lógica de STG de que solo el usuario que bloquea un trámite puede modificarlo. 
![#416_nob](https://user-images.githubusercontent.com/67064375/144593422-b2d45239-4a49-4503-a314-5c6a35210a1a.gif)
![#416_b](https://user-images.githubusercontent.com/67064375/144593524-0fe1366d-2eec-4b30-a9fe-72eba94022dd.gif)

**Comment by avillen-dgtic** [comment]
No podem donar per bona la correcció.
![#000](https://user-images.githubusercontent.com/83401259/144601191-7414161a-aa33-4623-bdea-82003a7c2a66.gif)

![image](https://user-images.githubusercontent.com/83401259/144601247-54ccc5e4-a8b3-453b-b9d6-1f5499721fc0.png)

**Comment by jparedes-indra** [comment]
Se resuelve enla compilación 0ed040f y se comprueba que haciendo la misma secuencia de acciones ya no se genera este error.

**Comment by avillen-dgtic** [comment]
L'error es corregeix.
