### ISSUE TITLE
La finestra del plugin de registre no presenta l'scroll correctament

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#420]
Supervisar totes les altres finestres
![a](https://user-images.githubusercontent.com/18436867/135580039-bd470a91-2ad7-4d07-abd7-a35ab9baafa9.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
![#420](https://user-images.githubusercontent.com/67064375/144593689-fbee8232-8617-42bd-943e-eaa75bb4ccc0.gif)

**Comment by avillen-dgtic** [comment]
👍
