### ISSUE TITLE
Després de desbloquejar hauria de mantenir focus la versió que acabam de desbloquejar

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#422]
![image](https://user-images.githubusercontent.com/18436867/135611245-fae7f68d-0ca9-4e93-9ed5-b0af35c25061.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jsastre-dgtic** [comment]
comprovat
