### ISSUE TITLE
Desactivar botó Exportar una vegada feta l'exportació

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#423]
Al generar quadern o exportar:

![image](https://user-images.githubusercontent.com/18436867/135611960-d314485a-aef1-474b-b49b-2a76973a852f.png)

**Comment by jparedes-indra** [comment]
![#423](https://user-images.githubusercontent.com/67064375/144593793-54ebe2bd-2cd5-4e58-b3be-048dad549d56.gif)

**Comment by avillen-dgtic** [comment]
👍
