### ISSUE TITLE
pantalla generar scripts no és responsive

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#424]
1.-
![image](https://user-images.githubusercontent.com/18436867/136004931-143027ed-25f0-4df5-8d5d-7f360e5d6ad2.png)

2.-
![image](https://user-images.githubusercontent.com/18436867/136005272-2fccb5cf-98d9-4d2a-ab75-31b0ca945788.png)

3.- 
![image](https://user-images.githubusercontent.com/18436867/136005341-ce3274d1-4cfe-4725-8aa9-6662718277fe.png)

**Comment by avillen-dgtic** [comment]
👍
