### ISSUE TITLE
Millores en el procés de validació de dominis utilitzats en un tràmit 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#425]
BUG: Validar versió no contempla els dominis emprats només en els scripts:

Al tràmit plantilla s'estira d'un domini anomenat gdescoddir3, que fa exactament el mateix que gesconsdir3 pèrò introduint un paràmetre coddir3

Per tal d'evitar tenir a PRE/PRO 3 dominis que fan el mateix, pensam que seria millor tenir un nom més descriptiu, amb la qual cosa hem provat de canviar el nom als dominis:
GESCONSDIR3 --> CONS_DIR3
GDESCANSDIR3 --> CONS_DIR3_PARAM

Però hem detectat que al tràmit plantilla es fa ús del segon a través d'scripts, i la funció "validar versió" això no ho contempla.

Tot i que hem canviat a l'script el nom del tràmit, ens surt un missatge de que el domini "cons_dir3_param" no s'empra a la versió, cosa que no és certa.
![image](https://user-images.githubusercontent.com/18436867/136019041-8e404187-d311-4400-9d37-f71d5b948a92.png)

**Comment by jparedes-indra** [comment]
También se considerará lo siguiente:

• Al validar un trámite, si salta la validación de dominio no empleado, se permitirá eliminarlo directamente de la lista de warnings mediante una acción desde la propia pantalla de validación. (Esta opción de corregir desde la propia ventana, por ahora solo se contempla para esta validación).

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
Validaciones añadidas: 
Al intentar eliminar un dominio que existe en el formulario
![#425_1](https://user-images.githubusercontent.com/67064375/144593927-b15406f0-181c-4d10-a43e-ebb9aadf8c8b.gif)

Al guardar un script que invoque un dominio no existente se añade automáticamente
![#425_2](https://user-images.githubusercontent.com/67064375/144593947-08aa7ef4-612d-4a5a-ac5a-7e2b964b467b.gif)

Al hacer llamada al método invocarDominio mediante variables, da error. 
![image](https://user-images.githubusercontent.com/67064375/144593978-bd2c7e07-18ec-4970-bb0f-f745e331a467.png)

Añadir dominio desde la ventana de scripts
![#425_3](https://user-images.githubusercontent.com/67064375/144594002-734b8387-d3bd-4e41-8f72-1f99b784eca9.gif)

getValor siempre ha de ir con el nombre del campo 
![#425_4](https://user-images.githubusercontent.com/67064375/144594036-093d0f11-1bee-49da-9f42-24135c23e013.gif)

Eliminar dominio no utilizado desde ventana validación
![#425_5](https://user-images.githubusercontent.com/67064375/144594064-5169a21a-a6c0-4ee8-b20e-d06cc7463024.gif)

**Comment by jparedes-indra** [comment]
Se ha observado que hay 2 scripts que no se comprueban en las validaciones (principalmente, porque se incluyeron después de la creación de las validaciones):

En propiedades página, el script de navegación
![image](https://user-images.githubusercontent.com/67064375/144594125-c850c1b6-b705-488e-bed5-b930e657643e.png)

En el paso de registrar, el script de al finalizar. 
![image](https://user-images.githubusercontent.com/67064375/144594148-eadda069-306c-4aaa-971f-5357dd72a40f.png)

**Comment by jsastre-dgtic** [comment]
ok
