### ISSUE TITLE
"Aplicació telemàtica" a RW

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#426]
La #320 està resolta, estaria millor visualitzar-ho gris.

**Comment by jsastre-dgtic** [comment]
A pro no tenim la mateixa descripció que a dev... La correcta a dev-pre-pro hauria de ser: Versió Sistra2 (No modificable)

![image](https://user-images.githubusercontent.com/18436867/136336183-6ca1b7f9-216b-4009-ae13-197b4bd315e4.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/144594234-da56b863-3508-4e41-804a-cf93ab523b98.png)

**Comment by jsastre-dgtic** [comment]
ok
