### ISSUE TITLE
error no controlat a SISTRAHELP   

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#427]
![image](https://user-images.githubusercontent.com/18436867/136748053-540fee38-287e-47d5-99fa-8e58fcbac020.png)
![image](https://user-images.githubusercontent.com/18436867/136748069-76b97103-32d0-4db4-9d95-fd32232479ca.png)
![image](https://user-images.githubusercontent.com/18436867/136748093-1322bfbb-b86a-47dc-9278-9d6e614a9908.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![#427](https://user-images.githubusercontent.com/67064375/140876284-ebc07b3c-71bf-4445-9b75-44337a9e9461.gif)

**Comment by avillen-dgtic** [comment]
Perfecte!
