### ISSUE TITLE
Canviar nom dels fitxers annexats

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#428]
Establir com a nom de fitxer annexat: IDANNEX-INSTÀNCIA a l'hora de passar les dades a RW3.

D'aquesta manera:
- Es prescindeix d'haver d'enviar un fitxer tècnic (XML)
- No hi haurà canvis en la versió 113 d'Helium, relatius al procés de captura de documents en les anotacions de distribució.
- Es reanomenaran els annexos segons el criteri: ANE1-X, ANE2-I, ... i es passaran a RW3 en la variable "nombreFicheroAnexado"

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/140876170-65c2ad1c-ae51-48aa-b377-ba409d7b1e9b.png)
![image](https://user-images.githubusercontent.com/67064375/140876183-eb72f0f5-42c9-4c95-8cad-1b70a0c0b8c0.png)

**Comment by jsastre-dgtic** [comment]
ok
