### ISSUE TITLE
Creació  d'una nova propietat global per a limitar la mida de cada annex

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#429]
1. Crear una propietat global "sistramit.anexos.tamanyoMaximoIndividual", de manera que es limiti la mida de cada annex.

2. Modificar la descripció de l'actual sistramit.anexos.tamanyoMaximo perquè indiqui que la mida màxima és la suma de tots els annexos del tràmit.

3. Al crear un annex en STG, si se supera no es permetrà guardar aquest annex en la definició del tràmit.

4. En el REST de STG, al retornar la definició d'un tràmit, aplicarà automàticament aquesta limitació, ajustant la definició del tràmit per assegurar el seu compliment en el STT (conf tam annex --> mida especificada en configuració annex / sistramit.anexos.tamanyoMaximoIndividual --> la nova propietat):

a. si sistramit.anexos.tamanyoMaximoIndividual <= 0 --> conf tam annex

b. si conf tam annex> sistramit.anexos.tamanyoMaximoIndividual --> sistramit.anexos.tamanyoMaximoIndividual

c. si conf tam annex <sistramit.anexos.tamanyoMaximoIndividual --> conf tam annex

d. si conf tam annex no establerta --> sistramit.anexos.tamanyoMaximoIndividual

5. Es permetrà indicar fins a 7 dígits en KB, per definir les mides màxims amb més precisió.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/140876074-b59b495d-b48d-4bb5-9e38-f345bae6f30e.png)
Cuando se supera el tamaño individual: 
![image](https://user-images.githubusercontent.com/67064375/140876111-d6814fe0-1e5c-4e80-b7e9-68444797b5c4.png)
Cuando se supera el tamaño global: 
![image](https://user-images.githubusercontent.com/67064375/140876132-60a3dbfc-29c3-42e0-a82e-dfe0418cd6ce.png)

**Comment by avillen-dgtic** [comment]
No tenim definida la propietat sistramit.anexos.tamanyMaximIndividual

**Comment by avillen-dgtic** [comment]
Afegits
