### ISSUE TITLE
STT: Integració amb el plugin del Catàleg de Procediment i Serveis

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#43]
Implementació de la integració amb el plugin del Catàleg de Procediment i Serveis Administratius https://github.com/GovernIB/pluginsib-cataleg/issues/1

**Comment by jsastre-dgtic** [comment]
Falta crear un SISTRA2-1.0\sistracom\sistracom-plugin-catalogoprocedimientos\doc 
També cal determinar els serveis que es requereixen del catàleg des del punt de vista de SISTRA2 (sistrages i sistramit)

**Comment by sgelabert-dgtic** [comment]
Entenc que el document es generarà en aquest 9è cicle. Podeu però afegir en aquest tiquet la configuració bàsica del component per poder fer-lo funcionar ?

**Comment by amaciam-indra** [comment]
El plugin de catàleg s'ha de configurar com un plugin d'entitat. Actualment existeixen dues implementacions d'aquest plugin, la mock i la de ROLSAC. Per configurar el plugin de catàleg ROLSAC s'haurà de donar d'alta un nou plugin d'entitat amb les dades següents:

Tipus de plugin => Plugin de catàleg de procediments
Classname => es.caib.sistra2.commons.plugins.catalogoprocedimientos.rolsac.CatalogoProcedimientosRolsacPlugin
Descripció plugin => Plugin de catàleg de procediments ROLSAC
Prefix de propietats => plugins.catalogoprocedimientos
Propietats plugin:
- url =>url de l'API de ROLSAC segons entorn (Ex: http://host:port/rolsac/api/rest/v1) 
- usr => usuari de consum dels serveis (per ara qualsevol valor ja que no està securitzat)
- pwd => password de l'usuari de consum dels serveis (per ara qualsevol valor ja que no està securitzat)

**Comment by jsastre-dgtic** [comment]
També cal determinar els serveis que es requereixen del catàleg des del punt de vista de SISTRA2 (sistrages i sistramit), esperam el document...

**Comment by jsastre-dgtic** [comment]
En principi està tot provat i correcte. Només ens resta determinar els serveis que es requereixen del catàleg des del punt de vista de SISTRA2. Potser podem tancar aquesta tasca. Rafa, no acabo de veure quina consulta tenim pendent de contestar...

**Comment by rsanz-indra** [comment]
Sí, correcto. Os comentábamos en el correo resumen que se podría cerrar:

> Esta tarea puede cerrarse ya que se ha verificado el funcionamiento del plugin en el entorno CAIB y en caibter. Restaría tema de documentación pero sería una tarea aparte y además hay que definir estructura de la documentación tal como se indica anteriormente.
