### ISSUE TITLE
Millorar documentació del manual d'integració

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#430]
El manual té mancances als apartats de tipus REST. 

Cal afegir:
1. Tipus de crida que es fan a cada moment
2. Els tipus de dades per a cada paràmetres.
3. Ampliar la descripció i l'ús que té cada un dels paràmetres.

També s'hauria de canviar el diagrama del GFE
![image](https://user-images.githubusercontent.com/83401259/138684229-bd03057c-964e-40c0-bfbb-5dc2bb27adfb.png)

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0 (49d5485)

**Comment by avillen-dgtic** [comment]
👍
