### ISSUE TITLE
Bug a STT amb  llista dinàmica d'annexos

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#431]
Si per un tràmit tan sols definim la llista dinàmica d'annexos, sense definir cap document a la llista fixa, la passa d'annexar documents de l'assistent de tramitació sempre falla. La solució que tenim és definir un document amb un script de dependència que sempre retorni N per a que el document no sigui visible,

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![#431](https://user-images.githubusercontent.com/67064375/140875991-8c7b794f-a26a-452e-a431-5e0997406bd5.gif)

**Comment by avillen-dgtic** [comment]
Correcte
