### ISSUE TITLE
Nou mètode per establir el nombre d'instàncies

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#432]
Quan definim un document des de l'script de Llista dinàmica d'annexos no sembla que hi hagi manera d'establir el nombre d'instàncies.
Ara per ara com a workaround, el que feim és crear el document com a fix, establir el nombre d'instàncies que volem, i amb l'script de dependència decidir si el mostram o no. 
Cal afegir aquest mètode a SISTRA2 per tal d'evitar haver de crear aquests documents fixes.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/144594304-f931e74e-4519-407e-94a4-e7382af4dc5a.png)

![image](https://user-images.githubusercontent.com/67064375/144594319-80cef6dc-f4a3-4be2-b656-68b7c3f66b3e.png)

**Comment by jsastre-dgtic** [comment]
ok
