### ISSUE TITLE
Afegir una propietat "precedència_annexosFixos" (true/false)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#433]
Per un mateix tràmit, si tenim llistes dinàmiques i fixes de documents, sempre surten primer els documents de la llista de fixa i després els documents de la llista dinàmica. Fer que aquest ordre sigui configurable.
Cal afegir una propietat "precedència_annexosFixos" (true/false). Per defecte serà true.
![image](https://user-images.githubusercontent.com/18436867/140021923-de961001-8abf-4bcf-8826-df1963f86f9b.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
Se ha añadido la propiedad y las ayudas correspondientes: 
![image](https://user-images.githubusercontent.com/67064375/140875552-4bcec552-be38-4f6d-8a37-d3ae212fc059.png)
![image](https://user-images.githubusercontent.com/67064375/140875660-502f4bb0-6488-4af3-b578-8e5c3a39f01c.png)

**Comment by avillen-dgtic** [comment]
Funcionalitat afegida.
