### ISSUE TITLE
Error quan es crea o s'edita un GFE

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#434]
Apareix un error quan s'edita un GFE
![#000](https://user-images.githubusercontent.com/83401259/141990514-0d96b27e-e5d3-49df-9a00-dc52e338626e.gif)
.
Estant a la 1.2.1 (eb89edf)

Excepción: javax.ejb.EJBException
Mensaje: es.caib.sistrages.core.api.exception.DatabaseException: Error en la capa de base de datos: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : es.caib.sistrages.core.service.repository.model.JGestorExternoFormularios.configuracionAutenticacion -> es.caib.sistrages.core.service.repository.model.JConfiguracionAutenticacion; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : es.caib.sistrages.core.service.repository.model.JGestorExternoFormularios.configuracionAutenticacion -> es.caib.sistrages.core.service.repository.model.JConfiguracionAutenticacion

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
![#434](https://user-images.githubusercontent.com/67064375/144595779-dfc628df-26d1-40ab-bfb5-a6699f9669bf.gif)

**Comment by jsastre-dgtic** [comment]
ok
