### ISSUE TITLE
Avaluació d'Accessibilitat a l'assistent de tramitació SISTRAMIT

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#435]
Per assegurar el compliment de les WCAG 2.1 (i, per tant, de la normativa que les utilitza com a referència), cal cobrir 20 Criteris de conformitat al seu Principi Perceptible, 17 a Operable, 10 per al Principi Comprensible i 3 per a Robust.

**Principi Perceptible:**
Contingut no textual
Informació i relacions
Seqüència significativa
Característiques sensorials
Orientació
Identificar el propòsit de camp
Ús del Color
Contrast (mínim)
Redimensió del text
Imatges de text
Reflow
Contrast en elements no textuals
**Principi Operable:**
Teclat
Sense trampes per al focus del teclat
Dreceres amb tecles de caràcters
Temps ajustable
Llindar de tres centelleigs o menys
Evitar blocs
Titulat de pàgines
Ordre del focus
Propòsit dels enllaços (en context)
Múltiples vies
Encapçalats i etiquetes
Focus visible
Gestos del punter
Cancel·lació del punter
Etiqueta al nom
Activació mitjançant moviment
**• Principi comprensible:**
Idioma de la pàgina
Idioma de les parts
En rebre el focus
En rebre entrades
Navegació coherent
Identificació coherent
Identificació d'errades
Etiquetes o instruccions
Suggeriments davant d'errors
Prevenció d'errades (legals, financers, dades)
**• Principi Robust:**
Processament
Nom, funció, valor
Missatges d'estat

**Comment by jparedes-indra** [comment]
El alcance de la issue es la evaluación del estado acual del asistente y el entregable, los informes cuantitativo y detallado, que indicarán tanto las estadísticas obtenidas como los detalles de cada prueba y su posible solución técnica, si fuese necesario.

**Comment by jparedes-indra** [comment]
Se entregaron informes cuantitativo y cualitativo por correo.

Data: 04/02/2022 10:18
Assumpte: RV: [GovernIB/sistra2] Avaluació d'Accessibilitat al assistent de tramitació SISTRAMIT (Issue #435)

**Comment by jsastre-dgtic** [comment]
I:\1. Serveis d'Administració Electrònica 2020-2024\01. Lot 1 Serveis electrònics per a la ciutadania\05. Àrea tramitació telemàtica\SISTRA2 - Documentació
