### ISSUE TITLE
Error no controlat quan es crea un GFE 

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#437]
Quan es crea un GFE de nou, el botó de tràmits associats mostra un error. Aquest botó hauria d'estar desactivat sigui per a tràmits nous o tràmits sense cap associació.

![#000](https://user-images.githubusercontent.com/83401259/142161632-846fbbfd-8782-43f8-8f9d-2ce79848b711.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
![#437](https://user-images.githubusercontent.com/67064375/144595834-91055825-fbbd-4359-adb1-919f8a21a986.gif)

**Comment by jsastre-dgtic** [comment]
Seria més desitjable que sortís un missatge informatius de que "No hi ha tràmits associats". Ara pitges el botó de Tràmits associats i no saps si funciona o no el botó.

**Comment by jcerdar-indra** [comment]
- Al pulsar en el botón de 'Trámites', aparece un mensaje informativo en caso de que no tenga trámites asociados el GFE. 

![image](https://user-images.githubusercontent.com/96287364/149173364-9e18f799-669e-4654-8163-936fff4bc7ea.png)

**Comment by avillen-dgtic** [comment]
👍
