### ISSUE TITLE
Detectat un bug en fer recerca de tràmits a STG quan s'utilitza el caràcter ‘_’

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#438]
![Busqueda](https://user-images.githubusercontent.com/18436867/142387903-4bc84da0-4459-4bbf-9f0e-48be28ce5f45.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
![#438](https://user-images.githubusercontent.com/67064375/144595891-61d54fbb-de1a-4b29-b1bc-2c9e3de69115.gif)

**Comment by jsastre-dgtic** [comment]
ok
