### ISSUE TITLE
Pantalla consulta: poder cercar elements a l'entitat (dominis, fonts, dades, GFE, …)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#441]
Pantalla consulta: poder cercar elements a l'entitat (dominis, fonts, dades, GFE, …)

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

Pantalla general: 

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161030664-80d4d7d5-8124-4dc5-b623-a6f7598cdaad.png">

Poner en la issue: siguiendo el doc de análisis y estimación se ha creado la pantalla: 
Consultas por textos: 

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161030694-a3823838-64bb-43e5-94c8-29d44baf6ae5.png">


Mínimo marcar un ámbito y una entidad: 

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161030726-62a0c197-0b5a-42b0-bbd4-b0eeb7a263f5.png">

Dependiendo de los roles, se puede modificar el elemento:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161030778-72955067-1bb3-47cd-9bc5-0b76f3a89186.png">

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161030798-9a3e9a10-b91b-4d12-b1b6-546ba5f862e8.png">

**Comment by jsastre-dgtic** [comment]
ok
