### ISSUE TITLE
Formatador automàtic del justificant de sol·licitud II

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#442]
1.- La mida de la lletra corresponent a subtítols (marcat en groc en la següent imatge) és massa petit. Proposam que la mida per aquest tipus de format sigui igual a la mida emprada pels noms dels camps.
![image](https://user-images.githubusercontent.com/18436867/143191253-9a2dc35c-fdb6-4f2b-85b7-a76b7dcaaee4.png)

2.- Eliminar el codi intern pels camps de selecció: En aquests moments es visualitza el codi intern per tots aquells camps de selecció (radio buttons, llistes desplegables, ...). Proposam que el codi intern no es visualitzi.
![image](https://user-images.githubusercontent.com/18436867/143191335-4cdc6dfc-b91e-403c-8882-bca555a50658.png)

3.- La marca d’aigua és massa gran: En aquests moments la imatge corresponent a la marca d’aigua consideram que és massa gran i que no correspon amb la mida del model indicat al document d’identitat corporativa següent on les dimensions de la imatge són de 7,79cm d’amplada i 11,87cm d’alçada.
https://www.caib.es/sites/manualdidentitatcorporativa/ca/plantilles_base_per_a_impresos/
![image](https://user-images.githubusercontent.com/18436867/143191450-1edb0a69-f663-4d94-a008-bf7fd243d8a6.png)

4.- El títol no està centrat segons l’amplada del justificant: En aquests moments el (títol + subtítol) del Procediment no està centrat segons l’amplada del justificant. Proposam que surti centrat.
![image](https://user-images.githubusercontent.com/18436867/143191527-befe74d0-5050-4d31-93d0-1b94e040fc66.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
1.- Tamaño avisos aumentado: 
![image](https://user-images.githubusercontent.com/67064375/144595971-9b3613b8-8567-44d0-8927-781e15fa98db.png)

2.- Eliminar código Selectores
![image](https://user-images.githubusercontent.com/67064375/144596005-4d5b5bf0-252c-4c46-ac20-92a0424e654c.png)

3.- Marca de agua con medidas correctas: 
![image](https://user-images.githubusercontent.com/67064375/144596123-17c31238-9200-49cf-a547-585194fd636d.png)

**Comment by jparedes-indra** [comment]
El punto 4 se aborda en la issue #445

**Comment by jsastre-dgtic** [comment]
ok
