### ISSUE TITLE
Odre «Informació sobre la protecció de dades»

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#443]
Actualment, l’ordre dels elements que surten a la finestra emergent «Informació sobre la protecció de dades» no és el mateix que l’odre de ROLSAC. Consideram que l’odre adequat seria el que es contempla a ROLSAC.

![image](https://user-images.githubusercontent.com/18436867/143191957-5d8894c9-578b-45a1-892d-b383ec1f3027.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/144596206-77e4a939-2ccb-4de8-9e5f-a18d1daa378b.png)

**Comment by jsastre-dgtic** [comment]
ok
