### ISSUE TITLE
cal canviar Representación per Representació, a la pantalla de Registrar STG

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#444]
![image](https://user-images.githubusercontent.com/18436867/143436551-12f88c0e-4912-4ad1-8289-3045c94532e3.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/144596337-034b6b89-6c7d-4cca-ac50-eede6ca343bf.png)

**Comment by jsastre-dgtic** [comment]
ok
