### ISSUE TITLE
Modificar la generació de formularis per ser detectats pel lector de pantalla

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#446]
Detectat un problema al frontal que interfereix amb el lector de pantalla a l'hora de fer servir els formularis. Calen proves d'accessibilitat i que el lector de pantalla en detecti el contingut per avaluar l'actual nivell d'accessibilitat als formularis.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.1_1 (cd55c2d)

**Comment by jsastre-dgtic** [comment]
No tenim cap detector de pantalla... ho podem validar d'una altra manera

**Comment by jparedes-indra** [comment]
Para probar esta issue puede activarse el Narrador de Windwos o descargar NVDA (https://nvda.es/).

Al acceder a un formulario con un lector de pantalla activo, su contenido será verbalizado en voz alta por el lector, al pasar el ratón o el foco de teclado por cada elemento.

Esta issue permite que el lector detecte el contenido de los formularios, pero la issue #435 determnará si el centenido es detectado apropiadamente.

**Comment by jsastre-dgtic** [comment]
Comprovam que llegeix l'assistent i el formularis associats
