### ISSUE TITLE
Paginació no es reinicia

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#447]
La casuística és aquesta:
1er. Fem una cerca per treure un nombre elevat de pàgines.
2on. Seleccionem una pàgina qualsevol.
3er. Fem una cerca diferent. 

La pàgina que havíem seleccionat al punt dos no es reinicia

**Comment by jparedes-indra** [comment]
Buenas, 

No conseguimos reproducirlo. ¿Podéis pasar más información para reproducirlo?

**Comment by avillen-dgtic** [comment]
Us ho passo per correu electrònic perquè hi ha dades personals.

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0 (49d5485)

**Comment by avillen-dgtic** [comment]
👍
