### ISSUE TITLE
Espais buits

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#448]
Això a les caixes de cerca de la part de SH. Havent-hi espai de sobra a la finestra, la taula de resultats afegeix scrolls.
![image](https://user-images.githubusercontent.com/83401259/143842701-c983d925-a04b-418e-b693-4b3cfbdb2e0c.png)

Entenc que aquesta caixa hauria d'anar creixent a mesura que les dades apareixen fins als límit de la finestra, una vegada allà començar amb la paginació.

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0 (49d5485)

**Comment by jcerdar-indra** [comment]
- El espacio que ocupa la tabla se aumenta.
![image](https://user-images.githubusercontent.com/96287364/149174553-be07fbe6-51e3-475f-becd-63fcde1a859e.png)

**Comment by avillen-dgtic** [comment]
👍
