### ISSUE TITLE
el check Valida representació no s'hauria de poder desar per no estar implementat. 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#449]
Hauria de sortir un missatge informant de perquè no es pot desar. 
![image](https://user-images.githubusercontent.com/18436867/143845412-98b6e466-4321-4727-93da-d803d63d5372.png)
![image](https://user-images.githubusercontent.com/18436867/143844428-bd07a06a-ad27-4be5-9fea-f7f60e4567f7.png)

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0 (49d5485)

**Comment by jcerdar-indra** [comment]
- Para actualizar los trámites que tienen el check marcado actualmente, se ha añadido un script de BBDD en el pase para desmarcar el check en cuestión. 
![#449](https://user-images.githubusercontent.com/96287364/149174683-4d87103e-57a4-46eb-b444-0c004de6ae7a.gif)

**Comment by avillen-dgtic** [comment]
👍
