### ISSUE TITLE
PLG: Component horitzontal de pagaments PaymentIB

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#45]
- Creació del component horitzontal de pagaments de la CAIB que s'integrarà d'inici amb la passarela de l'ATIB
- Definició del plugin d'integració

**Comment by amaciam-indra** [comment]
Per poder provar aquest component, com que el workflow de la passa pagar està previst per aquest cicle de desenvolupament, podeu provar els serveis del component mitjaçant swagger. Aquest prova la podeu efectuar a CAIBTER seguint les passes següents:

1. Accedir a swagger caibter.indra.es/paymentib/api/rest/swagger-ui.html

2. Al segon mètode (post /v1/iniciarPagoElectronico) haureu de passar uns paràmetres d'exemple:
{
  "datosPago": {
    "aplicacionId": "S2",
    "concepto": "co",
    "detallePago": "dp",
    "entidadId": "E1",
    "idioma": "es",
    "importe": 100,
    "modelo": "046",
    "organismoId": "O1",
    "pasarelaId": "ATIB",
    "sujetoPasivoNif": "12345678Z",
    "sujetoPasivoNombre": "Usuario Prueba Prueba",
    "tasaId": "1.21.1.2.1.4"
  },
  "urlCallback": "http://www.google.es"
}

3. El servei indicat us retornarà un ID i una URL. Exemple:

{
  "identificador": "KZ2JUIGK-STO9WNT8-T8FEDRHZ",
  "urlPago": "http://localhost:8080/paymentibfront/inicioPago/KZ2JUIGK-STO9R8T8-T8VZ2JS3.html"
}

4. Si anau a la URL podreu seleccionar el mètode de pagament.

**Comment by rsanz-indra** [comment]
Estamos pendientes de revisar un problema con el proxy de Indra al conectar con ATIB.

**Comment by rsanz-indra** [comment]
Ya se puede probar en caibter el componente PAYMENTIB y la integración con ATIB
