### ISSUE TITLE
Text dinàmic a “Cal saber”

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#450]
Afegir possibilitat d'establir instruccions d'inici per script:

- L'script haurà de tornar com a resultat un text (html) que serà el que es visualitzarà.
- L'script tindrà preferència sobre el text fix ( el de dalt: “Instruccions d'inici (HTML)”, per la qual cosa si s'omple l'script no es tendrà en compte aquest camp.
- Es crearà un nou tipus de missatges per permetre l'ús de codi html des de la finestra de “Script instruccions d'inici”

**Comment by aagudo-indra** [comment]
En el paso CAL SABER en STG: 

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161035443-b2a78e7e-d43f-48f5-95b3-0e3857651cf8.png">

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161035547-53ebc8f7-dca6-43fb-a855-45217bafe80b.png">

Los mensajes desde el script de instrucciones abren el editor Tiny.

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161035635-dd4bb73a-ea05-4f90-bb4f-54f223319260.png">

En el Tiny el mensaje de validación:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161035766-92896094-dc5d-40f8-ae53-329d61c3d8d6.png">

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161035787-1a928196-be68-4757-9aba-28479db98920.png">

Nuevas ayudas:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161035848-7cceb08a-7068-4281-b33f-ba22867afd5d.png">

Cabe remarcar que si hay tanto textos dinámicos como estáticos definidos se priorizará el dinámico.

Ejemplo de uso:

![450](https://user-images.githubusercontent.com/88820558/161035933-7197843c-caa7-41f6-8c1b-d17164898673.gif)

**Comment by jsastre-dgtic** [comment]
ok
