### ISSUE TITLE
Error eliminant un GFE a PRE

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#451]
Aquest error ens ha sortit quan hem volgut eliminar un GFE de PRE.
![image](https://user-images.githubusercontent.com/83401259/144231960-d6475327-49b5-402d-ba96-93c6bc470975.png)

**Comment by jparedes-indra** [comment]
Este error es el mismo que el de la issue #400, se soluciona al subir la versión 1.2.1 a PRE.

**Comment by avillen-dgtic** [comment]
No es pot donar per bona. Quan volem eliminar un GFE ens diu que té un tràmit associat, però el botó de tràmits associats no ens mostra res.

**Comment by avillen-dgtic** [comment]
![#000](https://user-images.githubusercontent.com/83401259/148907879-95fa6308-68e2-460a-a558-dd45b5b37335.gif)

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0 (49d5485)

**Comment by avillen-dgtic** [comment]
La informació que dona no és útil per trobar el tràmit associat.
Cal afegir el codi del tràmit per tenir una bona referència i ja no dic que també seria bona idea afegir un botó per obrir el tràmit a una tab nova.

![image](https://user-images.githubusercontent.com/83401259/149307995-0287b203-0aea-40e9-ad1e-7ca3fc0398c6.png)
![image](https://user-images.githubusercontent.com/83401259/149308007-c0916f58-0f50-4c28-a281-f196118fe7b4.png)

**Comment by jcerdar-indra** [comment]
- Se soluciona en el TAG 1.2.2_1(807f0a5)

**Comment by jcerdar-indra** [comment]
- En la columna 'Trámite' se pone el identificador del trámite para dar más facilidad de encontrar el trámite en cuestión. 
![image](https://user-images.githubusercontent.com/96287364/151119031-80c33a47-1dfa-48e2-a39f-a61103cdede9.png)
![image](https://user-images.githubusercontent.com/96287364/151119034-3ce849bd-4ca8-42ce-bf43-240693896526.png)

**Comment by avillen-dgtic** [comment]
👌
