### ISSUE TITLE
Dinamitzar logo per UA a Formatador Genèric

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#452]
![image](https://user-images.githubusercontent.com/18436867/144232178-a3c29ae7-8a0a-41cb-a7d5-8a51c6563bfe.png)

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0 (49d5485)

**Comment by jcerdar-indra** [comment]
- Para añadir el logo en función de la UA, se ha de añadir una nueva propiedad en el fichero properties del formateador genérico. En el fichero de properties incluido en el pase, ya se añade dicha propiedad. 
![image](https://user-images.githubusercontent.com/96287364/149175174-e819365c-c0ec-4748-9d40-9e1bf7a14813.png)
![image](https://user-images.githubusercontent.com/96287364/149175188-e58b1e03-d543-4fb8-870f-8a80a4af2dfd.png)

**Comment by jsastre-dgtic** [comment]
ok, es comprova el bon funcionament de la plataforma i l'existència dels logos a https://www.caib.es/logos/A04027005.png
