### ISSUE TITLE
La paginació desapareix

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#454]
La paginació desapareix quan seleccionem totes les àrees.

![#000](https://user-images.githubusercontent.com/83401259/144598801-658bc7e0-086b-4aed-a6d8-531f3367389d.gif)

Aquest problema ja ha sortit altres vegades i amb aquesta versió torna a sortir.

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0 (49d5485)

**Comment by jcerdar-indra** [comment]
![#454](https://user-images.githubusercontent.com/96287364/149175314-6bb1377a-8822-46e8-b6e4-15d93042aed1.gif)

**Comment by avillen-dgtic** [comment]
Ara passa el contrari. La paginació queda quan no existeix cap element al llistat.

**Comment by jcerdar-indra** [comment]
- Se soluciona en el TAG 1.2.2_1(807f0a5)

**Comment by jcerdar-indra** [comment]
- La paginación desaparece al no haber ningún área seleccionada. 
![#454](https://user-images.githubusercontent.com/96287364/151119165-40eb0c39-f106-44b6-880a-0e6a900d97a5.gif)
