### ISSUE TITLE
Error amb la Molla de pa

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#455]
Quan piquem la molla de pa surt un error no controlat.

![#000](https://user-images.githubusercontent.com/83401259/144600505-b61a4fa0-a05a-4731-833f-773fec443072.gif)

**Comment by avillen-dgtic** [comment]
javax.ejb.EJBException: es.caib.sistrages.core.api.exception.ErrorNoControladoException: Error no controlado en la capa de servicio: first-result value cannot be negative : -10<br/> at org.jboss.as.ejb3@7.2.0.GA-redhat-00005//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInNoTx(CMTTxInterceptor.java:223)<br/> at org.jboss.as.ejb3@7.2.0.GA-redhat-00005//org.jboss.as.ejb3.tx.CMTTxInterceptor.notSupported(CMTTxInterceptor.java:345)<br/> at org.jboss.as.ejb3@7.2.0.GA-redhat-00005//org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:142)<br/> at org.jboss.invocation@1.5.1.Final-redhat-1//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)<br/> at org.jboss.invocation@1.5.1.Final-redhat-1//org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)<br/> at org.jboss.weld.core@3.0.5.Final-redhat-00001//org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)<br/> at org.jboss.as.weld.common@7.2.0.GA-redhat-00005//org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89)<br/> at org.jboss.invocation@1.5.1.Final-redhat-1//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)<br/> at org.jboss.as.ejb3@7.2.0.GA-redhat-00005//org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)<br/> at org.jboss.invocation@1.5.1.Final-redhat-1//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)<br/> at org.jboss.as.ejb3@7.2.0.GA-redhat-00005//org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47)<br/> at org.jboss.invocation@1.5.1.Final-redhat-1//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)<br/> at org.jboss.as.ejb3@7.2.0.GA-redhat-00005//org.jboss.as.ejb3.security.AuthorizationInterceptor.processInvocation(AuthorizationInterceptor.java:138)<br/> at org.jboss.invocation@1.5.1.Final-redhat-1//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)<br/> at org.jboss.as.ejb3@7.2.0.GA-redhat-00005//org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100)<br/> at org.jboss.invocation@1.5.1.Final-redhat-1//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)<br/> at org.jboss.as.ejb3@7.2.0.GA-redhat-

**Comment by jparedes-indra** [comment]
Hemos intentado reproducir el error indicado en el entorno de desarrollo (CAIBdev) pero nos funciona correctamente. ¿Podéis volver a probar y, en caso de reproducir el error, indicarnos la casuística para poder reproducirlo?

**Comment by jparedes-indra** [comment]
![#455](https://user-images.githubusercontent.com/67064375/147064632-e705baea-dceb-4ca8-afb4-2bc90a34bde0.gif)

**Comment by jsastre-dgtic** [comment]
Suposam un error puntual, tampoc el reproduim ni a dev ni a pre.
Tancam
