### ISSUE TITLE
Optimització dels espais a la taula de tràmits

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#456]
#403
![image](https://user-images.githubusercontent.com/83401259/145783270-ef0bc561-884e-4139-95d0-d393e702532d.png)

hi ha molt d'espai buit a les taules de tràmits

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0 (49d5485)

**Comment by jcerdar-indra** [comment]
- Se redimensiona la tabla para poder ver mejor la descripción de la versión. 

![image](https://user-images.githubusercontent.com/96287364/149175962-6a0fbadd-f9e6-486e-a1b1-2c42d2a8c3e3.png)

**Comment by avillen-dgtic** [comment]
👌
