### ISSUE TITLE
Establir signants

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#458]
Actualment el funcionament dels signats és que hauran de firmar tots els que es fixin per script. L'opció de fer que un document hagi de ser signat per un signat o altre no està contemplat. (ve de STG: Millores desitjables a SISTRAGES (FASE III) #137

**Comment by jcerdar-indra** [comment]
- Para dar solución a esta issue, en el script de 'Establecer Firmantes' se añadirá un método addFirmanteOpcional(), para poder definir que firmante es obligatorio y que firmante es opcional. 

     - Los firmantes que se añadan con el método addFirmante(), deberán de firmar obligatoriamente el documento en cuestión. 
     - De los firmantes que se añadan con el método addFirmanteOpcional(), al menos uno de ellos deberá de firmar obligatoriamente.
 
Por ejemplo, si tenemos dos firmantes, A y B, y queremos que A sea obligatorio y B opcional.

En el script de definir firmantes, se pondría esto: 

addFirmante(dniA, nombreA);
addFirmanteOpcional(dniA, nombreA);  
addFirmanteOpcional(dniB, nombreB);

En el caso que sea indiferente cual debe ser el firmante, solo sería añadir firmantes opcionales: 

addFirmanteOpcional(dniA, nombreA);  
addFirmanteOpcional(dniB, nombreB);

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161036702-0292da7f-39d2-4c76-987d-bbab97c77e9b.png">

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161036719-be112636-d87c-41c1-9f3c-9ec2a0a5e9e5.png">

En STG se han añadido ayudas para el nuevo método: 

<img width="339" alt="image" src="https://user-images.githubusercontent.com/88820558/161036760-8c139636-2382-40b6-8cb8-551328c6d6c7.png">

Ejemplo de uso:

![458](https://user-images.githubusercontent.com/88820558/161036842-f552bc91-08f7-4073-878f-8fc9aac0ac9e.gif)

**Comment by jcerdar-indra** [comment]
Se corrige el error en el tag 1.3.0_1 (c2080ce). Ya se descargan correctamente los documentos firmados.

**Comment by jcerdar-indra** [comment]
![#458](https://user-images.githubusercontent.com/96287364/164166269-83fec2c3-bf92-4cda-9590-9bd06cfd8017.gif)

**Comment by jsastre-dgtic** [comment]
Es descarreguen els documents firmats, però si no es valida la signatura correctament (hem canviat la propietat verificarfirma=true), el quadre de diàleg surt tallat:

![image](https://user-images.githubusercontent.com/18436867/164206830-190b048e-9612-4f59-8078-0b2f30d5b784.png)

**Comment by jsastre-dgtic** [comment]
Tampoc aconseguim un funcionament correcte si firmam amb el mateix certificat. Ens bóta el mateix error

**Comment by jsastre-dgtic** [comment]
Passam a  Si definim verificarFirma=true al plugin de firma falla #534
