### ISSUE TITLE
Errors de compilació per codificació errònia UTF-8

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#46]
[INFO] Compiling 140 source files to C:\CAI\GitHub\sistra2-master\sistra2\sistrages\sistrages-core-api\target\classes
[ERROR] /C:/CAI/GitHub/sistra2-master/sistra2/sistrages/sistrages-core-api/src/main/java/es/caib/sistrages/core/api/model/TramiteVersion.java:[529,26] unmappable character for encoding UTF-8
[INFO] 
[INFO] sistramit-core ..................................... SUCCESS [ 20.701 s]
[INFO] sistramit-rest-ws .................................. SUCCESS [  3.848 s]
[INFO] sistramit-frontend ................................. SUCCESS [  6.150 s]
[INFO] sistramit-ear ...................................... SUCCESS [ 10.895 s]
[INFO] sistrages-core-api ................................. SUCCESS [ 10.016 s]
[INFO] sistrages-lib ...................................... SUCCESS [  0.044 s]
[INFO] sistrages-core ..................................... SUCCESS [  7.544 s]
[INFO] sistrages-rest-ws .................................. SUCCESS [  2.197 s]
[INFO] sistrages-frontend ................................. FAILURE [ 28.980 s]
[INFO] sistrages-ear ...................................... SKIPPED
[INFO] sistrahelp ......................................... SKIPPED
[INFO] sistrahelp-core-api ................................ SKIPPED
[INFO] sistrahelp-lib ..................................... SKIPPED
[INFO] sistrahelp-core .................................... SKIPPED
[INFO] sistrahelp-rest-ws ................................. SKIPPED
[INFO] sistrahelp-frontend ................................ SKIPPED
[INFO] sistrahelp-ear 0.0.1-SNAPSHOT ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:25 min
[INFO] Finished at: 2018-10-08T09:27:46+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:
run (default) on project sistrages-frontend: An Ant BuildException has occured:
IOException in C:\CAI\GitHub\sistra2-master\sistra2\sistrages\sistrages-frontend
\src\main\webapp\WEB-INF\sistrages-ac-frontend.xml - java.io.FileNotFoundExcepti
on:C:\CAI\GitHub\sistra2-master\sistra2\sistrages\sistrages-frontend\src\main\we
bapp\WEB-INF\sistrages-ac-frontend.xml (Acceso denegado)
[ERROR] around Ant part ...<replace dir="src/main/webapp/WEB-INF">... @ 5:42 in
C:\CAI\GitHub\sistra2-master\sistra2\sistrages\sistrages-frontend\target\antrun\
build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by amaciam-indra** [comment]
Hola,

Hem resolt el problema, podeu fer un pull i tornar a compilar? Gràcies.

**Comment by jsastre-dgtic** [comment]
ok
