### ISSUE TITLE
Botó Anterior no funciona

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#462]
Intenta anar a la passa Pagament però no existeix
![Anterior](https://user-images.githubusercontent.com/18436867/146738641-adbb2010-a1da-4a6a-b2db-3af02d5a423b.gif)

**Comment by jsastre-dgtic** [comment]
Si intentam navegar a la passa Emplenar directament tampoc no funciona:
![Anterior](https://user-images.githubusercontent.com/18436867/146739529-101df17a-d579-4927-bba3-c6802f80e13c.gif)

**Comment by jparedes-indra** [comment]
Al producirse un error en el registro, el botón Registrar pasa a modo Reintentar, por lo que no es posible ir a otros pasos. 

Se van a inhabilitar los enlaces relacionados, para impedir que en esas circunsantias se puedan pulsar con la intención de ir a un paso anterior.

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0 (49d5485)

**Comment by jcerdar-indra** [comment]
- Se han inhabilitado los enlaces relacionados al estar en modo 'Reintentar'. 
![#462](https://user-images.githubusercontent.com/96287364/149176854-49f32f9d-f5f6-411b-80d8-f246779de6a6.gif)

**Comment by jsastre-dgtic** [comment]
ok
