### ISSUE TITLE
Problema amb la m. cau del navegador

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#463]
Es deixen de veure els tràmits associats a una àrea. Només es tornen visualitzar reiniciant el navegador.
![tramitsnoseveuen](https://user-images.githubusercontent.com/18436867/146752918-9ad67eda-7606-4720-84ce-e5133efc9c71.gif)

**Comment by avillen-dgtic** [comment]
Aquest problema el vaig tenir jo també i el vaig poder resoldre eliminat les cookies. En qualque moment no deu permetre guardar les dades dels tràmits a l'objecte del navegador.

**Comment by jcerdar-indra** [comment]
- No conseguimos reproducir el error de la cache del navegador. ¿Podéis detallarnos como reproducirlo para ver que puede estar pasando?

**Comment by avillen-dgtic** [comment]
Aquest tipus d'issues són molt dolentes de reproduir.
