### ISSUE TITLE
Generar esdeveniment debug per veure a STH la informació enviada a RW3

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#464]
La mateixa prova a DEV funciona bé, passa només a PRE i amb el certificat de tipus 11 INZEPE (de prova), amb el FNMT tipus 12 va bé. Es detecta un tractament incorrecte dels certificats tipus 11 per part de Cl@ve-SE i no pot registrar.
 
Caused by: es.caib.sistra2.commons.plugins.registro.api.RegistroPluginException: Error realizando registro de entrada : Primer llinatge(interesado.apellido1): El camp és obligatori 
        at deployment.sistramit.ear//es.caib.sistra2.commons.plugins.registro.regweb3.RegistroRegweb3Plugin.registroEntrada(RegistroRegweb3Plugin.java:165)

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0 (49d5485)

**Comment by jcerdar-indra** [comment]
- Cuando en el trámite se habilita el modo debug, al registrar se genera un evento para ver la información del asiento registral. 
![image](https://user-images.githubusercontent.com/96287364/149177042-0674b727-4ab2-4002-aaef-0f2f06b25608.png)

**Comment by jsastre-dgtic** [comment]
Ok, però cal redimensionar la pantalla Esdeveniment i fer-la responsive

![image](https://user-images.githubusercontent.com/18436867/149731943-0fe0ca33-c160-45e6-9489-3db737864444.png)

**Comment by jcerdar-indra** [comment]
- Se soluciona en el TAG 1.2.2_1(807f0a5)

**Comment by jcerdar-indra** [comment]
![#464](https://user-images.githubusercontent.com/96287364/151119269-cb25b9b0-d037-45a6-a125-30e51af5c6b0.gif)

**Comment by avillen-dgtic** [comment]
👌
