### ISSUE TITLE
Redimensionar finestra plugin registre

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#465]
Ni amb les barres de desplaçament ni fent gran la finestra es pot visualitzar tota la informació

![finestra_plugin](https://user-images.githubusercontent.com/18436867/146898377-d8fdcd40-1ad3-4c15-9c25-3f186ae78bcb.gif)

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0 (49d5485)

**Comment by jcerdar-indra** [comment]
![465](https://user-images.githubusercontent.com/96287364/149178249-a0eac7a0-0646-4179-8e74-847ecf743e1a.gif)

**Comment by jsastre-dgtic** [comment]
ok, comprovat
