### ISSUE TITLE
Incloure component CAPTCHA a SISTRA2

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#467]
**C**ompletely **A**utomated **P**ublic **T**uring test to tell **C**omputers and **H**umans **A**part.
Possibilitar introduir components CAPTCHA al Gestor de Formularis intern a SISTRA2.

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

<img width="262" alt="image" src="https://user-images.githubusercontent.com/88820558/161039929-b587e75b-4530-4538-a475-1aece3dcd2c1.png">

Nuevo componente en el editor de formularios:
![image](https://user-images.githubusercontent.com/88820558/161040305-920a6e1e-3b47-47e9-9337-fb77d4f6d98c.png)

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161039968-3171b30a-466b-4900-9e3e-a0194628fda5.png">

Al añadir un captcha en un formulario, no se puede finalizar el formulario sin haber introducido el captcha correctamente. 
Lo mismo pasa si el captcha está en un formulario multipágina, no deja navegar a otras páginas si no se introduce correctamente el captcha.

**Comment by jsastre-dgtic** [comment]
1.- Al segon intent (el primer he fallat expressament):
![image](https://user-images.githubusercontent.com/18436867/161520794-b718e517-55b6-4bfc-8f16-a1a6be21f5ae.png)
No ho he pogut reproduir de nou... 

2.- En 2 casos m'ha passat que si pitjam damunt l'altaveu ens recita una lletra equivocada: en aquest cas diu d en comtes de c.
![image](https://user-images.githubusercontent.com/18436867/161520748-f801514f-de2b-4942-8159-46c479a6eba7.png)

**Comment by jsastre-dgtic** [comment]
S'ha canviat la veu però se sent molt de renou de fons.

**Comment by jsastre-dgtic** [comment]
és un tema de seguretat com el de les lletres embullades. Tancam
