### ISSUE TITLE
Descripció dels tràmits no es mostren a la taula

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#468]
Les descripcions no funcionen. Quan pico per introduir una descripció a l'input i guardar, la taula hauria de mostrar el text i no ho fa.

![#000](https://user-images.githubusercontent.com/83401259/148063046-147c1ee3-3c9d-447d-8643-1d03a8d84031.gif)

**Comment by jcerdar-indra** [comment]
- Se resuelve en el TAG 1.2.2_0 (49d5485)

**Comment by jcerdar-indra** [comment]
- Antes, al introducir 12 o menos caracteres no se mostraba la descripción. Se corrige para que se muestren siempre. 
![image](https://user-images.githubusercontent.com/96287364/149178513-7d687766-937d-4d14-8759-aab658310506.png)

**Comment by avillen-dgtic** [comment]
👌
