### ISSUE TITLE
Gestió de literals HTML

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#469]
No es respecten els estils que es defineixen al formulari.

- [ ] La llista ordenada no funciona 
- [ ] Tabulació a la llista no ordenada

![image](https://user-images.githubusercontent.com/83401259/148066808-ce8cbe98-e2c9-4afa-aa86-a851b365c469.png)
![image](https://user-images.githubusercontent.com/83401259/148067471-4347659c-f033-43a7-b835-f130570616b7.png)

**Comment by jcerdar-indra** [comment]
- Se soluciona en el TAG 1.2.2_1(807f0a5)

**Comment by jcerdar-indra** [comment]
- Se corrigen los estilos para mostrar correctamente las listas en los avisos de los formularios. 
![image](https://user-images.githubusercontent.com/96287364/151119695-7cd8637d-57f4-4579-b352-62d94cfbba79.png)
![image](https://user-images.githubusercontent.com/96287364/151119727-47025652-d00d-43c3-9a50-ee361bf00a04.png)

**Comment by avillen-dgtic** [comment]
👌
