### ISSUE TITLE
STG: Error de compilació de sistrages

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#47]
Després de compilar el login_ib surt un altre error de compilació de sistrages:

[INFO] sistramit .......................................... SUCCESS [  0.375 s]
[INFO] sistramit-rest-api ................................. SUCCESS [  0.904 s]
[INFO] sistramit-core-api ................................. SUCCESS [  1.950 s]
[INFO] sistramit-lib ...................................... SUCCESS [  0.047 s]
[INFO] sistramit-core ..................................... SUCCESS [ 33.366 s]
[INFO] sistramit-rest-ws .................................. SUCCESS [  2.247 s]
[INFO] sistramit-frontend ................................. SUCCESS [  8.597 s]
[INFO] sistramit-ear ...................................... SUCCESS [ 10.093 s]
[INFO] sistrages-core-api ................................. SUCCESS [  3.463 s]
[INFO] sistrages-lib ...................................... SUCCESS [  0.141 s]
[INFO] sistrages-core ..................................... SUCCESS [  7.254 s]
[INFO] sistrages-rest-ws .................................. SUCCESS [  2.885 s]
[INFO] sistrages-frontend ................................. FAILURE [01:00 min]
[INFO] sistrages-ear ...................................... SKIPPED
[INFO] sistrahelp ......................................... SKIPPED
[INFO] sistrahelp-core-api ................................ SKIPPED
[INFO] sistrahelp-lib ..................................... SKIPPED
[INFO] sistrahelp-core .................................... SKIPPED
[INFO] sistrahelp-rest-ws ................................. SKIPPED
[INFO] sistrahelp-frontend ................................ SKIPPED
[INFO] sistrahelp-ear 0.0.1-SNAPSHOT ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:42 min
[INFO] Finished at: 2018-10-10T12:09:03+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:
run (default) on project sistrages-frontend: An Ant BuildException has occured:
IOException in C:\CAI\GitHub\sistra2-sistra2-1.0\sistra2\sistrages\sistrages-fro
ntend\src\main\webapp\WEB-INF\sistrages-ac-frontend.xml - java.io.FileNotFoundEx
ception:C:\CAI\GitHub\sistra2-sistra2-1.0\sistra2\sistrages\sistrages-frontend\s
rc\main\webapp\WEB-INF\sistrages-ac-frontend.xml (Acceso denegado)
[ERROR] around Ant part ...<replace dir="src/main/webapp/WEB-INF">... @ 5:42 in
C:\CAI\GitHub\sistra2-sistra2-1.0\sistra2\sistrages\sistrages-frontend\target\an
trun\build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :sistrages-frontend

**Comment by rsanz-indra** [comment]
Si te fijas en la excepción que te da al compilar, parece que por alguna razón no se te ha bajado en tu local un fichero. Prueba a bajarte de nuevo el proyecto del Git

FileNotFoundException:C:\CAI\GitHub\sistra2-sistra2-1.0\sistra2\sistrages\sistrages-frontend\s 
rc\main\webapp\WEB-INF\sistrages-ac-frontend.xml (Acceso denegado)

**Comment by rsanz-indra** [comment]
Hemos probado a bajarnos de nuevo el proyecto del Github y nos baja el archivo correctamente.
Compila tanto desde el Eclipse como desde directamente con maven por consola (ver pantallazos).
Lo único raro acerca de este archivo es que en el momento de compilar se sustituyen tags para meter las versiones del git, pero eso es ya en la compilación no al bajarse el fichero del git.
Probad a hacerlo desde otro equipo a ver.
![maven-eclipse](https://user-images.githubusercontent.com/17456494/46818447-8cb5cc80-cd81-11e8-8066-6b7d32b79539.png)
![maven-consola](https://user-images.githubusercontent.com/17456494/46818543-d7374900-cd81-11e8-9122-e6f9ff76b2f5.png)

**Comment by jsastre-dgtic** [comment]
No acaba de ser molt clara la resposta, perquè sense cap problema des de la meva màquina m'he baixat i compilat els altres dos projectes (loginib i paymentib), i el misteri és que només falla aquest arxiu en concret (esborrat tot el directori git prèviament, vull dir, desde zero). Jo al manco no ho acabo de veure molt clar.

**Comment by rsanz-indra** [comment]
Sí, hay que averiguar que pasa. Es raro que no se te baje ese fichero ya que no parece haber ninguna razón para ello.
Por eso, os comentamos que probéis en otro equipo a ver.

**Comment by jsastre-dgtic** [comment]
Canviant el repositori maven del dir user de windows a un qualsevol no relacionat amb el perfil, m'ha anat bé. Tancam...
