### ISSUE TITLE
Detectar l'error de fitxer "no convertible a pdf" amb les validacions de versió

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#470]
En cas de marcar "convertir a PDF" i tenir un tipus de fitxer "no convertible" a la llista de fitxers permesos.

![image](https://user-images.githubusercontent.com/18436867/149078963-551cbf15-5ac5-43e0-8299-2f0599c81d4e.png)

![image](https://user-images.githubusercontent.com/18436867/149078991-628ba0a8-c1cc-4a8f-b2af-140cbaf3d27a.png)

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

Se detectan los archivos no convertibles a PDF al validar la versión:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161040875-1bbaec9f-322a-44e9-aa64-e6c08e82a4d9.png">

**Comment by jsastre-dgtic** [comment]
Detectam bug al no tractar ODT

**Comment by jcerdar-indra** [comment]
Se corrige en el tag 1.3.0_1 (https://github.com/GovernIB/sistra2/commit/c2080ce347b3f3dbee0cd9b203856589c04dd18d).
