### ISSUE TITLE
Diàleg no s'ajusta al contingut

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#471]
El diàleg no s'ajusta a la mida de text que hi ha, en aquest cas el llistat de correus electrònics. Cal fer-ho dinàmic per a cobrir totes les possibilitats.
![image](https://user-images.githubusercontent.com/83401259/149298731-f540c2a8-30bc-4666-ada3-a2ecbc6c62c4.png)

**Comment by jcerdar-indra** [comment]
- Se soluciona en el TAG 1.2.2_1(807f0a5)

**Comment by jcerdar-indra** [comment]
- En STG se controla que se añada un mail válido y no permite añadir más de 50 caracteres para que se vea correctamente en STT. 
![image](https://user-images.githubusercontent.com/96287364/151119787-ed894e48-f913-4588-8a6b-4481d8af3e4b.png)
![image](https://user-images.githubusercontent.com/96287364/151119876-32c22cf2-1a65-4ca2-aec0-ccb4aaec2cf3.png)

**Comment by avillen-dgtic** [comment]
Aquest INPUT té una funcionalitat de poder introduir llistes de correus separats pel caràcter ";"  per tant, la restricció de 50 caràcters no és una solució.

**Comment by avillen-dgtic** [comment]
👍 
Longitud de l'input canviat i css aplicat.

**Comment by jcerdar-indra** [comment]
Como os indicamos el viernes por teléfono, hemos realizado la prueba de poner un tamaño de anexo mayor en el trámite que en la propiedad global y en el asistente se muestra correctamente, mostrando el valor más limitante. 

Es por eso que nosotros añadiríamos la validación como no bloqueante, a modo de warning, ya que en el caso en que la propiedad global cambie a tamaños menores, no se bloquearían todos los trámites configurados con anexos con tamaños mayores, teniendo que ir a cambiar uno a uno el tamaño individual de cada anexo. Esto facilitaría el mantenimiento y por otra parte no tendría implicación alguna de cara al asistente ya que los ciudadanos siempre verán el tamaño indicado correctamente. 

Límite propiedad global: 
 
![image](https://user-images.githubusercontent.com/96287364/156990886-3dd5458d-c82e-4d5a-9a22-25edab945fb9.png)


Límite anexo en trámite: 
 
![image](https://user-images.githubusercontent.com/96287364/156990895-6c4c3eaf-9e6c-429a-9dbd-a731d4e9b941.png)

Vista en el asistente: 
 
![image](https://user-images.githubusercontent.com/96287364/156990904-5aa39711-3b7a-484c-987f-27378716a3cf.png)
