### ISSUE TITLE
Possibilitar la limitació del nombre de dígits als camps tipus telèfon

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#472]
Per a contemplar números estrangers podríem implementar la funció de manera similar al que tenim a S1

![image](https://user-images.githubusercontent.com/18436867/149510901-c38d9473-3ce5-4f97-bf94-f9fc1d14398f.png)

**Comment by jcerdar-indra** [comment]
- Se soluciona en el TAG 1.2.2_1(807f0a5)

**Comment by jcerdar-indra** [comment]
- Se ha limitado el número de caracteres que se pueden introducir en un campo de texto de tipo teléfono a 9. 
![image](https://user-images.githubusercontent.com/96287364/151120064-9a654cbc-c8c5-4b85-9ad6-c797ed1d289e.png)

**Comment by avillen-dgtic** [comment]
👌
