### ISSUE TITLE
Tractament dels números de telèfon estrangers

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#473]
Als camps del tipus telèfon del Gestor de Formularis de SISTRA2, no es contempla que el número de telèfon sigui estranger. Contemplar-ho.

**Comment by jparedes-indra** [comment]
Está en desarrollo, pero requiere más tiempo y se entregará en la siguiente versión, no en la 1.7.2.

**Comment by jsastre-dgtic** [comment]
La posposam per a la següent versió i la deixam a "no version yet"

**Comment by jparedes-indra** [comment]
Se puede crear un campo de texto de tipo teléfono internacional que luego es validado según el formato telefónico del país seleccionado.

- Check “Validación precisa” no marcado: Se valida si se introducen sólo números y la longitud (p.e. teléfonos nacionales hasta 9 dígitos).

- Check “Validación precisa” marcado: Se realizan validaciones por país (p.e. teléfonos nacionales empiezan por 9 o 6).

![image](https://github.com/user-attachments/assets/24c0a648-efd2-4397-a759-139b839d8307)
![image](https://github.com/user-attachments/assets/3cf5b1f9-2fb1-49da-aa65-347c6a8dc15e)

**Comment by jsastre-dgtic** [comment]
No ens surten banderetes i el núm per defecte 612 34 56 78 no ha de sortir al ciutadà

![Image](https://github.com/user-attachments/assets/8f0d05e3-bd7e-4288-9963-d04ba729ca53)

**Comment by jparedes-indra** [comment]
Ya se ven las banderas.
 
![imagen](https://github.com/user-attachments/assets/944725f0-2d82-4b8a-a1d1-08bb6840aab2)

**Comment by avillen-dgtic** [comment]
👍🏼
