### ISSUE TITLE
Comprovació de canvis en la configuració d'un domini remot abans de prémer el botó de "ping"

### ISSUE THREAD

**Issue by fjcalderon-dgtic** [GovernIB/sistra2#474]
Ahora mismo, cuando intentar probar un dominio remoto en SISTRA2, siempre aparece un mensaje de advertencia solicitándote que guardes los cambios. Ese mensaje sólo debe aparecer cuando se realice algún cambio en la configuración del dominio.

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).
 
Al no detectar cambios, se muestra el diálogo PING. Sin embargo si hay cambios en campos vinculantes (consulta BBDD, id, url, parámetros...), se muestra una pantalla de confirmación para guardar:

![474](https://user-images.githubusercontent.com/88820558/161041286-db368cdc-597d-4840-b1a8-f261ad2b82c0.gif)
