### ISSUE TITLE
Mostrar el número de resultats totals enlloc de mostrar el de pantalla a les recerques STH

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#476]
![image](https://user-images.githubusercontent.com/18436867/153138845-e0cd5475-d556-4620-a120-b8f8bcd638b5.png)

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

 Ahora se muestran todos los eventos en STH en vez de mostrar el de pantalla:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/88820558/161041803-850118e6-a020-4644-8447-3a6ac66720b1.png">

**Comment by jsastre-dgtic** [comment]
Pendents de la  #523

**Comment by avillen-dgtic** [comment]
👍
