### ISSUE TITLE
Eliminar qualsevol referència a Esmena o Lliurament presencial que hi hagi a STG

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#478]
![image](https://user-images.githubusercontent.com/18436867/153191338-4270f924-44c2-48a8-9c37-399a0c8503f3.png)
![image](https://user-images.githubusercontent.com/18436867/153191347-19e69381-e975-4c89-ba33-5c84b8c11fe8.png)

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

En este caso, se mantiene la lógica de estos checks y pestañas para cuando se realice la implementación de la issue #460 Permetre Esmena, a la que hace referencia el documento de estimación: 202202-SISTRA2-Subsanacion.pdf

Paso de pago: 

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161043589-ae524850-002f-46df-846e-e1ae27567af9.png">

Paso registrar: 

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161043618-b5e1917e-29da-4d46-bca8-bd322bd25aed.png">

Paso Anexar: 

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161043657-f75d029b-ffc0-4fb4-ab6f-e98bf1396726.png">

Configuración de entidad: 

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161043696-ce3d8c51-def7-4c98-88d7-0e03adbc5383.png">

**Comment by jsastre-dgtic** [comment]
Queden espais en blanc inexplicables a les passes de pagar i annexar

![image](https://user-images.githubusercontent.com/18436867/161523508-981bc727-149d-42a3-9eaa-ce750fff5938.png)


![image](https://user-images.githubusercontent.com/18436867/161523577-5c90a7fa-ea50-49ed-9f2e-6b35f5363816.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.0_1 (https://github.com/GovernIB/sistra2/commit/c2080ce347b3f3dbee0cd9b203856589c04dd18d).
![image](https://user-images.githubusercontent.com/96287364/164170425-7702ec7e-34d3-424d-baf2-b56d869922e3.png)
![image](https://user-images.githubusercontent.com/96287364/164170435-53a628f9-bb6d-47ef-97b6-877a7223c123.png)
