### ISSUE TITLE
Millorar l'editor de STG perquè permeti modificar el color de font

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#479]

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

<img width="337" alt="image" src="https://user-images.githubusercontent.com/88820558/161043976-562a916f-14bb-42f4-88b5-aca9285446eb.png">

![479](https://user-images.githubusercontent.com/88820558/161044081-c2c26b66-ed1a-43f2-9daa-86948216c5c2.gif)
