### ISSUE TITLE
A STH, el detall de l'error ha de ser en català

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#480]
A STH, el detall de l'error hauria d'estar també en català, atès que hauria de ser coherent amb l'idioma per defecte del GOIB. 

![image](https://user-images.githubusercontent.com/18436867/153581352-0bd38323-0d2f-4c54-93f8-f86a76ebc2b6.png)

**Comment by jcerdar-indra** [comment]
Como se comentó por teléfono, al ser textos internos de la plataforma, no pueden ser multiidioma. Se realizará la traducción de estos textos para que se muestre en catalán.

**Comment by jsastre-dgtic** [comment]
Pendents de la #523

**Comment by avillen-dgtic** [comment]
👍
