### ISSUE TITLE
Adaptar els ws perquè funcionin amb dominis resolts per SAP

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#481]

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.2.2_5 (4aac112).

**Comment by jcerdar-indra** [comment]
Para probar los cambios realizados y que funcione un dominio de consulta remota resuelto por SAP, se han creado unos tags nuevos para poder identificar los dominios de SISTRA1. 

Para referenciar a este tipo de dominios, en el campo de la URL, se han de añadir los siguientes tags para que se realice correctamente la petición SOAP: 

-	En dominios de SISTRA1 sin SAP: Hasta ahora en los dominios de Sistra1 se tenía que añadir el parámetro ‘?wsdl’ para que SISTRA2 detectara que era un dominio de SISTRA1. Esto se puede seguir utilizando pero ahora también se puede hacer referencia a estos dominios utilizando el tag ‘[SISTRA1]’ al inicio del campo URL. Un ejemplo utilizando un dominio de SISTRA1 sería el siguiente: 
o	 [SISTRA1][https://proves.caib.es/udit/integracion/sistra/services/SistraFacade](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fproves.caib.es%2Fudit%2Fintegracion%2Fsistra%2Fservices%2FSistraFacade&data=04%7C01%7Cjcerdar%40minsait.com%7C5339d013dca745b9398908d9f2beb28e%7C7808e00514894374954bd3b08f193920%7C0%7C0%7C637807723119796684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Pz4QSNRsUehy5O5yP73LCcO1tJVQn3jZEjpNHV%2BEVO8%3D&reserved=0)

-	En dominios de SISTRA1 con SAP: Además del tag ‘[SISTRA1]’, se tendrá que añadir otro tag para indicar el Soap Action requerido y poder realizar la petición correctamente. Este tag será el siguiente: ‘[SOAP-ACTION=<URL-SOAP>]’.
o	Por ejemplo, para el siguiente dominio remoto resuelto por SAP: ([https://geminis.caib.es:52001/sap/xi/engine?type=entry&amp;version=3.0&amp;Sender.Service=RHAPSODY_HERMES_SYSTRA&amp;Interface=urn:es:caib:sistra:ws:v2:model:SistraFacade^SI_Comunicaciones_Systra_SAP?wsdl](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgeminis.caib.es%3A52001%2Fsap%2Fxi%2Fengine%3Ftype%3Dentry%26version%3D3.0%26Sender.Service%3DRHAPSODY_HERMES_SYSTRA%26Interface%3Durn%3Aes%3Acaib%3Asistra%3Aws%3Av2%3Amodel%3ASistraFacade%255eSI_Comunicaciones_Systra_SAP%3Fwsdl&data=04%7C01%7Cjcerdar%40minsait.com%7C5339d013dca745b9398908d9f2beb28e%7C7808e00514894374954bd3b08f193920%7C0%7C0%7C637807723119796684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ks4y8MSY3mxwUaD4oEC3gYwyQyXBhrRpmcxbD6y6Y4U%3D&reserved=0)), al crearlo en SISTRAGES debería de rellenarse la URL de la siguiente forma: 
[SISTRA1][SOAP-ACTION=http://sap.com/xi/WebService/soap1.1][https://geminis.caib.es:52001/sap/xi/engine?type=entry&amp;version=3.0&amp;Sender.Service=RHAPSODY_HERMES_SYSTRA&amp;Interface=urn:es:caib:sistra:ws:v2:model:SistraFacade%5ESI_Comunicaciones_Systra_SAP](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgeminis.caib.es%3A52001%2Fsap%2Fxi%2Fengine%3Ftype%3Dentry%26version%3D3.0%26Sender.Service%3DRHAPSODY_HERMES_SYSTRA%26Interface%3Durn%3Aes%3Acaib%3Asistra%3Aws%3Av2%3Amodel%3ASistraFacade%255ESI_Comunicaciones_Systra_SAP&data=04%7C01%7Cjcerdar%40minsait.com%7C5339d013dca745b9398908d9f2beb28e%7C7808e00514894374954bd3b08f193920%7C0%7C0%7C637807723119796684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OmnREmJuAaZToHqgAXZzRT%2BHT75pJvyc7IOHeG0FqZQ%3D&reserved=0)

También hay que tener en cuenta la codificación de las URLs, sobre todo cuando se utilizan URLs complejas como las de los dominios resueltas por SAP. Estas URLs contienen caracteres especiales, como por ejemplo, en el caso de este dominio es el carácter ‘^’. Este carácter se tiene que sustituir por su codificación pertinente, que en este caso es ‘%5E’ (En el ejemplo que hemos añadido, si os fijáis, ya se ha realizado el cambio).

**Comment by jparedes-indra** [comment]
Para no referenciar a una aplicación concreta, se sustituye el TAG [SISTRA1] por [SOAP].

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161044639-3e6f6692-e46b-4e74-89d6-35d27ad6b0e8.png">

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161044662-04287736-148b-49f7-a777-abff0a3ba33e.png">

**Comment by jsastre-dgtic** [comment]
Intentam definir un domini contra SAP copiant el que posa l'ajuda:
[SISTRA1][SOAP-ACTION=http://sap.com/xi/WebService/soap1.1]https://geminis.caib.es:52001/sap/xi/engine?type=entry&version=3.0&Sender.Service=RHAPSODY_HERMES_SYSTRA&Interface=urn🇪🇸caib:sistra:ws:v2:model:SistraFacade%5ESI_Comunicaciones_Systra_SAP


![image](https://user-images.githubusercontent.com/18436867/161526655-0630831b-c150-46ec-bcda-12afc12f94bc.png)

**Comment by jsastre-dgtic** [comment]
URL:
[SOAP][SOAP-ACTION=http://sap.com/xi/WebService/soap1.1]https://geminis.caib.es:52001/sap/xi/engine?type=entry&version=3.0&Sender.Service=RHAPSODY_HERMES_SYSTRA&Interface=urn🇪🇸caib:sistra:ws:v2:model:SistraFacade%5ESI_Comunicaciones_Systra_SAP

ERR:
BD : DominioPluginException: Error conectándose a la url: Could not send Message.
