### ISSUE TITLE
Modificar textos STT segons recomanacions OAE

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#482]
Explicació detallada
Actualment, al punt 4 de l’explicació detallada que es veu a la primera passa **«Cal saber»** quan s’inicia un tràmit telemàtic s’indica el següent:

Català:
«4 Registrar el tràmit
Quan hagueu completat la sol·licitud, heu d'enviar-la. Una vegada enviada ja no podreu modificar les dades contingudes; per tant, en aquesta passa és important que reviseu les dades. En funció de les dades introduïdes, a més se vos podrà requerir perquè aporteu certa documentació presencialment una vegada finalitzat l'assistent.»
Castellà:
«4 Registrar el trámite
Cuando esté completada la solicitud, debe enviarla. Una vez enviada ya no podrá modificar sus datos; por tanto, en este paso es importante que revise los datos. En función de los datos introducidos, además, se le podrá requerir para que aporte cierta documentación presencialmente una vez finalizada su tramitación en este asistente.»

**Proposam el canvi de text següent (canviar enviar per registrar):**
Català:
«4 Registrar el tràmit
Quan hagueu completat la sol·licitud, heu de registrar-la. Una vegada registrada ja no podreu modificar les dades contingudes; per tant, en aquesta passa és important que reviseu les dades.»
Castellà:
«4 Registrar el trámite
Cuando esté completada la solicitud, debe registrarla. Una vez registrada ya no podrá modificar sus datos; por tanto, en este paso es importante que revise los datos.»

Consideram que el text següent **no és necessari** atès que només té sentit en els casos de pre-registre, de moment inexistents a SISTRA2.

«En funció de les dades introduïdes, a més se vos podrà requerir perquè aporteu certa documentació presencialment una vegada finalitzat l'assistent.»

-**Finestra emergent abans de registrar**

Actualment, abans de registrar un tràmit, apareix una finestra emergent amb el text següent:
«Atenció: a continuació registrarà la tramitació
A partir d’aquí, la sol·licitud quedarà guardada i ja no podreu modificar-la»
Proposam els següents texts (català/castellà):
«Atenció: a continuació registrarà el tràmit
Una vegada registrat el tràmit, ja no el podrà modificar»
«Atención: a continuación registrará el trámite
Una vez registrado el trámite, ya no podrá modificarlo»

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161045404-93873df9-0eab-4135-a7ba-7b2a8a58ee60.png">

<img width="323" alt="image" src="https://user-images.githubusercontent.com/88820558/161045415-d639a4e1-f45c-4707-a4db-1adb7ac45cb8.png">
