### ISSUE TITLE
Casella de verificació a «Informació sobre la protecció de dades»

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#483]
Si es marca la casella de «He llegit i accept la informació sobre protecció de dades» i posteriorment es signa el formulari, quan es torna a visualitzar la pantalla de la passa 4-Registrar, ens trobam que la casella de «He llegit i accept...» que ja havíem marcat, s’ha desmarcat
Proposam que es guardi el valor d’aquesta casella abans de signar el formulari i així en tornar a la mateixa pantalla no s’haurà desmarcat.
![image](https://user-images.githubusercontent.com/18436867/154017630-b2e536f1-9db7-41f9-aa35-116ad8d959d1.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.0_1 (https://github.com/GovernIB/sistra2/commit/c2080ce347b3f3dbee0cd9b203856589c04dd18d).

**Comment by jcerdar-indra** [comment]
![#483](https://user-images.githubusercontent.com/96287364/164172928-0aab343b-b4db-4853-86fb-985e9192dfba.gif)

**Comment by avillen-dgtic** [comment]
👍
