### ISSUE TITLE
Millorar el botó Signar (no està prou ressaltat)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#484]
En aquesta pantalla signar el formulari és necessari per poder continuar, però consideram que el botó Signar no està prou ressaltat i el ciutadà potser no sap què fer.

Suggeriment:
Es podria posar una capsa informativa addicional just devora el botó “Anterior” tal com es mostra en aquesta captura.

![image](https://user-images.githubusercontent.com/18436867/154040782-7796ecb0-9132-4514-8247-4a6c2eb345a3.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.0_1 (https://github.com/GovernIB/sistra2/commit/c2080ce347b3f3dbee0cd9b203856589c04dd18d).

**Comment by jcerdar-indra** [comment]
![image](https://user-images.githubusercontent.com/96287364/164173070-c177124d-37c0-4e25-b47f-f026dbeebccc.png)

**Comment by avillen-dgtic** [comment]
👍
