### ISSUE TITLE
Comportament erroni amb les opcions damunt una versió d'un tràmit

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#488]
Depenent del perfil amb el qual es troba l'usuari, tenim dos comportaments diferents quan parlem de les opcions que hi tenim en seleccionar una versió d'un tràmit.
**Al perfil d'administrador** 
si anem directament a seleccionar una versió d'un tràmit, surt l'opció de "més", també si anem navegant pitjant primer a l'àrea i després el tràmit.

**Al perfil de desenvolupador** 
si anem directament a seleccionar una versió d'un tràmit, NO surt l'opció de "més", però si anem navegant pitjant primer a l'àrea i en acabat el tràmit sí que surt.

![#000](https://user-images.githubusercontent.com/83401259/155113037-d42ea7b7-7223-4b6d-b419-dcb5388cc6e3.gif)

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

**Comment by avillen-dgtic** [comment]
👍
