### ISSUE TITLE
Aplicar correccions lingüístiques a la plataforma

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#489]

**Comment by jparedes-indra** [comment]
El literal "Seu Electrònica" ha de modificarse en el procedimiento asociado en Rolsac.

![imagen](https://user-images.githubusercontent.com/67064375/159432682-bbb74edb-d1ae-449e-b37e-467fea7ec15a.png)

**Comment by jparedes-indra** [comment]
El cambio propuesto para la Instancia Genérica, en el campo "DESTINACIÓ":...
*Conselleria EBAP maig 21
Convé canviar el nom per:
Escola Balear d’Administració Pública (EBAP)

...se ha de realizar en Rolsac, en el nombre de la Unidad Administrativa, ya que dicho campo se alimenta de un dominio que consulta esa BBDD.

![imagen](https://user-images.githubusercontent.com/67064375/159435669-4e49ed47-4727-46eb-a172-f218ac8daa4e.png)

![imagen](https://user-images.githubusercontent.com/67064375/159436266-dceaf198-b151-4db5-bd7b-a95952f84ba3.png)

**Comment by jparedes-indra** [comment]
El cambio solicitado en 16. Instància genèrica. Signar. Informació sobre la protecció de dades:

*De conformitat amb el reglament (UE)
De conformitat amb el Reglament (UE)

Se tiene que modificar en las properties de Rolsac, en:

es.caib.rolsac.lopd.cabecera.ca=De conformitat amb el reglament (UE) 2016/679 i la legistaci\u00F3 vigente en mat\u00E8ria de protecci\u00F3 de dades, s\u2019informa del tractament de les dades personales que cont\u00E9 aquest tr\u00E0mit
es.caib.rolsac.lopd.cabecera.es=De conformidad con el reglamento (UE) 2016/679 y la legistaci\u00F3n vigente en materia de protecci\u00F3n de datos, se informa del tratamiento de los datos personales que contiene este tr\u00E1mite

![imagen](https://user-images.githubusercontent.com/67064375/159443854-5e1928a6-3506-4765-a86a-2495237cab51.png)

**Comment by jparedes-indra** [comment]
El cambio solicitado en 25 a 29. Instància genèrica. Valoració opinió:

*Funcionament Complicat
Funcionament complicat

Se ha de modificar (ya está hecho) en STG, Configuración entidad:

![imagen](https://user-images.githubusercontent.com/67064375/159445440-fa255322-2743-4458-a3e2-6660578f59ed.png)

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

**Comment by jparedes-indra** [comment]
En el título del formulario no es posible añadir el apóstrofe ', debido a las restricciones de REGWEB3.

![imagen](https://user-images.githubusercontent.com/67064375/164064233-d99bec73-aea2-4ceb-95a4-d154bc89e09f.png)

**Comment by jsastre-dgtic** [comment]
Quina implicació tendria passar a RW3 l'Identificador enlloc de la Descripció ?

![image](https://user-images.githubusercontent.com/18436867/164445899-85a66032-39dd-4169-a8fd-618752d45a8e.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.0_2 (https://github.com/GovernIB/sistra2/commit/a8ddb58e46b00e925f887b44130e3a3380ea3da4).

Se permite añadir acentos en las descripciones de documentos en SISTRA2. Para el envío a RW3, SISTRA2 controla que no se envíen caracteres no permitidos internamente.
