### ISSUE TITLE
Alinear els límits dels camps que es passen de SISTRA2 a REGWEB3

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#490]
S'han detectats problemes relacionats amb aquestes limitacions quan S2 passa a RW3 mides massa llargues que RW3 no admet.

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

**Comment by avillen-dgtic** [comment]
Pendent de #523
