### ISSUE TITLE
Incongruència quan es limiten les mides d'annexos

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#491]
Hi ha una incongruència a l'hora de crear els tràmits amb les configuracions de l'entitat. Ens hem trobat que hi tenim una limitació a la plataforma, de per exemple 20 MB, als annexos que després en l'àmbit de tràmit, els desenvolupadors poden introduir una mida superior.

Per tant, la proposta és crear un diàleg a STG d'error quan s'introdueix una mida superior al que tenim configurat a la plataforma. És a dir, tenir en compte aquesta variable.
![image](https://user-images.githubusercontent.com/83401259/155694716-2968727a-2787-4de1-94be-4219f72e3b31.png)

Aquesta tasca implica el següent, 

- [ ] Crear el diàleg quan es detecta que el valor introduït per l'usuari és superior al configurat "Propietats de configuració global"
- [ ] Comprovar aquesta condició quan es valida el tràmit. (per aquells tràmits que ja el tenen configurat)

**Comment by jcerdar-indra** [comment]
Como os indicamos el viernes por teléfono, hemos realizado la prueba de poner un tamaño de anexo mayor en el trámite que en la propiedad global y en el asistente se muestra correctamente, mostrando el valor más limitante. 

Es por eso que nosotros añadiríamos la validación como no bloqueante, a modo de warning, ya que en el caso en que la propiedad global cambie a tamaños menores, no se bloquearían todos los trámites configurados con anexos con tamaños mayores, teniendo que ir a cambiar uno a uno el tamaño individual de cada anexo. Esto facilitaría el mantenimiento y por otra parte no tendría implicación alguna de cara al asistente ya que los ciudadanos siempre verán el tamaño indicado correctamente. 

Límite propiedad global: 
 
![image](https://user-images.githubusercontent.com/96287364/156990886-3dd5458d-c82e-4d5a-9a22-25edab945fb9.png)


Límite anexo en trámite: 
 
![image](https://user-images.githubusercontent.com/96287364/156990895-6c4c3eaf-9e6c-429a-9dbd-a731d4e9b941.png)

Vista en el asistente: 
 
![image](https://user-images.githubusercontent.com/96287364/156990904-5aa39711-3b7a-484c-987f-27378716a3cf.png)

**Comment by avillen-dgtic** [comment]
👍
