### ISSUE TITLE
Controlar annexos que no arriben

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#492]
Quan un annex s'envia i no arriba al servidor, es genera un NULL. 
S'ha de controlar aquesta casuística.

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

Ahora se controla en caso de que el fichero no llegue al servidor

<img width="385" alt="image" src="https://user-images.githubusercontent.com/88820558/161047732-ac9b3a0d-45b0-41cf-8111-a9da9a339f93.png">

**Comment by avillen-dgtic** [comment]
👍
