### ISSUE TITLE
Afegir funcionalitat a l'usuari per saber quins rols s'estan contemplant.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#493]
![image](https://user-images.githubusercontent.com/18436867/155698249-80681716-e52e-4c9f-8aef-8858f3b0e6f4.png)

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

<img width="270" alt="image" src="https://user-images.githubusercontent.com/88820558/161047921-5c755dd3-acdf-43d7-b872-ef658ef71645.png">

<img width="423" alt="image" src="https://user-images.githubusercontent.com/88820558/161047938-bb431e4b-557e-43ad-a2fa-452fbe0ae7ce.png">

**Comment by avillen-dgtic** [comment]
👍
