### ISSUE TITLE
Habilitar al la pantalla de ctrl d'accés una nova opció de check que digui "mostrar info de cada passa"

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#494]
Es proposa al Control d'accés habilitar una nova opció de check que digui "mostrar info de cada passa" que ens permeti més granularitat per a un tràmit concret que vegem que dóna problemes i no quedi clar el motiu.

![image](https://user-images.githubusercontent.com/18436867/155698785-6532e524-27f2-4c34-8857-821aaf21b4ac.png)

**Comment by avillen-dgtic** [comment]
Aquesta  funcionalitat hauria de poder creuar les dades entre STG i STT, és a dir que puguem tenir les traces d'una àrea a un mateix escenari. Com a exemple tenir a STH amb un filtre per àrea, per usuari.

**Comment by jcerdar-indra** [comment]
En caso de marcar el check 'Habilitar debug' en un trámite, se generan eventos de debug de flujo que permiten conocer en detalle los pasos que realiza un ciudadano: 
![image](https://user-images.githubusercontent.com/96287364/177800007-9eca331f-e754-4365-922c-b678784633fc.png)
