### ISSUE TITLE
Millorar la Gestió d'àrees amb una adreça de correu associada

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#495]
Introduir un nou camp associat a l'àrea (possibilitar diferents correus separats per ;, com és habitual.

![image](https://user-images.githubusercontent.com/18436867/156361415-fdfb01c2-839d-465f-a608-fabb8026e45e.png)

Les incidències del Formulari s'hauran de direccionar directament al correu associat a cada àrea

![image](https://user-images.githubusercontent.com/18436867/156361247-85f7ce71-862e-4a1d-b9e1-12798f73406d.png)

**Comment by jsastre-dgtic** [comment]
S'afegirà un camp al diàleg de gestió d'àrea perquè es puguin afegir correus electrònics específics a cada àrea 

![image](https://user-images.githubusercontent.com/18436867/157011357-c7a69fbe-033e-4c9e-af55-b2289382d708.png)

Des de Configuració d'entitat -> Ajuda -> Formulari de contacte, per mantenir la funcionalitat anterior i incorporar aquests nous correus, en crear un tipus d'incidència, al camp Tipus destinatari es mostrarà un llistat de checks on es permetrà a l'administrador d'entitat marcar els que vulgui per a l'enviament del formulari de contacte

- si es marca el check llista de correus electrònics, es mostra el camp per introduir els correus electrònics.
![image](https://user-images.githubusercontent.com/18436867/157011486-2df16db7-506d-4a15-8983-1bea9d73c3a2.png)

![image](https://user-images.githubusercontent.com/18436867/157011571-4be432e6-1246-4ced-a0f1-f38c59d2b267.png)

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

<img width="268" alt="image" src="https://user-images.githubusercontent.com/88820558/161048222-f4b25f00-04b3-4105-b68e-8c4e95700d8b.png">

![image](https://user-images.githubusercontent.com/88820558/161048375-8aabb704-8d98-4810-8c1a-b9e6fee37cb2.png)

**Comment by jsastre-dgtic** [comment]
ok
![image](https://user-images.githubusercontent.com/18436867/164388827-e4ebb7bd-ead9-450e-be46-7cdb169e4b0d.png)
