### ISSUE TITLE
Fer accessible la config. Autenticació des de la pantalla Dominis d'Àrea/Entitat (i a la inversa)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#499]
Afegir un desplegable semblant al que hi ha ara quan se selecciona una àrea. D'aquesta manera es podria accedir des de qualsevol finestra a qualsevol configuració de l'àrea i no caldria anar a l'àrea per accedir a la pantalla desitjada.

Ídem a les pantalles: Dominis Entitat i la futura Conf. Autenticacions d'Entitat 

![image](https://user-images.githubusercontent.com/18436867/157004691-70559e6b-0ec0-41c5-beb9-11f6dd4dee5c.png)

![image](https://user-images.githubusercontent.com/18436867/157004890-307e2dce-dca2-4e91-b08a-e57283f10f3b.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.1_0 ( https://github.com/GovernIB/sistra2/commit/b1380dff3750d3222705cb0d4fbbf980f0a0dfea)

**Comment by jcerdar-indra** [comment]
Se añade desplegable para hacer accesibles las opciones de área desde las diferentes opciones: 
![image](https://user-images.githubusercontent.com/96287364/177782607-12489697-bca3-478c-adb8-0b2d485b8b64.png)

**Comment by avillen-dgtic** [comment]
👍
