### ISSUE TITLE
STT: Integració plugin registre

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#50]
Definició i implementació del plugin RW3

**Comment by jsastre-dgtic** [comment]
- Finalizar implementación plugin Regweb3. Se deberá ampliar el alcance para tener en cuenta los problemas de rendimiento gestionados en Sistra1 (habrá que implementar nueva función para recuperar descripción oficina e implementar caché).

**Comment by jsastre-dgtic** [comment]
COMPROVAT... TANCAM

**Comment by rsanz-indra** [comment]
Se concatena codigo - descripción

**Comment by jsastre-dgtic** [comment]
Cal corregir el literal.
![image](https://user-images.githubusercontent.com/18436867/51243709-7ff9d380-1983-11e9-97fd-81bffc7b354d.png)

**Comment by jsastre-dgtic** [comment]
Passam a #80
