### ISSUE TITLE
check debug de la Pantalla Control Accés

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#501]
Fer editable només per administradors d'entitat el check debug a PRE i a PRO.
A DEV queda com està.

**Comment by jparedes-indra** [comment]
Entonces, tal como se ha confirmado por correo:
- En DEV no se modifica nada. 
- En PRE y PRO: 
   -- los administradores de entidad podrán modificar el check Debug 
   -- los administradores de entidad y área podrán tocar el resto de elementos de la pantalla de control de acceso.

**Comment by jcerdar-indra** [comment]
En PRE y PRO solo los administradores de entidad puede activar/desactivar el check
![image](https://user-images.githubusercontent.com/96287364/177786109-5680d0e1-524a-44f1-aa51-b57536c81e5b.png)

**Comment by avillen-dgtic** [comment]
👍
