### ISSUE TITLE
Problema detectat amb el focus

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#502]
En general la plataforma STG té un problema amb agafar el focus del qual visualment ja ens informa que el té. 
Quan acabem una acció, com per exemple, importar versió, queda marcat en groc la versió, però fins que no cliquem allà, no ens apareix el menú associat a la versió. 
Amb altres operacions passa el mateix...

**Comment by jcerdar-indra** [comment]
![#502](https://user-images.githubusercontent.com/96287364/177786239-6b4a1370-e0f9-49f7-a239-76784cc64367.gif)

**Comment by avillen-dgtic** [comment]
👍
