### ISSUE TITLE
centralitzar el control dels errors de STG i assegurar que es mostrin al log.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#503]
PING des de Sistra2 a la BD de ROLSAC (Domini consultaBD) dóna error Null Pointer si la query és buida, però no surt al log.

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

**Comment by avillen-dgtic** [comment]
Apareixen als logs
