### ISSUE TITLE
Tipo documento ENI --> Tipus document ENI

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#504]
Cal normalitzar aquest literal a STG:

![image](https://user-images.githubusercontent.com/18436867/157841519-f542fcc0-13bc-4b16-b005-e4447207df89.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.0_1 (https://github.com/GovernIB/sistra2/commit/c2080ce347b3f3dbee0cd9b203856589c04dd18d).

**Comment by jcerdar-indra** [comment]
![image](https://user-images.githubusercontent.com/96287364/164175087-046c8539-ce4c-45bc-8484-ba3d28053cc5.png)

**Comment by avillen-dgtic** [comment]
👍
