### ISSUE TITLE
Canviar a text tots els camps que ara són text àrea i no sigui necessari que ho siguin

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#505]

**Comment by jcerdar-indra** [comment]
Se modificará la ventana de gestión de literales para que en vez de multilínea, sea de sólo una línea (cambiar textarea por input) para evitar la introducción de ciertos caracteres ('\n', '\r', '\t').

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Finalmente se opta por mantener el aspecto en el gestor de literales, pero se controla que no puedan guardarse textos que contengan caracteres no válidos.

![image](https://user-images.githubusercontent.com/67064375/206704753-73c3634e-3d82-42ad-8b4d-fb20f50f990c.png)

**Comment by jsastre-dgtic** [comment]
ok, comprovat
