### ISSUE TITLE
Evitar l'enviament de \n \t a RW3

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#506]
Controlar tot el que surti de l'editor Tiny per a que no enviï caràcters estranys.
Cal eliminar de l'enviament a RW3 els següents caràcters del camp tituloDoc: 
Cometes dobles: " 
\t 
\n

**Comment by jsastre-dgtic** [comment]
Cometes simples i dobles també poden dur mal de caps a Arxiu, vos concretam exactament...

**Comment by jcerdar-indra** [comment]
Se incorporará el carácter '\' a los caracteres no permitidos para el envío a RW3.

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

 Se filtran los carácteres \n \t ‘  “

![506](https://user-images.githubusercontent.com/88820558/161049141-e08199e3-e560-4149-aa2e-540f20072837.gif)

**Comment by avillen-dgtic** [comment]
👍
