### ISSUE TITLE
Amb Chrome no funciona check "Visualitzar totes les àrees"

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#507]
Amb perfil desenvolupador

![image](https://user-images.githubusercontent.com/18436867/157869631-a32670a2-722d-4462-bb23-88765f6c28e6.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.1_0 ( https://github.com/GovernIB/sistra2/commit/b1380dff3750d3222705cb0d4fbbf980f0a0dfea)

**Comment by jcerdar-indra** [comment]
![#507](https://user-images.githubusercontent.com/96287364/177786366-3c645a1f-c032-4628-871a-b69559f16bcf.gif)

**Comment by avillen-dgtic** [comment]
El botó de visualització de totes les àrees ha desaparegut.
![image](https://user-images.githubusercontent.com/83401259/178927538-bf05c42f-c1eb-4c45-81c0-88de68bf31ff.png)

**Comment by jparedes-indra** [comment]
Cuando se está con el rol de Administrador de Entidad, ya se ven tosas las áreas, por lo que no tiene sentid que aparezca ese che. 

Sí aparece como administrador de área o desarrollador, ya que puedes ver el área sobre el que se tiene permisos y el resto si se marca ese check inferior.

![imagen](https://user-images.githubusercontent.com/67064375/178930836-53f8791c-6535-450c-87c5-4cbbf36ec978.png)

**Comment by avillen-dgtic** [comment]
👍
