### ISSUE TITLE
No es veuen botons per a veure tots els valors en la finestra "Ping de domini"

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#508]
Continuem amb problemes de mides de finestres i com es mostren les dades als components.

![image](https://user-images.githubusercontent.com/83401259/158173908-70d15f29-ceb2-47dc-bbe6-a10f4db2da5c.png)

Desapareix la paginació
![image](https://user-images.githubusercontent.com/83401259/158173944-58c13665-4c34-4f20-920f-22a818a54284.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.0_1 (https://github.com/GovernIB/sistra2/commit/c2080ce347b3f3dbee0cd9b203856589c04dd18d). 
![image](https://user-images.githubusercontent.com/96287364/164175314-8f00b79b-34ad-49f9-a63a-5972ab36437c.png)
