### ISSUE TITLE
 La pantalla de GFE no pot ser editada per un Administrador d'Àrea

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#509]

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

![509](https://user-images.githubusercontent.com/88820558/161049623-0b909b48-a62a-40ec-8104-cb3f177f63bd.gif)

**Comment by avillen-dgtic** [comment]
👍
