### ISSUE TITLE
Mostrar quins Dominis estiren d'una Font de Dades en concret

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#511]
No tenim informació de quins Dominis estiren d'una Font de Dades en concret, estaria bé tenir-ho. 

Faltaria això: 
![image](https://user-images.githubusercontent.com/18436867/159430433-f43b7818-f5a7-4224-89ef-d49614a268ea.png)
![image](https://user-images.githubusercontent.com/18436867/159430450-ae73cb3c-c1a4-42c1-857a-96fbffca67e3.png)

![image](https://user-images.githubusercontent.com/18436867/159430472-6385f32c-aa33-4aca-873a-63af9ead4ad6.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.0_1 (https://github.com/GovernIB/sistra2/commit/c2080ce347b3f3dbee0cd9b203856589c04dd18d). 
![image](https://user-images.githubusercontent.com/96287364/164175570-7f79585c-7224-49a4-b421-f446208b6e1e.png)
![image](https://user-images.githubusercontent.com/96287364/164175582-4b8d736d-35dd-4252-b7ec-251e200369b8.png)

**Comment by avillen-dgtic** [comment]
👍
