### ISSUE TITLE
La funció de mostrar tràmits associats ha de mostrar el codi i s'ha de poder copiar

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#512]
Quan accedim als tràmits associats hauríem de poder copiar el codi de tràmit, però pareix que ens mostra la descripció i no el codi: 

![image](https://user-images.githubusercontent.com/18436867/159430660-2b835353-73a1-49b9-a415-c4505f92d7f4.png)
![image](https://user-images.githubusercontent.com/18436867/159430676-9a1d017a-2ea7-4f13-900e-f107dec50a7d.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.0_1 (https://github.com/GovernIB/sistra2/commit/c2080ce347b3f3dbee0cd9b203856589c04dd18d). 
![image](https://user-images.githubusercontent.com/96287364/164175699-0b354712-62ba-4f84-a2cc-7d3d6d6189cd.png)

**Comment by avillen-dgtic** [comment]
👍
