### ISSUE TITLE
Pantalla de versions de tràmit. Canviar la condició perquè mostri el que diu: darrera modificació.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#513]
Modificar un desplegable del formulari de TEST-REGISTRE v13 i no es reflecteix:
![image](https://user-images.githubusercontent.com/18436867/159430999-e0c4ba5e-f672-4880-aa29-90956f8084b3.png)
![image](https://user-images.githubusercontent.com/18436867/159431033-ac9f30af-0f56-4e56-bc66-6d37dffbe4a2.png)
Actualment la data de darrera modificació s'assigna un cop es realitza el desbloqueig del tràmit.Mentre es té el tràmit bloquejat per l'usuari, aquesta data no canvia. 
Això confon perquè la columna posa darrera modificació, no "darrer desbloqueig". Canviar-ho per a que mostri el que diu: darrera modificació.

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.1_0 ( https://github.com/GovernIB/sistra2/commit/b1380dff3750d3222705cb0d4fbbf980f0a0dfea)

**Comment by jcerdar-indra** [comment]
![#513](https://user-images.githubusercontent.com/96287364/177791217-6a14cff7-cd5e-4e2c-a323-ff132520dc21.gif)

**Comment by avillen-dgtic** [comment]
👍
