### ISSUE TITLE
Error en processar quaderns de càrrega

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#514]
A l'hora de processar el quadern de càrrega, es genera un 'null point' quan s'annexa.
Cal testejar,  per a una nova àrea amb un rol d'administrador d'àrea, fer annexos de quaderns.

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

Tal y como se acordó el campo "descripción " del área no se tendrá en cuenta a la hora de procesar cuadernos de carga.

**Comment by avillen-dgtic** [comment]
Ajornat fins tenir un usuari no administrador d'entitat

**Comment by avillen-dgtic** [comment]
Ho comprovarem PRE, quan es processen els quaderns.

**Comment by avillen-dgtic** [comment]
Comprovat i va bé 👍
