### ISSUE TITLE
Error a l'hora d'eliminar una àrea

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#515]
Després de crear una àrea i crear el rol associat a aquella àrea, hem pitjat el botó d'eliminar i ens ha botat aquesta excepció. Aquesta falla passa a tots els entorns. 
S'ha comprovat que si l'àrea té un rol associat genera aquest error. En canvi, si eliminem el rol podem eliminar l'àrea.
![image](https://user-images.githubusercontent.com/83401259/159470501-e81d8b0c-6778-4a4b-a0a7-bbaa48f5836b.png)
![image](https://user-images.githubusercontent.com/83401259/159470259-29786899-ee88-4374-a01b-29e3a36e5f7f.png)

**Comment by avillen-dgtic** [comment]
SISTRAGES 1.2.2[(2807dbc)](https://github.com/GovernIB/sistra2/commit/2807dbc)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.1_0 ( https://github.com/GovernIB/sistra2/commit/b1380dff3750d3222705cb0d4fbbf980f0a0dfea)

**Comment by jcerdar-indra** [comment]
Área de prueba: 
![image](https://user-images.githubusercontent.com/96287364/177786521-1240a038-5a67-4364-b0b0-6435cdac8b9e.png)
Se crea rol asociado al área: 
![image](https://user-images.githubusercontent.com/96287364/177786566-b4aee602-f409-4387-a813-7ac0a95aa57e.png)
Se puede borrar el área y se borra el rol: 
![image](https://user-images.githubusercontent.com/96287364/177786610-c5f1e0a8-b91b-46a6-ab03-6faff29686d7.png)

**Comment by avillen-dgtic** [comment]
👍
