### ISSUE TITLE
L'API externa de SISTRAMIT no recupera correctament els tràmits que tenen una data de caducitat associada

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#516]
Tant si la tenim definida a través de l'script de personalització com si ve informada de rolsac

![image](https://user-images.githubusercontent.com/18436867/160090887-3a562f26-2fac-4d90-a75d-84ec63f3e220.png)

![image](https://user-images.githubusercontent.com/18436867/160090913-b8288ced-c892-465e-a2f6-fba4104cb43b.png)

**Comment by avillen-dgtic** [comment]
No podem comprovar-ho fins no tenir STH aixecat.

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/164615292-28705490-d3da-41dd-8262-60da2e69aacf.png)

![image](https://user-images.githubusercontent.com/18436867/164615554-3e97c779-a554-41fb-9222-8d7945b30df7.png)
