### ISSUE TITLE
Possibilitar exportació a excel dels warnings de migració de tràmits

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#517]
![image](https://user-images.githubusercontent.com/18436867/160354753-24a29136-98ed-4a7c-a45f-7a6ef217473c.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.0_1 (https://github.com/GovernIB/sistra2/commit/c2080ce347b3f3dbee0cd9b203856589c04dd18d). 
![#517](https://user-images.githubusercontent.com/96287364/164175779-ce9ba7c3-9425-4523-9d0e-059511d584b7.gif)

**Comment by avillen-dgtic** [comment]
👍
