### ISSUE TITLE
Missatge d'error sense format

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#519]
Quan fem una consulta a ROLSAC, per la issue #503 ens apareix un missatge sense format.

![image](https://user-images.githubusercontent.com/83401259/161237421-f380000e-2848-48dd-8562-f342f7373020.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.1_0 ( https://github.com/GovernIB/sistra2/commit/b1380dff3750d3222705cb0d4fbbf980f0a0dfea)

**Comment by jcerdar-indra** [comment]
Se pasa la excepción a la ventana emergente y el growl es un mensaje informativo: 
Dom BBDD
![image](https://user-images.githubusercontent.com/96287364/177787087-bcf10064-22cd-4ec5-bab7-bd363d249fc8.png)
Dom Consulta Rem
![image](https://user-images.githubusercontent.com/96287364/177787110-1c9382d6-f94d-4932-8fde-3c8a784941ce.png)

**Comment by avillen-dgtic** [comment]
👍
