### ISSUE TITLE
STT: Workflow de tramitació

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#52]
- pas pagar i disseny integració frontal per a execució formularis.

**Comment by rsanz-indra** [comment]
Se ha finalizado el desarrollo del workflow hasta paso pagar pero no se ha podido completar el diseño de como integrar con el sistema de formularios (se pospondrá esta parte en nueva entrada diferenciada  para próximo ciclo).

Para poder probar los pagos hay que tener en cuenta:

- Definir plugin de pago a nivel de entidad: para definir el plugin de pago de PaymentIB hay que definir el siguiente plugin adaptando url y pwd a la instalación correspondiente:

> Clasname: es.caib.sistra2.commons.plugins.pago.paymentib.ComponentePagoPaymentIBPlugin
Descripción: Plugin pagos PaymentIB
Propiedades:
	url = http://_host:port_/paymentib/api/rest/v1
	usr = api-pib
	pwd = _pwd api-pib_
	idAplicacion = SISTRA2

- Definir pago con script de pago para indicar datos del pago: se puede definir este script

> DATOS_PAGO.setPasarela('ATIB'); 
> DATOS_PAGO.setDetallePago('046','Concepto x','1.21.1.2.1.4', 1);

- Para probar pago presencial y electrónico hay que tener en cuenta las reglas de entrega presencial (las que se indicaron originalmente en el análisis, no las últimas que se han definido): si hay algún anexo presencial se permitirán pagos presenciales/electrónicos según configuración del pago y si no hay ningún anexo presencial solo se permitirá pago electrónico.

**Comment by jsastre-dgtic** [comment]
Observacions:
1.- Tenim definit un pagament opcional
![image](https://user-images.githubusercontent.com/18436867/48550541-5a911080-e8d3-11e8-9ff7-90704f7d14e7.png)
i accedint a http://sdevapplin5.caib.es:48080/sistramitfront/asistente/iniciarTramite.html?tramite=SA001&version=1&idioma=ca&idTramiteCatalogo=3273454, no ens diu que és opcional i a més falla a l'intentar pagar mock:

![image](https://user-images.githubusercontent.com/18436867/48550639-9b892500-e8d3-11e8-8804-e63c3ea2568a.png)

L'API respon:
![image](https://user-images.githubusercontent.com/18436867/48550703-ca070000-e8d3-11e8-802e-fa7a1b9844c4.png)
 I ho tenim configurat segons instruccions:
![image](https://user-images.githubusercontent.com/18436867/48550755-ea36bf00-e8d3-11e8-9d85-c1aa06757410.png)

**Comment by jsastre-dgtic** [comment]
Llençat alter:
/* 22/10/2018 - 26/10/2018 */ 
alter table STT_PAGEXT drop column PAE_NIVAUT; 
  
Ja funciona el pagament, però cal fer unes observacions:
1.- On diu Verificar hauria de dir Validar (o a la inversa). "á" surt "?"
![image](https://user-images.githubusercontent.com/18436867/48611713-20814680-e987-11e8-8f3e-debaf4efba43.png)
2.- En cas de que l'usuari descarti el pagament però s'hagi pagat (no segueixi les instruccions) tenim pensat com resoldre la incidència?
![image](https://user-images.githubusercontent.com/18436867/48611804-4dcdf480-e987-11e8-9ca8-fd0eff25708a.png)

**Comment by jsastre-dgtic** [comment]
2.- No té molt de sentit dir "Se ha verificado que el pago no se ha realizado." i després "Si tiene constancia de que ha realizado el pago..." 
**Proposta de canvi:**

Atención
No se ha podido verificar que el pago se ha realizado.
Para realizar el pago de nuevo pulse en Descartar pago e inicie de nuevo el pago. 
Si tiene constancia de que ha realizado el pago es importante que no descarte el pago, si no consigue verificar el pago póngase en contacto con nuestro soporte técnico

**Comment by jsastre-dgtic** [comment]
Al pas de pagament he definit un segon pagament opcional com a MOCK tal i com heu indicat i quan pitjam damunt electrònic per pagar, surt error. Ho podeu comprovar?
![image](https://user-images.githubusercontent.com/18436867/48941643-b2a3c480-ef1c-11e8-938f-350b2ac24b2a.png)

![image](https://user-images.githubusercontent.com/18436867/48941628-99027d00-ef1c-11e8-8fd2-58c15a6a7440.png)

**Comment by rsanz-indra** [comment]
Respecto a esto: 

> 2.- No té molt de sentit dir "Se ha verificado que el pago no se ha realizado." i després "Si tiene constancia de que ha realizado el pago..."
> Proposta de canvi:
> 
> Atención
> No se ha podido verificar que el pago se ha realizado.
> Para realizar el pago de nuevo pulse en Descartar pago e inicie de nuevo el pago.
> Si tiene constancia de que ha realizado el pago es importante que no descarte el pago, si no consigue verificar el pago póngase en contacto con nuestro soporte técnico

Creo que debe aparecer antes de indicar de Descartar pago, el aviso de que si tiene constancia de que el pago se ha hecho. La gente no suele leer hasta el final.

Quizás algo así:
No se ha podido verificar que el pago se ha realizado, no obstante si usted tiene constancia de que el pago se ha efectuado es importante que no descarte el pago (intente verificar de nuevo el pago y si no lo consigue póngase en contacto con nuestro soporte técnico).
Si no ha realizado el pago, pulse en Descartar pago e inicie de nuevo el pago.

**Comment by jsastre-dgtic** [comment]
El text em sembla correcte. Ho canviau i ho provam?

**Comment by rsanz-indra** [comment]
Texto modificado

**Comment by jsastre-dgtic** [comment]
Accedint a:
http://sdevapplin5.caib.es:48080/sistramitfront/asistente/iniciarTramite.html?tramite=SA001&version=1&idioma=ca&idTramiteCatalogo=3270471

1.- No es reflecteix l'idioma:
![image](https://user-images.githubusercontent.com/18436867/51244285-fea34080-1984-11e9-888a-21135a3fca82.png)

2.- A l'intentar adjuntar doc: 
![image](https://user-images.githubusercontent.com/18436867/51244507-8db05880-1985-11e9-9631-c568c709d35c.png)
 
Cal incorporar a nivell de flux un control per no convertir a PDF documents que ja ho són.

3.- Accedint al pagament amb targeta bancària: 
 
![image](https://user-images.githubusercontent.com/18436867/51244577-b9334300-1985-11e9-9501-bd03ac6576a8.png)

Tampoc respecta l'idioma. 
El text és més llarg i conté més frases de les acordades a l'issue. 
Problemes amb el missatge de pagament. Sembla que tot i que s’havia inclòs el nou missatge pactat, havia quedat part de l’antic. Ho corregim.

**Comment by jsastre-dgtic** [comment]
Surt canviat. Només indicar que hi ha incorreccions a la traducció del text acordat: 

Atenció
No s'ha pogut verificar que el pagament s'hagi efectuat, no obstant si teniu constància **de** que el pagament s'ha efectuat, és important que no descarteu el pagament (intentau verificar **de** de nou el pagament i si no ho aconsegueix posau-vos en contacte amb el nostre suport tècnic).
Si no ha efectuat el pagament, pitjau **en** Descartar pagament **e** **(i)** iniciau de nou el pagament.

**Comment by jsastre-dgtic** [comment]
Comprovat ok
