### ISSUE TITLE
Implementar un tràmit TEST-IDENT només amb el tractament de les dades dels diferents certificats

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#521]
Un tràmit TEST que faci el tractament per a tot tipus de certificat, només amb això i documentar-ho millor, perquè és cert que no queda del tot clar. 

Mentrestant, l'únic que podem fer és prendre mostra del TEST-IG i aplicar el tractament que allà es fa al nostre tràmit, però potser és un tractament massa complex que no caldria fer a altres tràmits. 

El problema és de com s'implementen els scripts si es vol admetre representació, tot i que: 

- Si l'script de Càrrega de dades inicials afecta al registre s'hauria d'explicar. 

- Si no posam res als scripts d'"Establir dades representació", hauria de funcionar, perquè la plataforma te deixa marcar el vist "Admet representació" i no t'informa que hagis de fer res més.

**Comment by jparedes-indra** [comment]
Además de crear el trámite solicitado y modificar la documentaciòn para la formación avanzada, se ha modificado la ayuda, a la que se puede acceder desde el paso "Registrar":

![imagen](https://user-images.githubusercontent.com/67064375/164065536-45ff3941-16ac-4025-9890-95040eff5282.png)

![imagen](https://user-images.githubusercontent.com/67064375/164065939-d71906ea-3f73-499f-80be-aad70cbf7b13.png)

**Comment by avillen-dgtic** [comment]
👍
