### ISSUE TITLE
Ajudes no traduïdes

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#524]
![image](https://user-images.githubusercontent.com/18436867/161526314-049af531-0de1-4939-b9b9-e41a3e0bff79.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.0_2 (https://github.com/GovernIB/sistra2/commit/a8ddb58e46b00e925f887b44130e3a3380ea3da4).
