### ISSUE TITLE
Mantenir format en copiar i aferrar entre pestanyes

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#525]
Ve de https://github.com/GovernIB/sistra2/issues/479#issuecomment-1087375869

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.0_1 (https://github.com/GovernIB/sistra2/commit/c2080ce347b3f3dbee0cd9b203856589c04dd18d).

**Comment by avillen-dgtic** [comment]
👍
