### ISSUE TITLE
 Afegir al disseny de formularis la tipificació dels camps "IBAN"

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#526]
![image](https://user-images.githubusercontent.com/18436867/161697702-c3f0055f-9cdf-4d56-bd89-933bc5c65dfd.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Ahora se puede seleccionar el tipo de campo de texto IBAN y se controla que tenga 2 columnas.

![image](https://user-images.githubusercontent.com/67064375/206699559-a29618c2-55dc-440d-8ae5-29b93dea55f6.png)

Además, al ejecutar el trámite, se controla si el dato introducido a mano o copiado de otro medio, es correcto o no.

![image](https://user-images.githubusercontent.com/67064375/206699659-10009471-e5dc-4016-b3c7-30e735b23e9d.png)

**Comment by jsastre-dgtic** [comment]
Pareix que només accepta IBAN espanyols.

![image](https://user-images.githubusercontent.com/18436867/207296413-f23d336e-6169-41d2-a657-c1363fa3a183.png)

![image](https://user-images.githubusercontent.com/18436867/207296554-d9f7fc13-31ed-4f55-a40e-4d3cf190ec32.png)


En canvi aquest altre de prova si l'accepta: ES7921000813610123456789 

Ho podeu comprovar?

**Comment by avillen-dgtic** [comment]
👍
