### ISSUE TITLE
SIA com a filtre de cerca de tràmits a STH

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#528]
A STH tenim molts de filtres per a fer cerques, i donat que com a resultat hi apareix el codi SIA, veiem que ens pot ser de molta utilitat incloure aquest filtre també com a cerca.

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.1_0 ( https://github.com/GovernIB/sistra2/commit/b1380dff3750d3222705cb0d4fbbf980f0a0dfea)

**Comment by avillen-dgtic** [comment]
👍
