### ISSUE TITLE
STT: Frontal - implementació capa HTML / Javascript formularis (1a FASE)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#53]
-  implementació capa HTML / Javascript formularis (connexió amb lògica servidor mitjançant JSON).

**Comment by rsanz-indra** [comment]
Se entrega versión inicial implementación frontal HTML/JS integrado con la lógica de servidor de formularios
En el siguiente ciclo se realizará un revisión en profundidad de todo el asistente en el que se corregirán los bugs que se encuentren.

**Comment by jsastre-dgtic** [comment]
Tancam aquesta i seguim amb la 2a fase.
