### ISSUE TITLE
Nou element al Gestor de Formularis amb Seccions Reutilitzables

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#530]
al Document d'estimació pertinent

**Comment by jparedes-indra** [comment]
Se resuelve en el tag sistra2-1.4.0_0 (c0e2029).

**Comment by jsastre-dgtic** [comment]
Ha donat un error no controlat perquè he intentat introduir una secció reutilitzable sense abans crear-ne una i no n'ha trobada cap.
![image](https://user-images.githubusercontent.com/18436867/198562967-8e4e5538-949e-4f1f-8710-af9005950e57.png)

**Comment by jsastre-dgtic** [comment]
L'edició del disseny de les SR s'hauria de dir Disseny de Secció Reutilitzable, no Disseny del formulari:

![image](https://user-images.githubusercontent.com/18436867/198563671-51beac0c-d80c-448e-b8c0-6d62635b4e34.png)

**Comment by jsastre-dgtic** [comment]
En la pantalla de disseny de SR abans esmentada, quan intentam copiar un camp i aferrar, falla:

![image](https://user-images.githubusercontent.com/18436867/198563999-546a3c96-b713-4796-8ba1-a138d6a345da.png)

**Comment by jparedes-indra** [comment]
Se resuelve en la revisión 1.4.0_1 (0abdce8).

1.- Si no existen SR o existen pero ninguna está activa, aparece vacío el combo cuando se va a seleccionar una desde el formulario, en lugar de saltar un error.

![imagen](https://user-images.githubusercontent.com/67064375/201204274-51258acb-2019-4679-ac47-9deec1908db1.png)

2.- Se ha corregido el literal que aparece en la cabecera del diseñador de la SR.

![imagen](https://user-images.githubusercontent.com/67064375/201204561-e3a2ccf2-58d0-41f1-a3fc-a49d6f9b815d.png)

3.- Cuando se copia o se corta un componente en el diseñador de SR y se pega, lo hace correctamente y no salta un error.

**Comment by avillen-dgtic** [comment]
👍
