### ISSUE TITLE
Millora al document d'instal·lació de SISTRAGES 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#531]
Documentar la necessitat de pujar properties manualment al Formatador genèric

**Comment by jcerdar-indra** [comment]
Se modifica el manual de instalación de SISTRAGES. Concretamente se añade el apartado 7.3: 
https://github.com/GovernIB/sistra2/blob/sistra2-1.3/sistrages/doc/SISTRAGES_Manual_Instalacio.odt
