### ISSUE TITLE
Eliminar el case sensitive als camps de cerca

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#532]
Estaria bé llevar la restricció de majúscules i minúscules a l'hora de fer cerques dintre de STH.

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.1_0 ( https://github.com/GovernIB/sistra2/commit/b1380dff3750d3222705cb0d4fbbf980f0a0dfea)

**Comment by avillen-dgtic** [comment]
👍
