### ISSUE TITLE
A STH quan miram el detall de l'error a Auditoria, els scrolls no van bé ni es redimensiona la finestra

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#533]
![image](https://user-images.githubusercontent.com/18436867/164408738-b0d4edaf-ccbc-4660-aa4b-f0d5f60e26a0.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.0_2 (https://github.com/GovernIB/sistra2/commit/a8ddb58e46b00e925f887b44130e3a3380ea3da4). Ya solo aparece un scroll. 

La rediminesión depende del tamaño de la primera ventana emergente. Por lo tanto, esta segunda ventana se podrá redimensionar teniendo en cuenta que los límites son el tamaño de la primera ventana. 

![image](https://user-images.githubusercontent.com/96287364/167801986-52444acc-04ab-494b-9a97-2bb5184d9c7c.png)
