### ISSUE TITLE
Si definim  verificarFirma=true al plugin de firma falla

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#534]
Seguretat ens ha informat de:

1.- A DEV el perfil de firma FIRMAAPISIMPLE que té definit pfib (https://se.caib.es/portafib/common/rest/apifirmawebsimple/v1/ ) no valida cap nif 

2.- A PRE el matix perfil FIRMAAPISIMPLE de pfib si valida nifs.

3.- Per altra banda, a DEV no hauria de fallar, sinó simplement no validar la firma.

4.- Entenc també que si cridam directament a https://afirmades2.caib.es/afirmaws/services/DSSAfirmaVerify si hauria de funcionar (a tots els entorns)

5.- El quadre de diàleg no ha de sortir tallat:
![image](https://user-images.githubusercontent.com/18436867/164627946-2d2c0398-60cc-4fc3-ba16-2a4b7a89f788.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.0_2 (https://github.com/GovernIB/sistra2/commit/a8ddb58e46b00e925f887b44130e3a3380ea3da4).

Ya funciona correctamente el plugin de validación de firma.

**Comment by jsastre-dgtic** [comment]
ok, només falla l'accent greu...
![image](https://user-images.githubusercontent.com/18436867/168241285-9d2f5d2b-94d3-4aa7-b198-b49100883ed8.png)
