### ISSUE TITLE
Permetre personalitzar el logo i el títol de les pestanyes del navegador de SISTRAMIT des de la configuració d'entitat en SISTRAGES

### ISSUE THREAD

**Issue by fjcalderon-dgtic** [GovernIB/sistra2#535]

**Comment by jcerdar-indra** [comment]
En la configuración de entidad de SISTRAGES se pueden definir tanto el favicon como el título de la pestaña de SISTRAMIT: 
![image](https://user-images.githubusercontent.com/96287364/177800570-248edc35-cf6b-4429-8590-0fc787239fc4.png)

**Comment by avillen-dgtic** [comment]
Quan tanques el diàleg del favicon, les dades del títol sistramit s'esborren

![#000](https://user-images.githubusercontent.com/83401259/178484026-71b9de3c-ad97-4cae-8591-c3bf39ee74c8.gif)

**Comment by jcerdar-indra** [comment]
![#535](https://user-images.githubusercontent.com/96287364/184168275-49401ff1-ee87-4596-951b-68086e50c4dc.gif)

**Comment by avillen-dgtic** [comment]
No la podem donar per bona encara.
![#000](https://user-images.githubusercontent.com/83401259/193546742-e0e27c6d-db6b-45d2-8e0b-19cfe807abc0.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag sistra2-1.4.0_0 (c0e2029).

**Comment by avillen-dgtic** [comment]
👍
