### ISSUE TITLE
Afegir enllaç SICRES

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#536]
Arran de la issue #490 cal afegir un enllaç a la documentació de SICRES.  Els desenvolupadors han de poder tenir o llegir els estàndards que segueix la versió actual de registre, avui dia SICRES a la versió 3.0, per això afegir un enllaç a l'ajut amb la documentació o diu quines són les mides dels camps ens pareix raonable.

**Comment by avillen-dgtic** [comment]
Afegim l'enllaç a la documentació.

https://administracionelectronica.gob.es/pae_Home/dam/pae_Home/documentos/Estrategias/pae_Interoperabilidad_Inicio/Normas_tecnicas/Guia_de_Aplicacion_NTI_Asientos_Registrales_SICRES3.pdf

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.0_2 (https://github.com/GovernIB/sistra2/commit/a8ddb58e46b00e925f887b44130e3a3380ea3da4).

![image](https://user-images.githubusercontent.com/96287364/167802632-c375fbe2-9142-4976-aade-0e4b29d8726b.png)
![image](https://user-images.githubusercontent.com/96287364/167802643-208224d9-ef34-4d91-9574-c78fe6611d14.png)

**Comment by avillen-dgtic** [comment]
👍
