### ISSUE TITLE
Mostrar info autenticació a STH

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#537]
Esdeveniment inici toca mostrar el que ha arribat de LIB

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.0_2 (https://github.com/GovernIB/sistra2/commit/a8ddb58e46b00e925f887b44130e3a3380ea3da4).

Se añade información de autenticación que envía LoginIB a Sistra2 en los eventos de inicio de trámite de SISTRAHELP. Así, se puede conocer los datos del usuario autenticado y del representante en caso de que tenga: 

![image](https://user-images.githubusercontent.com/96287364/167802885-b0708ca7-a61c-4005-a4ae-7341da64d5db.png)

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/168242802-a934fdd2-9409-4f8d-b75e-5fb1a20079b8.png)
00000000T_PRUEBASPF_APELLIDOUNOPF__R:_Q0000000J_

**Comment by jsastre-dgtic** [comment]
Donam per bona la issue i ja en cream una altra si escau
