### ISSUE TITLE
Actualitzar ajudes de DR (contractes SOAP)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#538]
Tenir en copmte "%5E" ja s'explica però cal esmentar que en el contracte SOAP es necessita mantenir l'Identificador de Tràmit amb el mateix nom.

A més veim que l'ajuda està en castellà:

![image](https://user-images.githubusercontent.com/18436867/165929158-1ed43f74-8432-4e2c-b2de-d9116bde1e65.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.0_2 (https://github.com/GovernIB/sistra2/commit/a8ddb58e46b00e925f887b44130e3a3380ea3da4).

![image](https://user-images.githubusercontent.com/96287364/167803025-c9e56bdf-16b8-4df6-988a-e2d2d5e05307.png)

**Comment by jsastre-dgtic** [comment]
Ens heu passat la versió catalana de l'ajuda? No la veig...
A banda de l'idioma, no veim correcte parlar de dominis de sistra1 i de sistra2 (si referenciar que el soap és el que empra sistra1, però això ja surt a la pantalla anterior). En aquesta pantalla cal llevar referències a sistras i parlar només de soap o rest, amb la particularitat de SAP (soap action). La udit, de fet, té dominis soap que poden sobreviure si tancam sistra1... 

![image](https://user-images.githubusercontent.com/18436867/168007153-40790d3b-a385-408f-808e-820246593be1.png)

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/168040785-0922f219-aa33-4d90-b77b-b63aadcffd27.png)

**Comment by avillen-dgtic** [comment]
👍
