### ISSUE TITLE
Considerar tots els valors que es poden definir al desplegable Tipus document ENI

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#539]
També cal traduir el literal "Tipo documento ENI" --> "Tipus document ENI"

![image](https://user-images.githubusercontent.com/18436867/166412770-1b581ff5-eadb-4e57-8bc5-6115d3b01a5e.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.0_2 (https://github.com/GovernIB/sistra2/commit/a8ddb58e46b00e925f887b44130e3a3380ea3da4).

**Comment by jsastre-dgtic** [comment]
Feim prova amb ACOrD i funciona.
