### ISSUE TITLE
Configurar mètodes pagament alternatius a nivell de tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#540]

**Comment by aagudo-indra** [comment]
@jsastre-dgtic 

Se resuelve en el tag [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se añade un nuevo método que permite definir los métodos de pago que se mostrarán en STT al realizar un pago. 

<img width="360" alt="image" src="https://user-images.githubusercontent.com/88820558/182546320-ddd9777d-b86a-4813-b9fb-a601e0d99564.png">

<img width="360" alt="image" src="https://user-images.githubusercontent.com/88820558/182546310-6fa8fcab-1bfb-45e1-a549-a9ad12c3e283.png">

Por defecto en el plugin de la ATIB, si no se utiliza el mètodo, solo se permitirá el pago por tarjeta

**Comment by jsastre-dgtic** [comment]
ok, però trobam a faltar un exemple i els requisits que té la plataforma TPV.

**Comment by jcerdar-indra** [comment]
Se ha enviado correo para configuración de la pasarela TPV.

**Comment by jsastre-dgtic** [comment]
No l'hem rebut. A més, el que falta és explicar-ho a l'ajuda

**Comment by jcerdar-indra** [comment]
Se añade la explicación en la ayuda indicada en la issue #582

**Comment by jsastre-dgtic** [comment]
ok
