### ISSUE TITLE
Millorar script autoemplenat

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#541]
Es detecta un error en cridar a la funció DADES_VALOR.resetValor() en un script d'autoemplenat d'un camp que depèn d'un camp d'una pàgina anterior. Bóta un error.

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.0_2 (https://github.com/GovernIB/sistra2/commit/a8ddb58e46b00e925f887b44130e3a3380ea3da4).

**Comment by jcerdar-indra** [comment]
Se añade corrección en el TAG 1.3.0_3 ([2a1dfa1](https://github.com/GovernIB/sistra2/commit/2a1dfa1c6bd2d65f6157f668fc9d4227a41fde30)

Para probarlo, en un formulario multipágina definir en la primera página un selector, por ejemplo de lista fija, 'CSEL':
![image](https://user-images.githubusercontent.com/96287364/168251863-ee8a73e3-cbd5-4ca4-ae2a-1007bcc689c8.png)

En la segunda página del formulario definir otro selector, 'CSEL1', con el siguiente script de autorrelleno: 
![image](https://user-images.githubusercontent.com/96287364/168252088-7103eea5-4778-4dad-b47c-401f83af35af.png)

En las anteriores versiones, esta lógica lanzaba un error en SISTRAMIT.

**Comment by avillen-dgtic** [comment]
Pendent de les issues #546 i #545

**Comment by jsastre-dgtic** [comment]
No bóta error però no funciona l'script

var codi = PLUGIN_DATOSFORMULARIO.getValorCompuesto('CSEL').getCodigo();
var codi1 = PLUGIN_DATOSFORMULARIO.getValorCompuesto('CSEL1').getCodigo();
var desc1 = PLUGIN_DATOSFORMULARIO.getValorCompuesto('CSEL1').getDescripcion();

if( codi != 1 ){
  PLUGIN_LOG.debug('Entra aquí');
  DATOS_VALOR.resetValor();
}else{
  DATOS_VALOR.setValorCompuesto(codi1,desc1);
}

![image](https://user-images.githubusercontent.com/18436867/168553430-4e1aa34a-f52e-41e9-bc70-9d71747c8f57.png)

**Comment by jsastre-dgtic** [comment]
Ok, reset valor no té sentit. hem provat amb setvalor i ok
