### ISSUE TITLE
Memòria cau API per a DR

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#542]
Al modificar la url d'un DR tot i esborrar memòria cau de STG, desar i esperar, esborrar dades de navegació del navegador, reiniciar-lo... no es reflecteix el canvi a STT. Cal revisar l'API i la seva actualització i refresc.

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.1_0 ( https://github.com/GovernIB/sistra2/commit/b1380dff3750d3222705cb0d4fbbf980f0a0dfea)

**Comment by avillen-dgtic** [comment]
👍
