### ISSUE TITLE
Pareix que falla el joc de caràcters amb accent greu

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#543]
![image](https://user-images.githubusercontent.com/18436867/168241555-4f68e310-0bf2-435d-9def-759779d2fa1e.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.1_0 ( https://github.com/GovernIB/sistra2/commit/b1380dff3750d3222705cb0d4fbbf980f0a0dfea)
