### ISSUE TITLE
Error duplicant tràmits

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#545]
Aquest error l'hem trobat quan volíem fer un duplicat d'una versió d'un tràmit. En qüestió de l'àrea d'Educació cap a Tests.

![image](https://user-images.githubusercontent.com/83401259/168256702-9dd326d1-ec04-48c4-9dcc-b4e243383bfb.png)

**Comment by jsastre-dgtic** [comment]
L'error és degut a manca de fitxers a SE que venien de DEV. Controlarem això en fer la migració
