### ISSUE TITLE
Controlar error quan una configuració d'autentificació no tingui elements associat

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#547]
Opcions – Configuració d'autenticació i consultem els dominis o GFE associats a una configuració d'autenticació, bota un NullPointer

**Comment by jcerdar-indra** [comment]
![#547](https://user-images.githubusercontent.com/96287364/177790774-f9f99260-b044-4fef-9c6f-bae5ed339b2e.gif)
