### ISSUE TITLE
Tractament de la propietat només lectura al tipus selector múltiple

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#549]
Si cream un formulari amb un selector de tipus selector múltiple/única i marca el check de només lectura. Es pot modificar perquè no està atenent aquesta propietat d'estat.

**Comment by jsastre-dgtic** [comment]
no podem validar perquè a l'afegir un camp de selecció múltiple falla el DR

![imatge](https://user-images.githubusercontent.com/18436867/183028522-7b000e19-970d-4a86-b6ec-27b6a0d75d6e.png)

**Comment by jcerdar-indra** [comment]
Este error se relacionaba con la issue #608 , la cual ya está solucionada en el TAG 1.3.2_1 (b308a01).

**Comment by jsastre-dgtic** [comment]
Comprovat, tancam
