### ISSUE TITLE
STT: API Rest interna - serveis HLP

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#55]

**Comment by jsastre-dgtic** [comment]
Com avaluam els canvis?

**Comment by rsanz-indra** [comment]
Se pueden evaluar mediante SistraHelp que usa estos servicios

**Comment by jsastre-dgtic** [comment]
ok, per ara no aconseguim que funcioni sistrahelp (veure issue STH: Funcionalitat de recerca d'esdeveniments i operativa ROLS #108)
https://github.com/GovernIB/sistra2/issues/108#issuecomment-470098192
