### ISSUE TITLE
Fer primar els missatges d'avís d'entitat per damunt de tot

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#554]
![image](https://user-images.githubusercontent.com/18436867/170670546-26e679ef-b346-4cd9-bed3-9ee786989ed4.png)

No serveix si rolsac no apunta al codi correcte.
![image](https://user-images.githubusercontent.com/18436867/170670838-823513d9-dc21-4eab-b3af-2d8d46b4af10.png)

**Comment by jparedes-indra** [comment]
Si se crea un mensaje de entidad con el check “Deshabilitar acceso” marcado (que impide el acceso al trámtie tras mostrar el mensaje), se muestra dicho mensaje y se impide su acceso.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/8c814b47-0064-4078-97d9-9cc044448684)

Por ejemplo, si se intenta acceder a un trámite con el argumento idTramiteCatalogo=12345 (que no exista en ROLSAC), aparece el mensaje y luego no se accede al trámite.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/06e1c785-24e0-41dc-9baf-a39b4bd1b4fe)
