### ISSUE TITLE
Sense dades a STH

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#555]
Amb l'actualització de la versió 1.3.0 de S2, a la plataforma de STH s'han deixat de veure els registres d'abans del 27 de maig. Només es mostren aquells posterios.

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/170983839-371d6d97-2560-4b03-99cf-5044db3b3cf5.png)

**Comment by jparedes-indra** [comment]
Para poder recuperar la información de los trámites persistentes anteriores a la versión 1.3.0, se han actualizado los identificadores del área y del trámite para convertirlos en identificadores compuestos en los registros anteriores a la actualización. Para ello, se ejecutó una sentencia en la BBDD de SISTRAMIT y, tras el envío del resultado, se ejecutaron los updates necesarios para actualizar los registros anteriores en la BBDD de SISTRAMIT y poder recuperar esa información en SISTRAHELP. 

Issue resuelta.
