### ISSUE TITLE
Llevar el caseSensitive dels camps de cerca

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#557]
![image](https://user-images.githubusercontent.com/83401259/171142130-5e023bd4-2575-4312-9dee-1a2d6f611167.png)

Cal llevar aquesta restricció perquè ens limita a l'hora de fer cerques.

**Comment by aagudo-indra** [comment]
@jsastre-dgtic

Se resuelve en el tag [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se elimina la restricción caseSentive de los campos de búsqueda.

![557](https://user-images.githubusercontent.com/88820558/182548279-07df14a4-30d7-45d5-865a-e252d447bfcd.gif)
