### ISSUE TITLE
Poder seleccionar i copiar tots els texts que mostri a STG i STH

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#558]
Concretament, no podem seleccionar l'usuari, en aquest cas

![image](https://user-images.githubusercontent.com/18436867/171336663-38e59f97-41ad-4226-8435-95a22dc6f5ae.png)

**Comment by jparedes-indra** [comment]
Puesto que la resolución no es inmediata, se postpone para versiones posteriores.

**Comment by jparedes-indra** [comment]
Se resuelve en el tag sistra2-1.4.0_0 (c0e2029).

Tanto en STH como en la pantalla de historial de versiones aparece un botón copiar.

![imagen](https://user-images.githubusercontent.com/67064375/198516290-0b3f4e2a-56d4-4d9e-99f8-7a9a0c185612.png)

![imagen](https://user-images.githubusercontent.com/67064375/198516485-305e7174-a907-4fcb-bffe-4556cfc94eff.png)

**Comment by avillen-dgtic** [comment]
Cal retirar el botó i permetre que qualsevol text de STG sigui susceptible de ser copiat, ja sigui taules com qualsevol altre text seleccionat.

![#000](https://user-images.githubusercontent.com/83401259/198552539-ac2ed720-c629-44b1-97e9-f7d76a19d38d.gif)

**Comment by avillen-dgtic** [comment]
Afegim que també s'ha de permetre fer a STH

**Comment by jsastre-dgtic** [comment]
Es resol eliminar el botó copiar i enlloc d'això afegir un menú contextual, de manera que es puguin copiar els textos de la cel·la assenyalada i veurem la possibilitat de poder copiar també els textos en mode només lectura (seleccionant amb el ratolí i/o amb el menú contextual). Aquest menú contextual també permetrà realitzar les accions pròpies de l'element assenyalat, com ara editar, consultar, bloquejar... una versió d'un tràmit.

**Comment by jparedes-indra** [comment]
Puesto que la solución se modifica, se pasa a la versión 1.4.1

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Se añade un menú contextual que permite copiar cualquier texto situado debajo del puntero del mouse y realizar funciones propias de la zona señalada.

![image](https://user-images.githubusercontent.com/67064375/206707520-e1dd4558-f9ed-4d3b-b935-6b27c314eef9.png)
![imagen](https://user-images.githubusercontent.com/67064375/206854532-f06d1c04-26bf-45e9-b6fd-a89f43a55156.png)
![imagen](https://user-images.githubusercontent.com/67064375/206854547-608ab016-be4d-4377-9b55-86157b3a8bb6.png)

**Comment by jsastre-dgtic** [comment]
ok...

**Comment by jsastre-dgtic** [comment]
Arran d'algunes proves veim que la funcionalitat del menú contextual està per tot, però sense cap mena de control. 

![image](https://user-images.githubusercontent.com/18436867/218728265-d5ad63fe-2d7b-452a-b521-f963262a0827.png)

--- 
if(window.PrimeFaces){PrimeFaces.settings.locale='ca';}        Generar Quadern de Càrrega                        function stop(){                                document.getElementById('dialogExportar:btnExportar').disabled = true;                                document.getElementById('dialogExportar:btnExportar').classList.add("ui-state-disabled");                                document.getElementById('dialogExportar:btnHidden').click();                }                                #dialogExportar\:j_idt16 {                        padding-bottom: 38px !important;                }                                                          window.onload=function(){                            let contextMenu =  document.getElementsByClassName('ui-contextmenu')[0];                                onVisible(contextMenu, () => eliminarResaltar());                                document.addEventListener('contextmenu', function(ev) {                                    ev.preventDefault();                                    getPos();                                    return false;                                }, false);                          }                                function eliminarResaltar(){                                        let contextMenu =  document.getElementsByClassName('ui-contextmenu')[0];                                          let elementos = document.getElementsByClassName('resaltar');                                          if(contextMenu!=null && contextMenu.style.display=='none' && elementos.length > 0){                                                for(let i = 0; i < elementos.length; i++){                                                        elementos[i].classList.remove('resaltar');                                                }                                          }                                }                                function onVisible(element, callback) {                                  new IntersectionObserver((entries, observer) => {                                    entries.forEach(entry => {                                      if(entry.intersectionRatio == 0) {                                        callback(element);                                      }                                    });                                  }).observe(element);                                }                          function getPos(){                                 var e = window.event;                            var posX = e.clientX;                            var posY = e.clientY;                            var el = document.elementFromPoint(posX, posY);                            let elementos = document.getElementsByClassName('resaltar');                                          if(elementos.length > 0){                                                for(let i = 0; i < elementos.length; i++){                                                        elementos[i].classList.remove('resaltar');                                                }                                          }                                el.classList.add("resaltar");                                var aux = document.getElementById("dialogExportar:auxCopiar");                                if(el.textContent!='' && el.textContent!='ui-button'){                                        aux.value = el.textContent;                                }else if(el.firstChild!=null && el.firstChild.value!=undefined){                                        aux.value = el.firstChild.value;                                }else if(el.value!=null && el.value!=''){                                        aux.value = el.value;                                }else{                          aux.value = '';                        }                         }                        ui-button                                                                Versió tràmiteÀrea:TESTS - TESTS UNITARIS I FUNCIONALSTràmit:TEST-REGISTRE - TRÀMIT TEST DE REGISTREVersió:5 - (Release 36)Elements comunsCodiÀmbitTipusGESCONSDIR3EntitatConsulta BBDDFormatadorsCodiDescripcióNo s'han trobat dadesGestors externs de formularisCodiDescripcióNo s'han trobat dadesSeccions reutilitzablesCodiDescripcióNo s'han trobat dadesGenerar resumExportarTancarAjudaCopiar

**Comment by jparedes-indra** [comment]
Ahora ya no se permite copiar zonas con varios elementos.

**Comment by avillen-dgtic** [comment]
👍
