### ISSUE TITLE
Afegir la declaració d'accessibilitat a l'assistent de tramitació

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#559]

**Comment by aagudo-indra** [comment]
@jsastre-dgtic 

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se añade una nueva pestaña para añadir declaración de accesibilidad en configuración entidad (STG): 

<img width="360" alt="image" src="https://user-images.githubusercontent.com/88820558/182548789-aabc07ef-0490-490c-a844-6ce359108105.png">

En STT, en Accesibilidad, si clicamos se nos desplegará una opción llamada DECLARACIÓN, la cual si clicamos nos conducirá a una página con el texto definido en la pestaña anteriormente mencionada.

<img width="360" alt="image" src="https://user-images.githubusercontent.com/88820558/182548871-757c1de3-f315-4bc3-bad9-bae8180ae77e.png">

<img width="360" alt="image" src="https://user-images.githubusercontent.com/88820558/182548885-0f2f9f98-a8f0-4367-9e93-aceb38d8d4b5.png">

![559](https://user-images.githubusercontent.com/88820558/182548909-91867645-f152-4d44-a099-9b2927b5a564.gif)

**Comment by jsastre-dgtic** [comment]
A l'intentar definir https://www.caib.es/seucaib/ca/fichainformativa/4266780

surt:
![imatge](https://user-images.githubusercontent.com/18436867/182822405-58b7dacd-2961-4d21-9582-1c02773a93f2.png)

**Comment by jsastre-dgtic** [comment]
Queda pendent redactar la Declaració i veure si supera els 4000 (veure #327 )

**Comment by avillen-dgtic** [comment]
👍
