### ISSUE TITLE
Els Adm d'àrea no poden veure res a STH i els Adm d'Entitat no podem filtrar per tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#561]
Ho relacionam amb l'API de STT

Adm_Entitat: 
![image](https://user-images.githubusercontent.com/18436867/171590860-1f2c6d31-e149-4849-90fc-fe36a9275366.png)

Adm_Àrea_Test:
![image](https://user-images.githubusercontent.com/18436867/171590845-492baa75-cb48-4572-a5a5-419ca9ec3805.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG sistra2-1.3.0_7 (7faf55c).

**Comment by avillen-dgtic** [comment]
No funcionen els camps de cerca. 
![image](https://user-images.githubusercontent.com/83401259/172113143-41c930a0-f7c5-4588-8911-964352b0e15e.png)

![image](https://user-images.githubusercontent.com/83401259/172113150-04366000-e307-4aad-95a3-9ee15813720f.png)

**Comment by avillen-dgtic** [comment]
Mostra dades.
