### ISSUE TITLE
Disposar d'un esdeveniment TR_SIG per a la signatura? 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#563]
A l'auditoria de tràmits hi hauria d'haver aquest tipus d'esdeveniment per capturar problemes amb firma.
![image](https://user-images.githubusercontent.com/18436867/171794334-b878f62a-9df7-48a9-bf56-e5ee62f69924.png)

**Comment by jcerdar-indra** [comment]
Se añaden 4 nuevos eventos en la auditoría de trámites: 

- TR_FRI: Inicio formulario
- TR_FRF: Fin formulario
- TR_SGI - Inicio firma
- TR_SGF: Fin firma
![image](https://user-images.githubusercontent.com/96287364/177795297-90e259fe-62ae-43fe-9720-d35ee020071b.png)
![image](https://user-images.githubusercontent.com/96287364/177795313-ffc32458-e103-42f9-a847-c155782227d6.png)
![image](https://user-images.githubusercontent.com/96287364/177795323-a3a7ad54-742c-4cce-bb34-c7b0cf226b38.png)
Se añaden también eventos de invalidación en auditoría de eventos de plataforma: 
![image](https://user-images.githubusercontent.com/96287364/177795362-13fd1053-9625-4ce6-9b22-d1b121b811b8.png)
