### ISSUE TITLE
Possibilitar consulta de Dominis amb rol de consulta

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#564]
desenvolupador pogués consultar (mode lectura) els Dominis de les àrees de test (rol consulta)

**Comment by aagudo-indra** [comment]
@jsastre-dgtic

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Ahora un desarrollador con rol Consulta puede revisar la definición de los dominios. 

![564](https://user-images.githubusercontent.com/88820558/182549446-4fc1264e-d264-46a5-b5d4-5c6e9b587969.gif)
