### ISSUE TITLE
Controlar error de domini no definit a desplegable i mostrar-ho a STH

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#565]
Actualment, si un camp de formulari tipus Llista Desplegable de Domini, no té definit cap domini quan intentam llençar el tràmit a SISTRAMIT dona error no controlat

es.caib.sistramit.core.api.exception.ErrorNoControladoException: Error no controlat a la capa de servei: 500 Internal Server Error 

(veure exemple amb  IBSALUT > OPOS_PLAN_ESTABI > Versión 1 )

![image](https://user-images.githubusercontent.com/18436867/172132634-c9149277-81b8-4080-8895-1d74082395de.png)

**Comment by jparedes-indra** [comment]
Puesto que su resolución es compleja, se aplaza a versiones posteriores.

**Comment by jsastre-dgtic** [comment]
![imatge](https://user-images.githubusercontent.com/18436867/182820678-2aad67fb-3565-4c1e-9717-bd3e31e322f1.png)

**Comment by jparedes-indra** [comment]
Este escenario no lo podemos reproducir, ya que, si no se define un dominio en un selector de tipo lista valores "Dominio", avisa si no se define un dominio.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/4951166a-c820-4b3d-aa25-d38d131276da)

**Comment by avillen-dgtic** [comment]
👍
