### ISSUE TITLE
Millora dels camps de cerca

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#566]
Cal revisar la funcionalitat de cada un dels camps de cerca. Ens trobem que hi ha camps que quan introdueixes un "paste" de la mateixa informació de les taules de STH inclou un espai o una tabulació que impedeix un resultat correcte.

Cal fer una revisió profunda de tots els camps de STH i tenir en compte aquests punts: 
- Revisar que els camps funcionin com toca.
- Revisar majúscules i minúscules. 
- Trimar el text dels camps si tenen espais o tabulacions al començament i a l'acabament. 
- SubString. Permetre fer cerques de troços de texte  
        ex. T8NPH8V9  -> hauria de treure aquestes idSessions NIQIV9P3-LRHTWNT8-T8NPH8V9   T8NPH8V9

**Comment by aagudo-indra** [comment]
#566

Se Trima el texto del buscador al buscar, se quita caseSensitive, se permite buscar con textos incompletos y se revisa la funcionalidad de los campos.

![566](https://user-images.githubusercontent.com/88820558/182550441-a66835ee-2e04-43a8-aa06-74511cacb0d7.gif)
