### ISSUE TITLE
Format dels documents vàlids

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#569]
A més d'incloure els formats vàlids, posar per defecte que apareguin a STG els formats PDF i ODT, llevant PDF i DOC.

**Comment by jsastre-dgtic** [comment]
Les extensions que ha d'admetre SISTRA2 són:
pptx, jpg, jpeg, txt, xml, xsig, xlsx, odg, odt, ods, pdf, odp, png, svg, tiff, docx, rtf

**Comment by jcerdar-indra** [comment]
Se añade propiedad de configuración global con las extensiones que se permiten. 
![image](https://user-images.githubusercontent.com/96287364/177797492-4c365ae1-99b7-4357-9aca-bb5f494e36a2.png)

**Comment by avillen-dgtic** [comment]
👍
