### ISSUE TITLE
STG:   Adaptació connector registre

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#57]
- pantalla versió tràmit (pas registrar) i procés exportació.

**Comment by rsanz-indra** [comment]
Se ha modificado la pantalla de paso registrar en versión de trámite y la pantalla de importación para que los datos de registros se recuperen a través de campos desplegables conectados a través del plugin de registro (se ha utilizado el plugin mock de registro para pruebas).

**Comment by jsastre-dgtic** [comment]
Tot i tenir un pagament i doc opcionals, no ens permet registrar:
![image](https://user-images.githubusercontent.com/18436867/48550874-2a963d00-e8d4-11e8-8f4d-328f1d25423c.png)

**Comment by amaciam-indra** [comment]
El workflow de la passa registrar no està implementat, tal i com es reflecteix a les planificacions de cicles

**Comment by jsastre-dgtic** [comment]
ok, sorry!

**Comment by jsastre-dgtic** [comment]
Observacions:
1.- Perquè no podem exportar un tràmit bloquejat? Té sentit?
![image](https://user-images.githubusercontent.com/18436867/48551984-6252b400-e8d7-11e8-8f43-22284cb1e04c.png)
2.- Intentam exportar-lo una vegada desbloquejat i importar-lo.
Seguim sense entendre que ens demani paràmetres de registre enlloc de simplement demanar un canvi de versió perquè la 1 ja existeix.
![image](https://user-images.githubusercontent.com/18436867/48552158-fcb2f780-e8d7-11e8-8ace-c872a23ff52b.png)

A més, pareix que el mock no funciona amb el llibre:
![image](https://user-images.githubusercontent.com/18436867/48552143-f4f35300-e8d7-11e8-8d0f-82ac647743fc.png)
![image](https://user-images.githubusercontent.com/18436867/48552150-f7ee4380-e8d7-11e8-8952-543c8379bba1.png)

**Comment by rsanz-indra** [comment]
1. No se permite exportar un trámite bloqueado porque el mecanismo de exportación/importación está diseñado para promocionar versiones de trámite entre entornos manteniendo la trazabilidad. Si un trámite está bloqueado es porque se está modificando, debe desbloquearse una vez finalizados los cambios para tener una nueva release y que al promocionar entre entornos se puede tener una trazabilidad.
2. Revisamos lo del libro con el plugin mock. Lo que comentas del cambio de versión es precisamente lo mismo del punto anterior, el mecanismos de exportación/importación no es un sistema de copia de versiones es un mecanismo de promoción de versiones entre entornos para que se pueda mantener la trazabilidad.

**Comment by jsastre-dgtic** [comment]
Si els paràmetres de registre existeixen (al no canviar d'entorn han d'existir), perquè ens surt la pantalla per revisar lels paràmetres de registre?

**Comment by rsanz-indra** [comment]
Se soluciona problema con desplegables, era debido a que contenía valores anteriores a meter el desplegable.
En la importación de una versión de trámite se muestran para revisar los parámetros de registro tal como se realiza en Sistra1 cuando se importa un trámite. Sirve para confirmar que los datos son correctos.

**Comment by jsastre-dgtic** [comment]
Seguim sense veure perquè noi es carreguen les dades de registre que existeixen als desplegables:
![image](https://user-images.githubusercontent.com/18436867/49009306-897b7200-f170-11e8-94c0-1e8a25ee1538.png)

**Comment by amaciam-indra** [comment]
En principi s'haurien de fixar els valors existent sempre que la versió exportada els tingui emplenats. Podeu per favor verificar que la versió exportada té fixats el paràmetres de registre?

**Comment by jsastre-dgtic** [comment]
Pareix que si...
![image](https://user-images.githubusercontent.com/18436867/49010878-d82b0b00-f174-11e8-979b-a685d33387c5.png)

**Comment by jsastre-dgtic** [comment]
Proposta de canvi de pantalla per desvincular la versió del registre. Veure issue: STG: Millores diverses #71
Tancam aquesta
