### ISSUE TITLE
Ordenar alfabèticament segons Codi del tràmit dins les àrees seleccionades

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#570]
Actualment l'ordre alfabètic és a dins cada pàgina, no afecta a tota l'àrea o àrees. A la 3a pàgina tenim 7 tràmits ordenats alfabèticament en aquesta pàgina, però s'inclouen Codis que haurien de ser a la primera pàgina

![image](https://user-images.githubusercontent.com/18436867/172806828-bc3c5de6-a3b4-4207-b60e-74d2d4caf977.png)

S'hauria de poder ordenar segons la capçalera de la columna que es picàs. 
Cal afegir una columna nova que ens permeti ordenar per la darrera modificació de qualsevol de les versions associades.

**Comment by aagudo-indra** [comment]
@jsastre-dgtic 

Se resuelve en el tag [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se cambia la forma en la que se muestran los trámites para que se ordenen alfabéticamente, independientemente de las áreas seleccionadas.

![570](https://user-images.githubusercontent.com/88820558/182551376-d897bc7e-d43f-47d7-ace1-516bdebe1cd5.gif)
