### ISSUE TITLE
Ajustar finestra perquè no es talli desplegable

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#571]
![image](https://user-images.githubusercontent.com/18436867/172808888-52528c4c-cf6d-4a8b-b957-f8568e80b97b.png)

![image](https://user-images.githubusercontent.com/18436867/172808850-72f9acbe-5fd6-4f67-81a0-940dff398957.png)

**Comment by aagudo-indra** [comment]
@jsastre-dgtic 

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se ajusta la ventana para no cortar el contenido.

<img width="301" alt="image" src="https://user-images.githubusercontent.com/88820558/182552412-d2f1c9b4-7454-4bac-b68b-baf6a1116b79.png">
