### ISSUE TITLE
Canviar el tractament de la concatenació Entitat+Àrea+Nom_tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#572]
Des de Rolsac cridam des d'una Entitat amb un Codi DIR3, no hauria de fer falta especificar a Sistra2 l'Entitat a cada tràmit

![image](https://user-images.githubusercontent.com/18436867/172810263-00ccf1c2-9834-464e-9d53-66fd1e365b0f.png)

**Comment by jsastre-dgtic** [comment]
1.- Cal eliminar també el nom de l'entitat al visualitzar a STH
2.- L'àrea ha de ser columna i s'ha de poder filtrar, separar-la del nom del tràmit, perquè a STG el nom del tràmit no inclou nom d'àrea.

![image](https://user-images.githubusercontent.com/18436867/173332881-433cd1c2-ce71-4846-96a3-78b693795717.png)

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/173333923-c084fcf0-ef32-4de5-9bcb-426aac89d88f.png)

**Comment by jsastre-dgtic** [comment]
L'àrea a Dades sessió ha de ser tests, no caib.tests

![image](https://user-images.githubusercontent.com/18436867/173754570-66810638-a2d0-4e97-96be-3fd087d973e9.png)

**Comment by jsastre-dgtic** [comment]
ídem,...
![image](https://user-images.githubusercontent.com/18436867/173810312-f11db9c6-9ba5-4492-9424-346e009623ef.png)

**Comment by jsastre-dgtic** [comment]
El filtra no troba ni CAIB.PESCA.AUT_RECRE_EMB, ni PESCA.AUT_RECRE_EMB ni AUT_RECRE_EMB
![image](https://user-images.githubusercontent.com/18436867/173810476-651f263c-109a-4670-89bc-aef5ac847561.png)

**Comment by aagudo-indra** [comment]
@jsastre-dgtic

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se cambia el identificador compuesto por el simple al hacer referencia a áreas / trámites

<img width="360" alt="image" src="https://user-images.githubusercontent.com/88820558/182552691-55ee7bd3-bbea-4d23-93a3-d7af64496eeb.png">

<img width="360" alt="image" src="https://user-images.githubusercontent.com/88820558/182552669-e8b0c7b8-549e-435e-911e-039401f5e325.png">

<img width="360" alt="image" src="https://user-images.githubusercontent.com/88820558/182552709-7f54fc0c-9e70-4233-a61b-263c0822ea63.png">

Se soluciona casuística del filtro de búsqueda en la pantalla de Consulta General.

![572](https://user-images.githubusercontent.com/88820558/182552824-2aec9780-195d-4eae-934b-86d0377499c8.gif)

**Comment by jsastre-dgtic** [comment]
Manquen 2 punts

Des de Rolsac cridam des d'una Entitat amb un Codi DIR3, no hauria de fer falta especificar a Sistra2 l'Entitat a cada tràmit
3.- Canviar el nom de l'entitat CAIB per GOIB de manera transparent per tothom

**Comment by avillen-dgtic** [comment]
Es desestima
