### ISSUE TITLE
No surt l'opció de previsualització a la pantalla de tràmits/versions

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#574]
Amb usuari desenvolupador:

![image](https://user-images.githubusercontent.com/18436867/172998946-e0bc3576-5e45-45be-8156-dbeaa19a6015.png)

En canvi, en entrar a la versió si
![image](https://user-images.githubusercontent.com/18436867/172999104-d2e78152-0d06-4a78-941d-0358fdf5bf5a.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.1_0 ( https://github.com/GovernIB/sistra2/commit/b1380dff3750d3222705cb0d4fbbf980f0a0dfea)

**Comment by jcerdar-indra** [comment]
![image](https://user-images.githubusercontent.com/96287364/177797987-4fa7de99-385a-4db9-9859-3973491c1a9f.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en versión 1.3.2 ([49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)) 

![image](https://user-images.githubusercontent.com/96287364/182841743-6e45f554-675e-43a4-9c75-ea59bcb17271.png)
![image](https://user-images.githubusercontent.com/96287364/182841798-c8f6c81b-c7de-4d6d-b298-46f5367a5e95.png)
