### ISSUE TITLE
Realitzar la validació de QAA en reprendre un tràmit des de Carpeta

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#575]
Mantenir el QAA=1 a CARPETA (així endemés facilitam l'accés a la resta de serveis de CARPETA) i que a l'hora de reprendre un tràmit de nivell 2, s'informés a l'usuari que la qualitat de l'autenticació és insuficient i se li ofereixi la possibilitat de tornar-se autenticar. Aquesta vegada es botaria de nou a LOGINIB però amb QAA=2 i reprendre així el tràmit. 

Per això, quan es cliqui al botó de ‘Continuau’ es faria una redirecció a LoginIB amb el QAA adequat per al tràmit. Així, Cl@ve tornaria a sol·licitar l'autenticació del ciutadà amb un mètode d'autenticació adequat al nivell de QAA i, consegüentment, aquest podria reprendre la tramitació. També es canviarà el missatge que es mostri al ciutadà perquè sigui més aclaridor i adreçar-lo a fer clic al botó ‘Continuau’.

Missatge que es mostra actualment en cas de reprendre tramitació amb un QAA inferior al del tràmit:

![image](https://user-images.githubusercontent.com/18436867/173043688-2a9224d5-01d1-47fa-9348-e00fad6efc0d.png)

Cal canviar el text "Heu de tancar la sessió i autenticar-vos de nou" per "Pitjau Continuar per a accedir-hi amb un nivell d'autenticació superior" (o una cosa així, perquè si posam tancar sessió tancaran el navegador i a tornar començar)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.1_0 ( https://github.com/GovernIB/sistra2/commit/b1380dff3750d3222705cb0d4fbbf980f0a0dfea)

**Comment by jcerdar-indra** [comment]
Se inicia trámite con QAA medio y se accede con cualquier método:
![image](https://user-images.githubusercontent.com/96287364/177791323-7ef16671-94a5-4b33-92e1-f0d238a0de36.png)
Se accede a Carpeta con QAA bajo: 
![image](https://user-images.githubusercontent.com/96287364/177791359-291b76fa-da13-4a14-b041-938a22b169fc.png)
Se intenta retomar trámite anterior. Aparece error de QAA.
![image](https://user-images.githubusercontent.com/96287364/177791396-5eca6ca6-b32e-4949-a8f9-b47e82e48efb.png)
![575](https://user-images.githubusercontent.com/96287364/177791427-b8836301-cc06-48b2-83de-221c759e8363.gif)

**Comment by jcerdar-indra** [comment]
Ahora al intentar acceder a un trámite desde Carpeta con un QAA inferior al del trámite aparece el siguiente mensaje: 
![image](https://user-images.githubusercontent.com/96287364/177791915-eb3178e2-8fa1-46ef-a6f0-d4cdb9560961.png)
Una vez se clica en 'Continuau', se vuelve a realizar una petición de login con el QAA adecuado para el trámite y permite al ciudadano reautenticarse y acceder al trámite.

**Comment by jsastre-dgtic** [comment]
Enviada proposta:
![imatge](https://user-images.githubusercontent.com/18436867/183034266-c1a4867c-8be8-4091-8c78-abcd450d4793.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.2_1 (https://github.com/GovernIB/sistra2/commit/b308a01a1b1260bd6364486f0d4e26991fdd2093) el tema de los mensajes. 
![image](https://user-images.githubusercontent.com/96287364/184172270-0554e57e-e029-4059-b4e9-30aae0a446c1.png)


En cuanto a la mejora en la propuesta visual, deberemos de analizarlo con mayor detalle. Actualmente, para generar un determinado tipo de excepciones en SISTRAMIT se genera una vista que es genérica y en la que se pueden personalizar aspectos como el mensaje o la URL de redirección del botón. Sin embargo, cambiar aspectos visuales supone cambios en la lógica que hemos de revisar y analizar con detalle.

**Comment by jparedes-indra** [comment]
Se ha personalizado la pantalla de aviso. 

![image](https://user-images.githubusercontent.com/67064375/231981277-61789d00-aa38-4e81-8d19-84d15c839ae2.png)

**Comment by avillen-dgtic** [comment]
👍
