### ISSUE TITLE
A l'intentar definir les opcions del formulari de suport dóna error

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#576]
![image](https://user-images.githubusercontent.com/18436867/173045908-ed165913-df6f-4e28-ab85-4e41c9b826e3.png)

![image](https://user-images.githubusercontent.com/18436867/173045812-d6c44b80-faa3-4f50-98f4-b02945bdcf8a.png)

**Comment by avillen-dgtic** [comment]
👍
