### ISSUE TITLE
STG: Adaptació connector dominis

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#58]
- pantalla dominis (ping)

**Comment by rsanz-indra** [comment]
Se ha implementado la pantalla de ping y se ha probado la resolución de dominios contra:
- dominios tipo lista fija
- dominios tipo sql
- dominios tipo fuente de datos
- dominios tipo remoto (contra plugin mock de dominios remotos)

**Comment by jsastre-dgtic** [comment]
No tenim la informació per donar d'alta domninis SQL ni remots. Hem donat d'alta llista fixa i Font de dades amb resultat positiu però no del tot acurat:

1.- Quan fem un ping de domini de llista fixa ens surt una presentació diferent que si el fem de llista fixa. Surt en columnes enlloc de en files, cosa que és problemàtica per a visualitzar resultats:

![image](https://user-images.githubusercontent.com/18436867/48549337-c8d3d400-e8cf-11e8-899d-37205b2936a4.png)
En aquesta pantalla no funciona el desplegable de quants resultat visualitzam i si en tenim més de 10 ja no es mostren.
![image](https://user-images.githubusercontent.com/18436867/48549459-2405c680-e8d0-11e8-9896-c81e783ef53c.png)

2.- Quan donam d'alta un domini i pitjam el +, el focus no va al camp codi i hi hauria d'anar:
![image](https://user-images.githubusercontent.com/18436867/48549403-fde02680-e8cf-11e8-9ca4-29ed061d5c36.png)

3.- Seguim amb el problema dels emergents, desapareixen molt ràpid.
![image](https://user-images.githubusercontent.com/18436867/48549439-19e3c800-e8d0-11e8-8a5e-092593416c0d.png)

4.- A la pantalla Gestió de Domini posa JDNI enlloc de JNDI. Ens podríeu passar un exemple d'aquest camp per a poder fer proves?
![image](https://user-images.githubusercontent.com/18436867/48549719-dd649c00-e8d0-11e8-84f7-d56fb39daeda.png)

**Comment by jsastre-dgtic** [comment]
Tenim un problema de cache quye quan canviam a remot no ens canvia el camp jndi pel de url:
![image](https://user-images.githubusercontent.com/18436867/48942410-9b1a0b00-ef1f-11e8-8b00-0d116cf10c4b.png)

**Comment by amaciam-indra** [comment]
El problema que indicau no és un tema de caché, es deu al fluxe JSF de validació de camps requerits. Si emplenau els camps requerits podreu veure com es poden canviar valor de la resta de camps i s'actualitzen correctament els camps depenents del tipus de domini.
En tot cas revisarem si es pot trobar una solució per canviar aquest comportament.

**Comment by jsastre-dgtic** [comment]
És així com dius, però ja ens sembla bé revisar aquest comportament

**Comment by jsastre-dgtic** [comment]
Seguim amb el problema de gramàtica?
![image](https://user-images.githubusercontent.com/18436867/49010119-9a2ce780-f172-11e8-86f8-0a48ed76c19e.png)

**Comment by amaciam-indra** [comment]
En principi anteriorment no hi havia cap problema d'aquest tipus. Ho revisam, ja que pareix que és un efecte col·lateral de la implementació del mecanisme per evitar l'SQL en pla en el manteniment de dominis.

**Comment by jsastre-dgtic** [comment]
Homogeneitzar  l'order by:
A la llista fixa pareix que ordena per Id
![image](https://user-images.githubusercontent.com/18436867/51245459-031d2880-1988-11e9-8bc5-c01be6155eb0.png)

A la Font de Dades pareix que inverteix aquest ordre... és més normal el primer criteri.
![image](https://user-images.githubusercontent.com/18436867/51245503-28119b80-1988-11e9-96e8-a2d4e91ab572.png)
