### ISSUE TITLE
Entrada de texts d'altres fonts

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#580]
Arran de problemes amb els Copy&Paste, s'ha de trobar una solució perquè a qualsevol punt de les plataformes no hi hagi cap classe de problema. Com a suggeriment, fer servir expressions regulars que validin l'entrada de dades abans de guardar.

**Comment by avillen-dgtic** [comment]
Recordad incluir las minúsculas, [a-z]

**Comment by aagudo-indra** [comment]
@jsastre-dgtic

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se filtran los elementos pegados y se sustituyen los carácteres conflictivos al guardar.

![580](https://user-images.githubusercontent.com/88820558/182553234-ececcd8b-71be-4e71-9a10-6219adcbf513.gif)
