### ISSUE TITLE
No funciona importar dominis d'àrea

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#581]
Cal fer el mateix tractament que als d'entitat tenint en compte els perfils. 

Ara passa això amb Administrador d'Entitat (no ho he provat com a Administrador d'Àrea)

Quan intentes promocionar noi deixa perquè no existeix --> S'ha de crear si no existeix.

![image](https://user-images.githubusercontent.com/18436867/175875010-06cb2670-f22b-48ab-b7b4-1afceacc10d6.png)

Quan intentes importar-lo manualment no te deixa i el missatge diu que no pot perquè no existeix (sic)

![image](https://user-images.githubusercontent.com/18436867/175875066-d6749e40-929a-4b41-87eb-cb14db81dbd7.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.3.1_0 ( https://github.com/GovernIB/sistra2/commit/b1380dff3750d3222705cb0d4fbbf980f0a0dfea)

**Comment by jcerdar-indra** [comment]
Al procesar un cuaderno, se permite crear dominios de área si no están creados en el entorno en el que se procesa: 
![#581](https://user-images.githubusercontent.com/96287364/177796796-adc2bba0-6592-47d3-a072-05fbe37a236c.gif)

**Comment by avillen-dgtic** [comment]
👍
