### ISSUE TITLE
Millora Ajuda Pagaments - Scripts

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#582]
Eliminar: (no surt a la pantalla Gestió Pagament)
Tipus de pagament: selector que pemite fixar el tipus de pagament disponible per a la taxa.

Cal descriure els conceptes exposats (passarel·les, necessitats de cada una, etc)

**Comment by aagudo-indra** [comment]
@jsastre-dgtic 

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se mejoran las ayudas de los pagos.

**Comment by jsastre-dgtic** [comment]
S'hauria d'informar del que cal per a TPV (properties)

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.2_1 (https://github.com/GovernIB/sistra2/commit/b308a01a1b1260bd6364486f0d4e26991fdd2093).

**Comment by jcerdar-indra** [comment]
![image](https://user-images.githubusercontent.com/96287364/184170120-d9bf7eab-a877-4ce0-b12a-5d9dbbc3fc26.png)

**Comment by jsastre-dgtic** [comment]
Permite --> Permet
![image](https://user-images.githubusercontent.com/18436867/188114913-7aa19578-5b60-418d-81f6-39448b9aa4e9.png)

**Comment by jsastre-dgtic** [comment]
Ja ho veim bé
