### ISSUE TITLE
Controlar errors PIB

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#583]
Validar passa pagament a STG: Si no es simula pagament s'ha d'emplenar script de pagament
Controlar passarel·les de pagament possibles. Valorar millora de l'API (ara falla amb 500 si es referencia una passarel·la que no existeix a les properties de PIB)

**Comment by jparedes-indra** [comment]
Se controla si existe o no script de pago si no se simula el pago.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/dba4d8f5-c729-4b18-a9ce-4d2fef47ee27)

También se controla que al guardar un script de pago, avise en caso de no haber añadido o haberlo hecho mal, una pasarela de pago de las configuradas en paymentib.properties. Para ello es necesario añadir una propiedad Pasarelas=”MOCK;ATIB;TPV”, que contenga las pasarelas configuradas.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/3e272e34-a72f-469a-87e8-7e526728cc56)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/c5130ef2-535a-45eb-a1f8-2cff6fc4c86b)

**Comment by avillen-dgtic** [comment]
👍
