### ISSUE TITLE
Correcció del bug m. cau a l'hora d'activar un tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#585]
Problema amb el refresc de la memòria cau:
· D'una banda STG invoca STT per inserir en taula STT_INVALI.
· A STT hi ha un job automàtic que s'executa cada minut i mira la taula STT_INVALI per veure si ha d'invalidar alguna cosa.
Hi ha un problema a la trucada de STG a STT, o al job auto de STT.

**Comment by avillen-dgtic** [comment]
👍
