### ISSUE TITLE
Eliminar text de pas "cal saber"

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#588]
Cal revisar el comportament quan s'eliminar el text del pas "cal saber"

**Comment by aagudo-indra** [comment]
@avillen-dgtic 

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se añade botón eliminar para poder borrar texto en debe saber.

![588](https://user-images.githubusercontent.com/88820558/182556653-6cb05d9e-b72c-431a-af4a-c2a56d1c77c7.gif)
