### ISSUE TITLE
Millores al suport: Quadre de comandament

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#589]
Referit al document de millores al suport i monitoratge dels tràmits i la plataforma

**Comment by jparedes-indra** [comment]
Se acuerda que en la versión 1.5.0 se entregue la funcionalidad “Cuadro de mandos y pantalla de alertas SISTRAHELP” y en la 1.5.1 la funcionalidad “Consulta de los formularios de incidencias desde SISTRAHELP".

**Comment by jsastre-dgtic** [comment]
Millores proposades:

1.- Accés al detall de l'error:

![image](https://user-images.githubusercontent.com/18436867/224968073-de4767cd-bd96-4cf1-87ae-5e56a80bca3c.png)

hauria d'accedir a:
![image](https://user-images.githubusercontent.com/18436867/224967859-a5179bbc-14ad-4683-8052-2ff3f62d57f6.png)

2.- Possibilitat de filtrar per "Data Inici" i "Data Fi" el "Quadre de Comandament"


3.- Corregir errors ortogràfics: Cuadre --> Quadre i Errores --> Errors

![image](https://user-images.githubusercontent.com/18436867/224969417-6c20885a-405f-4755-bce7-a936674769ce.png)

4.- Possibilitar definir una Alerta que contempli el resultat:
i) (Ok o KO) de l'esdeveniment, com per exemple la firma o el registre.
ii) (Tipus autenticació) de l'esdeveniment inici tràmit
iii) Pagaments (Ok o KO).
iv) etc.

5.- Possibilitar Alertes per un tràmit concret

6.- Botó switch (classificació per error o per tràmit)

7.- Incloure les seccions "Els més tramitats", "Els més Accedits", "Tramitació Dades totals: tramitacions, tramitacions amb pagament, tramitacions amb annexos, tramitacions amb firma..."

8.- Possibilitar la creació d'Alertes a nivell d'àrea.

**Comment by jparedes-indra** [comment]
Se han creado las dos funcionalidades, tal como se indica en el documento de análisis y estimación presentados.

![image](https://user-images.githubusercontent.com/67064375/231981600-bd01859d-affd-4b73-8552-a2c77e8e1bf3.png)

![image](https://user-images.githubusercontent.com/67064375/231981638-6dc5de1f-c07b-4e59-bc1c-895a9ee48fe9.png)

**Comment by avillen-dgtic** [comment]
👍

**Comment by jparedes-indra** [comment]
Se modifica algún literal y se añade la posibilidad de hacer doble click sobre un tipo de error y mostrar los detalles en un popup.

![imagen](https://user-images.githubusercontent.com/67064375/233858504-189d6da2-82fa-47cd-af2b-150378c958e3.png)

**Comment by jsastre-dgtic** [comment]
Detectat error a sth_pro (també passa a SE)
A DEV/PRE no ho podem reproduir per no tenir prou tràmits amb errades...

![err_sth](https://github.com/GovernIB/sistra2/assets/18436867/66669eb6-61ef-434f-8adb-c8b04af70b04)

**Comment by jparedes-indra** [comment]
Se han realizado modificaciones en el cuadro de mando para separar los errores de tramitación de los errores de plataforma. También se ha creado un panel nuevo para los trámites inacabados sin errores.
 
![image](https://github.com/GovernIB/sistra2/assets/67064375/f9d5936c-786f-4da7-bc5a-71876cc47178)
![image](https://github.com/GovernIB/sistra2/assets/67064375/248dc325-a0d7-409b-bbef-4eb959bb6d84)

Se ha completado la parte de gestión de incidencias, conforme al documento de análisis inicial. Se accede mediante la nueva opcion de menú.
 
![image](https://github.com/GovernIB/sistra2/assets/67064375/7b4ec686-4678-4632-8014-a4c4c78c4f2c)
![image](https://github.com/GovernIB/sistra2/assets/67064375/7bde628c-3b79-4d03-b781-dd07a514861b)

Queda pendiente añadir el control de la purga en las incidencias.

**Comment by avillen-dgtic** [comment]
![image](https://github.com/GovernIB/sistra2/assets/83401259/ae146970-e875-4004-8df5-11f51be94df0)

**Comment by jsastre-dgtic** [comment]
Atención --> Atenció

No té sentit un desplegable "errors per tràmit", perquè només hi ha una opció. Cal eliminar-lo, entenem.

![image](https://github.com/GovernIB/sistra2/assets/18436867/9be05dc4-8811-4f32-9c20-ac4fcebb6106)

**Comment by avillen-dgtic** [comment]
Les consultes des del formulari es guarden i es mostren a l'apartat de "Consulta incidències" 👍

**Comment by jparedes-indra** [comment]
El combo muestra una clasificación de los errores de tramitación: "Errores por trámite", pero en la versión 2 añadiremos la otra clasificación: "Trámites por error".

**Comment by jsastre-dgtic** [comment]
Tenint en compte el darrer comentari, per ara bastaria solucionar Atención --> Atenció.
En tenir la segona opció al desplegable ja tendrà sentit.

**Comment by jsastre-dgtic** [comment]
Validat literal, esperarem a tancar quan cobri sentit el desplegable
