### ISSUE TITLE
Comunicacions entre STG i STH

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#590]
Referit al document de millores entre les dues plataformes.

**Comment by aagudo-indra** [comment]
@avillen-dgtic 

Se desarrolla en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se añaden enlaces entre STG y STH para consultar diversas utilidades del otro entorno.

<img width="360" alt="image" src="https://user-images.githubusercontent.com/88820558/182557005-6307f653-9b55-419a-980e-96e6561bbfa7.png">

En STG se añade un botón que abre la pantalla de viewAuditoríaTramites con todas las entradas
relacionadas con la versión seleccionada.

<img width="360" alt="image" src="https://user-images.githubusercontent.com/88820558/182557046-18c3dc67-23ce-463e-8b26-2858d8c13624.png">

En STH se añade otro botón en el diálogo de evento que nos permite acceder a la definición de 
versión que provoca dicho evento.

<img width="360" alt="image" src="https://user-images.githubusercontent.com/88820558/182557101-1724edad-8034-48e9-816d-ddded3fabfb7.png">

<img width="360" alt="image" src="https://user-images.githubusercontent.com/88820558/182557122-6c925957-8474-4378-a956-c4282e5f8e4f.png">

**Comment by jsastre-dgtic** [comment]
![imatge](https://user-images.githubusercontent.com/18436867/182805574-a55e1165-3625-4c9e-90c9-e12efb1b4f31.png)

![imatge](https://user-images.githubusercontent.com/18436867/182805941-f2ee47da-db5f-4331-bff2-69fd4caef673.png)

**Comment by jcerdar-indra** [comment]
Contestado correo con las indicaciones.
