### ISSUE TITLE
Error esborrant una àrea no buida

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#591]
L'error apareix quan s'intenta esborrar una àrea que té associat un tràmit.
![image](https://user-images.githubusercontent.com/83401259/178239033-25b460e2-8a6e-4e34-894d-a61244f4e732.png)

**Comment by avillen-dgtic** [comment]
#515

**Comment by aagudo-indra** [comment]
@avillen-dgtic 

Solucionado en https://github.com/GovernIB/sistra2/issues/515
