### ISSUE TITLE
Desactivar els annexos signats

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#592]
Cal desactivar aquesta opció fins que el seu desenvolupament estigui fet a la v1.4. 
La issue associada és #109 
![image](https://user-images.githubusercontent.com/83401259/178242911-cadae1d1-17df-4366-8b8f-9d5c2fe7eb17.png)

**Comment by aagudo-indra** [comment]
@avillen-dgtic 

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se elimina opción anexar firmado

<img width="360" alt="image" src="https://user-images.githubusercontent.com/88820558/182557477-63e98544-b749-4e2e-90f5-be8ff3907892.png">

**Comment by jsastre-dgtic** [comment]
![imatge](https://user-images.githubusercontent.com/18436867/182813069-4eddb15e-77cd-4709-afc7-3fe145990428.png)
