### ISSUE TITLE
Barra desplaçament desapareix

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#593]
La barra de desplaçament desapareix quan cancel·les l'edició d'una entitat.
![#000](https://user-images.githubusercontent.com/83401259/178265905-fbb30089-33e6-4db0-8e68-5982a235aaab.gif)

**Comment by aagudo-indra** [comment]
@avillen-dgtic 

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

![593](https://user-images.githubusercontent.com/88820558/182558181-0550f464-d7a8-4bfa-ab20-20556cd06acd.gif)
