### ISSUE TITLE
Llistat canviant en l'ordre dels seus elements.

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#595]
El llistat és canviant en l'ordre. Associat a la issue #499
![image](https://user-images.githubusercontent.com/83401259/178474623-9e0481ce-27b4-4bc7-aab9-1737a00cf357.png)
![image](https://user-images.githubusercontent.com/83401259/178474878-e0859e22-2c58-4e64-96bd-41c918eed789.png)

**Comment by aagudo-indra** [comment]
@avillen-dgtic 

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

![595](https://user-images.githubusercontent.com/88820558/182558850-b60396d1-97c6-4734-b29a-f987b599dc35.gif)
