### ISSUE TITLE
Camp de cerca Cod.SIA

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#596]
Quan aferres un text al camp o introdueixes espais al començament o a l'acabament, la cerca retorna un buit. El text s'hauria de trimar abans de fer la consulta.

Referència a #528 

![#000](https://user-images.githubusercontent.com/83401259/178476914-2393306a-32d6-4f29-824a-2f0381a77f1f.gif)

**Comment by aagudo-indra** [comment]
@avillen-dgtic

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se corrige en [#566](https://github.com/GovernIB/sistra2/issues/566)

**Comment by jsastre-dgtic** [comment]
El camp de recerca funciona, però seguim sense poder copiar i aferrar:
![sel](https://user-images.githubusercontent.com/18436867/182811410-7be1c9d9-b5a6-4e65-8c01-e1c8d48d174f.gif)

**Comment by jcerdar-indra** [comment]
Correo enviado relacionado con esta issue. El punto anterior se puede mover a: https://github.com/GovernIB/sistra2/issues/558
