### ISSUE TITLE
Millorares als camps de cerca

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#597]
Estaria bé que els camps de cerca no fossin tan restrictius. 
Ara mateix, els camps fan una cerca caràcter a caràcter, és a dir, si el camp no comença amb el que hi ha a ddbb no el troba.
![image](https://user-images.githubusercontent.com/83401259/178480742-781f0423-f1fd-446a-8a8f-f9af1dd8dbd2.png)

![image](https://user-images.githubusercontent.com/83401259/178480759-64584c5c-5ff4-4713-baf5-2aaa5f0b23a4.png)

#532

**Comment by aagudo-indra** [comment]
@avillen-dgtic

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se corrige en [#566](https://github.com/GovernIB/sistra2/issues/566)
