### ISSUE TITLE
Evitar aferrar texts a qualcuns components

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#598]
Així com s'indica al correu, es manifesta la necessitat de no permetre aferrar texts a certs components.

**Comment by jparedes-indra** [comment]
Si se configura un componente de tipo texto para impedir pegar, en el formulario no se permite pegar texto sobre él.

![image](https://user-images.githubusercontent.com/67064375/231981958-d4604989-f799-4f86-a1f9-6ee7e54c164f.png)

![image](https://user-images.githubusercontent.com/67064375/231981992-23a130c9-3b5d-4dc1-adb4-ba20a448f4db.png)

**Comment by avillen-dgtic** [comment]
👍
