### ISSUE TITLE
Duplicar automàticament els dominis d'un tràmit

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#599]
Cal que quan es faci un duplicat d'un tràmit d'una àrea a una altra, també es dupliquin els dominis automàticament.
Això no s'està fent ara amb les importacions.

**Comment by aagudo-indra** [comment]
@avillen-dgtic

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Ahora al duplicar un trámite a otra área se duplican los dominios asociados a dicho trámite.

![599](https://user-images.githubusercontent.com/88820558/182560081-f64d52b0-3ee4-4ce0-872a-89f36b67c821.gif)
