### ISSUE TITLE
STT: Anàlisi funcional de pantalles per entitat

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#6]
Definició funcional l'assistent de tramitació i definició de les opcions a particularitzar per entitat. En concret es definirà:
- Assitent d'un pas de tramitació
- Assitent per emplenar un formulari

**Comment by amaciam-indra** [comment]
S'han incorporat al directori de documentació els esbossos de proposta per l'assistent de tramitació. El commit associat és el 41e3e43e28367bd9518c51a953706f3a4bf53a08

**Comment by rsanz-indra** [comment]
Queda pendiente revisión con DGDT de los bocetos realizados.

**Comment by sgelabert-dgtic** [comment]
- Respecte a la validació dels mockups adjunts a la issue es pre-selecciona 01_B en front 01.
- Respecte a la validació de l'esbós JavaScript http://caibter.indra.es/sistra2form/ s'informa dels problemes js relacionats amb la presentació de dates. desplegables predictius, etc.
- Es sol·licita avaluar la inclusió d'utilitats js/jQuery per incorporar al frontal camps d'escriptura predictiva (https://jqueryui.com/autocomplete/).
