### ISSUE TITLE
Esborrar un domini amb fonts de dades associades

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#600]
Quan s'esborra un domini amb fonts de dades associades, aquestes no s'esborren.
Cal que, quan s'esborri el domini es notifiqui a l'usuari que té una font de dades associada, i que si es continua amb l'acció, aquesta font de dades també s'esborrarà.

**Comment by aagudo-indra** [comment]
@avillen-dgtic

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Ahora si se borra un dominio con una fuente de datos y esta fuente de datos no tiene más dominios asociados, se elimina.

![600](https://user-images.githubusercontent.com/88820558/182560360-f2d6beda-d58f-4019-8495-82a5db07c9e8.gif)
