### ISSUE TITLE
No permetre exportar o generar quaderns de càrrega sent desenvolupador

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#601]
Quan tens el rol de desenvolupador i no tens accés a algunes àrees, quan pigues damunt "Visualitzar totes les àrees" es pot exportar i/o generar el quadern de càrrega.
Aquestes funcionalitats no haurien de ser permeses si no tens cap permís damunt d'aquestes àrees.

**Comment by jparedes-indra** [comment]
Funciona en DEV.

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/211281289-77477a1e-e2ea-47f2-8ef5-13011ade781e.png)
