### ISSUE TITLE
Límit als IDs dels tràmits i àrees

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#602]
Els límits dels ids pels tràmits i les àrees s'han vist afectats amb el canvi de la longitud per la composició composta. Cal augmentar aquestes mides.

**Comment by aagudo-indra** [comment]
@avillen-dgtic

Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se añade limitación a los ids y se comprueba que no exceda el tamanyo al generar id 
compuesto

**Comment by jsastre-dgtic** [comment]
1.- S'ha de poder copiar el contingut de tots els camps. En aquests 2 no podem:

![imatge](https://user-images.githubusercontent.com/18436867/182807402-a9883e33-b4de-4dc9-93dc-a23f20a6f7cb.png)

2.- SEGUIM AMB LA INCOHERÈNCIA DE DIFERENTS ID PEL MATEIX TRÀMIT:

![imatge](https://user-images.githubusercontent.com/18436867/182807654-4ae34de9-577a-461c-b3a9-18e480119b81.png)


3.- Quina és la limitació? A quin camp?
