### ISSUE TITLE
Problemes amb l'actualització de la taula STG_SESION

### ISSUE THREAD

**Issue by fjcalderon-dgtic** [GovernIB/sistra2#603]
Hem detectat un problema relacionat amb l'actualització de la taula STG_SESION, que provoca tant el nullPointer a l'hora que un usuari nou accedeixi als dominis d'àrea,

**Comment by jparedes-indra** [comment]
Funciona en DEV.

**Comment by jsastre-dgtic** [comment]
No entenem la casuística del problema, esperam en Paco...
