### ISSUE TITLE
Missatge mal format a les extensions d'annexos i processament a PRE

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/sistra2#604]
En la definició de les extensions permeses dels annexos, s'ha detectat que el missatge no està bé format. Tampoc es correcte el missatge al processar quaderns de càrrega en PRE.

![imagen](https://user-images.githubusercontent.com/67064375/179833780-4aa0856e-99af-447c-9aa6-d0a5f1bb9218.png)

![imagen](https://user-images.githubusercontent.com/67064375/179944545-4b3a4fee-4fd6-47b4-b40d-5a068167014f.png)

**Comment by aagudo-indra** [comment]
Se resuelve en el tag: [49adbe1](https://github.com/GovernIB/sistra2/commit/49adbe18fa3c9324e5314a3cb5bc6c1f8c3f0e8a)

Se corrigen los mensajes.

**Comment by jsastre-dgtic** [comment]
permesa, no permessa:

![imatge](https://user-images.githubusercontent.com/18436867/182806651-69be5ef5-414a-4e5d-87a9-aca29f2711d1.png)

Canviam doc per jpg, desam i segueix pensant que volem incloure doc:

![imatge](https://user-images.githubusercontent.com/18436867/182806866-98256c3d-18e0-47da-be0e-06bca48d0ae1.png)

No podem validar el tema de processar a pre perquè no veim a la imatge què posava ni quin és l'error a corregir (massa petita).

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.2_1 (https://github.com/GovernIB/sistra2/commit/b308a01a1b1260bd6364486f0d4e26991fdd2093).

**Comment by jcerdar-indra** [comment]
![image](https://user-images.githubusercontent.com/96287364/184169137-daa11f68-2a9a-4a44-8589-57b7bcb80f5b.png)

**Comment by jcerdar-indra** [comment]
En cuanto al punto 2, aunque se cambie a jpg, sigue habiendo una extensión doc en el listado, por ello salta la validación. 

Respecto al punto 3, al procesar un cuaderno de carga de un trámite se generaba un mensaje informativo indicando que no se había podido invalidar el trámite, pero en realidad sí se estaba realizando la invalidación. Se ha corregido este literal y ya se muestra adecuadamente.

**Comment by jsastre-dgtic** [comment]
ok
