### ISSUE TITLE
Fer visible que s'ha exportat la versió

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#607]
Ara quan exportam una versió, l'exporta i no te diu que ha acabat. Si tornam pitjar Exportar ho torna fer, i així successivament.
Una millora seria capturar l'acció feta i informar l'usuari de que s'ha acabat l'acció

![imatge](https://user-images.githubusercontent.com/18436867/183025077-e12622db-63f5-4ff8-90fe-4227971176f7.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Aparece el mensaje y se atenúa el botón “Exportar”, con lo que no puede ser pulsado sucesivamente en esa misma pantalla.

![image](https://user-images.githubusercontent.com/67064375/206700174-b63f2839-9eac-48f4-823d-d0703c80388f.png)

**Comment by jsastre-dgtic** [comment]
ok

**Comment by jsastre-dgtic** [comment]
Passa el mateix exportant dominis... 
![export](https://user-images.githubusercontent.com/18436867/208655052-3d54055c-2921-4191-8259-dfb57cef0dd0.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by avillen-dgtic** [comment]
👍
