### ISSUE TITLE
A les configuracions d'autenticació no s'estan substituint els placeholders correctament

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#608]
l'usu/pwd que envia SISTRAMIT als dominis remots és incorrecte i apareix l'error 401 Unauthorized

![imatge](https://user-images.githubusercontent.com/18436867/183046126-3be8d9ff-dc88-462b-a4c0-2359231929ee.png)

**Comment by jcerdar-indra** [comment]
Ya se sustituyen correctamente los placeholder en las configuraciones de autenticación al obtenerlas desde SISTRAMIT.

**Comment by jsastre-dgtic** [comment]
Ja funciona
