### ISSUE TITLE
 Fer que l'esdeveniment valoració apareixi al filtre desplegable de STH

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#610]
![imatge](https://user-images.githubusercontent.com/18436867/183347248-ab10d9bf-0ba6-4274-86a5-39397fc51f80.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.3.2_1 (b308a01).

**Comment by jcerdar-indra** [comment]
![image](https://user-images.githubusercontent.com/96287364/184167591-30a0fe8f-9cd9-4ab9-9523-82196b6de602.png)

**Comment by avillen-dgtic** [comment]
👍
