### ISSUE TITLE
El botó copiar no copia però diu que si (pro)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#611]
![imatge](https://user-images.githubusercontent.com/18436867/183370760-7543f90f-3bca-4e73-8af6-6eed6a477a62.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Se copia el elemento seleccionado con el menú contextual y se pega correctamente.

![image](https://user-images.githubusercontent.com/67064375/206700682-57288323-9145-425c-bd69-19bf83cf3640.png)

**Comment by jsastre-dgtic** [comment]
ok
