### ISSUE TITLE
Mantenir la configuració d'autenticació al cridar DR des de Formulari

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#612]
![imatge](https://user-images.githubusercontent.com/18436867/184323892-5895d15e-0efc-4340-9080-8fdc9b1d0a91.png)

**Comment by avillen-dgtic** [comment]
![#000](https://user-images.githubusercontent.com/83401259/187621067-93b7de19-f002-4ca3-8e57-d0041a2dae7f.gif)

**Comment by avillen-dgtic** [comment]
👍
