### ISSUE TITLE
La migració dóna un err ConstraintViolationException

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#613]
Tant a DEV com a SE:

![imatge](https://user-images.githubusercontent.com/18436867/184325837-1ab5751b-1edc-4e5c-8824-3ae0067f3176.png)

![imatge](https://user-images.githubusercontent.com/18436867/184325918-c29b8000-0083-4629-b5c8-e1bf4b75bfe6.png)

**Comment by avillen-dgtic** [comment]
👍
