### ISSUE TITLE
Actualitzeu el contingut dels scripts per quan es dupliqui un tràmit en una altra àrea, tingueu en compte aquests canvis

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#614]
Ara el procediment per a promocionar una producció tots aquests desenvolupaments en SISTRA2, que cridin en els seus scripts a dominis personalitzats... 

1) duplicar primer aquest tràmit a l'àrea destinació que toqui
2) modificar manualment els scripts i verificar que funciona tot correctament
3) i finalment, generar el quadern de càrrega, des d'aquesta versió nova, a l'àrea destinació que toqui, la que s'utilitzarà en producció.

Demanam automatitzar i simplificar aquest procés

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf993).

Ahora se duplica la versión en otra área y se modifica la referencia del dominio de área en el script.

**Comment by avillen-dgtic** [comment]
👍
