### ISSUE TITLE
Millora pantalla previsualització STG

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#615]
1.- Eliminar limitació de resultats provinents de l'api de rolsac
2.- Poder filtrar en aquest desplegable, perquè comença a ser difícil trobar el PA que cerques.
3.- També podríem pensar si a banda de filtrar textualment, podríem posar 2 checks per visualitzar o no els tràmits no vigents o no incorporats a SIA.

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Se puede filtrar y marcar los checks de “Solo incorporados en SIA” y “Solo vigentes”.

![image](https://user-images.githubusercontent.com/67064375/206703501-16687861-fc15-41ca-a133-2ed9b12607d7.png)
![image](https://user-images.githubusercontent.com/67064375/206703521-193d69cc-34c1-42f2-b829-7000a303fa65.png)

No se ha implementado la funcionaidad "1.- Eliminar limitació de resultats provinents de l'api de rolsac", que puede hacerse en una issue aparte.

**Comment by jsastre-dgtic** [comment]
La pantalla mescla dos idiomes als checks nous

![image](https://user-images.githubusercontent.com/18436867/207031287-61ec664c-6159-4db9-a588-7b1ac3fac738.png)

**Comment by jsastre-dgtic** [comment]
ok

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

Se añade la funcionalidad 1, dejando un límite de 200.

**Comment by avillen-dgtic** [comment]
👍
