### ISSUE TITLE
Verificació dels CIF

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#616]
Cal revisar la verificació dels CIF per a persones jurídiques.
El CIF utilitzat, que és erroni, és Q28080141 (Universidad Complutense de Madrid), i la validació per defecte de NIF de persona jurídica de SISTRA2 ho dóna com a bo.

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf993).

Ahora, un campo de texto de tipo identificador, como NIF de persona jurídica, valida correctamente los datos introducidos y no genera falsos positivos.

![image](https://user-images.githubusercontent.com/67064375/206697957-6ad22df0-6cd1-415f-abe0-06e23412659c.png)
![image](https://user-images.githubusercontent.com/67064375/206697970-e2f914fc-27ae-407a-bfc9-ea176ed89e9e.png)

**Comment by jsastre-dgtic** [comment]
ok
