### ISSUE TITLE
Problemes amb el DEBUG dels tràmits

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#617]
El DEBUG de tramitació a l’entorn de Serveis Estables ([https://se.caib.es/sistramitfront/debug/logSesionTramitacion.html] no funciona (no treu informació en cas d’error).

**Comment by jsastre-dgtic** [comment]
![imatge](https://user-images.githubusercontent.com/18436867/187871506-aba9ed3d-cb35-42ce-9185-2e5e0eeb6910.png)

**Comment by jsastre-dgtic** [comment]
No torna funcionar...

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/231982216-278bd4f7-a684-4efc-b416-9d20534b7931.png)

**Comment by avillen-dgtic** [comment]
👍
