### ISSUE TITLE
Error intentant migrar TF0101SOLCER --> SOL_CERT (i no està duplicat):

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#621]
Excepció: javax.ejb.EJBException
Missatge: es.caib.sistrages.core.api.exception.migracion.MigracionException: No tiene el destino adecuado

![imatge](https://user-images.githubusercontent.com/18436867/188416507-c9674e9f-f915-405d-b6b3-948521831e90.png)

**Comment by jsastre-dgtic** [comment]
Si falla, potser seria millor que no creàs la versió. Veiem que la crea sense formulari:
A més l'identificador no és correcte (caib.treball hauria de ser transparent per l'usuari)

![image](https://user-images.githubusercontent.com/18436867/188563821-ff429036-686f-41c0-aada-3d547143506e.png)

**Comment by jsastre-dgtic** [comment]
Aquest tràmit és de consulta (retorna un resultat en pdf). Això no està implementat a S2, però s'hauria de controlar l'error.

**Comment by jcerdar-indra** [comment]
Se añade más detalle en la excepción que se produce en estos casos en el TAG 1.3.2_3 ([6103692](https://github.com/GovernIB/sistra2/commit/610369220b7f5e572e5241b3122c3b291cec8528))

![image](https://user-images.githubusercontent.com/96287364/188843004-2c5c5502-5b2a-4e05-8cbb-721e907977e8.png)

**Comment by jsastre-dgtic** [comment]
D'acord, però seria possible posar aquest missatge (El tràmit té el camp 'Destinació del tràmit' amb valor 'Consulta' o 'Assistent' i per això no es pot migrar) dins una capseta groga i no fer botar excepció?

![image](https://user-images.githubusercontent.com/18436867/189298172-3a1183b0-8576-4b54-8158-d0f50443d8fc.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Sale un mensaje en lugar de una excepción.

**Comment by jsastre-dgtic** [comment]
Se'ns informa via wapp que no funciona però ja resolt es posarà a la 1.4.1_1

**Comment by avillen-dgtic** [comment]
Incoherència amb els missatges, diu que la migració s'ha fet però després mostra un error que diu que no s'ha fet. 

![image](https://user-images.githubusercontent.com/83401259/209310189-b9343ee5-793a-4146-aa36-a56c412455db.png)

![image](https://user-images.githubusercontent.com/83401259/209310161-51396345-b564-4d0f-997f-7c430a35e883.png)

**Comment by avillen-dgtic** [comment]
![image](https://user-images.githubusercontent.com/83401259/210065780-c311fc50-aef5-4011-9bc4-4af3e8d26a66.png)
![image](https://user-images.githubusercontent.com/83401259/210065791-83bd5102-2667-4023-9097-73c04b77497f.png)

👍
