### ISSUE TITLE
Error intentant migrar IN0008IBSA cap QSSI_QUEIXES de l'àrea de IBSALUT

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#622]
![image](https://user-images.githubusercontent.com/83401259/188443590-205e7ed0-f9a7-4c77-9754-7895fa37321d.png)

**Comment by jsastre-dgtic** [comment]
Degut a un camp de text de 10000 caràcters. Cal truncar el camp a S2.

**Comment by jcerdar-indra** [comment]
Se soluciona este error en el TAG 1.3.2_3 ([6103692](https://github.com/GovernIB/sistra2/commit/610369220b7f5e572e5241b3122c3b291cec8528))

![image](https://user-images.githubusercontent.com/96287364/188843336-fec9a30f-0abc-4c01-9a17-59ae427564f4.png)

**Comment by avillen-dgtic** [comment]
👍
