### ISSUE TITLE
Error intentant migrar SC00051USEL cap BORSA_UNICA a l'àrea d'IBSALUT

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#623]
![image](https://user-images.githubusercontent.com/83401259/188575651-84a69522-c81f-4a9e-a20a-7f59653a8329.png)

**Comment by jsastre-dgtic** [comment]
Relacionat amb un Id d'un camp ocult inexistent.

**Comment by jcerdar-indra** [comment]
Se soluciona este error en el TAG 1.3.2_3 ([6103692](https://github.com/GovernIB/sistra2/commit/610369220b7f5e572e5241b3122c3b291cec8528))

**Comment by avillen-dgtic** [comment]
👍
