### ISSUE TITLE
No funciona la recerca si posam un espai al final

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#626]
![image](https://user-images.githubusercontent.com/18436867/189284451-733c2f97-a986-44b3-af79-b1a3281af429.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Se puede buscar por mayúsculas y minúsculas y poner un espacio al final y encuentra el resultado apropiado.

![image](https://user-images.githubusercontent.com/67064375/206701340-b0f0734f-76bd-4958-b9ad-1d1c9e6df986.png)

**Comment by jsastre-dgtic** [comment]
ok, comprovat
