### ISSUE TITLE
Canvi definicions als literals STG

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#627]
Per tal de ser coherents amb rolsac i la resta d'Administracions, hauríem de parlar sempre de tràmits associats a PA/SV (Procediment Administratiu/Servei)

![image](https://user-images.githubusercontent.com/18436867/190371249-33cf538d-acf5-4682-9ed1-97b22c11b51e.png)

**Comment by jsastre-dgtic** [comment]
Si tipus és Servei no ha de sortir "5. Registrar", sinó "5. Finalitzar"

![image](https://user-images.githubusercontent.com/18436867/190376417-e1954bb7-5b39-438f-aa5c-5f8826ff1edf.png)

**Comment by jsastre-dgtic** [comment]
No sabem com funciona l'Enviament remot perquè no surt a l'ajuda

![image](https://user-images.githubusercontent.com/18436867/190377208-bc4b7af5-1156-4a12-9101-1c8c026738a9.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag sistra2-1.4.0_0 (c0e2029).

![imagen](https://user-images.githubusercontent.com/67064375/198518937-e0a0475b-a234-455b-8c61-4729b4d0bfe0.png)

**Comment by avillen-dgtic** [comment]
👍
