### ISSUE TITLE
Desactivar la casella de selecció "Sense autenticació" quan es tria Tipus=PA

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#628]
Tot són tràmits, i poden pertànyer a un Procediment Administratiu (PA) o a un Servei (SV)

![image](https://user-images.githubusercontent.com/18436867/190566929-31259b36-acc6-4477-a962-1791567f7485.png)

**Comment by jsastre-dgtic** [comment]
Deixam aquesta en Stand-by

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf993).

Cuando seleccionas el tipo PA, si estaba activo el check “sin autenticación”, se desactiva y queda atenuado, con lo que no se puede activar. 

![image](https://user-images.githubusercontent.com/67064375/206697653-2ca0a9b3-6de0-4e12-9bc0-3adf277de79d.png)

**Comment by jsastre-dgtic** [comment]
No el veim desactivat:

![image](https://user-images.githubusercontent.com/18436867/207287083-1b0640f3-4d2d-49f6-9c1f-2b909e6fbe3f.png)


![image](https://user-images.githubusercontent.com/18436867/207287107-f3aae7ae-2f5d-42a0-9cfb-cd4eb382b3ce.png)

**Comment by jsastre-dgtic** [comment]
Si passa que no es pot tornar a activar, però l'atenuació deixant la casella activada pot dur a confusions...

**Comment by jsastre-dgtic** [comment]
Resta pendent d'script per actualitzar checks ja marcats

**Comment by jsastre-dgtic** [comment]
Tot ok llevat d'informar l'usuari perquè no funciona el check de Sense autenticació. Potser podria sortir un emergent en cas que s'intenti marcar-lo tenint PA seleccionat.

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by avillen-dgtic** [comment]
👍
