### ISSUE TITLE
No funciona scroll de tràmits en triar àrea

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#629]
![image](https://user-images.githubusercontent.com/18436867/192453424-cc4be21f-bcf8-446a-b1af-c4376345a0b1.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Ya funciona el scroll.

![image](https://user-images.githubusercontent.com/67064375/206701702-f4498689-51e9-4418-8141-697408ca5a75.png)
