### ISSUE TITLE
MGR: estudi de tràmits candidats a ser migrats a Sistra2

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#63]
Migració tràmits Sistra1 a Sistra2: es vol que es faci un estudi de tràmits candidats a ser migrats a Sistra2. El major entrebanc seria que gairebé tots els formularis de Sistra1 són multipàgina (en part a causa dels problemes tècnics que tenia FORMS per gestionar pàgines amb bastants camps). Es farà un estudi de tràmits amb formularis simples que puguin ser tractats com un formulari únic.

**Comment by rsanz-indra** [comment]
Se ha realizado estudio de migración y propuesta de migración de trámites junto con planificación de mejoras.

**Comment by jsastre-dgtic** [comment]
Després d'una reunió interna hem pres les següents decisions, atenent també a l'estat d'alguns desenvolupament de Distribució i Ripea.

- En primer lloc, per a la fase V0, considerem que de moment ens hem de centrar en quatre candidats.

- Instància genèrica de la CAIB.
- Tràmit plantilla ja definit al Github.
- [IN0026SIPR] - Sol·licitud d'inici de projecte per al desenvolupament de tràmits telemàtics.
- [AP0041PSAG] - Autorització per a la pesca marítima submarina al Parc natural de s'Albufera des Grau.

Aquest últim és de la D.G. de Pesca, no té integració i hem confirmat que els gestors ens ajudaran a provar i testejar la migració.

Més enllà d'aquesta primera fase, i tenint present que aquest cicle ja ho hem tancat, de cara al següent considerem oportú prioritzar aquells aspectes que vagin adreçats a incloure, en el procés de migració, alguns dels tràmits dels nostres millors clients, és a dir , per exemple UDIT, Educació, Pesca, Treball i algun més. En altres paraules, la nostra idea és comptar amb els tècnics d'aquests organismes que coneixem de fa anys i oferir-los dues coses:

1. - prioritzar aquelles millores en SISTRA2 que possibilitarien la migració d'alguns dels seus tràmits.
2. - organitzar jornades de formació per a ensenyar-los la nova plataforma i explicar-los tots els bakoffice, des d'un punt de vista del desenvolupador.

Respecte al punt 1 i de cara a concretar noves fites del següent cicle, després de revisar el full de càlcul que ens vau presentar, cconsidero que hi ha tres característiques que destaquen, per sobre de les altres:

- camps ocults
- formulari multipàgina
- gestor de formularis externs (molt centrat en les necessitats actuals d'Educació) 
- camp llista d'elements.

Les dues primeres característiques les considero bàsiques i que caldria prioritzar. Les dues últimes, podrien quedar per més endavant. Però per prendre aquesta decisió considero que és vital conèixer l'estimació de cost i esforç per implementar cadascuna d'aquestes característiques, perquè si el formulari multipàgina, per posar un exemple, considereu que requereix un temps considerable, en comparació al cost d'implementar el gestor de formularis externs o la llista d'elements, hauríem de tenir en compte per marcar de forma definitiva les noves prioritats.

Per la nostra part, prioritzarem la necessitat d'implementar l'opció d'integracions entre "Distribució" i "backoffices departamentals", perquè això no suposi una trava en els propers mesos.

**Comment by rsanz-indra** [comment]
Entendemos que la tarea de estudio de trámites candidatos se puede dar por finalizada tras el estudio realizado y la planificación que se va a realizar para Lote2
