### ISSUE TITLE
Compatibilitat de Safari amb annexar arxius

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#631]

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Ya funciona en Safari en macOS.

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Ya funciona en Safari en macOS.

**Comment by jsastre-dgtic** [comment]
Esperam a tenir-ho en pro per la dificultat de validar-ho a dev amb VM

**Comment by jsastre-dgtic** [comment]
Comprovat!
