### ISSUE TITLE
Tractament previsualització en cas de no SIA o no vigent.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#632]
Llançar un avís en prémer Previsualitzar o Copiar, en cas que el tràmit de Rolsac no estigui vigent o no tingui SIA i no avançaria a STT. En cas que es marqui Simular, sí que permetria la previsualització i la còpia.

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Ahora, si se selecciona un trámite de ROLSAC que está sin vigencia o no tiene código SIA, el sistema lo avisa y no permite previsualizar ni copiar enlace.

![image](https://user-images.githubusercontent.com/67064375/206702226-b1f8d67e-dc18-4bbd-8639-e2365960e456.png)

Además, si no se indica trámite ROLSAC, también lo indica y si se marca el check “Simular”, permite previsualizar y copiar enlace.
