### ISSUE TITLE
Incloure una propietat per activar o desactivar la possibilitat d'implementar tràmits tipus Serveis a S2

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#633]
![image](https://user-images.githubusercontent.com/18436867/193811062-d97f2b11-bf06-413f-b7b6-b2482064f52c.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf993).

Con la propiedad en sistrages.properties, permetreServeis=false, no se permite configurar el trámite como un servicio.

![image](https://user-images.githubusercontent.com/67064375/206698241-572f0b3d-4bc5-4bd9-b998-3ef427ddc302.png)
![image](https://user-images.githubusercontent.com/67064375/206698259-a2343c86-6656-4369-88bb-5979bcff8432.png)

**Comment by jsastre-dgtic** [comment]
2 observacions:
1.- Si canviam la propietat a true i reiniciam tampoc no surt l'opció Servei

![image](https://user-images.githubusercontent.com/18436867/207539463-626fd20e-7b21-4c20-8a07-09ea4cf59739.png)


2.- Es demanava deixar-ho en gris i no seleccionable, no eliminar-ho visualment

![image](https://user-images.githubusercontent.com/18436867/207539612-b244b951-ead6-4ca3-b590-df7759a42523.png)

**Comment by jparedes-indra** [comment]
Se acuerda que si la propiedad está a false, debe ocultarse la opción de "Envios remotos" a nivel entidad y de "Envio remoto" de área...

**Comment by jsastre-dgtic** [comment]
ok, trobam a faltar el mateix que a Sense Autenticar, una explicació en growl de perquè no funciona activar el check de Servei. Visualment no queda res atenuat, perquè només s'atenuava el check blau, no la lletra normal... 

![image](https://user-images.githubusercontent.com/18436867/208429648-301d7d4d-668f-4ce7-8c59-a6af262d7853.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by avillen-dgtic** [comment]
👍

**Comment by jsastre-dgtic** [comment]
No surt atenuat el Servei (com surt Sense autenticació), tot i que no es pot seleccionar per tenir a false la propietat. 
# Admetre definir un tràmit tipus Servei
admetreServeis=false

<img width="1138" height="703" alt="Image" src="https://github.com/user-attachments/assets/2bff1f2f-efcc-4f72-871f-6bad4439f3be" />
