### ISSUE TITLE
BUG a l'importar Dominis de Se a PRO

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#637]
Una vegada tenim un domini a SE, l'hauríem de poder importar a PRO. Dóna un error incoherent: "només es pot pujar a desenvolupament"

![image](https://user-images.githubusercontent.com/18436867/195011815-6d9a71ca-d18b-4e4a-82f7-4b28256c047e.png)

**Comment by jsastre-dgtic** [comment]
En importar a pro ja va bé. Cal canviar memòria caché per memòria cau...


![image](https://user-images.githubusercontent.com/18436867/208655542-3761afff-535c-419d-8040-1bf94a5efebf.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by avillen-dgtic** [comment]
👍
