### ISSUE TITLE
Canviar camp data de recerca

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#638]
Canviar la data de recerca a un dia abans, o una setmana. Que sigui una cosa que puguem decidir mitjançant una property

![image](https://user-images.githubusercontent.com/83401259/196348893-d8d16651-a392-4659-930f-689fb73e0444.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

En sistrahelp.properties se pueden indicar los días a restar alla fecha de inicio de la búsqueda, que se ejecuta automáticamente al cargar SISTRAHELP. Si pones filtroInicial=15 y hoy es día 17 de noviembre de 2022, aparece la fecha 2 de noviembre de 2022 como fecha de inicio. 

![image](https://user-images.githubusercontent.com/67064375/206704114-a41c93b0-1e82-4929-bf3b-b44b02347f56.png)
