### ISSUE TITLE
Eliminar limitació 4k caràcters

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#639]
Per poder definir la Declaració d'Accessibilitat a S2 ens hi trobem limitats amb la mida de caràcters que podem introduir.

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.4.0_1 ([f1de49e](https://github.com/GovernIB/sistra2/commit/f1de49e78bc7d983bd90849dc6b56c0746cb86fb))

**Comment by jcerdar-indra** [comment]
Se aum
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/96287364/201276269-6a32ff8e-5ff9-4368-9fad-4e88a99d90b9.png)
entan los caracteres permitidos en la declaración de accesibilidad:

**Comment by avillen-dgtic** [comment]
👍
