### ISSUE TITLE
Per a totes les pantalles de S2 fer que es redimensioni correctament

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#640]
![image](https://user-images.githubusercontent.com/18436867/198204405-ddc901b3-45a3-48d6-a69e-9874a2b34ada.png)

![image](https://user-images.githubusercontent.com/18436867/198213729-1b526784-876d-48b1-b528-1ffb79f629ca.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Se mejora la forma de gestionar los tamaños de los componentes de los popups para que aprovechen el espacio y coloquen las barras de desplazamiento apropiadamente.

![image](https://user-images.githubusercontent.com/67064375/206707926-81152b1e-97da-4b91-b173-5b65ce30c8b2.png)
![image](https://user-images.githubusercontent.com/67064375/206707947-f51b7adf-cbd0-4ce8-8fca-3334b25a8ee3.png)
