### ISSUE TITLE
Traduir a l'anglès els literals de sistramit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#641]

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Se muestran las pantallas en inglés.

![image](https://user-images.githubusercontent.com/67064375/206705245-4d1dec9a-d094-4ecd-b601-ecd797ae631c.png)
![image](https://user-images.githubusercontent.com/67064375/206705263-369abac5-439e-49fa-b840-0ee6e9c749ab.png)
![image](https://user-images.githubusercontent.com/67064375/206705285-5e1d1053-07b8-4123-8a11-47c97f6d2f5e.png)
![image](https://user-images.githubusercontent.com/67064375/206705310-3f430bd0-5ac1-496b-85ac-1523b1fd7fb4.png)
![image](https://user-images.githubusercontent.com/67064375/206705410-786b12ac-ba39-4f3a-8b34-e32e7a520b72.png)

**Comment by jsastre-dgtic** [comment]
En introduir l'anglès i intentar validar, acabam en un error no controlat

![validacions_err](https://user-images.githubusercontent.com/18436867/207560723-132c076c-9ffa-4a58-af4a-4ca8e7095bef.gif)

**Comment by jsastre-dgtic** [comment]
Pitjant el botó corregir, passa el mateix error no controlat

**Comment by jsastre-dgtic** [comment]
Si fem ús d'una SR no podem corregir introduint l'idioma nou

![image](https://user-images.githubusercontent.com/18436867/207565484-a3777987-1b00-418d-bbb2-91cf579db21d.png)

**Comment by jsastre-dgtic** [comment]
Si introduïm un camp qualsevol, per defecte s'emplena "camp" a la descripció catalana, "campo" a la castellana, però a l'anglès res...

![image](https://user-images.githubusercontent.com/18436867/207566028-774fb427-544d-493e-95c6-93e80a56f1ac.png)

**Comment by jsastre-dgtic** [comment]
Si introduïm un nom de camp, a la previsualització també falla

![image](https://user-images.githubusercontent.com/18436867/207566278-c7e163db-86ac-4bd8-95fa-f70a621f7acb.png)


Aquesta pantalla d'error no és responsive.... hauria de mostrar més info sense scroll:

![image](https://user-images.githubusercontent.com/18436867/207566542-c8d6c000-61fb-4afb-9bca-6a8252b5ebc4.png)

**Comment by jsastre-dgtic** [comment]
En pitjar "tornar" hauria de tornar a la versió del TEST-JST, no a la pantalla de tots els tràmits:

![tornar_pant origen](https://user-images.githubusercontent.com/18436867/207566994-6666bbe3-ca7a-4c45-b855-a692f23738c8.gif)

**Comment by jsastre-dgtic** [comment]
gif sobre com reproduir el null pointer:

![angles_validacions](https://user-images.githubusercontent.com/18436867/207839856-cef938bb-1592-4002-b9f5-d05090fb686f.gif)

**Comment by jsastre-dgtic** [comment]
ok, ja no falla
