### ISSUE TITLE
Taula de SR no es refresca

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#643]
Després de crear un SR, dins de la gestió de seccions reutilitzables, la taula no es refresca amb el nou SR.
ref. #530

**Comment by jparedes-indra** [comment]
Se resuelve en la revision 1.4.0_1 (0abdce8).

Al crear una SR se actualiza la lista automáticamente.

**Comment by avillen-dgtic** [comment]
👍
