### ISSUE TITLE
Checkbox sense memòria

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#644]
Quan es crea una SR nova, el checkbox no guarda l'estat.

![image](https://user-images.githubusercontent.com/83401259/199699419-5081ded9-488e-4260-ba99-4a6c06db20f2.png)
![image](https://user-images.githubusercontent.com/83401259/199699434-f7aa9ac0-c021-462f-b50c-e46402659bde.png)

Ref. #530

**Comment by jparedes-indra** [comment]
Se resuelve en la revisión 1.4.0_1 (0abdce8).

Cuando pulsas "Desar", se mantiene el check como estaba antes de pulsar dicho botón.

![imagen](https://user-images.githubusercontent.com/67064375/201205284-cfc9adcf-544f-4540-bfeb-25973f577ea0.png)

**Comment by avillen-dgtic** [comment]
👍
