### ISSUE TITLE
Diàleg exportar SR no es tanca

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#645]
Després de fer una exportació de qualsevol SR, el diàleg d'exportació no es tanca.
![image](https://user-images.githubusercontent.com/83401259/199700864-24ad2473-0cf3-4650-9c8e-370962383432.png)

Ref. #530

**Comment by jparedes-indra** [comment]
Se resuelve en la revisión 1.4.0_1 (0abdce8).

Ahora se cierra la pantalla tras exportar y pulsar "Cerrar" o la cruz de la parte superior derecha.

**Comment by avillen-dgtic** [comment]
👍
