### ISSUE TITLE
Augmentar a 50 caràcters els identificadors de Dominis i Tràmits

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#647]
Augmentar a 50 caràcters els identificadors de Dominis i Tràmits

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Tanto en dominios como en trámites se pueden indicar identificadores de hasta 50 caracteres y queda limitado ese campo en STG.

![image](https://user-images.githubusercontent.com/67064375/206705730-73093a65-cac0-4f6a-a459-2bc2df9cced9.png)
![image](https://user-images.githubusercontent.com/67064375/206705747-48e9bed9-c8e2-4076-9355-6267a3352f20.png)
