### ISSUE TITLE
Minúscules als identificadors de camps

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#648]
![ids_majuscules](https://user-images.githubusercontent.com/18436867/199916920-3c09374a-72b8-46b7-b88d-3e3783f94c28.gif)

**Comment by jsastre-dgtic** [comment]
ref. https://github.com/GovernIB/sistra2/issues/530 (però imagin que passa als camps en general)

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.4.0_1 ([f1de49e](https://github.com/GovernIB/sistra2/commit/f1de49e78bc7d983bd90849dc6b56c0746cb86fb))

**Comment by avillen-dgtic** [comment]
👍
