### ISSUE TITLE
STG:  Generar ajuda online dels diferents mòduls 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#65]
Aquesta ajuda online ha d'anar a un directori del servidor en format html i fora del ear per tal de poder mantenir-la sense haver de desplegar l'ear cada vegada que es produeixi un petit canvi.

**Comment by jsastre-dgtic** [comment]
1. Accedir a SISTRAGESBACK amb perfil de SuperAdministrador, situar-se a la pantalla "Gestió d'Entitats" i pijtar el botó "Ajuda". Validar tant estructura com contingut de l'ajuda de la pantalla.
Dubtes: Què passa amb els tràmits associats a una Entitat si esborram l'Entitat? Hi ha manera de recuperar-ho?
L'Ajuda ens pareix bé... 

2. Editar entitat, obrir ajuda de diàleg d'entitat i validar contingut i estructura de l'ajuda -> Ok

**Comment by rsanz-indra** [comment]
Se ha generado el contenido de la ayuda para la vista de Superadministrador.

Se ha implementado la ventana de ayuda para los plugins accesibles desde la ventana de script (externalización de las paginas de ayuda a ficheros html, la navegación entre el plugin y sus métodos, la estructura de la ayuda así como el mecanismo para copy&paste de los métodos). Queda pendiente mostrar los plugins accesibles según cada script y generar el contenido de las ayudas para cada plugin.

**Comment by jsastre-dgtic** [comment]
PLUGIN_VALIDACIONES
![image](https://user-images.githubusercontent.com/18436867/51246392-aec77800-198a-11e9-86e2-acc4df960acb.png)

**Comment by amaciam-indra** [comment]
La ajuda d'aquest plugin encara no està implementada. Només es poden validar les indicades al resum de proves a realitzar:

Entrar a la pantalla d'edició de algun dels scripts de la versió del tràmit i revisar l'ajuda de PLUGIN_LOG, PLUGIN_DOMINIOS, PLUGIN_ERROR, VALORES_DOMINIO, FICHERO, MENSAJE_VALIDACION, PLUGIN_MENSAJEVALIDACION i PARAMETROS_DOMINIO.

**Comment by jsastre-dgtic** [comment]
Ok...

**Comment by jsastre-dgtic** [comment]
**IMPORTANT:** Aquesta ajuda online ha d'anar a un directori del servidor en format html i fora del ear per tal de poder mantenir-la sense haver de desplegar l'ear cada vegada que es produeixi un petit canvi.

**Comment by rsanz-indra** [comment]
Se ha implementado la ventana asistida para script junto a la generación de los contenidos de todas las ayudas de plugins.
Quedan pendientes la generación de ayudas para las pantallas de vista de Administrador Entidad / Desarrollador.

**Comment by jsastre-dgtic** [comment]
Tancam aquesta i obrim nova issue: https://github.com/GovernIB/sistra2/issues/121#issue-431861046
