### ISSUE TITLE
Les SR no detecten l'existència dels Dominis Globals si es referencien per script

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#650]
![image](https://user-images.githubusercontent.com/18436867/199920676-db9ce20e-da34-416f-b4d5-2c383f705b68.png)

es.caib.sistramit.core.api.exception.EngineScriptException: Error executant script: org.mozilla.javascript.WrappedException: Wrapped es.caib.sistramit.core.api.exception.DominioNoExisteException: No existeix domini GLOBAL.PROVINCIES en la definició del tràmit (<Unknown source>#8) in <Unknown source> at line number 8

**Comment by jsastre-dgtic** [comment]
ref. https://github.com/GovernIB/sistra2/issues/530

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.4.0_1 ([f1de49e](https://github.com/GovernIB/sistra2/commit/f1de49e78bc7d983bd90849dc6b56c0746cb86fb))

Ya se añaden los dominios que se incovan por script a la lista de dominios de un trámite
