### ISSUE TITLE
Que el formatador genèric tengui en compte les pàgines per on s'ha escrit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#651]
En aquests moments, el formatador no contempla la possibilitat que el flux de pantalles d'un tràmit no sigui lineal. Això implica que al justificant es mostrin tots els camps del formulari: aquells que s'han utilitzat al flux de navegació del tràmit i també aquells pels quals l'usuari no ha passat.
El formatador automàtic només hauria de considerar els camps de les pàgines del formulari per on ha passat l'usuari i descartar els altres. D'aquesta manera, al justificant només es veurien els camps que l'usuari ha vist. A més, considerem que aquesta funcionalitat és especialment útil en aquells casos on es reutilitza un mateix formulari per a diferents casuístiques (lògiques complexes, procediments semblants,...)

**Comment by jparedes-indra** [comment]
Ahora, si una página no se rellena, no se muestra en el formateador genérico.

![image](https://github.com/GovernIB/sistra2/assets/67064375/9bbd0875-262f-46f4-ac0f-18ed49f20e4c)

**Comment by jsastre-dgtic** [comment]
Al tràmit: 
https://dev.caib.es/sistramitfront/asistente/iniciarTramite.html?tramite=CAIB.TESTS.TEST_AVH&version=14&idioma=ca&servicioCatalogo=false&idTramiteCatalogo=$--SIMULADO--$

tenim la 2a pàgina en blanc que no emplenam:

![image](https://github.com/GovernIB/sistra2/assets/18436867/d2ca80e4-166b-4760-89b2-67bbf7d0b09f)

![image](https://github.com/GovernIB/sistra2/assets/18436867/8e5e3b9d-d726-4886-a80d-a79c84efb948)

Al justificant surten les 2 pàg on no hem emplenat res:

![image](https://github.com/GovernIB/sistra2/assets/18436867/bf9b78de-4834-461a-9aac-20dcaf17a5d4)

**Comment by avillen-dgtic** [comment]
👍
