### ISSUE TITLE
Modificar ajudes per a alinear mides de camps sicres3

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#652]
Indicar a l'ajuda del PLUGIN dels scripts apropiats, el nombre de caràcters màxim que cal utilitzar en cas d'emplenar els camps utilitzant la informació que ve d'aquestes aplicacions. 
Proposaríem incloure una referència a sicres3

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Se modifican las ayudas de los métodos que obtienen el nombre y órgano destino del trámite y del procedimiento asociado, para indicar la longitud proveniente de ROLSAC.

![image](https://user-images.githubusercontent.com/67064375/206705949-9c14a2d1-eab6-418a-9590-7cb549532ee5.png)

**Comment by jsastre-dgtic** [comment]
ok...
