### ISSUE TITLE
No apareix botó de guardar sense finalitzar

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#653]
![image](https://user-images.githubusercontent.com/83401259/200290142-0ae16104-3a9b-4096-9662-f5634422b299.png)
 
Quan es pica aquesta opció, al tràmit no apareix el botó.

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.4.0_1 ([f1de49e](https://github.com/GovernIB/sistra2/commit/f1de49e78bc7d983bd90849dc6b56c0746cb86fb))

**Comment by jcerdar-indra** [comment]
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/96287364/201276042-30568991-7ab7-4dfa-afde-f32bdcf89692.png)

**Comment by avillen-dgtic** [comment]
El botó surt, però no resol el problema.
![image](https://user-images.githubusercontent.com/83401259/201312335-513443ee-2f20-418a-8d7b-720410244f6f.png)
![image](https://user-images.githubusercontent.com/83401259/201312440-ff840ee9-b9ca-48bf-abe6-9fb85efb4d10.png)

**Comment by avillen-dgtic** [comment]
![image](https://user-images.githubusercontent.com/83401259/201312657-7cd5230b-a1d8-4d04-8ca4-d82ba5c17b00.png)

**Comment by avillen-dgtic** [comment]
![#000](https://user-images.githubusercontent.com/83401259/201867304-695c769f-fbb7-4234-af47-28d22e8e0b87.gif)

**Comment by avillen-dgtic** [comment]
S'ha trobat l'error i no té res a veure amb la multipàgina.
