### ISSUE TITLE
En canviar el nom d'un Domini surt un missatge amb l'idioma equivocat

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#654]
El 2on missatge hauria de sortir en català i surt en castellà
![image](https://user-images.githubusercontent.com/18436867/201599113-6eb6545e-ba9d-4931-849b-5536638692e9.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.0_2 (aa47b4c).

Se ha optado por eliminar el mensaje, ya que es un mensaje interno de desarrollo.

**Comment by avillen-dgtic** [comment]
👍
