### ISSUE TITLE
Error duplicant versions dintre d'una mateixa àrea.

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#655]
Quan es duplica una versió dintre una mateixa àrea apareix aquest error. 

![image](https://user-images.githubusercontent.com/83401259/201909833-c99878c4-e474-4c32-8ac7-0c26050be80f.png)

![image](https://user-images.githubusercontent.com/83401259/201909846-6b2b0656-d731-4d01-8fd8-c6e6efd88f98.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Se duplica sin indicar que ya existe el dominio en esa área.

**Comment by jsastre-dgtic** [comment]
ok, però quan es duplica ha d'agafar focus en la versió acabada de crear 

![focus em duplicar ver](https://user-images.githubusercontent.com/18436867/207572549-02578315-9786-4530-9798-0608e05b21d6.gif)

**Comment by avillen-dgtic** [comment]
Agafa el focus, però no pagina fins a on està el focus

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by avillen-dgtic** [comment]
👍
