### ISSUE TITLE
Botons Corregir i Validar un tràmit sense feedback

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#656]
Els botons no tenen cap mena d'acció apreciable de cara a l'usuari. En aquest cas amb el tràmit hi ha un domini que no s'empra i el missatge de corregir no fa res, i tampoc notifica res.
![image](https://user-images.githubusercontent.com/83401259/201912519-565bd833-f758-4233-917b-3cd52c3a57f1.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Cuando el trámite está bloqueado y se detecta algo en la validación, no se puede corregir.

Cuando el trámite está desbloqueado y se detecta algo en la validación, si, por ejemplo, el dominio no se utiliza, al pulsar “Corregir” se elimina automáticamente.

**Comment by jsastre-dgtic** [comment]
https://github.com/GovernIB/sistra2/issues/641#issuecomment-1350771792

**Comment by avillen-dgtic** [comment]
👍  per a la correcció dels dominis no emprats
