### ISSUE TITLE
Problemes amb el captchas

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#657]
Arrel amb la issue #653 s'ha trobat que tot apunta al captcha. Quan s'intenta sortir d'un formulari amb multipàgina i un captcha buit el tràmit et duu a una plana "not found".

**Comment by jcerdar-indra** [comment]
Se resuelve en el tag 1.4.0 (a4b5cf2). Al tener un Captcha en un formulario multipágina, en caso de pulsarse el botón de 'Guardar y Salir' sin rellenar el Captcha, no se realiza la validación propia del Captcha y ya no aparece el error que se generaba antes.

**Comment by avillen-dgtic** [comment]
👍
