### ISSUE TITLE
Possibilitar arrossegar arxius per annexar arxius

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#659]

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.1_0 (293cf99).

Ahora es posible arrastrar un fichero desde el explorador de archivos, por ejemplo, y soltarlo dentro del cuadro de diálogo del paso anexar.

![image](https://user-images.githubusercontent.com/67064375/206709485-4222f9fd-03d1-4390-a321-132cc47e5740.png)

**Comment by jsastre-dgtic** [comment]
ok. Comprovat
