### ISSUE TITLE
Missatge Avís Entitat

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#660]
Afegir "tràmits amb annexos" al "Tipus  i eliminar duplicitats a la llista de tràmits:

![image](https://user-images.githubusercontent.com/18436867/207024864-5bb4fc53-be28-42bf-ae5d-a42ceb827dce.png)

**Comment by jsastre-dgtic** [comment]
Si definim l'avís no surt a l'executar el tràmit afegit a la llista (hem refrescat m- cau)

![image](https://user-images.githubusercontent.com/18436867/207026944-cc75e2a7-5c6c-46fe-b7e6-3a310b0bc281.png)

**Comment by jsastre-dgtic** [comment]
Al Desar aquesta pantalla, s'hauria de mantenir a la pantalla anterior, i torna al llistat de tràmits general

![image](https://user-images.githubusercontent.com/18436867/207028110-1c41b9e4-8184-4382-afce-ca7a6b38a355.png)

**Comment by jsastre-dgtic** [comment]
El missatge d'avís tampoc no surt si el definim des de la pantalla de Control d'accés de la versió

![image](https://user-images.githubusercontent.com/18436867/207028332-9eaa615b-6142-408e-aafe-c5cbd824ab66.png)

**Comment by jsastre-dgtic** [comment]
https://github.com/GovernIB/sistra2/issues/660#issue-1491546848
Introduir a l'esquerra del desplegable de tràmits un desplegable d'àrea (una vegada seleccionada filtra el desplegable de tràmit)

![image](https://user-images.githubusercontent.com/18436867/207046829-54eb36ff-65bf-4498-9e1f-4eb01fc01047.png)

**Comment by jparedes-indra** [comment]
Sobre el dubte de funcionament: 
•	Si es defineix des de missatges d'avis entitat, no apareix al control d'access per al mateix tràmit i versió. --> Hauria de sortir si és un tràmit afectat (en mode lectura pels administradors d'àrea per ser un missatge a nivell de Adminsitrador d'entitat) 
•	Si es defineix des de misatges d'avis entitat i despres des de control d'access, apareixen 2 missatges per al tràmit i versió. --> Si es compleix el primer punt aquest queda "resolt".

**Comment by jparedes-indra** [comment]
Finalmente se decide que se muestren los mensajes que coincidan para un trámite y versión, provenientes del mantenimiento de mensajes aviso entidad y del control de acceso.

![imagen](https://user-images.githubusercontent.com/67064375/207320383-37e05fb3-39fe-4a8e-847c-ab137333426d.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

**Comment by jsastre-dgtic** [comment]
Al definir Nou avís tenim més opcions d'editar que si editam una vegada creat.... perquè?

![image](https://user-images.githubusercontent.com/18436867/217772841-f21fd5de-1dc7-4e12-af4a-1c52e4bbfafa.png)


Aquí hauríem de poder canviar d'una versió a tots els tràmits amb annexos, per exemple...
![image](https://user-images.githubusercontent.com/18436867/217773276-9d83117d-a521-4ac9-9536-6d6713f30780.png)

**Comment by jsastre-dgtic** [comment]
Si triam una àrea /tràmit, la versió cau fora de la pantalla

![image](https://user-images.githubusercontent.com/18436867/217773770-daca632a-f619-4cec-8d12-540b45239dd7.png)

**Comment by jparedes-indra** [comment]
Resuelto en el TAG sistra2-1.4.2_1 (4e8b824).

En próximas versiones se completará la funcionalidad, permitiendo crear mensajes tipo versión (para un trámite y versión concretos), desde el mantenimiento de mensajes de entidad, con lo que se verá reflejado tal mensaje en el control de acceso de ese trámite y versión.

También se permitirá editar tanto el trámite y versión afectado en ese mensaje, como la posibilidad de cambiar entre este tipo de mensaje y el resto.

**Comment by jparedes-indra** [comment]
Ya es posible crear mensajes de tipo versión desde el mantenimiento y cambiar de tipo entre diferentes tipos, incluido el tipo version.

![image](https://user-images.githubusercontent.com/67064375/231982741-54e1ba53-8c4e-4718-8ee0-e3161aadd460.png)

**Comment by avillen-dgtic** [comment]
👍
