### ISSUE TITLE
Afegir una funció als scripts que retorni l'entorn actual (DEV, PRE, PRO o SE)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#661]
afegir una funció als scripts que retorni l'entorn actual (DEV, PRE, PRO o SE

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

![image](https://user-images.githubusercontent.com/67064375/217573142-dddde416-98fd-48f4-8059-af9266b5b04c.png)

![image](https://user-images.githubusercontent.com/67064375/217573184-268e73c7-b9f3-4196-b24e-de786213faa6.png)
