### ISSUE TITLE
Mantenir pantalla anterior en crear nova versió des de recerca

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#662]
Quan accedim a un tràmit mitjançant recerca, en crear-se canvia a la pantalla general, quan s'hauria de mantenir on era

![mantenir pantalla de tràmit](https://user-images.githubusercontent.com/18436867/207559524-2d6559c3-da33-4c12-85ac-489a3d2f09c7.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by avillen-dgtic** [comment]
👍
