### ISSUE TITLE
En crear nova versió, hauria d'agafar focus en aquesta i no al tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#663]
![focus nova versió](https://user-images.githubusercontent.com/18436867/207563656-b6771ac8-3c57-43a4-a4ac-02b5a9d729e3.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by avillen-dgtic** [comment]
👍
