### ISSUE TITLE
Si passam a majúscules en crear el formulari, ho hauríem de mantenir a l'edició d'aquest.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#664]
![edicio form](https://user-images.githubusercontent.com/18436867/207564585-c1804370-5385-4f00-8801-ccd531f8b982.gif)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

Ahora se convierte a mayúscula al guardar el formulario y se muestra en mayúscula en la lista de formularios.
