### ISSUE TITLE
Focus a la versió acabada de crear

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#665]
Quan cream una nova versió d'un tràmit es perd el focus tot i estar seleccionada la nova versió, amb la qual cosa no surt el botó d'editar la nova versió

![image](https://user-images.githubusercontent.com/18436867/207834992-79fc8c21-6fd4-4730-85f7-3fa7083b66aa.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by avillen-dgtic** [comment]
👍
