### ISSUE TITLE
No surten scrolls a la pantalla de propietats globals

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#666]
![image](https://user-images.githubusercontent.com/18436867/207837634-34e30e61-b0f2-4f23-84b9-25615a85de8f.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

![image](https://user-images.githubusercontent.com/67064375/217571276-0383f076-42d8-43de-92cd-407db2dfa676.png)
