### ISSUE TITLE
Creació d'un botó tipus toogle que alterni entre plugin real i mock

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#667]
Mostrar un segon camp de classname a la pantalla de gestió de plugin per tal de poder tenir definit la classe mock corresponent.

![image](https://user-images.githubusercontent.com/18436867/208412353-0d0aeef7-c4f3-4820-9ec2-54cdf151763d.png)

Crear un botó de switch que reflecteixi de manera clara quina classe es fa servir, si la bona o la de mock. Per exemple, que el nou botó digui "Switch to Mock" quan s'estiri del real i"Switch to Real" quan s'estiri del mock...

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

![image](https://user-images.githubusercontent.com/67064375/217569981-4e08b6e1-15d6-46e7-aaff-5ddab1bedce9.png)

**Comment by jsastre-dgtic** [comment]
No entenem pq tenim un camp ClassnameMOCK si no s'emplena al fer switch. L'únic que passa és que es posa en gris el classname (real). Ens podeu explicar aquest fet?

![mock](https://user-images.githubusercontent.com/18436867/217814082-86dc14bb-e3a4-4c6f-ab32-245465f6af36.gif)
