### ISSUE TITLE
Canviar l'ordre (nom PA + nom TT) que envia el plugin de rw3

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#668]
Ara a l'extracte de registre es mostra nom PA+nomTT, es tracta de canviar-ho per a visualitzar nom TT+ nomPA

![image](https://user-images.githubusercontent.com/18436867/208413736-b2623226-1330-4ecb-b219-4a9055389796.png)

**Comment by jparedes-indra** [comment]
Esto afectaría también al título en el Asistente de tramitación.

**Comment by jsastre-dgtic** [comment]
Cap problema

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by jsastre-dgtic** [comment]
Assistent:
![image](https://user-images.githubusercontent.com/18436867/211287590-ea8ae191-a5cb-49bc-acdc-b3f8f9299577.png)

Formulari formatat:
![image](https://user-images.githubusercontent.com/18436867/211288028-b6a319a6-6066-49b4-be03-e1aaa484b259.png)

Justificant RW3:
![image](https://user-images.githubusercontent.com/18436867/211288282-a1307889-8982-4822-b221-9716a8cdf38f.png)
