### ISSUE TITLE
Breadcrumb llança un error

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#669]
![image](https://user-images.githubusercontent.com/83401259/208438332-d50eb36b-0b25-4505-bb4c-d4d9806d4c2b.png)

![image](https://user-images.githubusercontent.com/83401259/208438315-2433381f-c77d-4e65-92d4-d15cba8d7948.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by avillen-dgtic** [comment]
Quan es pitja a la molla de pa, el focus no apunta al tràmit d'on acaba de sortir.
