### ISSUE TITLE
STG: Modificacions referides al nou esquema de lliurament presencial

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#67]
**Passa Annexar**
- Script de presentació: Se afegirà un script de presentació que possibiliti indicar el tipus de presentacions permeses, a partir de dades del formulari, tenint en compte les presentacions habilitades al catàleg de procediments i serveis.
- Casella «Forçar electrònic» 2: S'afegirà aquesta casella per marcar que en cas d'arribar a la passa annexar de forma electrònica únicament es permeti l'opció a d'annexar els documents electrònicament.

**Definició del document annex** 
S'eliminarà la casella de selecció única de tipus de presentació. A més es modificarà el literal de l'apartat per “Propietats document electrònic”.

**Passa Pagar Taxa** 
S'incorporarà una casella de verificació “Forçar electrònic” que permetrà indicar que únicament es possibiliti el pagament electrònic tot i que en el catàleg de procediments i serveis es permeti també la via presencial.

**Definició del pagament** 
S'eliminarà el selector de tipus de pagament.

**Passa Registrar** 
S'incorporarà una casella “Forçar electrònic” que permetrà indicar que si s'arriba a la passa de registre tramitant de manera electrònica només es doni l'opció a registrar de manera electrònica, no permetent la conversió a la via presencial.

**Comment by rsanz-indra** [comment]
Pendiente de validar esquema de funcionamiento para entrega presencial

**Comment by rsanz-indra** [comment]
Se han redefinido requisitos para entrega presencial / subsanación.
Se trasladarán requisitos a documento de análisis funcional y se analizarán los cambios a realizar para planificar tareas.

**Comment by jsastre-dgtic** [comment]
Després de diverses reunions i decisions, tancam i obrim noves issues per a l'entrega presencial...
