### ISSUE TITLE
Si ens posicionam en camps de gràfics surt l'opció copiar

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#670]
Surt l'opció, surt el growl dient que s'ha copiat correctament, però no copia res. Quan està desplegat surt només l'opció de copiar, quan no hi està també surt la de nova versió... 

A més, al camp de desplegar versions, el botó dret desplega cada 2 clics...

![image](https://user-images.githubusercontent.com/18436867/208643748-ae5ed2fd-0ca3-447e-be62-63f7103bdef9.png)
![image](https://user-images.githubusercontent.com/18436867/208643769-f81023fb-36cd-42e9-80c3-bb52b727abab.png)
![image](https://user-images.githubusercontent.com/18436867/208643791-00a86dad-deb4-4902-9de6-1113bfdf761e.png)

**Comment by jsastre-dgtic** [comment]
Això també passa al check de les àrees:

![image](https://user-images.githubusercontent.com/18436867/208644039-b3dcaeda-af41-48ff-aa93-367546ec942a.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

Ahora, si se intenta copiar un icono o una imagen, aparece este mensaje y no se copia nada en el portapapeles.

![image](https://user-images.githubusercontent.com/67064375/217569373-f0d0f95c-e6c9-4be2-83b4-402b5ac1afce.png)
