### ISSUE TITLE
Menú contextual: Crear una línia de separació entre copiar camp i el que pertany a la fila

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#671]
![image](https://user-images.githubusercontent.com/18436867/208646947-5c5d1f88-2e49-49c9-9762-96218b918417.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

![image](https://user-images.githubusercontent.com/67064375/217568917-7d23956b-26cb-4b9c-b67f-f83d0ca27998.png)
