### ISSUE TITLE
Esborrar una àrea amb tràmits

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#672]
![image](https://user-images.githubusercontent.com/83401259/208655564-264cbcfe-97a6-4e1f-b413-ccc76a1e03b1.png)

![image](https://user-images.githubusercontent.com/83401259/208655368-a8a592df-b5ca-4574-952c-f8231c594504.png)

**Comment by avillen-dgtic** [comment]
L'error pareixia que tenia a veure quan hi ha qualque versió bloquejada, però no. 
Aquí teniu a DEV una àrea amb aquest problema.
![image](https://user-images.githubusercontent.com/83401259/208658062-b3332d35-52de-4182-a398-d227c4672fc1.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by avillen-dgtic** [comment]
👍
