### ISSUE TITLE
Menú del tràmit no correspon a l'estat de la pantalla

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#673]
![#000](https://user-images.githubusercontent.com/83401259/208656711-f6f51dcf-a78a-4656-8ab5-b35cca37b673.gif)

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by avillen-dgtic** [comment]
👍
