### ISSUE TITLE
Crear mecanisme per desplegar i contraure versions d'un tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#674]

**Comment by jparedes-indra** [comment]
Se acuerda que, sobre un trámite:
- El click simple con el botón izquierdo del mouse abre y cierra el panel de versiones.
- El doble click izquierdo no abre el popup del detalle del trámite, ya que interfiere con la nueva funcionalidad del click simple y puede abrirse con el botón de la barra superior y con el comando integrado en el menú contextual.
- El click derecho abre el menú contextual.

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by avillen-dgtic** [comment]
👍
