### ISSUE TITLE
Error tractant l'identificador de les SR

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#675]
![image](https://user-images.githubusercontent.com/83401259/208850017-8717826d-a54a-4b1f-8da3-0df04eaeef5f.png)

![image](https://user-images.githubusercontent.com/83401259/208849756-62f1edd6-866e-43b6-b711-afd2631acf6e.png)

**Comment by avillen-dgtic** [comment]
#530

**Comment by jparedes-indra** [comment]
Se resuelve en el tag 1.4.1_2 (940fdcb).

**Comment by avillen-dgtic** [comment]
👍
