### ISSUE TITLE
Barra de desplaçament desapareguda

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#676]
No apareix la barra de desplaçament a la taula de rols
![image](https://user-images.githubusercontent.com/83401259/209308671-d42139d9-3fdf-4809-9cb8-769865714a5b.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

Ahora aparece tanto en la pantalla de Roles y permisos como en los roles de los datos de sesión del usuario.

![image](https://user-images.githubusercontent.com/67064375/217573697-66e83043-6ed0-4ef6-91db-808b4d3a7987.png)

**Comment by avillen-dgtic** [comment]
Torna a fallar aquesta funcionalitat.
