### ISSUE TITLE
Eliminar domini d'àrea sense feedback

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#677]
Arran d'aquesta issue, #637, hem vist que no surt cap missatge quan esborrem el domini.  
El domini està emprat, i quan dones a eliminar el domini d'àrea no fa menció d'esborrar-se ni de mostrar cap feedback
![image](https://user-images.githubusercontent.com/83401259/209341958-48d5738c-d7f6-4c99-af83-d47436d11f4e.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

Ahora se muestra un mensaje si el dominio se está utilizando, por lo que no se puede eliminar.

![image](https://user-images.githubusercontent.com/67064375/217573978-c145dadb-768c-4b07-a9df-f2d4d3fca89d.png)
