### ISSUE TITLE
Separar visualment les funcions dels botons del menú contextual

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#679]
Arran d'aquesta tasca, #674, separar les funcions que hi ha dintre del menú contextual de forma visual.

Exemple ràpid
![image](https://user-images.githubusercontent.com/83401259/209344512-dc4677e5-4183-4edf-a97e-1b688d81ccb0.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

En el menú contextual de versiones aparecen las separaciones apropiadas.

![image](https://user-images.githubusercontent.com/67064375/217575422-baebf83e-66f5-48ca-9270-7171facc8b7c.png)
