### ISSUE TITLE
STT: Workflow tramitació (nou esquema de lliurament presencial)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#68]
**Passa Cal Saber**
S'inclourà informació relativa a la possibilitat de que el tràmit incorpori pagament electrònic i signatura electrònica.

**Assistent de tramitació - Passa Annexar**
- Clarificació d'operativa d'usuari respecte als annexos: Es revisarà la pantalla i les instruccions existents en aquesta per clarificar a l'usuari respecte al que ha de fer amb els annexos.
- Incorporació de possibilitat de canvi a tramitació presencial: S'incorporarà, mitjançant enllaç o altre mitjà, la possibilitat de que l'usuari canviï a entrega presencial.
- Icona identificador tramitació presencial: En cas de que la tramitació passi a presencial, es mostrarà una icona il·lustrativa d'aquest tipus de tramitació.
- Incorporació de possibilitat de canvi a tramitació electrònica: S'incorporarà, mitjançant enllaç o altre mitjà, la possibilitat de que l'usuari canviï a tramitació electrònica quan es trobi en mode d'entrega presencial.

**Assistent de tramitació – Passa Pagar Taxa**
S'incorporarà, mitjançant enllaç o altre mitjà, la possibilitat de que l'usuari canviï a entrega presencial.
Assistent de tramitació – Passa Registrar: S'incorporarà, mitjançant enllaç o altre mitjà, la possibilitat de que l'usuari canviï a entrega presencial.

**Comment by jsastre-dgtic** [comment]
Tot i que queda pendent una reunió, apuntam el darrer que havíem comentat:
Formularis a entregar presencialment:
S'eliminarà la casella de verificació «Presentar en preregistre» a nivell de formulari. En cas que el tràmit es converteixi en entrega presencial el ciutadà haurà d'imprimir i entregar tots els formularis emplenats.

Propietats de versió d'un tràmit:
S'incorporarà una casella de verificació “Forçar electrònic” que permetrà indicar que la tramitació només pot ser electrònica, independentment de que al catàleg de procediments i serveis es permeti també la via presencial.

Passa Annexar:

Script de presentació: Se afegirà un script de presentació que possibiliti indicar el tipus de presentacions permeses, a partir de dades del formulari, tenint en compte les presentacions habilitades al catàleg de procediments i serveis.
Casella «Forçar electrònic» 2: S'afegirà aquesta casella per marcar que en cas d'arribar a la passa annexar de forma electrònica únicament es permeti l'opció a d'annexar els documents electrònicament.
Definició del document annex:
S'eliminarà la casella de selecció única de tipus de presentació. A més es modificarà el literal de l'apartat per “Propietats document electrònic”.

Passa Pagar Taxa:
S'incorporarà una casella de verificació “Forçar electrònic” que permetrà indicar que únicament es possibiliti el pagament electrònic tot i que en el catàleg de procediments i serveis es permeti també la via presencial.

Definició del pagament:
S'eliminarà el selector de tipus de pagament.

Passa Registrar:
S'incorporarà una casella “Forçar electrònic” que permetrà indicar que si s'arriba a la passa de registre tramitant de manera electrònica només es doni l'opció a registrar de manera electrònica, no permetent la conversió a la via presencial.

Passa Cal Saber:
S'inclourà informació relativa a la possibilitat de que el tràmit incorpori pagament electrònic i signatura electrònica.
Assistent de tramitació - Passa Annexar:

Clarificació d'operativa d'usuari respecte als annexos: Es revisarà la pantalla i les instruccions existents en aquesta per clarificar a l'usuari respecte al que ha de fer amb els annexos.
Incorporació de possibilitat de canvi a tramitació presencial: S'incorporarà, mitjançant enllaç o altre mitjà, la possibilitat de que l'usuari canviï a entrega presencial.
Icona identificador tramitació presencial: En cas de que la tramitació passi a presencial, es mostrarà una icona il·lustrativa d'aquest tipus de tramitació.
Incorporació de possibilitat de canvi a tramitació electrònica: S'incorporarà, mitjançant enllaç o altre mitjà, la possibilitat de que l'usuari canviï a tramitació electrònica quan es trobi en mode d'entrega presencial.
Assistent de tramitació – Passa Pagar Taxa:
S'incorporarà, mitjançant enllaç o altre mitjà, la possibilitat de que l'usuari canviï a entrega presencial.

Assistent de tramitació – Passa Registrar:
S'incorporarà, mitjançant enllaç o altre mitjà, la possibilitat de que l'usuari canviï a entrega presencial.

PD: Valorar si convé i és possible canviar el concepte de "Forçar electrònic" per "Permetre Presencial"

**Comment by rsanz-indra** [comment]
Se han redefinido requisitos para entrega presencial / subsanación.
Se trasladarán requisitos a documento de análisis funcional y se analizarán los cambios a realizar para planificar tareas.

**Comment by jsastre-dgtic** [comment]
Herència de la STT: Workflow tramitació II (implementació pas registrar - Cicle12) #79 , posposada per a la tasca d'adaptació al decret i lliurament presencial:
PROPOSTA NOVA: Incloure num registre per pantalla a la secció de descàrrega del Justificant
![image](https://user-images.githubusercontent.com/18436867/54024880-2fd80a00-4199-11e9-83a6-78bba9f0f6da.png)

**Comment by jsastre-dgtic** [comment]
Després de diverses reunions i decisions, tancam i obrim noves issues per a l'entrega presencial...
