### ISSUE TITLE
Creació de variables personalitzades d'àrea.

### ISSUE THREAD

**Issue by fjcalderon-dgtic** [GovernIB/sistra2#680]
Crear un mecanisme que faciliti la tasca als desenvolupadors de tràmits, de manera que s'automatitzin aquests processos de gestió i manteniment d'URLS d'elements externs, mitjançant la creació d'una sèrie de variables a nivell d'àrea.

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

La funcionalidad implementada es la indicada en el documento de análisis enviado por correo.

**Comment by jsastre-dgtic** [comment]
La validarem en tenir promocionada la versió als 4 entorns...

**Comment by jcerdar-indra** [comment]
Hemos detectado un error al realizar llamadas a los dominios remotos de entidad desde SISTRAMIT. 

 Carregant classe es.caib.sistra2.commons.plugins.dominio.rest.DominioPluginRest ...
11:05:19,238 ERROR [io.undertow.request] (default task-8) UT005023: Exception handling request to /sistragesws/rest/interna/entidad/CAIB: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException

**Comment by jparedes-indra** [comment]
Ya no aparece el error al invocar DR de entidad.

**Comment by jsastre-dgtic** [comment]
a validarem en tenir promocionada la versió als 4 entorns...
