### ISSUE TITLE
No hi ha espai per a fer la modificació d'un element

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#681]
Donat un tipus de dada com en aquest cas el IBAN, si no hi ha espai que notifiqui els requisits del tipus de dades per a donar informació al desenvolupador del tràmit.
![#000](https://user-images.githubusercontent.com/83401259/210058404-609a92f9-9b9b-468d-a79a-243ee754b6ea.gif)

**Comment by jparedes-indra** [comment]
En este escenario se mostrará el mensaje ya previsto en este tipo de campos.

![imagen](https://user-images.githubusercontent.com/67064375/210060106-2161be27-39d9-4c64-a681-bf10d25e4020.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

Se controla que el tipo de campo IBAN tenga 3 columnas como mínimo, por lo que no se puede añadir en un hueco en el que no quepa.

![image](https://user-images.githubusercontent.com/67064375/217576066-fdb31409-fcb1-4ba7-bc50-c9d17aa5f21b.png)

**Comment by avillen-dgtic** [comment]
👍
