### ISSUE TITLE
 Error en importar una SR

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#684]

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

Ya se pueden importar Secciones reutilizables.

**Comment by avillen-dgtic** [comment]
👍

**Comment by jparedes-indra** [comment]
Ya no se produce un error que se producía al importar SR con script de CDI.

**Comment by jparedes-indra** [comment]
Se ha detectado que al exportar trámites con SR que referencian a dominios en su script de CDI, estos dominios no se reconocen y el validador de trámites indica que no se está utilizando esos dominios, cuando sí existen en el apartado "Dominios utilizados".

**Comment by jsastre-dgtic** [comment]
Tot i tenir l'script no emplena el camp NIF:

![image](https://github.com/GovernIB/sistra2/assets/18436867/ebdfcaa8-b86a-4028-9747-877f12e94e7f)

![image](https://github.com/GovernIB/sistra2/assets/18436867/f4725326-6367-4a9f-868a-8e4050df8f8e)


![image](https://github.com/GovernIB/sistra2/assets/18436867/3cc649a4-5eef-4b17-9902-3ecb5a392ba4)

**Comment by jsastre-dgtic** [comment]
Validarem en tenir la versió a se

**Comment by jsastre-dgtic** [comment]
Restam pendents de la validació de les SR per part de l'OAE per a poder importar les SR i els tràmits TP i IG a SE
