### ISSUE TITLE
Problemes en la lectura de l'ordre intern de les SR (scripts)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#685]

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

Antes, un trámite realizado con secciones reutilizables, cambiaba el orden interno de algunas líneas del formulario, con lo que los scripts de los campos asociados a otros campos no se ejecutaban correctamente (podía darse el caso de que la línea de un campo que depende de otro campo estuviera antes que el campo del que depende). Ahora, con los cambios realizados ya se ejecutan correctamente los scripts de cada campo y en el orden adecuado. 

![image](https://user-images.githubusercontent.com/67064375/217579894-33a674fd-c4e4-41dd-86ce-2a621b9a4723.png)

![image](https://user-images.githubusercontent.com/67064375/217579932-3199cdd4-918c-479c-b338-a57cee3e2888.png)

![image](https://user-images.githubusercontent.com/67064375/217580030-b9b4007f-633c-4fc5-a1fd-bea7f26c5ed2.png)

Los campos de la sección C se rellenan correctamente con los valores de las secciones A y B

![image](https://user-images.githubusercontent.com/67064375/217581066-4969d3a3-b73a-4a7e-99fe-aeae3a4245ce.png)

![image](https://user-images.githubusercontent.com/67064375/217581120-b310e478-adef-41ce-8319-d338ab7526f8.png)
