### ISSUE TITLE
Vincle d'URL a l'editor Tiny

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#687]
Els complements de l'editor Tiny no permet enllaços.
![image](https://user-images.githubusercontent.com/83401259/211794054-0d522d6f-41a5-4e30-b07a-ec436e3b6a00.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

Ya se pueden añadir enlaces en Tiny.

![image](https://user-images.githubusercontent.com/67064375/217579457-726fc9b1-c088-4f5c-a98c-6b4d09de42b8.png)

**Comment by avillen-dgtic** [comment]
👍
