### ISSUE TITLE
Correcció dels comportaments d'estats de RW3

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#688]
Cal revisar el comportament de S2 quan tracta els tràmits.
Hi ha problemes quan consulta l'estat de RW3 amb l'estat 0 però amb un ID de sessió. Afecta als tràmits que provenen de Carpeta bàsicament.

Estats de RW3:
0 - No iniciat. 
1 - En procés
2 - Realitzat.
3 - Error.

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG sistra2-1.4.1 (fde6ddf).

**Comment by jsastre-dgtic** [comment]
El commit no reflecteix el canvi i no la podem validar
