### ISSUE TITLE
Incloure visualització de progrés a STG.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#689]
Quan previsualitzam, per exemple
![8puiO](https://user-images.githubusercontent.com/18436867/212044321-6cf61828-7bfd-47ea-b489-d9ddee610d9a.gif)
![rellotge](https://user-images.githubusercontent.com/18436867/212044326-d75ee75e-b8ef-4b68-93af-5e7d8f1125ff.gif)

**Comment by jparedes-indra** [comment]
Utilizaremos el gif que ya existe y revisaremos que salga al cargar la pantalla Previsualizar.

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

Mientras carga los trámites en el combo aparece un literal que indica ese estado y un puntito en movimiento que indica el progreso. Durante la carga se puede realizar ciertas acciones.

![image](https://user-images.githubusercontent.com/67064375/217578946-0bfc7642-50fe-440c-b287-316f454fd753.gif)

**Comment by avillen-dgtic** [comment]
👍
