### ISSUE TITLE
 STT: Workflow tramitació (implementació pas registrar)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#69]

**Comment by jsastre-dgtic** [comment]
Observacions:
1.- No tallar llista de propietats si tenim prou finestra:
![image](https://user-images.githubusercontent.com/18436867/51246989-14683400-198c-11e9-9a49-43dd68e37e87.png)
2.- Accedint al tràmit a través de l'assistent de tramitació (http://sdevapplin5.caib.es:48080/sistramitfront/asistente/iniciarTramite.html?tramite=SA001&version=1&idioma=ca&idTramiteCatalogo=3270471) 
i seguir totes les passes de l'assistent fins a registrar la sol·licitud:
![image](https://user-images.githubusercontent.com/18436867/51247047-382b7a00-198c-11e9-9317-e99f55298520.png)
2019-01-16 12:37:44,392 ERROR [es.caib.sistramit.core.service.FlujoTramitacionServiceImpl] (default task-16) Error no controlado en la capa de servicio: null: java.lang.NullPointerException
	at

**Comment by amaciam-indra** [comment]
1. Ho revisam.

2. Hem acotat el problema i sembla derivat de la no inclusió d'annex en la prova realitzada. S'està produint un nullPointer al intentar verificar unes condicions del documents. Ho miram de corregir.
En tot cas, podeu provar de registrar un annex (un doc o un odt per exemple). Pensau també a deshabilitar la signatura de l'annex o canviar la configuració del plugin de signatura de l'entitat per apuntar al plugin mock:

Classname => es.caib.sistra2.commons.plugins.firmacliente.mock.ComponenteFirmaPluginMock

**Comment by jsastre-dgtic** [comment]
Comprovat funcionament de registre amb 2 condicions: guardar formulari i adjuntar doc+generar pdf (o decantar la conversió pdf del check).
Queden pendents aquests 2 bugs.

PROPOSTA NOVA: Incloure num registre per pantalla a la secció de descàrrega del Justificant
![image](https://user-images.githubusercontent.com/18436867/51377323-e9581e80-1b0a-11e9-9800-9bd87285e1a3.png)

**Comment by jsastre-dgtic** [comment]
Passam a #79
