### ISSUE TITLE
Optimitzar pantalla de Previsualització

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#690]
Estudiar si podem filtrar per l'Estat de Publicació de ROLSAC i eliminar del resultat els que tenguin Estat=En reserva.

Hem comprovat que tots els que no tenen Òrgan estan en reserva amb aquesta query:

select rsc_tramit.tra_codi, rsc_tramit.tra_idtramtel, rsc_tratra.ttr_nombre, rsc_tramit.tra_orgcomp, rsc_proced.pro_valida as estat
from rolsac.rsc_tramit, rolsac.rsc_tratra, rolsac.rsc_proced
where rsc_tramit.TRA_CODPLN=5233805
and rsc_tramit.tra_codi=rsc_tratra.ttr_codttr
and rsc_tramit.tra_codpro = rsc_proced.pro_codi
and rsc_tratra.ttr_codidi='ca'
and rsc_tramit.tra_orgcomp is null;

![image](https://user-images.githubusercontent.com/18436867/212048620-2173e129-4680-47c6-8b63-984cd5b2e26c.png)

**Comment by jsastre-dgtic** [comment]
Atès que l'API de rolsac1 no té la capacitat per filtrar per estat, posar l'opció de que surtin o tots o només els actius.
Potencialment, si triam tots, es pot tornar a produir l'error en trobar "en reserva", però no val la pena modificar api de rolsac1 si ja estam a la fase final de rolsac2. Rolsac 2 hauria de ser capaç de fer-ho... ho farà?

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

Ahora se puede filtrar por los trámites públicos. Si se desmarca el check, muestra los 3 estados.

![image](https://user-images.githubusercontent.com/67064375/217576448-3e8eb5d8-b667-4202-8b2a-afdda860de4e.png)

**Comment by avillen-dgtic** [comment]
👍
