### ISSUE TITLE
Error en accedir des de STH a la Definició del tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#691]
![image](https://user-images.githubusercontent.com/18436867/212309781-935e581d-80b0-424e-8f42-053e57ca7cbf.png)

![image](https://user-images.githubusercontent.com/18436867/212309889-083da91b-fed2-42c3-8d1e-beb1079072bc.png)

**Comment by jsastre-dgtic** [comment]
Indra diu: Si STG se ha quedado con el perfil “Superusuario” es cuando genera el error. Si cambiáis a “Administrador de entidad” os funcionará.
S'hauria de controlar l'error, en qualsevol cas.

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

![image](https://user-images.githubusercontent.com/67064375/217581380-fa7c53f9-995f-4403-a846-e7a0e4a93ae8.png)

**Comment by avillen-dgtic** [comment]
👍
