### ISSUE TITLE
Caràcter desconegut al front STT

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#692]
![image](https://user-images.githubusercontent.com/18436867/212315523-61e2547f-996c-4121-a570-3831f562adc2.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

![image](https://user-images.githubusercontent.com/67064375/217581713-b1887d72-efbd-4170-a44a-0b6332ea4572.png)

**Comment by avillen-dgtic** [comment]
![image](https://user-images.githubusercontent.com/83401259/217761088-95a89b91-e2e7-4a05-b81e-04ae23baadf8.png)
Apareixen també a altres missatges.

**Comment by jparedes-indra** [comment]
Este mensaje pertenece a LOGINIB.

**Comment by jsastre-dgtic** [comment]
Caràcter desconegut al front LIB #32
https://github.com/GovernIB/LOGINIB/issues/32
