### ISSUE TITLE
Visualitzar els avisos sense dates definides

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#693]
![image](https://user-images.githubusercontent.com/18436867/212656201-70e8f852-b16f-4812-8290-f647be5c47c3.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

Ahora ya se pueden poner mensajes sin fechas o con una de las dos vacía.

![image](https://user-images.githubusercontent.com/67064375/217582545-767a3e72-2920-4cbf-ad74-9209fd063cb7.gif)

**Comment by avillen-dgtic** [comment]
👍
