### ISSUE TITLE
Equiparar el criteri amb les dates de l'"Auditoria de tràmits" en la pantalla "Informació de Persistència"

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#694]
La data d'inici ha de seguir el mateix criteri que a la pantalla "Auditoria de tràmits"

![image](https://user-images.githubusercontent.com/83401259/217752714-894ad7ad-6565-4120-b952-bc2b5e56c4d1.png)

**Comment by avillen-dgtic** [comment]
👍
