### ISSUE TITLE
Millores a la Pantalla Informació de Persistència

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#695]
![image](https://user-images.githubusercontent.com/18436867/212670696-e7b5c4e7-9472-4868-a7e2-f7714fb1256d.png)

**Comment by jsastre-dgtic** [comment]
1.- Tota la columna de la dreta no surt informada i veim que potser hauria d'anar com a "capçalera" de cada secció de la columna esquerra.
2.- L'estat=omplint hauria de ser = Emplenat
3.- A l'ajuda F. caducitat --> D. caducitat (Data)
4.- Pas i tipus pas sempre coincideixen? Podem obviar el "pas" o ens pot aportar info?

**Comment by jsastre-dgtic** [comment]
A la pantalla inicial de Persistència. 
Omplint--> Emplenant

![image](https://user-images.githubusercontent.com/18436867/212671794-1cd53299-4bb2-4b46-a1f9-d56da0af6291.png)

**Comment by jsastre-dgtic** [comment]
El filtre Tipus no funciona

![image](https://user-images.githubusercontent.com/18436867/212672198-a3b16605-73e7-43cc-b2f8-fb1bf695cb8f.png)

**Comment by jsastre-dgtic** [comment]
Si no és persistent, per què ens surt la info i podem baixar els annexos?

![image](https://user-images.githubusercontent.com/18436867/212673123-60636986-2588-4dab-9a8a-6a4da59bfc29.png)

**Comment by jparedes-indra** [comment]
Revisar tambie´n que puedan buscarse por trámite.

**Comment by jparedes-indra** [comment]
Resueltas todas las peticiones de la issue.
