### ISSUE TITLE
Permetre l'opció de "sense autenticació" per a tràmits de procediments administratius amb normativa específica especial.

### ISSUE THREAD

**Issue by fjcalderon-dgtic** [GovernIB/sistra2#697]

**Comment by jsastre-dgtic** [comment]
Poden existir casos de tràmits "especials", que tenen normativa específica pròpia, que està per sobre de les lleis generals d'AE (39 i 40/2015). Per tant, cal permetre que, encara que es marqui a SISTRAGESBACK que un tràmit és de tipus "Procediment Administratiu", es pugui després activar l'opció d'autenticació anònima (sense autenticació), per cobrir els casos on la normativa específica sí ofereix aquesta major flexibilitat, fins i tot encara que es tracti de tràmits que després acabin en un registre electrònic. Ara mateix no és possible perquè bota un missatge avisant aquest fet.

**Comment by jsastre-dgtic** [comment]
Validat a DEV
