### ISSUE TITLE
Ajudes a Previsualització

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#699]
Manca explicar les opcions dels checks:

![image](https://user-images.githubusercontent.com/18436867/213375007-04c35af5-e13c-45ee-88b3-aaee5e4d5d6d.png)

**Comment by jsastre-dgtic** [comment]
Entenem que tot això depèn de rolsac, on:

Només vigents: Tràmits entre la data de publicació i la de caducitat

![image](https://user-images.githubusercontent.com/18436867/213377746-34eccc17-d823-4b97-8e9d-55c19cc5a5c1.png)


Només incorporats en SIA ("Només" es pot eliminar per redundant. Basta posar "Incorporats en SIA"):

Els tràmits associats a un PA amb Codi SIA

![image](https://user-images.githubusercontent.com/18436867/213378109-090d55e8-257b-400d-ba29-220b354b3a01.png)

A més, s'afegirà el nou check: "Públics"

Estat: Per defecte haurà de sortir un check amb Estat=Pública. Si es desmarca, intentarà trobar també tots els tràmits associats a PA independentment de l'estat (entrarien intern i reserva).

![image](https://user-images.githubusercontent.com/18436867/213377326-2f9c8976-f4ad-41d0-90ba-d3f3a94654b1.png)

És així?

Preguntes:
1.- Si intentam executar un "no vigent" o "sense SIA" STT ens permetria visualitzar-ho? i si és intern?

Tot això s'ha d'explicar a l'ajuda...

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

![image](https://user-images.githubusercontent.com/67064375/217583158-0ff1cfb8-b0dc-4916-9429-ec8fb731c609.png)

**Comment by avillen-dgtic** [comment]
👍
