### ISSUE TITLE
STT: Definició del model de dades

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#7]
Definició del model de dades del mòdul d'Assistent de Tramitació:
- Disseny físic de dades.
- Documentació del model de dades.
- Scripts de creació de l'esquema físic de dades.

**Comment by amaciam-indra** [comment]
Creada documentació de model de dades i scripts de creació de l'esquema físic de dades. El commit associat és el c9b819243ab253a8bea786e2988a07221eecef6f.

**Comment by rsanz-indra** [comment]
Queda pendiente establecer el almacenamiento de LOBs en el script de creación según estandar CAIB.

**Comment by sgelabert-dgtic** [comment]
Tenint en compte que es poden produir canvis substancials en el disseny físic de dades (per exemple fins que no es tanquin requeriments de pre-registre #14 o de migració #10 ) i que les dades introduïdes són simples proves, es proposa:
- Incorporar script DDL per l'esborrat complet dels objectes de la BBDD
- Incorporar script DML per incorporar aquelles dades de configuració bàsiques de l'aplicació.

**Comment by sgelabert-dgtic** [comment]
Adjunt log d'execució de l'script "sistramit_create_schema.sql" [sistramit_create_schema.txt](https://github.com/GovernIB/sistra2/files/1898743/sistramit_create_schema.txt)
Falta incorporar script d'esborrat d'esquema.

**Comment by amaciam-indra** [comment]
Es preveu que durant el desenvolupament hi hagi ajustos de taules i camps al model de dades

**Comment by rsanz-indra** [comment]
Como comenta Alex, esta tarea puede darse como finalizada ya que el objetivo es definir el modelo inicial de SISTRAMIT, aunque como es lógico durante el proceso de desarrollo se deberán realizar pequeños ajustes sobre el modelo de datos.
Proponemos darla como finalizada ya que si no tendríamos que tenerla abierta durante todo el ciclo de desarrollo (tiene más sentido asumir los cambios que puedan surgir sobre el modelo de datos en las tareas específicas de desarrollo).

**Comment by sgelabert-dgtic** [comment]
Adjunt log execució script inicial [log_sistramit_20180417.txt](https://github.com/GovernIB/sistra2/files/1918423/log_sistramit_20180417.txt)
