### ISSUE TITLE
Error inesperat quan no s'introdueix un títol per a l'annex

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#701]
Al Pas 3 Annexar documents, si no emplenes el camp opcional "Introduïu un títol per a l'annex" dóna error inesperat i l'usuari no sap per què (només es veu què ha passat a HelpDesk):

![image](https://user-images.githubusercontent.com/18436867/214010872-2c8f9d09-76bc-4823-8edd-44f444f94abf.png)

**Comment by jparedes-indra** [comment]
Resuelto en el tag sistra2-1.4.2_0 (61f8507).

![image](https://user-images.githubusercontent.com/67064375/217582945-bca92cd4-1504-457b-9231-9bf92319ffb7.png)

**Comment by avillen-dgtic** [comment]
👍
