### ISSUE TITLE
Controlar que no hi hagi extensions no permeses

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#703]
Tant al camp de “Personalitzades” com a l'script d'annexos dinàmics, durant el procés de validació, abans de promocionar un tràmit a PRO. 
Implementar també un control perquè en executar el tràmit a STT es filtrin les extensions no permeses.

**Comment by jparedes-indra** [comment]
Si se añade una extensión no válida en los scripts de anexo dinámico, salta un aviso.
 
![image](https://github.com/GovernIB/sistra2/assets/67064375/6e56428f-8fa5-40a1-93b6-06a19215eacb)

También se controla el formato y extensiones no válidas en el campo de extensiones personalizadas.

![image](https://github.com/GovernIB/sistra2/assets/67064375/dcdf80df-bcfb-49f5-b669-b8f0085abc4e)
![image](https://github.com/GovernIB/sistra2/assets/67064375/029c4600-3af2-4eed-bedb-d64ceb30a954)

**Comment by avillen-dgtic** [comment]
👍
