### ISSUE TITLE
Missate d'Avís d'entitat per a Carpeta 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#705]
La idea seria concatenar aquest missatge als ja existents d'Entitat, just abans del LOGINIB:

- Si anteriorment ja heu iniciat aquest tràmit i no l'heu finalitzat, podeu reprendre'l recuperant les dades ja introduïdes des de la Carpeta Ciutadana, apartat "Els meus tràmits".

![image](https://user-images.githubusercontent.com/18436867/214815225-649e3887-f135-4099-82d4-9cff9b250665.png)

**Comment by jparedes-indra** [comment]
Ahora, y siguiendo el documento de análisis, si un usuario tiene sesiones inacabadas, se muestra una pantalla que le permite retomarlas o iniciar una nueva.

![image](https://github.com/GovernIB/sistra2/assets/67064375/0e757fc0-b816-44ce-8396-1b3b890f001b)

**Comment by avillen-dgtic** [comment]
👍
