### ISSUE TITLE
Fer que la Capçalera del Formulari coincideixi amb la Descripció del Formulari 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#706]
La Capçalera del Formulari (que es reflecteix al tramitador) ha de coincidir amb la Descripció del Formulari (que, tanmateix, no es reflecteix al tramitador, pel que hem pogut observar). Bastaria doncs definir una Descripció i que aquesta fos automàticament la capçalera el formulari.
![image](https://user-images.githubusercontent.com/18436867/215984071-f7dad901-c2fd-4ff5-9f9c-6fbef17c49a7.png)

![image](https://user-images.githubusercontent.com/18436867/215984095-003cbdc5-4d5e-4334-9759-74dff33378e8.png)

![image](https://user-images.githubusercontent.com/18436867/215984121-65ad4e70-2761-48df-a163-8676576a4bcf.png)

Al PDF tendrem: 

![image](https://user-images.githubusercontent.com/18436867/215984144-ca93a95f-c414-4195-85ff-0fc64b22a87d.png)

**Comment by jparedes-indra** [comment]
Ahora, en el campo Cabecera de las propiedades del formulario en STG se copia lo que se ha indicado en el campo Descripción en la definición del formulario y es lo que aparece en el formulario y en el pdf en el asistente de tramitación.

![image](https://github.com/GovernIB/sistra2/assets/67064375/3677940f-7e81-4c97-8523-b523becfd710)
![image](https://github.com/GovernIB/sistra2/assets/67064375/fad33585-b8b9-43ee-8ac0-a82be2f57595)
![image](https://github.com/GovernIB/sistra2/assets/67064375/44fe8bcf-8ba7-4892-8b64-71ae69466e12)
![image](https://github.com/GovernIB/sistra2/assets/67064375/142ccd08-ebfd-4c51-b2b6-38ac498373fc)

**Comment by avillen-dgtic** [comment]
👍

**Comment by jsastre-dgtic** [comment]
Corregir l'ajuda... "y" - "des de el"... "mostra la descripció del formulari, que apareix el formulari" no s'entén. 

![image](https://github.com/GovernIB/sistra2/assets/18436867/53628aa7-7c7b-4b6a-a371-b287ee5b01a4)
