### ISSUE TITLE
Eliminar la data de caducitat de sistra2

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#707]
Si tanmateix es purga als 90 dies (si no té pagament, si en té als 365), sistra2 no ha de definir el que no està definit al Catàleg de Procediments. 

S'eliminaran, per tant, les opcions de configurar quants de dies persisteix, passant la responsabilitat al Catàleg (rolsac)

![image](https://user-images.githubusercontent.com/18436867/216902752-2782e80c-8d41-4d74-86c2-be17f0197470.png)

**Comment by jparedes-indra** [comment]
Se han eliminado las opciones de persistencia, haciendo que siempre persista y que sea sin límite, para que sea ROLSAC el que indique el plazo de caducidad.

![image](https://github.com/GovernIB/sistra2/assets/67064375/0901f306-821d-49db-9a98-9684d630944b)

**Comment by jparedes-indra** [comment]
Se han eliminado las opciones de persistencia, haciendo que siempre persista y que sea sin límite, para que sea ROLSAC el que indique el plazo de caducidad.

![image](https://github.com/GovernIB/sistra2/assets/67064375/0901f306-821d-49db-9a98-9684d630944b)

Se han deshabilitado las funciones setPlazoInicio() y setPlazoFin() de DATOS_PERSONAIZACIÓN, para que no se pueda ejecutar si se define un trámite de personalización.

![image](https://github.com/GovernIB/sistra2/assets/67064375/1bb65eb2-b373-41a8-add6-a0ee7f9be22f)

Se han modificado las ayudas para eliminar toda referencia a las funcionalidades desabilitadas.

**Comment by jparedes-indra** [comment]
Se han eliminado las opciones de persistencia, haciendo que siempre persista y que sea sin límite, para que sea ROLSAC el que indique el plazo de caducidad.

![image](https://github.com/GovernIB/sistra2/assets/67064375/0901f306-821d-49db-9a98-9684d630944b)

Se han deshabilitado las funciones setPlazoInicio() y setPlazoFin() de DATOS_PERSONAIZACIÓN, para que no se pueda ejecutar si se define un trámite de personalización.

![image](https://github.com/GovernIB/sistra2/assets/67064375/1bb65eb2-b373-41a8-add6-a0ee7f9be22f)
![image](https://github.com/GovernIB/sistra2/assets/67064375/8a38cf16-93f6-4f11-9101-b8723c8d8b21)

Se han modificado las ayudas para eliminar toda referencia a las funcionalidades desabilitadas.

**Comment by avillen-dgtic** [comment]
👍
