### ISSUE TITLE
Detectar document sense firma

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#709]
Si s'intenta adjuntar un document sense firma, es podria detectar enlloc de pressuposar que la firma és errònia (quan en realitat no s'ha firmat)? (ve de la #109)
![image](https://user-images.githubusercontent.com/18436867/218036169-43225102-d384-4f77-b2c7-f51469e3769c.png)

**Comment by jparedes-indra** [comment]
Esta funcionalidad tiene implicaciones importantes en el asistente de tramitación y no conviene implementarla para esta versión de la plataforma.

**Comment by jsastre-dgtic** [comment]
La posposam per a la següent versió i la deixam a "no version yet"

**Comment by jparedes-indra** [comment]
Si se configura un anexo para anexarse firmado (con o sin validación de firmantes), en caso de adjuntar un documento que no contiene firma, se informa adecuadamente.

![image](https://github.com/user-attachments/assets/54cedf10-d998-44b9-83ae-6e4ef4197295)

![image](https://github.com/user-attachments/assets/d0d49a52-12cb-4ff7-adb9-f4225a408231)

**Comment by avillen-dgtic** [comment]
👍🏼

**Comment by jparedes-indra** [comment]
Con los cambios en #758 ya no aplica esta issue.
