### ISSUE TITLE
STG: Millores diverses 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#71]
- Duplicar versió tràmit: permetre canviar àrea / tràmit
- Duplicar domini: afegir funcionalitat
- Canviar nom fitxers exportació versió tràmit i domini per seguir format: tramit-versio-release-entorn.zip / domini-entorn.zip
- Control d'accés: treure pantalla fora del manteniment de versió.
- Augmentar la grandària literals
- Afegir botons de refresc de memòria cau per millorar usabilitat

**Comment by rsanz-indra** [comment]
Hay que implementar también mecanismo para evitar enviar SQL en plano en el mantenimiento de dominios ya que en caibter se detecta como ataque de SQL-Injection

**Comment by jsastre-dgtic** [comment]
Duplicar versió tràmit: permetre canviar àrea / tràmit -> Ok

Duplicar domini: afegir funcionalitat ->Ok

Canviar nom fitxers exportació versió tràmit i domini per seguir format: tramit-versio-release-entorn.zip / domini-entorn.zip
Potser convé valorar si distingir entre tràmits i dominis, ara dels 2 zips generats no sabem què és qui a no ser que tots els dominis contenguin la paraula domini... 
![image](https://user-images.githubusercontent.com/18436867/49009495-03136000-f171-11e8-8a21-b375628be0b2.png)

Control d'accés: treure pantalla fora del manteniment de versió-> Ok

Augmentar la grandària literals: 
Quins són els literals que heu augmentat?

Afegir botons de refresc de memòria cau per millorar usabilitat
Surt botó tallat... corregir-ho:
![image](https://user-images.githubusercontent.com/18436867/49008973-8633b680-f16f-11e8-870e-9a5122690925.png)

**Comment by jsastre-dgtic** [comment]
A la configuració d'Entitat hem hagut de canviar els logos perquè es produia un error a l'intentar accedir-hi, i a més, no es mostraven ni al back ni al front de l'assistent.
El de sistrages ens funciona bé, però a sistramit no aconseguim visualitzar el png inserit... 
![image](https://user-images.githubusercontent.com/18436867/49011501-e712bd00-f176-11e8-8171-d361bad3c599.png)

**Comment by jsastre-dgtic** [comment]
Resolució:
![image](https://user-images.githubusercontent.com/18436867/49011625-33f69380-f177-11e8-89db-3b118c6dd871.png)

**Comment by jsastre-dgtic** [comment]
Afegim a aquesta tasca la desvinculació dels paràmetres de registre de la importació d'una versió, separant els dos conceptes:
![image](https://user-images.githubusercontent.com/18436867/49217790-dc526500-f3ce-11e8-85b4-8afa25ebbf85.png)

**Comment by rsanz-indra** [comment]
Se recoge el nuevo requisito de retocar pantalla de importación de versión de trámite para establecer los parámetros de registro de forma diferenciada:
![importar](https://user-images.githubusercontent.com/17456494/49217862-0efc5d80-f3cf-11e8-93b8-c7fbd2368f71.png)

**Comment by jsastre-dgtic** [comment]
1. Accedir a SISTRAGESBACK, anar a la definició de versió d'un tràmit i comprovar que el botó "Refrescar caché" es visualitza correctament.
**Comprovat i Ok**
2. Comprovar la incorporació de prefixos diferenciadors dels elements resultants de l'exportació:
**Comprovat i Ok**
