### ISSUE TITLE
Afegir una propietat per indicar una ajuda a l'hora de crear un annex mitjançant script.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#711]
Es demana afegir a la llista de dinàmica d'annexos un cop has introduït el títol del document un Help (explicació de la documentació que es demana o si cal incloure-la)  com es pot fer en format html quan crees un document normal.

![image](https://user-images.githubusercontent.com/18436867/218965545-936f0dfb-93ab-4c42-bdf3-4b07401893f0.png)

![image](https://user-images.githubusercontent.com/18436867/218965561-6d0a3df2-d6e8-4929-8143-0b1af1e44a45.png)

**Comment by jparedes-indra** [comment]
Esta funcionalidad tiene implicaciones importantes en el asistente de tramitación y no conviene implementarla para esta versión de la plataforma.

**Comment by jsastre-dgtic** [comment]
La posposam per a la següent versió i la deixam a "no version yet"

**Comment by jparedes-indra** [comment]
Si en el script de anexo dinámico se introduce la línea siguiente, aparece la ayuda en el diálogo. IMPORTANTE: Se debe introducir la etiqueta HTML para mostrarla correctamente.

anex.setAyuda('\<p>Ayuda del anexo dinámico con un texto extremadamente largo para ver si detecta bien los saltos de líneas y el cuadro se adapta bien al multilínea.\</p>');

![image](https://github.com/user-attachments/assets/701e7826-06b8-4460-8a89-864e02690cc8)
![image](https://github.com/user-attachments/assets/ceb0c1fe-4f4d-4461-9b87-3c6c044c2564)
