### ISSUE TITLE
 Mostrar quan s'ha iniciat un pagament i el motiu de si ha fallat

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#712]
Actualment, només mostra els pagaments correctes, cal mostrar també quan ha anat malament i el motiu. Equiparar també la data d'inici en aquesta pantalla, com la d'auditoria i la de persistència.

![image](https://user-images.githubusercontent.com/18436867/219326962-e923f4ab-bc9a-47a3-954a-e91991d23722.png)

![image](https://user-images.githubusercontent.com/18436867/219326997-f630a2a2-c885-412b-bd9a-37004aae1e28.png)

**Comment by jsastre-dgtic** [comment]
Això pot incloure el mètode de pagament? atib-bizum-Targeta...

**Comment by jparedes-indra** [comment]
Si el pago está en curso y tiene errores, ahora pueden filtrarse sólo los que tienen errores.

![image](https://github.com/user-attachments/assets/f0dee68c-ca02-442a-9d8c-e6a4665fd6a4)

**Comment by jsastre-dgtic** [comment]
A l'auditoria en trobam 3 i a la info de pagaments només un. Perquè? Podríem suprimir el requisit d'haver de posar el NIF i que els mostràs tots?

![Image](https://github.com/user-attachments/assets/d19c9f91-14c0-4409-b1ee-0f7e49f93da6)

![Image](https://github.com/user-attachments/assets/b4979b4d-0295-4123-9362-e9abb32aeb52)

**Comment by jparedes-indra** [comment]
Se elimina la obligatoriedad del campo NIF e id sesión al filtrar y se muestran todos los pagos de forma automática, según los días configurados en la propiedad “filtroInicial” del sistrahelp.properties. 

Se muestran los pagos en curso (iniciados y que no se han validado todavía), y los completados, que aun estén en persistencia.

![imagen](https://github.com/user-attachments/assets/080e308d-347d-4b13-ae04-deabc98fc612)

![imagen](https://github.com/user-attachments/assets/bc1731b9-c8f7-45be-afd3-7d8b022e0c62)

Los pagos de trámites que no estén en persistencia no aparecerán, pero sí se podrán ver sus eventos en la auditoría, mientras esos eventos no se hayan purgado. Tampoco aparecerán los pagos que hayan sido cancelados.

**Comment by avillen-dgtic** [comment]
👍🏼
