### ISSUE TITLE
Incloure a l'ajuda els requisits d'importació 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#713]
Actualment, només funciona si les dues versions dels 2 entorns són exactament la mateixa

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/231983573-763a62f4-abe2-4b61-b2a4-1d7f40faf8ae.png)

**Comment by avillen-dgtic** [comment]
👍
