### ISSUE TITLE
Recerca i ordre de tràmits associats

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#714]
Actualment, i sobretot als Dominis Globals o d'Entitat, necessitam poder ordenar els tràmits associats a un Domini i filtrar amb un camp de recerca.

![image](https://user-images.githubusercontent.com/18436867/221179410-c693a7cb-aa88-42fe-abe0-08d5c713dbfd.png)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/231983731-fd926d47-e85d-440f-8870-1ae054d633d4.png)
