### ISSUE TITLE
Documentar perfil necessari per configurar securitzacions

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#715]
Un desenvolupador no pot configurar autenticacions de dominis d'àrea, però a la documentació només diu això:

4.2.3. Perfil Desenvolupador d’una Àrea concreta (exemple: STG_DES_GOIB_AREA01): 
Què pot fer a l’entorn SE: 
• Dominis/Fonts dades: manteniment complet de dominis/fonts dades 
d'àrea

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/231984042-df364a2a-9cf0-4fb8-8970-5ba8422abbf2.png)

**Comment by jsastre-dgtic** [comment]
Manca actualitzar documentació:
https://github.com/GovernIB/sistra2/blob/sistra2-1.5/doc/SISTRA2_Arquitectura.odt

**Comment by jparedes-indra** [comment]
Se actualiza documento con los cambios en entornos, BBDD, requisitos para promocionar, perfil para modificar autenticaciones...

**Comment by jsastre-dgtic** [comment]
Manca BD a l'esquema de l'arquitectura:

![image](https://user-images.githubusercontent.com/18436867/235843968-89414242-d277-4a40-becb-b4c0ac228ad8.png)

**Comment by jparedes-indra** [comment]
Se actualiza el esquema de BBDD en el documento de arquitectura.

![image](https://github.com/GovernIB/sistra2/assets/67064375/faf4d412-8c99-419d-8630-a4068c1a9807)

**Comment by avillen-dgtic** [comment]
👍
