### ISSUE TITLE
Corregir la visualització de les pàgines

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#716]
![image](https://user-images.githubusercontent.com/83401259/221856703-53ab9b64-2152-4866-906c-4f2ada04946b.png)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/231984202-65d5e2cd-9141-49c9-8e87-bb14a4bc07ab.png)

**Comment by avillen-dgtic** [comment]
👍

**Comment by avillen-dgtic** [comment]
![image](https://user-images.githubusercontent.com/83401259/232772387-15880ed5-7b93-4e8f-907a-7ab1a3edeae8.png)

A mesura que afegeixes noves pàgines, creix la finestra.

**Comment by jparedes-indra** [comment]
![imagen](https://user-images.githubusercontent.com/67064375/233858634-029ffad2-32de-42a9-8683-be0a5eddc393.png)

**Comment by avillen-dgtic** [comment]
👍
