### ISSUE TITLE
Crear una funció que retorni l'identificador del tràmit i la versió

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#717]
Així podríem distingir i classificar al BO aquestes coses:
https://se.caib.es/sistramitfront/asistente/iniciarTramite.html?tramite=CAIB.EDUCACIO.IQPIB_CURSHABILITA&version=1&idioma=ca&servicioCatalogo=false&idTramiteCatalogo=3972481&parametros= 

https://se.caib.es/sistramitfront/asistente/iniciarTramite.html?tramite=CAIB.EDUCACIO.IQPIB_CURSHABILITA&version=1&idioma=ca&servicioCatalogo=false&idTramiteCatalogo=1564828&parametros= 

https://se.caib.es/sistramitfront/asistente/iniciarTramite.html?tramite=CAIB.EDUCACIO.IQPIB_CURSHABILITA&version=1&idioma=ca&servicioCatalogo=false&idTramiteCatalogo=2889722&parametros= 

https://se.caib.es/sistramitfront/asistente/iniciarTramite.html?tramite=CAIB.EDUCACIO.IQPIB_CURSHABILITA&version=1&idioma=ca&servicioCatalogo=false&idTramiteCatalogo=4488552&parametros=

**Comment by jparedes-indra** [comment]
Se crean las funciones getIdTramite() y getVersionTramite(), que devuelven el id compuesto y la versión del trámite en ejecución.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/d3a64bef-1258-4dea-b1e4-8f369e81ea4a)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/09d6ca13-847a-46f9-af1e-42672ba1cea5)

**Comment by avillen-dgtic** [comment]
👍
