### ISSUE TITLE
Quatre millores a la finestra de desenvolupament dels scripts

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#718]
1. Al tauler d'ajuda fer que apareguin línies per distingir visualment a quina línia correspon cada icona de ? facilitar-ne la visualització.

![image](https://user-images.githubusercontent.com/18436867/223110558-27611d0c-4967-4ead-a817-0ee7c588d4d6.png)

2. Fer que el tauler d'ajuda aparegui també quan l'script està en mode només lectura, ja que mentre es llegeix l'script es podria consultar l'ajuda de cada funció.

3. Al panell de codificació, podeu personalitzar els colors, per exemple per permetre que, per defecte, aparegués amb el fons blanc (per homogeneïtzar-se amb la resta de la pantalla) i, si els usuaris volen posar una altra combinació de colors, amb el fons negre, per exemple, poder canviar amb facilitat.
![image](https://user-images.githubusercontent.com/18436867/223110889-0df39523-fe73-43d4-b368-3693a4c4a3be.png)

4. Quan navegues per l'ajuda, caldria millorar la “molla de pa” per permetre tornar a pantalles anteriors, ja que no sempre és possible i has de tornar a accedir des de la pantalla principal.

**Comment by jparedes-indra** [comment]
Ahora se ven unas líneas en las ayudas que permiten identificar mejor el botón correspondiente a cada una de ellas. También se permite acceder a las ayudas, mensajes y otros elementos en modo sólo lectura y se ha mejorado la navegación en las ayudas, con un botón para ir atrás. Además, se ha homogeneizado el color del editor de código, aunque se permite cambiarlo como estaba antes.

![image](https://github.com/GovernIB/sistra2/assets/67064375/6cac06b7-d087-4d98-bf6d-fd83aa7b1f1e)
![image](https://github.com/GovernIB/sistra2/assets/67064375/57631f66-dc07-44ae-952f-45e8c536b4fd)

**Comment by avillen-dgtic** [comment]
El comportament és estrany. 

![#000](https://github.com/GovernIB/sistra2/assets/83401259/b328068c-96a5-4e52-831c-5681dc52920b)

**Comment by jsastre-dgtic** [comment]
ok
