### ISSUE TITLE
La paginació a STH canvia el num dels resultats, però no els resultats de la consulta

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#719]
![paginacio STH](https://user-images.githubusercontent.com/18436867/223710269-c31e93c6-d8a1-418e-9bdc-8f4e2b6e60a7.gif)

**Comment by jsastre-dgtic** [comment]
També cal substituir el literal de peu de pàgina on es mostra el total de resultats:

1-30 of 19090

Aquí es mesclen 2 conceptes: els resultats i les pàgines. Cal distingir i posar:
 "1-30 de X pàgines (total de resultats: 19090)"

**Comment by jparedes-indra** [comment]
Se ha modificado el texto del pié en la auditoría, pero no se ha resuelto aun el problema del refresco si la sesión ha expirado. Se resolverá en la siguiente revisión.

![image](https://user-images.githubusercontent.com/67064375/231984625-5a637eae-0a9d-461f-b4bb-8bc0adfc8549.png)

**Comment by jsastre-dgtic** [comment]
Ho acabam de validar en acabar la tasca pel tema refresc.

**Comment by jparedes-indra** [comment]
Se ha generalizado el uso de la nueva forma de indicar los resultados y las páginas en todas las pantallas de STG y STH.
 
![image](https://github.com/GovernIB/sistra2/assets/67064375/07f89664-2723-423d-a0f1-880c8cc85e01)

Queda pendiente prevenir la caducidad de la sesión.

**Comment by avillen-dgtic** [comment]
👍

**Comment by jsastre-dgtic** [comment]
Cal afegir el missatge en caducar sessió

**Comment by jparedes-indra** [comment]
Al pasar 30 minutos (o el tiempo de inactividad configurado en el web.xml), aparece un popup que indica la caducidad de la sesión y al pulsar el botón se recarga la aplicación (STG y STH).

![image](https://github.com/GovernIB/sistra2/assets/67064375/42d32c3f-9c49-4f08-97e2-65f43e07afcf)

**Comment by avillen-dgtic** [comment]
👍
