### ISSUE TITLE
Tractament de caràcters a les extensions dels fitxers

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#720]
Quan es configuren les extensions als tràmits i s'introdueix les extensions permeses, si aquestes estan en majúscules, al ciutadà li dona error.

![image](https://user-images.githubusercontent.com/83401259/224269019-29f5f1d7-7974-493d-8818-7f03ae186aad.png)
![image](https://user-images.githubusercontent.com/83401259/224269025-037ea9c4-f0b8-497d-80a5-15873ae77566.png)

Cal tractar aquesta casuística.

**Comment by jparedes-indra** [comment]
Se facilitarán los updates necesarios por correo.

**Comment by avillen-dgtic** [comment]
👍
