### ISSUE TITLE
Esborrar els espais a l'input

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#721]
S'han de llevar els espais del començament i acabament dels inputs de STG, STH i STM mitjançant un trimat del camp.

**Comment by jparedes-indra** [comment]
Se eliminan los espacios del principio y del final del texto al clicar fuera del input, en todas las pantallas de STG y STH.

![image](https://github.com/GovernIB/sistra2/assets/67064375/9a7c1b6b-5796-4be0-acae-ee6db0cfdaf9)
![image](https://github.com/GovernIB/sistra2/assets/67064375/deebb231-afc6-4298-b619-e814b69394e2)

**Comment by jparedes-indra** [comment]
Se eliminan los espacios del principio y del final del texto al clicar fuera del input, en todas las pantallas de STG y STH.

![image](https://github.com/GovernIB/sistra2/assets/67064375/9a7c1b6b-5796-4be0-acae-ee6db0cfdaf9)
![image](https://github.com/GovernIB/sistra2/assets/67064375/deebb231-afc6-4298-b619-e814b69394e2)

Queda pendiente hacer lo mismo en SISTRAMIT.

**Comment by avillen-dgtic** [comment]
![image](https://github.com/GovernIB/sistra2/assets/83401259/34fd97f3-fd6d-4716-9758-7d39ca6d3975)

**Comment by jsastre-dgtic** [comment]
ok

**Comment by jparedes-indra** [comment]
Debe reabrirse, ya que quedaba pendiente hacer el trimado en STT.

**Comment by jsastre-dgtic** [comment]
Oberta

**Comment by jsastre-dgtic** [comment]
ok
