### ISSUE TITLE
Llista elements: Adaptar editor formulari

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#723]

**Comment by jparedes-indra** [comment]
- [x] Lógica para renderizado HTML del nuevo componente
- [x] Adaptar editor formulario (pantalla principal)
- [x] Adaptar editor formulario (pantalla detalle)
- [ ] Adaptar scripts formulario
- [x] Vista del editor de formularios

**Comment by jparedes-indra** [comment]
Se añade el nuevo elemento y todas las propiedades necesarias.

![image](https://github.com/GovernIB/sistra2/assets/67064375/4690e99d-9a4f-42fd-906f-f701f46d7841)
![image](https://github.com/GovernIB/sistra2/assets/67064375/0fd0d29d-e395-43ce-9352-6a277e70d402)

Se actualizan las ayudas del editor de formularios.

**Comment by avillen-dgtic** [comment]
👍
