### ISSUE TITLE
Llista elements: Adaptar scripts flux tramitació

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#724]

**Comment by jparedes-indra** [comment]
Se añaden las siguientes funciones para los scripts.
DATOS_VALOR.crearValorListaElementos
DATOS_VALOR.setValorListaElementos
DATOS_VALORESINICIALES.crearValorListaElementos
DATOS_VALORESINICIALES.setValorListaElementos
PLUGIN_DATOSFORMULARIO.getNumeroElementos
PLUGIN_DATOSFORMULARIO.getNumeroValoresValorElementoMultiple
PLUGIN_DATOSFORMULARIO.getValorElemento
PLUGIN_DATOSFORMULARIO.getValorElementoCompuesto
PLUGIN_DATOSFORMULARIO.getValorElementoMultiple
PLUGIN_FORMULARIO.getNumeroElementos
PLUGIN_FORMULARIO.getNumeroValoresValorElementoMultiple
PLUGIN_FORMULARIO.getValorElemento
PLUGIN_FORMULARIO.getValorElementoCompuesto
PLUGIN_FORMULARIO.getValorElementoMultiple

**Comment by avillen-dgtic** [comment]
👍
