### ISSUE TITLE
Llista elements: Adaptació part frontal

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#728]

**Comment by jsastre-dgtic** [comment]
- [x] Maquetació component
- [x] Adaptar lògica presentació pantalla principal (taula elements)
- [x] Adaptar lògica presentació pantalla detall (formulari element)

**Comment by jparedes-indra** [comment]
Se pueden ejecutar los trámites que integran LEL.

![image](https://github.com/GovernIB/sistra2/assets/67064375/b0b7b671-378d-44ca-8431-521ea2587c6e)
![image](https://github.com/GovernIB/sistra2/assets/67064375/d0116abe-fa56-4f5b-a9cd-c440dae678a5)
![image](https://github.com/GovernIB/sistra2/assets/67064375/cb062d3e-ed2e-410a-8a92-c816d6463e83)

**Comment by avillen-dgtic** [comment]
👍

**Comment by jsastre-dgtic** [comment]
ok
