### ISSUE TITLE
Llista elements: Adaptació lògica de negoci

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#729]

**Comment by jsastre-dgtic** [comment]
o Adaptar controlador formulari per a integració frontal
o Adaptar consum REST
o Adaptar la lògica del formulari intern (pantalla principal)
o Adaptar la lògica del formulari intern (pantalla detall)
o Adaptar scripts formulari
o Adaptar scripts flux tramitació
o Adaptació tractament XML
o Adaptació generació PDF genèric

**Comment by jsastre-dgtic** [comment]
- [x]  Adaptar controlador formulari per a integració frontal
- [x]  Adaptar consum REST
- [x]  Adaptar la lògica del formulari intern (pantalla principal)
- [x]  Adaptar la lògica del formulari intern (pantalla detall)
- [x]  Adaptar scripts formulari
- [x]  Adaptar scripts flux tramitació
- [x]  Adaptació tractament XML
- [x] Adaptació generació PDF genèric

**Comment by jparedes-indra** [comment]
Se modifica la lógica para todo el funcionamiento interno.

**Comment by avillen-dgtic** [comment]
👍
