### ISSUE TITLE
STG:  Importació tràmits: tréure paràmetres de registre en un apartat separat

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#73]
Treure el paràmetres de registre en un apartat separat, no vinculat a la versió

**Comment by jsastre-dgtic** [comment]
No veiem que ens aporti res els literals que surten tipus "codofi1 -", el que proposàvem és que es visualitzassin les dades que hem importat des de l'xml, i a la pantalla de revisió, haurien d'emplenar-se els desplegables que trobassin els mateixos valors a l'entorn on importam. Vull dir, que si existeix, simplement confirmem. Potser no fa falta tornar emplenar els 3 camps cada vegada. Ja ens pareix bé la revisió forçada, però no és necessari tornar emplenar si trobam l'oficina que ja estava definida a l'entorn previ. Si no trobam el mateix valor, el desplegable que surti en blanc i forçam a emplenar amb un valor vàlid.
![image](https://user-images.githubusercontent.com/18436867/51240510-2215bd80-197c-11e9-9000-b114cc28348f.png)

**Comment by amaciam-indra** [comment]
Sembla que la versió del tràmit que estau intentant importar ha quedat amb dades de destí del plugin mock de registre. Per favor, per fer la prova mirau d'establir valors del plugin REGWEB3.
El funcionament és bàsicament el que comentau. A la pantalla es previsualitzaran les dades de destí de la versió del tràmit i al pitjar al botó sortiràn els desplegables amb els valor precarregats, simplement per confirmar-los.
Per favor feu la prova tal i com vos indicam.

**Comment by jsastre-dgtic** [comment]
Exportam de nou una versió amb les dades correctes de rw3:
![image](https://user-images.githubusercontent.com/18436867/51247434-68bfe380-198d-11e9-927e-2488c8017976.png)
No s'hauria d'obrir la finestra d'exportar si el tenim bloqujat, bastaria digués això: està bloquejat (sense obrir la finestra que tanmateix només podem tancar)
![image](https://user-images.githubusercontent.com/18436867/51247498-986eeb80-198d-11e9-81af-6b9b5e430012.png)

Ara si visualitzam el que dius:
![image](https://user-images.githubusercontent.com/18436867/51247555-c6543000-198d-11e9-9f0b-78bf6335e895.png)

**Comment by jsastre-dgtic** [comment]
Deixo oberta la tasca per la petita millora proposada. Si vos estimau més traslladar la tasca ho comentam.
