### ISSUE TITLE
APB: Personalitzar codi SIA en dades de registre

### ISSUE THREAD

**Issue by fjcalderon-dgtic** [GovernIB/sistra2#730]
La funcionalitat permetrà personalitzar el codi SIA que SISTRA2 envia a RegWeb3, obtingut durant la consulta a un WebService per fer un registre d'entrada, mitjançant una nova funció a l'script "Establir dades destinació". Si aquesta funció no s'utilitza, el codi SIA enviat a registre serà el que té associat el tràmit en el procediment de ROLSAC corresponent

**Comment by jparedes-indra** [comment]
Ahora es posible indicar un código SIA diferente al asociado al PA.

![image](https://user-images.githubusercontent.com/67064375/231984882-06bcd0f9-344e-42b5-9619-c1b08b445e3c.png)

![image](https://user-images.githubusercontent.com/67064375/231984908-7f74c70f-81e4-43a0-92c5-94f5d654f3dd.png)

![image](https://user-images.githubusercontent.com/67064375/231984979-2de40381-74b7-4400-98ca-431787176ecc.png)

**Comment by avillen-dgtic** [comment]
👍
