### ISSUE TITLE
Canvi títol PA per títol Tràmit al formatador genèric

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#731]

**Comment by jparedes-indra** [comment]
Se crean dos nuevas propiedades en el properties del formateador: titulo.tramite (true/false) y subtitulo.mostrar (true/false)

![image](https://user-images.githubusercontent.com/67064375/231985254-687f4270-73e5-4634-b109-235daf834320.png)

**Comment by jsastre-dgtic** [comment]
Canviam properties:
# Indica si en el titulo se muestra el procedimiento junto con el titulo del formulario
#titulo.procedimiento=false

# Indica si en el títol se mostra el nom de tràmit
titulo.tramite=true 

#Aquesta propietat indica si es mostra sa descripció des formulari de SISTRA2
#subtitulo.mostrar=true

Refrescam m.cau, esperam més d'un min.

Executant: 
https://dev.caib.es/sistramitfront/asistente/iniciarTramite.html?tramite=CAIB.TESTS.TEST-REGISTRE&version=5&idioma=ca&servicioCatalogo=false&idTramiteCatalogo=3927161

Es reflecteix l'esperat: 
![image](https://user-images.githubusercontent.com/18436867/232987437-22b60aeb-68f5-4079-b2fd-da23598adbe0.png)
