### ISSUE TITLE
El botó Tanca no Tanca

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#732]
A l'accedir a la definició del tràmit des de STH, quan obrim l'script de firma, després no ens tanca finestra

![image](https://user-images.githubusercontent.com/18436867/228227420-3b17303e-4832-4211-a43f-adeaec4f0116.png)

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/228227669-629f2716-d114-41af-8bc2-35241c21077b.png)

**Comment by jparedes-indra** [comment]
Ya permite cerrar la ventana de cualquier script.

![image](https://github.com/GovernIB/sistra2/assets/67064375/4258af15-9600-4d39-a13d-57079fc5ed85)

**Comment by avillen-dgtic** [comment]
👍
