### ISSUE TITLE
Millorar el tractament d'un camp numèric amb l'opció "sense format"

### ISSUE THREAD

**Issue by fjcalderon-dgtic** [GovernIB/sistra2#733]
Si en un camp de formulari de tipus "número" se selecciona l'opció "sense format", després es permet indicar decimals i introduir els caràcters "." i “,” amb el problema addicional que no sempre es mostra un error de manera controlada.

**Comment by jparedes-indra** [comment]
Se ha corregido el problema que generaba error al seleccionar un campo numérico sin formato. Ahora se evita poner decimales y añadir la coma y se controla que se haya indicado un rango si se ha marcado el check.
 
![imagen](https://github.com/GovernIB/sistra2/assets/67064375/4aa319d0-b65e-4fca-9c05-ec2854792d7e)

**Comment by jsastre-dgtic** [comment]
Si introduïm 3.4 automàticament elimina el .4.
En canvi, si introduïm 3,4 o 3'4 no l'elimina i surt el missatge d'error corresponent:

![image](https://github.com/GovernIB/sistra2/assets/18436867/b5d30e65-3119-4d4c-bb79-06a2ef107ddf)

Cal homogeneïtzar comportaments i evitar eliminar automàticament el .4. Millor si surt l'avís.

**Comment by jparedes-indra** [comment]
Se modifica el comportamiento para que siempre muestre mensaje si el valor introducido no respeta el formato, en lugar de truncar el valor sobrante.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/6a86c725-45aa-4815-bf0c-f3045e3c73d7)

**Comment by avillen-dgtic** [comment]
👍
