### ISSUE TITLE
Separar l'àrea de l'Id. Tràmit (obviar Entitat)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#734]
Tenim una incongruència funcional:

quan copiam l'Id Tràmit a STH:

![image](https://user-images.githubusercontent.com/18436867/233621181-f378ac5e-93a1-4c18-bd8c-2b61e5ed092d.png)
No el trobam a STG
![image](https://user-images.githubusercontent.com/18436867/233621207-44d21ae7-146e-4df6-b2c2-ee71c3c12dc2.png)

**Comment by jparedes-indra** [comment]
![imagen](https://user-images.githubusercontent.com/67064375/233858397-5b6313b4-e096-4f21-bc11-e02199284257.png)

**Comment by avillen-dgtic** [comment]
👍
