### ISSUE TITLE
Controlar error al no posar valor al check

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#737]
![image](https://github.com/GovernIB/sistra2/assets/18436867/a39f8c63-983f-47c1-a02b-0ea6d6a4f767)

**Comment by jparedes-indra** [comment]
Ahora, si no se indica un valor en las propiedades siguientes en el componente Check, se muestra un aviso.

![image](https://github.com/GovernIB/sistra2/assets/67064375/56cf07fa-3cde-4041-bcd2-5d7de5fef54e)

**Comment by avillen-dgtic** [comment]
No s'hauria de permetre introduir espais o caràcters no visibles.

![image](https://github.com/GovernIB/sistra2/assets/83401259/02f2d18f-b9e2-4ee1-bf40-3ba312313a47)

#721

**Comment by jsastre-dgtic** [comment]
ok
