### ISSUE TITLE
En posar un missatge de control d'accés no ens deixa accessible el botó "Continuar". 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#739]
![image](https://github.com/GovernIB/sistra2/assets/18436867/70d18647-f78d-424b-9633-66ea21a03f97)

**Comment by jsastre-dgtic** [comment]
validarem en tenir-ho visible des de SE

**Comment by avillen-dgtic** [comment]
Es comprova i funciona
