### ISSUE TITLE
PLG: Anàlisi de requeriments instal·lació FIRe

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#75]
Es sol·licita avaluar els requeriments d'instal·lació del component centralitzat de FIRe a la CAIB,  a fi de poder oferir els serveis de Cl@ve Firma al ciutadà des de l'Assistent de Tramitació.

**Comment by rsanz-indra** [comment]
Pendiente de actualización FirmaWeb a FIRe 2.3

**Comment by rsanz-indra** [comment]
La instalación de los componentes de FIRe ha sido llevada a cabo por CAIB.
Hay que ver si es necesario por parte de Indra alguna actuación adicional.

**Comment by rsanz-indra** [comment]
Documentar estado del plugin

**Comment by rsanz-indra** [comment]
Se adjunta documento con el análisis de la integración con FIRe
[SISTRA2_FIRe.pdf](https://github.com/GovernIB/sistra2/files/3846642/SISTRA2_FIRe.pdf)
