### ISSUE TITLE
Permetre consultar Seccions reutilitzables utilitzades des del tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#750]
En els casos en què el formulari només tingui script de càrrega de dades inicial a través de seccions reutilitzables, es permetrà la consulta de l'script per poder revisar el contingut dels scripts des del formulari. El botó es marcarà d'un color diferent per indicar que la càrrega de dades només té codi als scripts de les seccions.

**Comment by jsastre-dgtic** [comment]
Crear una pantalla nova per poder consultar les SR que utilitzi el tràmit des d'on es puguin consultar (disseny i script). Per afegir i eliminar ja s'hauria de fer al dissenyador del formulari.
D'aquesta manera ja no caldria anar a l'script de CDI del tràmit per consultar els inserits a les SR, com es va proposar, ja que des d'aquesta nova pantalla ja es pot accedir, en mode lectura, a tota la definició de la SR.
![image](https://github.com/GovernIB/sistra2/assets/18436867/4be76442-acbc-40bf-b0a1-29b107d50286)

**Comment by jparedes-indra** [comment]
Dentro de una versión de trámite se pueden consultar las SR utilizadas, tanto el diseño del formulario como el script.

![image](https://github.com/GovernIB/sistra2/assets/67064375/ff7b0f14-e523-4053-801f-7d1442747fbd)

**Comment by jsastre-dgtic** [comment]
Cal canviar literal: Seccions Reutilitzables **emprades**

![image](https://github.com/GovernIB/sistra2/assets/18436867/3f2773df-c334-4e8e-a325-4d998194ccdf)

**Comment by jsastre-dgtic** [comment]
La resta ok

**Comment by avillen-dgtic** [comment]
👍
