### ISSUE TITLE
APB: Millorar correus que es generen en executar-se una alerta de STH o incidència de STT

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#753]
Al correu incloure una URL de manera que:

Si és una alerta, l'URL permet obrir STH i fer una cerca automàtica a l'auditoria d'esdeveniments, filtrant per l'esdeveniment, tràmit i versió associats a aquesta alerta. Si hi ha més d'un tràmit i versió (com succeirà a la versió 2), es generaria una URL per cada tràmit i versió (en la mesura del possible, segons la complexitat de la configuració definida).
Si és una incidència, l'URL permet obrir STH i fer una cerca automàtica a l'auditoria d'esdeveniments, filtrant per la sessió associada a la incidència.

**Comment by jparedes-indra** [comment]
Se añade enlace al final de correo, que permite abrir STH filtrando por sesión y ordenando por fechas.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/bc932ab6-733d-40b4-a481-6b4e547d93d0)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/3f773348-ab37-4243-90cc-b73a0fd442a7)

También se permite buscar por NIF en diferentes pantallas, al igual que se permitía ya buscar por sesión en esas pantallas.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/3025b9e4-c345-4200-9a4a-3181285ad7ac)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/00abddcf-e881-4581-b384-2b12c5f91980)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/f80896fe-c958-44d7-bf43-07152a575baa)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/de409bd9-f8b8-4725-8300-bf1be5134e09)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/f28e067f-9001-4389-b137-eae8c10c8d09)

**Comment by avillen-dgtic** [comment]
👍
