### ISSUE TITLE
Possibilitar l'exportació dels tràmits en mode consulta

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#754]
Modificar literal posant article a :
![image](https://github.com/GovernIB/sistra2/assets/18436867/d1c4be43-1e30-4314-825d-a84d8ef6a63e)

**Comment by jparedes-indra** [comment]
Se permitirá que un usuario que tenga permisos de consulta sobre un área, pueda exportar.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/66e425a5-a28b-4838-92f8-da102fc86280)

**Comment by jparedes-indra** [comment]
Ahora, un usuario con permisos de consulta, puede exportar trámites de su área.

![image](https://github.com/GovernIB/sistra2/assets/67064375/e9a5d725-11a6-464d-a42f-c2bf69ee6ff0)
![image](https://github.com/GovernIB/sistra2/assets/67064375/49cc3e88-efe6-4fa8-9de4-99ca9c26d312)
![image](https://github.com/GovernIB/sistra2/assets/67064375/84f64947-ddfe-44d8-8864-42977ed66938)

**Comment by avillen-dgtic** [comment]
👍
