### ISSUE TITLE
Canviar el missatge growl per popup i ok

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#755]
![image](https://github.com/GovernIB/sistra2/assets/18436867/bd6240fa-ae2b-4e6c-87e7-9aa38dfaeb84)

**Comment by jparedes-indra** [comment]
Ahora, este mensaje concreto se visualiza como un popup.

![image](https://github.com/GovernIB/sistra2/assets/67064375/34306055-eb93-4260-827b-aa2910102fda)

**Comment by avillen-dgtic** [comment]
Cal canviar el text per 
"Si el tràmit conté un domini o gestor de formularis amb un placeholder, la variable d'àrea corresponent ha d'estar creada."

**Comment by avillen-dgtic** [comment]
👍
