### ISSUE TITLE
Forçar majúscules

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#759]
Hem detectat que si configures un camp amb el check “Forçar majúscules” activat, funciona bé al formulari, però no al PDF ni XML.

**Comment by jparedes-indra** [comment]
Se ha añadido la funcionalidad que controla que en el XML se ponga a mayúsculas los campos en los que se ha indicado esa propiedad.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/6e5a0b40-94ab-4053-a98d-897b37347f94)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/c4efd090-320f-4350-9812-c4b3ec0298ae)

**Comment by jsastre-dgtic** [comment]
ok

**Comment by jsastre-dgtic** [comment]
Hem detectat que en configurar un camp de text com a no modificable i amb el check actiu de “Forçar majúscules”, dóna un error arran de la issue #759.

**Comment by jparedes-indra** [comment]
Ahora, si se marcan los checks "Forzar mayúscula" y "No modificable", lanza un aviso que impide guardar hasta no desactivar uno de ellos.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/f765d353-7526-41e7-babb-23cabec96e25)

**Comment by avillen-dgtic** [comment]
👍
