### ISSUE TITLE
STT: Workflow tramitació V: implementació lògica negoci de formularis (1a FASE)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#76]

**Comment by rsanz-indra** [comment]
Se entrega versión inicial implementación lógica de servidor de formularios con test unitarios.
En el siguiente ciclo se realizará un revisión en profundidad de todo el asistente en el que se corregirán los bugs que se encuentren.

**Comment by jsastre-dgtic** [comment]
Tancam 1a FASE i obrim 2a
