### ISSUE TITLE
No mostrar els camps ocults al pdf genèric

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#760]
Per defecte, no es mostrin aquests camps ocults al pdf. Al xml sí que ha d'aparèixer tot el que hi ha al formulari, però se n'evitarà la visualització al pdf genèric.

**Comment by jparedes-indra** [comment]
Se ha modificado la lógica para que, por defecto, no se muestren los campos ocultos en el PDF. También se obtiene este efecto si se añade lo siguiente en los properties del formateador genérico:

# Indica si se muestran los campos ocultos en el PDF
mostrar.campos.ocultos=false

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/17e9a8b1-6793-406c-8a65-ff37634f2bb9)

Por el contrario, si se indica lo siguiente, aparecerán los campos ocultos:

# Indica si se muestran los campos ocultos en el PDF
mostrar.campos.ocultos=true

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/1798f99d-53d7-42af-be46-78792d23a959)

**Comment by jsastre-dgtic** [comment]
En lloc de dependre d'un properties a nivell plataforma, podria dependre d'una propietat del tràmit concret?

![image](https://github.com/GovernIB/sistra2/assets/18436867/106ead55-af2b-4421-b389-90d841127a92)

![image](https://github.com/GovernIB/sistra2/assets/18436867/6dab397c-46c8-4f6c-9ba3-a4380615c7ae)

**Comment by jsastre-dgtic** [comment]
ok
