### ISSUE TITLE
Malformació d'URL dels tràmits

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#761]
Els URL per accedir als tràmits no s'estan muntant bé. 

![image](https://github.com/GovernIB/sistra2/assets/83401259/4c2f5ed1-ef6d-45cf-8fc5-183976a39429)

**Comment by jparedes-indra** [comment]
Se modifica la lógica para montar bien la URL al previsualizar un servicio de ROLSAC.

**Comment by jsastre-dgtic** [comment]
No la podem validar per no actualitzar-se el desplegable, tot i que hem esperat 15 min després de desar a rolsac la informació i de reiniciar tot sistra2... 

![image](https://github.com/GovernIB/sistra2/assets/18436867/ed41e2f3-f2c5-4895-b693-0041b17305b7)

**Comment by jsastre-dgtic** [comment]
veure #769

**Comment by jsastre-dgtic** [comment]
seguim igual https://github.com/GovernIB/sistra2/issues/761#issuecomment-1717383353

**Comment by jsastre-dgtic** [comment]
Seguim igual... &servicioCatalogo=false&idTramiteCatalogo=4070666

![image](https://github.com/GovernIB/sistra2/assets/18436867/8eb52fae-d17e-4bc5-9501-c39e20505cbf)

**Comment by jsastre-dgtic** [comment]
Ok, testejam:
https://dev.caib.es/sistramitfront/asistente/iniciarTramite.html?tramite=CAIB.APUBLICA.VALIDACION_PODERES&version=1&idioma=ca&servicioCatalogo=true&idTramiteCatalogo=4070666
