### ISSUE TITLE
Tractament d'extensions a nivell d'script no es respecta

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#763]
A la definició global tenim aquesta propietat, 
![image](https://github.com/GovernIB/sistra2/assets/83401259/8a6a8fb8-8db7-4a1d-86b7-4cc252e3b3a8)

A la definició del tràmit tenim definida que s'accepten totes les extensions, 
![image](https://github.com/GovernIB/sistra2/assets/83401259/05ece92e-7dfa-48bb-8087-46e259319486)

Tot així no deixa afegir aquests als scripts.
![image](https://github.com/GovernIB/sistra2/assets/83401259/d4c99378-f2c0-4838-9a4c-0ff1fb4cb805)

**Comment by avillen-dgtic** [comment]
Afegim la següent casuística
![image](https://github.com/GovernIB/sistra2/assets/83401259/e05daa4d-31e7-452a-b22b-b55b6933769a)

**Comment by jparedes-indra** [comment]
Se modifica la lógica para que las extensiones se separen por comas (se actualiza la ayuda para indicarlo).

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/8c4a04b3-7ba0-421c-af92-93f3aaecb0d9)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/c42fad0a-a287-4c87-ad31-87b06e507db8)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/d9629f58-89bf-4828-ab5f-87ae12d9f99c)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/1d13b283-9b43-49e4-bc35-1700cd4f3462)
