### ISSUE TITLE
Falla la importació de tràmits amb llistes d'elements

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#764]
![image](https://github.com/GovernIB/sistra2/assets/83401259/37d4c5dd-44b6-46ee-b9e0-750a93579046)

**Comment by avillen-dgtic** [comment]
👍

**Comment by jsastre-dgtic** [comment]
ok

![image](https://github.com/GovernIB/sistra2/assets/18436867/843a31b2-52be-411d-8266-e44b59ab9788)
