### ISSUE TITLE
Incloure gestió nou IDP de cl@ve

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#765]
- Nou check i la lògica apropiada per al tractament, per donar l'opció d'indicar que aparegui aquest nou IdP en entrar a Cl@ve des de cada tràmit que el tingui activat.
- Llençar un script SQL que detecti els tràmits que tenen activat un o els dos checks dels IdP a substituir i activeu el nou check per a aquest nou IdP. En els tràmits que no tinguin activat cap dels checks corresponents als IdP obsolets, el nou check del nou IdP quedarà sense activar.

**Comment by jparedes-indra** [comment]
Se permite configurar el nuevo IdP ofreció por Cl@ve en las propiedades de la definición del trámite y si se ha marcado, se incluye entre los métodos de autenticación.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/5dd7b7a9-b136-4eb7-a316-ccd305bd5e0b)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/4402f194-d388-4316-92a7-c14c75a398fd)

**Comment by avillen-dgtic** [comment]
👍
