### ISSUE TITLE
Filtre per al tipus de problema i àrea

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#766]
Poder filtrar per Tipus Problema a la pantalla Consulta d'Incidències 
Tipus Problema(combo que llegís els tipus configurats a STG)

**Comment by jparedes-indra** [comment]
Se permite buscar por los tipos de problema de las incidencias existentes y las áreas se pueden seleccionar mediante un combo para realizar las búsquedas.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/a3172f18-5266-49f9-aca5-4f9403efe648)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/287dbbf0-1d2c-4c20-a0a3-2eb8dd1594ed)

**Comment by avillen-dgtic** [comment]
![image](https://github.com/GovernIB/sistra2/assets/83401259/e4c19435-3167-431d-9849-e0fcc72ed8a5)
Cal revisar la col·locació dels elements. Aquesta distribució es reprodueix amb una resolució de 1080.

**Comment by jparedes-indra** [comment]
Se revisan los filtros de las pantallas de STH, para que se vea mejor la fecha y hora y quepan mejor en la pantalla.

**Comment by avillen-dgtic** [comment]
👍
