### ISSUE TITLE
Amplada Llista d'Elements 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#768]
Amplada igual i no l'accepta
![image](https://github.com/GovernIB/sistra2/assets/18436867/4163f212-1d42-48b8-8a8b-cc2bb5fd6bae)

![image](https://github.com/GovernIB/sistra2/assets/18436867/2846d099-0e78-40cb-a89a-6473e511c03a)
Corregir literal pantalla validacions
![image](https://github.com/GovernIB/sistra2/assets/18436867/d0afcea8-fbc0-48b8-bbc1-7314453798ef)

**Comment by jparedes-indra** [comment]
Se han corregido ayudas y literales, cambiando "llesta" por "llista".

**Comment by jsastre-dgtic** [comment]
NO S'HA CORREGIT LA MATEIXA ERRADA AL POPUP:
![image](https://github.com/GovernIB/sistra2/assets/18436867/6a5727ac-5a75-452f-8df3-f7fba23458e6)
