### ISSUE TITLE
 Desar configuracions per usuari

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#772]
Elements per pàgina, opcions invertir colors de l'editor

**Comment by jparedes-indra** [comment]
Se permite guardar la paginación desde cualquier página que la contenga y se persiste para ese usuario cuando inicia otra sesión en STG. También se añaden más valores en la paginación.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/8c820c2e-642b-46f6-8b66-ce9d46f473c6)

También se guarda el color seleccionado en el editor de scripts.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/7c4b24e5-3db4-40eb-8fdc-a42b22d84669)

**Comment by avillen-dgtic** [comment]
👍
