### ISSUE TITLE
A les Propietats globals, fer que en guardar s'eliminin els espais, si n'hi ha

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#773]
extensions permeses, idiomes...

**Comment by jparedes-indra** [comment]
Ahora, al guardar el valor de cualquier propiedad global, se eliminan los espacios.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/5473e6bb-62f1-4801-b899-d3525cebc452)

**Comment by avillen-dgtic** [comment]
👍
