### ISSUE TITLE
BUG en editar SERVEIS

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#775]
Problema amb editar TEST-SERVEI 
Intentant canviar l'Autenticació: 

![image](https://github.com/GovernIB/sistra2/assets/18436867/e58a5c92-825b-4859-a458-a5b9715034ee)
![image](https://github.com/GovernIB/sistra2/assets/18436867/7e646741-5231-4848-86d6-4254d4a6a63c)

**Comment by jparedes-indra** [comment]
Ya se puede guardar un servicio sin que se produzca este error al modificar la autenticación.

**Comment by avillen-dgtic** [comment]
👍
