### ISSUE TITLE
Comportament botó Nou Tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#776]
Quan tenim seleccionades totes les àrees no hauria d'estar activat el botó Nou Tràmit, perquè no sabem a quina àrea es vol. 
De fet, ara mateix he fet una prova i el m'ha posat a l'àrea de tests, cosa que no hauria de passar (àrea tests) 
A més a més, si cancel·lam tarda moltíssim a reaccionar (cancel·lar nou tràmit). Passa el mateix si seleccionam i des-seleccionam totes les àrees... tarda molt. Es podria optimitzar?

**Comment by jparedes-indra** [comment]
Ahora, si se selecciona más de un área, no aparece el botón "Nuevo trámite", pero si se selecciona sólo un área, sí lo hace.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/2ae6882e-7078-4a6b-87d4-661eec5617d1)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/68c4d37a-adfb-4223-b9e2-6a8e7578aa04)

**Comment by avillen-dgtic** [comment]
👍
