### ISSUE TITLE
BUG a l'script navegació entre pàgines des de "Verure pàg"

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#777]
![image](https://github.com/GovernIB/sistra2/assets/18436867/bf93e35d-a428-4013-a8c9-be47b5849272)
En fer clic a acceptar, després guardar canvis, el nostre script s'esborra de
validació i es passa a script de següent pàgina

**Comment by jparedes-indra** [comment]
Ya se ha corregido el guardado de las propiedades de la página actual, desde el botón "Veure pag" del editor de formulario.

**Comment by avillen-dgtic** [comment]
👍
