### ISSUE TITLE
Al correu que s'envia després del registre surt un ¿

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#778]
Al correu que s'envia després del registre, si s'ha configurat l'script d'Avís i s'executa el tràmit en català, inclou un "¿" al cos del missatge.

![image](https://github.com/GovernIB/sistra2/assets/18436867/e17b4297-87bb-415e-8798-abfe0c164b9f)

**Comment by jparedes-indra** [comment]
El problema radica en el propio html que se sube en la configuración de la entidad. No es un problema de la plataforma. Si se sube un html de un entorno en el que no se produce el problema, funcionará en el entorno que se configure ese html.

**Comment by avillen-dgtic** [comment]
👍
