### ISSUE TITLE
STG: Millores no crítiques pendents (Cicle12)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#78]
1.- Afegir botó de refresc en la capçalera per actualitzar la informació d'accés

2.- En les finestres modals convindria canviar el títol en funció de l'acció. Per exemple, si botó "Editar" --> "Edició d'Entitats", si botó "Nou" --> "Alta d'Entitat". 

3.- Permetre limitar l'accés a tràmits d'una àrea per al rol desenvolupador. Això està?

4.-La molla de pa ha d'actuar sobre cada element:
- Quan s'entra en la pantalla de definició de versió ha de marcar l'opció per defecte "Propietats"
- La versió del tràmit ha d'enllaçar a la pantalla de tràmits amb la versió seleccionada

5.- Presentar proposta per traduir automàticament català/castellà els camps de descripcions

6.- No canviar el coloret del “Vist” quan tenim seleccionada la fila. Ara canvia de blanc a groc. Deixar el blanc per evitar confusions del que vol dir. Aplicar-ho d'aquesta manera a tota l'aplicació.

7.- Millores missatges emergents (growl). "No té sentit treure un missatge emergent que desapareix abans de poder-lo llegir. Fent feina amb SISTRAGES, aquests missatges poden ser molestos perquè es posen damunt el botó que vols pitjar i has d'esperar a que se'n vagi l'emergent."

8.- Revisar totes les pantalles a nivell de correcció lingüística i el respectar l'opció d'idioma triada.

9.- Quan caduca la sessió surt un error genèric. Potser hauríem de tenir el missatge d'error més concret...

10.- Establir signants: actualment el funcionament dels signats és que hauran de firmar tots els que es fixin per script. L'opció de fer que un document hagi de ser signat per un signat o altre no està contemplat. Contemplar-ho com a millora.

**Comment by jsastre-dgtic** [comment]
Document de detall de les tasques de la issue #78

[issue 78_ Llistat de millores detectades ordenades per prioritat.pdf](https://github.com/GovernIB/sistra2/files/2782703/issue.78_.Llistat.de.millores.detectades.ordenades.per.prioritat.pdf)

**Comment by jsastre-dgtic** [comment]
Document on es detalla tot el que ha quedat pendent i el que s'ha fet de l'antiga #22 
[Issue 22millores detallades.pdf](https://github.com/GovernIB/sistra2/files/2782709/Issue.22millores.detallades.pdf)

**Comment by jsastre-dgtic** [comment]
Document on es detalla tot el que ha quedat pendent i el que s'ha fet de l'antiga #22
[Issue 22 millores detallades.pdf](https://github.com/GovernIB/sistra2/files/2782713/Issue.22.millores.detallades.pdf)

**Comment by jsastre-dgtic** [comment]
Quan caduca la sessió surt un error genèric. Potser hauríem de tenir el missatge d'error més concret...
![image](https://user-images.githubusercontent.com/18436867/52046620-735ea900-2547-11e9-90ca-ac4b6f605cdd.png)

![image](https://user-images.githubusercontent.com/18436867/52046606-6cd03180-2547-11e9-97fc-dcfdfebe91a0.png)

**Comment by jsastre-dgtic** [comment]
Establir signants: actualment el funcionament dels signats és que hauran de firmar tots els que es fixin per script. L'opció de fer que un document hagi de ser signat per un signat o altre no està contemplat. Contemplar-ho com a millora.

**Comment by jsastre-dgtic** [comment]
A nivell general, respectar els idiomes definits al formulari-propietats:
![image](https://user-images.githubusercontent.com/18436867/53475521-6793d300-3a70-11e9-81fb-613c913f2ca6.png)
![image](https://user-images.githubusercontent.com/18436867/53475525-6bbff080-3a70-11e9-93ef-e752b1761bf8.png)

**Comment by jsastre-dgtic** [comment]
PROPOSTA MILLORA: AL FORMATADOR FORMULARI INCLOURE CHECKBOX «PER DEFECTE», DE TAL MANERA QUE NO FOS OBLIGAT DEFINIR LA PLANTILLA PER DEFECTE A CADA FORMULARI.
![image](https://user-images.githubusercontent.com/18436867/53475565-84c8a180-3a70-11e9-82f7-5e2268375879.png)

**Comment by jsastre-dgtic** [comment]
Herència de la STT: Workflow tramitació II (implementació pas registrar - Cicle12) #79 , posposada per a la tasca d'adaptació al decret i lliurament presencial:
PROPOSTA NOVA: Incloure num registre per pantalla a la secció de descàrrega del Justificant
![image](https://user-images.githubusercontent.com/18436867/53476412-a32f9c80-3a72-11e9-81a8-28c3bc8a50b0.png)

**Comment by rsanz-indra** [comment]
Entendemos que esta entrada se puede dar por entregada, ya que se ha creado la #117 con las mejoras pendientes.
