### ISSUE TITLE
Millorar les descripcions i ajudes de les Propietats de la Plataforma

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#782]
![image](https://github.com/GovernIB/sistra2/assets/18436867/62f1716f-e6cd-4caa-82c2-dbbe5005ee95)

**Comment by jparedes-indra** [comment]
Se modifican las ayudas de las propiedades relativas a la purga y se eliminan las relativas a límites, al no utilizarse.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/7ca4e396-36eb-4c37-99b2-13591798299f)

**Comment by avillen-dgtic** [comment]
👍
