### ISSUE TITLE
Crear funció per calcular les hores entre una franja horària

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#783]

**Comment by jparedes-indra** [comment]
Se crea la función distanciaHoras(), que devuelve la distancia en horas, minutos y segundos entre dos fechas y/o dos horas.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/53625abc-c76e-4a90-8971-881e11142af8)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/91f0276a-483e-4f02-a58c-1789cb0ef865)

**Comment by avillen-dgtic** [comment]
👍
