### ISSUE TITLE
Crear funció per formatar cadena a Integer

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#784]

**Comment by jparedes-indra** [comment]
Se crea la función formateaCadenaAInt(), que permite transformar un string en un integer.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/ea553ea5-ef82-4ed3-be03-b41472dfc497)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/d811bf44-c018-47cf-ac0a-2268f5b358e3)

**Comment by avillen-dgtic** [comment]
👍
