### ISSUE TITLE
Modificar exemple d'ajuda NIE

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#785]
Cal revisar la documentació que fa referència als NIE. Pareix que hi ha una errada.

**Comment by jparedes-indra** [comment]
Se modifica la ayuda de la función esNie() para ofrecer ejemplos correctos.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/e241e0cb-a38f-43ed-bdd5-7cc9ca2040a0)

**Comment by avillen-dgtic** [comment]
👍
