### ISSUE TITLE
Canviar mida del camp NOM

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#786]
El camp NOM està capat amb una mida de 12 caràcters. Cal llevar les limitacions
![image](https://github.com/GovernIB/sistra2/assets/83401259/79140daa-76db-4a1a-8989-280cacfe4db4)

**Comment by jparedes-indra** [comment]
Se aumenta el tamaño del campo para permitir más caracteres y ver mejor su contenido.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/a9306f71-8e93-4d35-aff9-c6d06f5d8c09)

**Comment by avillen-dgtic** [comment]
👍
