### ISSUE TITLE
Guardar propietats a STH

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#787]
De la mateixa manera que a STG tenim una taula a ddbb on es guarda totes les configuracions de l'usuari, fer exactament el mateix però per a l'aplicació de STH.

**Comment by jparedes-indra** [comment]
Se guarda la paginación global, el idioma y el rol, a nivel de usuario.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/ded41c85-d18c-4588-9f07-e43a65abf8c4)

**Comment by avillen-dgtic** [comment]
👍
