### ISSUE TITLE
Canvi a l’ajuda: DATOS_VALORESINICIALES.setValorListaElementos (camp, valors)

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#788]
A la documentació, l'ajuda, cal canviar DATOS_VALOR (plugin inexistent), per DATOS_VALORESINICIALES.

Revisar la resta de la documentació que afecta aquest canvi.

**Comment by jparedes-indra** [comment]
Se corrige el texto de la ayuda y revisan resto de ayudas relacionadas con lista de elementos.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/6cbf5f5c-c459-43db-8cd1-95d365c33fea)

**Comment by avillen-dgtic** [comment]
👍
