### ISSUE TITLE
Canviar literal ajuda en línea

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#789]
Cal canviar el literal 'ajuda en línea' per 'ajuda contextual'.

![image](https://github.com/GovernIB/sistra2/assets/83401259/333774ab-b29c-4eb0-b63c-5e8aaef93612)

**Comment by jparedes-indra** [comment]
Se sustituye el literal.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/219a81ad-3232-4b8a-bfcb-7d86ef4bfb78)

**Comment by avillen-dgtic** [comment]
👍
