### ISSUE TITLE
STT: Workflow tramitació II (implementació pas registrar - Cicle12)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#79]
Venim de la tasca #69 
1.- Corregir haver de guardar formulari 
2.- Corregir el fet que a l'adjuntar un pdf no funcioni. Si posam un doc+generar pdf si.

NOTA: Cal deshabilitar la signatura de l'annex o canviar la configuració del plugin de signatura de l'entitat per apuntar al plugin mock:
Classname => es.caib.sistra2.commons.plugins.firmacliente.mock.ComponenteFirmaPluginMock

PROPOSTA NOVA: Incloure num registre per pantalla a la secció de descàrrega del Justificant
![image](https://user-images.githubusercontent.com/18436867/51592057-f439f700-1eee-11e9-9edb-13b7c9c7f926.png)

**Comment by jsastre-dgtic** [comment]
#79: Los puntos 1 y 2 están corregidos (commit 5371944 de GITHUB).  

#80: El punto 2 del detalle de la issues ya está resuelto (commit 89b8808 de GITHUB).

**Comment by rsanz-indra** [comment]
De esta tarea sólo quedaría incluir la nueva propuesta de mostrar el nº de registro al finalizar el trámite.
Como el frontal habrá que modificarlo para la tarea de adaptación al decreto y entrega presencial se propone posponer la modificación a dicha tarea para optimizar.

**Comment by jsastre-dgtic** [comment]
Ok, posposam la proposta
