### ISSUE TITLE
Formularis amb "Llista d'elements" no mostra bé l'estructura

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#790]
L'estructura no es mostra així com toca

**Comment by jparedes-indra** [comment]
Se corrige el problema y ahora es posible ver la estructura de formularios que contienen listas de elementos.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/d9a8a9d0-29b5-4df4-87cb-7cfa383724ae)

**Comment by avillen-dgtic** [comment]
👍
