### ISSUE TITLE
Error mostrant avís de validació

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#791]
El comportament en l'àmbit de mostrar l'avís és correcte. El problema és que després de mostrar l'error, si es prem "Acceptar", es tanca l'avís i si es prem "Següent" per continuar tramitant, es produeix l'error "Error no controlat a la capa de servei: null".

**Comment by jparedes-indra** [comment]
Se ha corregido el comportamiento para que, si se configura un mensaje como WARNING, tras cerrarlo se pueda continuar con la tramitación. 

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/b7efac59-6cb5-4f2f-8935-825fe2f75dae)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/c857f1a2-694a-4b84-a18d-731f64ee80e1)

**Comment by avillen-dgtic** [comment]
👍
