### ISSUE TITLE
Error no controlat fent una consulta a un domini d'un script

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#792]
Fent una consulta a un domini ens bota un missatge d'error. 
![image](https://github.com/GovernIB/sistra2/assets/83401259/ca47e086-33ba-470a-b831-da6bb9373316)

**Comment by jparedes-indra** [comment]
Se resuelve el problema y se permiten consultar dominios globales, de entidad y de área desde la pestaña “Dominios” del editor de scripts.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/70cb6f64-1dd4-4d71-a22f-84d0d7ba693a)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/400c2e7e-c94a-458e-8d4b-116c30197d0d)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/03427450-fc20-4d64-859a-d62adfcaab99)

**Comment by avillen-dgtic** [comment]
👍
