### ISSUE TITLE
Afegir propietat global TIMEOUT

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#794]
Afegir com a propietat global el temps en segons per tenir el control abans que aparegui el timeout de connexió.

**Comment by jparedes-indra** [comment]
Se crea la propiedad global para controlar el Timeout para STG.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/bb8c1ce3-d66d-4de8-b1a3-e559a15735d6)

**Comment by jparedes-indra** [comment]
También se añade una propiedad que activa o desactiva el timeout, por si se produjesen problemas en la ejecución de trámites.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/32bafc50-0ed0-4d45-867a-231690546132)
