### ISSUE TITLE
Error no controlat quan selecciones un tràmit

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#795]
Quan se selecciona un tràmit a STG i es vol copiar el text bota un error no controlat.

![image](https://github.com/GovernIB/sistra2/assets/83401259/00a73a47-f521-42c3-a59f-0694a8946523)

**Comment by jparedes-indra** [comment]
Se ha corregido e problema que provocaba un nullPointer al hacer click derecho sobre un trámite como desarrollador.

**Comment by avillen-dgtic** [comment]
👍
