### ISSUE TITLE
Exception dintre quadre de comandaments

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#796]
L'escenari és:

Entrem al quadre de comandament, busquem en temps real o per interval de temps i seleccionem a "Errors de tramitació", la classificació "Tràmits per error".
Cliquem sobre un error i s'obre el panell.
Fem clic per seleccionar el tràmit en el qual s'ha produït aquest error o doble clic per obrir les sessions associades a aquest error.
Tornem a fer clic sobre aquest mateix error (tancant el popup amb les sessions si l'hem obert) i es tanca el panell, desapareixent la marca de fila seleccionada.
En fer clic sobre aquest mateix error o un altre qualsevol, es produeix el nullPointer.

**Comment by jparedes-indra** [comment]
Se corrige el nullpointer al seleccionar la fila en el escenario indicado en la issue.
