### ISSUE TITLE
Resultats negatius al quadre de comandaments

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#797]
![image](https://github.com/GovernIB/sistra2/assets/83401259/17f11976-564d-4f90-bd8c-53f6322868e4)

Cal revisar la consulta que treu aquesta informació.

**Comment by jparedes-indra** [comment]
Se revisa la consulta que alimenta el CM y corrige la aparición de números negativos en el cuadro de mando.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/87e13c53-fcb5-4df4-85f7-a56acf91370b)

El problema estaba en que no se estaban considerando las sesiones, por lo que al buscar eventos de un día X, aparecía número negativo si se iniciaba un trámite el día anterior y al día siguiente se recuperaba y finalizaba con errores. Ahora esa sesión ya no se cuenta en la columna "Sesiones no finalizadas", al haber finalizado.

**Comment by avillen-dgtic** [comment]
👍🏼
