### ISSUE TITLE
Modificar l'ajuda  de PLUGIN_DOMINIOS

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#799]
Modificar l'ajuda de PLUGIN_DOMINIOS per indicar que els dominis d'àrea i entitat han d'anar precedits de “[idEntidad].[idArea].” i “[identitat].” respectivament.

**Comment by jparedes-indra** [comment]
Se especifica en la ayuda el formato y las palabras necesarias para referenciar un dominio según su ámbito.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/9f9a3007-3797-4c5c-a103-61c7b3a8ce0e)
