### ISSUE TITLE
STT: Anàlisi dels plug-ins d'integració

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#8]
Definició del mecanisme d'integració amb plug-ins de "navegació externa", per exemple (passarel·la de pagaments, firmaweb, clave autenticació)

**Comment by rsanz-indra** [comment]
Se actualiza documento de diseño técnico para recoger la propuesta de operativa de integración entre plugins para SISTRA2

**Comment by sgelabert-dgtic** [comment]
- Cal recollir en el document de disseny tècnic la integració amb la nova API Firma Web Simple. https://github.com/GovernIB/portafib/issues/148
- Cal avaluar si s'empra una API nova que permeti estendre la validesa dels documents signats emmagatzemats de manera temporal a SISTRA2

**Comment by amaciam-indra** [comment]
A la planificació del cicle 4 no s'havia previst avançar en la qüestió dels plugins, però si ho considerau oportú es pot mirar d'analitzar a nivell tècnic i fer algunes proves de concepte.

**Comment by rsanz-indra** [comment]
Respecto a la implementación de los plugins estamos analizando la nueva API Firma Web Simple y PluginsIB y nos ha surgido la duda de como se quieren definir los plugins de Sistra2:

-  Los plugins se definen desde el punto de uso de Sistra2 y en su implementación pueden usarse plugins ya existentes de PluginsIB, de otro proveedor o una implementación propia. Esta solución aislaría Sistra2 del proyecto de PluginsIB respecto a la evolución de requerimientos de Sistra2.
- Los plugins a usar en Sistra2 deben definirse dentro del proyecto de PluginsIB (en caso necesario habría que añadir, modificar o ampliar los plugins existentes, ya hemos visto temas que se deberían cambiar para Sistra2). Esta solución estaría ligada a la definición de PluginsIB y permitiría usar directamente plugins definidos en PluginsIB pero ante nuevos requerimientos podría afectar a resto aplicaciones que usen dichos plugins.

Las 2 soluciones tienen sus pros y contras, ya nos comentáis como queréis que se implemente.

**Comment by rsanz-indra** [comment]
Pendiente de trasladar últimos cambios del acta al documento

**Comment by rsanz-indra** [comment]
Actualizado el documento con los cambios del acta.

**Comment by sgelabert-dgtic** [comment]
No trobam la darrera versió del document "Análisis de plugins requeridos en SISTRA2", cal commitar-ho dins el directori SISTRA2/doc/pdf i fer-hi referència dins aquesta issue.
