### ISSUE TITLE
STT: Integració plugin registre II (Cicle 12)

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#80]
Venim de la tasca #50 
Definició i implementació del plugin RW3:
1.- Incloure el CODI SIA amb la informació que enviam a RW3.
2.- Cal corregir el literal:
![image](https://user-images.githubusercontent.com/18436867/51592233-5eeb3280-1eef-11e9-8b14-9477a881fc49.png)

**Comment by rsanz-indra** [comment]
Actualmente se indica por parte de la FBIT que no maneja el código SIA y está pendiente de decidir como incorporarlo

**Comment by jsastre-dgtic** [comment]
Adaptació codi SIA. 
Un cop s'adapti Regweb3 per passar-li el codi SIA del procediment cal ajustar el connector de registre per traslladar aquesta dada. Ara mateix Regweb3 no tracta aquesta dada.

**Comment by rsanz-indra** [comment]
Integrado con plugin actual de Regweb3 y ya se traslada código SIA. Se está tratando en #129.
Se puede cerrar esta entrada.
