### ISSUE TITLE
Evitar que aparegui error no controlat, perquè avisi si no es localitza el domini.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#800]
Veure https://github.com/GovernIB/sistra2/issues/799

**Comment by jparedes-indra** [comment]
Se muestra un mensaje en caso de no encontrar el dominio

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/bf2fb2bd-c7a5-4dec-82c1-3230a92b4234)
