### ISSUE TITLE
Domini referenciat sense  identificador vàlid

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#801]
Quan la plataforma avisa que el domini referenciat en un script no té un identificador vàlid, mostra uns paràmetres entre claus.

![image](https://github.com/GovernIB/sistra2/assets/18436867/abf50d50-aafb-4dcb-a8b7-c936641637c5)

**Comment by jparedes-indra** [comment]
Se muestran los parámetros en el mensaje de validación

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/6a137be6-5d91-4efe-9ff5-12cd5f34413b)
