### ISSUE TITLE
Bot erroni d'idioma a la pantalla  "Autenticació necessària"

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#802]
Quan intentam botar des de Carpeta a STT, ens canvia l'idioma, però només a la pantalla "Autenticació necessària":

![image](https://github.com/GovernIB/sistra2/assets/18436867/75540a28-3766-4ca0-8976-34331a3ec456)
Pantalla errònia:
![image](https://github.com/GovernIB/sistra2/assets/18436867/1fa64edd-c7d4-4f53-a8a8-0cf838030481)

![image](https://github.com/GovernIB/sistra2/assets/18436867/02ed3182-0f69-441f-92b1-7207b599fe6e)

**Comment by jparedes-indra** [comment]
Probarse en DEV para poder enlazar desde Carpeta.

**Comment by jsastre-dgtic** [comment]
Sense bot també surt el missatge en castellà

![image](https://github.com/GovernIB/sistra2/assets/18436867/855aec2a-cf71-4186-a8c3-ff6d1a655a30)

**Comment by jparedes-indra** [comment]
Se comprueba que aparece el Cargando en el idioma correspondiente.

**Comment by jsastre-dgtic** [comment]
comprovat i tancam
