### ISSUE TITLE
Millorar visualització informes-QC mòbil

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#804]
Resum diari i el correu que es rep en sol·licitar un informe del CM no es veuen adequadament al mòbil.

**Comment by jparedes-indra** [comment]
Se corrige la visualización desde el móvil de los correos de envío del cuadro de mando y el resumen diario.

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/c1e0dc90-a360-4128-9895-f53ddddef14a)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/45269715-a153-448c-8453-58ec0a5f863d)

![imagen](https://github.com/GovernIB/sistra2/assets/67064375/2d88a607-6de2-4c65-890e-f2f3f8f75804)

**Comment by jsastre-dgtic** [comment]
Seguim amb problemes de visualització (client HCL Verse 14.0.1 corporatiu + IOS 17.4.1)

![image](https://github.com/GovernIB/sistra2/assets/18436867/a9330930-5960-407d-8e84-9222f941bb1b)

**Comment by jparedes-indra** [comment]
Cada cliente de correo trata el código HTML de forma diferente y en este caso parece que no acepta correctamente las etiquetas ni estilos que sí son aceptados en la mayoría de clientes de correo móvil....

El objetivo de la issue es mejorar en lo posible la visualización de estos informes en la mayoría de clientes de correo.
