### ISSUE TITLE
A la pantalla Esdeveniment no ha de sortir el calendari

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#806]
![image](https://github.com/GovernIB/sistra2/assets/18436867/4f9d8735-3646-40f0-8ecf-4b4af9b8baf7)

**Comment by jparedes-indra** [comment]
Ya no se muestra el calendario en el detalle del evento cuando pulsas sobre la fecha.

![image](https://github.com/user-attachments/assets/c70c2a22-7fd7-4ae4-abe6-2404307bf15f)

**Comment by avillen-dgtic** [comment]
👍🏼
