### ISSUE TITLE
Ús de selectors de tipus cerca dinàmica als subformularis de les llistes d'elements

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#809]
L'ús de selectors de tipus cerca dinàmica als subformularis de les llistes d'elements no funcionen adequadament i impedeixen que es renderitzin els components que té darrere seu.

**Comment by jparedes-indra** [comment]
Si se añade un selector tipo búsqueda dinámica y luego otros componentes en el detalle de la lista de elementos, al ejecutar el trámite se muestra correctamente todo el contenido del subformulario.

![image](https://github.com/user-attachments/assets/bde9da2c-49c3-445d-921c-d3e2c392116d)
![image](https://github.com/user-attachments/assets/33006bcc-3a7f-4827-bc53-75f05433ab3c)

**Comment by jsastre-dgtic** [comment]
Intentam afegir el selector a la LEL d'abans i ens trobam això:
![Image](https://github.com/user-attachments/assets/fd3e26bf-1c98-4447-9bd8-84f3b8594d2d)

I a l'intentar validar:
![Image](https://github.com/user-attachments/assets/f4421066-9e74-44b4-97bc-636bb9449033)

**Comment by jparedes-indra** [comment]
Se prueba el caso y no se replica el problema.

![809pruebaErrorSelectorLel](https://github.com/user-attachments/assets/3948d2e0-8824-4a1e-b080-06eb00750183)

**Comment by jsastre-dgtic** [comment]
Trobam una incoungruència

![Image](https://github.com/user-attachments/assets/dfb3d1e0-c8fd-484d-8c4b-810f9d29ec20)
