### ISSUE TITLE
Introducció de valors a la llista d'elements 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#810]
Es detecta un mal funcionament del camp del formulari on s'entra aquest valor (10 o 99). Es comporta de manera estranya. Per poder escriure has d'esborrar el que hi ha prèviament, i si ho lleves s'inicialitza a 1. Per escriure 99, has d'esborrar-ho tot (Surt un 1), posar un 9 darrere l'1, i esborrar l'1 per afegir un 9 davant... 
Sembla un problema del mateix PrimeFaces, potser convé esperar a pujar versió PF, però cal mirar-ho.

**Comment by jparedes-indra** [comment]
Se pueden borrar todas las cifras de la propiedad “Nº máximo de elementos” y al guardar aparecerá un aviso.

![image](https://github.com/user-attachments/assets/f2b22e58-ed89-440f-9d1e-c1bc44857b13)

**Comment by jsastre-dgtic** [comment]
No s'eliminen les files
![Image](https://github.com/user-attachments/assets/6518d535-61c9-49e4-87f3-8124f9e63271)

**Comment by jparedes-indra** [comment]
Se ha solucionado el problema y ya se pueden eliminar elementos.
