### ISSUE TITLE
"Configuració d'entitat - Logo d'entitat" no representa un logo

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#812]
![image](https://github.com/GovernIB/sistra2/assets/18436867/f120d043-b801-4631-a983-5501e527f3b9)

**Comment by jparedes-indra** [comment]
Ahora se puede seleccionar un icono para el gestor de trámites, al igual que para el favicon del asistente.

![image](https://github.com/user-attachments/assets/e9fb47be-8229-4e1b-be37-dcdfc0d34156)
