### ISSUE TITLE
Traducció i correcció de l'ajuda "TABLA SCRIPTS REPRESENTACIÓN"

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#813]
Falta traduir l'ajuda a la 1.7.2 no hi és.
A més s'han de corregir errades...

![image](https://github.com/GovernIB/sistra2/assets/18436867/c697496a-09d9-4316-9015-174472e16d68)

**Comment by jparedes-indra** [comment]
Se corrigen erratas y se traduce a catalán.

![image](https://github.com/user-attachments/assets/03e82b76-a6e7-41eb-ba7f-69e99bb532bc)
![image](https://github.com/user-attachments/assets/a0911fd5-8232-4e04-ad6a-cbf502bd4f90)
