### ISSUE TITLE
PLUGIN_UTILS.esNif(NIF) només funciona si la lletra està en majúscules

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#814]
Si se configura el campo como identificador y se marcan los checks correspondientes, lo que se introduce manualmente o viene por script (autorrelleno, CDI…) se pone en mayúscula.
Si se configura como texto normal y se utilizan las funciones esNif, esNie, etc…, no admite las minúsculas.

**Comment by jparedes-indra** [comment]
Si en el script de validación del segundo campo se configura como texto normal y en el script de validación se usan funciones relacionadas con la validación de identificadores, se permite el uso de minúsculas y se registra correctamente.

![image](https://github.com/user-attachments/assets/22ff3dc9-e8a2-4505-86b7-88d4040ae1bc)
![image](https://github.com/user-attachments/assets/8409b701-7314-472c-80e2-079a8825b4b8)

**Comment by jsastre-dgtic** [comment]
No m'accepta la minúscula

var nif= PLUGIN_DATOSFORMULARIO.getValor('ESNIF');
var valid = PLUGIN_UTILS.esDni(nif);
if (!valid) {
PLUGIN_VALIDACION.setExisteAviso(true, 'WARNING');
PLUGIN_VALIDACION.setTextoMensajeAviso('dni erroni');
}

![Image](https://github.com/user-attachments/assets/e283b869-ab1d-4bcd-abe4-3095c1791670)

**Comment by jparedes-indra** [comment]
Se permite introducir minúsculas con los distintos métodos de validación.

![imagen](https://github.com/user-attachments/assets/c1a205c2-9a5c-4d68-8e58-4c0e1a7d2c0f)
