### ISSUE TITLE
Error java.lang.NullPointerException al consultar els scripts generats

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#815]
Quan es vol generar scripts. 
![image](https://github.com/user-attachments/assets/870935ed-cabb-4da5-8d6e-53ee197eb789)

![image](https://github.com/user-attachments/assets/e96c8ed2-687e-4aa7-8675-811dc4b6ee48)

![image](https://github.com/user-attachments/assets/29fa458e-abe6-4352-a444-95b24677be29)

**Comment by jparedes-indra** [comment]
Ya no se produce el nullPointer al consultar scripts desde la pantalla de “Generar scripts”.

![image](https://github.com/user-attachments/assets/88c4bdbe-94d0-499d-b1c4-460d37e4bb7e)
