### ISSUE TITLE
Previsualització de la versió d'un tràmit

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#818]
El botó de copiar no funciona quan el tràmit pertany a «Incorporats en SIA», però la previsualització sí que el pot obrir.
![#001](https://github.com/user-attachments/assets/af21fd91-d7f4-4f14-9231-a73274b8bd41)

**Comment by jparedes-indra** [comment]
Se permite copiar la URL con trámites incorporados en SIA y se corrige error que no permitía copiar URL cuando solo hay un elemento en el desplegable de trámites catálogo procedimientos.

![PruebaCopiarPrevisualizar](https://github.com/user-attachments/assets/e566e60a-1a45-447f-bdb1-aeaf5349b7bf)

**Comment by jsastre-dgtic** [comment]
https://dev.caib.es/sistramitfront/asistente/iniciarTramite.html?tramite=CAIB.TESTS.TEST-REGISTRE&version=5&idioma=ca&servicioCatalogo=false&idTramiteCatalogo=4159608
