### ISSUE TITLE
Les url de previsualització a SE mostren sempre el mateix idioma

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#820]
https://se.caib.es/sistramitfront/asistente/iniciarTramite.html?tramite=CAIB.IBSALUT.ANTICIPOS&version=2&idioma=es&servicioCatalogo=false&idTramiteCatalogo=4095671
mostra el tràmit en Català, tot i tenir idioma = es

**Comment by jparedes-indra** [comment]
Se comprueba que se puede tramitar en ambos idiomas.

**Comment by avillen-dgtic** [comment]
👍🏼
