### ISSUE TITLE
Actualitzar connector RW3

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/sistra2#821]
La versió 3.1.2 d'aquest connector ha deixat d'existir al repositori Maven del Govern, cal actualitzar el projecte de s2 a una versió superior.

**Comment by jparedes-indra** [comment]
Se ha subido la versión de la 3.1.2 a la 3.2.5 en el pom.xml del proyecto.

![image](https://github.com/user-attachments/assets/a183b189-14a8-439b-aed3-efe12f51e7f7)
