### ISSUE TITLE
Control d'accés - Error en esborrar Missatge d'avís

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#823]
Reproduïm l'error amb un tràmit diferent (TRAMIT_PLANTILLA v1) a l'entorn de dev (no se), on hi tenim un usuari de prova amb perfil desenvolupador:

![image](https://github.com/user-attachments/assets/c5943812-cb8e-440e-ab97-cdafb6497d9b)

![image](https://github.com/user-attachments/assets/6dfb925c-cea7-4f2e-a261-ac517937be9d)

**Comment by jparedes-indra** [comment]
Un usuario con único perfil de Desarrollador, puede eliminar un mensaje de aviso desde el control de acceso de una versión de un trámite.

![823-ezgif com-effects](https://github.com/user-attachments/assets/137a336a-07ca-42b6-b88a-fa1056d66f7c)
