### ISSUE TITLE
No es visualitzen les llistes numerades. 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#825]
N'hem creada una al "Cal saber":

![image](https://github.com/user-attachments/assets/d2d00d1c-be99-4acb-acde-052b21200507)

**Comment by jparedes-indra** [comment]
Ya se visualizan correctamente si se han definido en STG.

![image](https://github.com/user-attachments/assets/f2a4fe7d-05c9-42a0-ac33-b3e0fb1a6b42)
