### ISSUE TITLE
En importar un tràmit amb GFE a una àrea diferent no troba el GFE creat

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#826]
Si dupliques el tràmit en una altra àrea no dóna error
No obstant, si importes versió, sí que dóna l'error de no trobar el GFE.

![image](https://github.com/user-attachments/assets/42cc65e3-4bbb-464a-8227-2959eafe1e8d)

![image](https://github.com/user-attachments/assets/284e180e-cb78-4a5d-be7f-4c31ef28c1a6)

**Comment by jparedes-indra** [comment]
Se ha resuelto un problema con la caché tras importar, que impedía que se localizase el GFE en el área nueva.

**Comment by jsastre-dgtic** [comment]
Provat important un tràmit de se a dev (pinbal)
