### ISSUE TITLE
STG: Consulta de procediments de catàleg a partir de tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#83]
Mostra l'opció de consulta de procediments en selecció de tràmit-versió. Estudiar si a més dels procediments convindria mostrar el tràmit telemàtic del catàleg associat. Presentar una proposta de visualització.

**Comment by rsanz-indra** [comment]
Realizamos la siguiente propuesta:
- Consulta de procedimientos accesible desde Trámite (se verían los procedimientos asociados a las versiones del trámite) y desde Versión Trámite (se verían los procedimientos asociados a una versión en concreto)
- A la hora de visualizar el procedimiento, se visualizarían:  Procedimiento Rolsac (código rolsac procedimiento, código sia procedimiento, descripción procedimiento) y Trámite Rolsac (código rolsac, descripción trámite, plazo)

**Comment by sgelabert-dgtic** [comment]
ok em sembla correcte. Avisau-nos quan estiguin implementades sobre l'API de ROLSAC per poder-ho testejar sobre Swagger.

**Comment by jsastre-dgtic** [comment]
CORRECTE:
![image](https://user-images.githubusercontent.com/18436867/53562804-a9954580-3b52-11e9-9793-075789e27829.png)
