### ISSUE TITLE
iframe propertie a Portafib

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#830]
la propietat iframe del plugin de signatura no funciona correctament, ja que sempre mostra el contingut de PortaFIB en un iframe, quan si es posa a 'false' ho hauria de mostrar a pantalla completa i no en un iframe.

**Comment by jparedes-indra** [comment]
Si se configura la propiedad “iframe” a false en el plugin de firma, al firmar en el asistente aparecen las opciones de firma a pantalla completa.

![image](https://github.com/user-attachments/assets/feeceb92-20ba-4636-81f5-a3c3eb83a9c1)
![image](https://github.com/user-attachments/assets/77566439-f80d-46d3-be2e-dda68cdef1ed)
