### ISSUE TITLE
Autoemplenat de llistes d'elements

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#831]
S'ha detectat una deficiència a Helium amb els camps de llista d'elements dels formularis de S2.

Volem que les dades introduïdes d'una llista d'elements, d'un primer formulari, autoemplenin dues llistes d'elements d'un segon formulari. 
Ara mateix SISTRA2 no permet realitzar autoemplenaments de llistats d'elements d'aquesta manera… 
(No ho fa tant amb Postguardar formulari com utilitzant l'script d'autoemplenat de la llista d'elements i dels propis elements dins de la llista)

**Comment by jparedes-indra** [comment]
Para realizar la prueba se debe crear el script en el Postguardar del formulario origen y haber creado previamente la LEL en el formulario destino.
La lista de elementos del segundo formulario se rellena con los datos que le indicamos en el script Postguardar formulario.

![image](https://github.com/user-attachments/assets/7ae418dc-6e6e-4b08-8c02-da07e2aa1339)
![PruebaAutorellenarListaElementos](https://github.com/user-attachments/assets/b5d4defd-2dab-460f-a7da-7570061c5e49)
