### ISSUE TITLE
Canviar el comportament de l'edició de les SR.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#833]
Ara mateix, només pot editar una SR l'usuari que té tant rol d'administrador d'entitat com de desenvolupador, entra com a desenvolupador i prèviament ha bloquejat aquesta SR com a administrador d'entitat.

El que es desitja és que si el rol és de Desenvolupador, no pugui editar, encara que aquest mateix usuari l'hagi bloquejat com a Administrador d'entitat. Només s'han de poder editar amb el rol d'Administrador, i ha de bastar aquest rol per a fer-ho.

**Comment by jparedes-indra** [comment]
Si un usuario ha bloqueado una SR como administrador de entidad, con el rol de desarrollador solo puede consultarla, como el resto de desarrolladores.

![image](https://github.com/user-attachments/assets/4bf4e2b0-6ed9-48e7-8780-b6a79e4eee12)
