### ISSUE TITLE
Que STT pugui recuperar informació del mètode de pagament utilitzat a PIB

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#834]

**Comment by jparedes-indra** [comment]
Si se produce un problema con la comunicación con la pasarela de pago y ante el hecho de que el estado del pago no se puede conocer con seguridad (si se ha iniciado, si se ha validado…), se muestra un mensaje que indica que el pago no se ha podido validar y en STH se muestra el detalle del evento “Pago electrónico no verificado”.

![image](https://github.com/user-attachments/assets/5b6d5256-46f8-4339-9332-4878b3836598)

**Comment by jparedes-indra** [comment]
Si se produce un problema con la comunicación con la pasarela de pago y ante el hecho de que el estado del pago no se puede conocer con seguridad (si se ha iniciado, si se ha validado…), se muestra un mensaje que indica que el pago no se ha podido validar y en STH se muestra el detalle del evento “Pago electrónico no verificado”.

![image](https://github.com/user-attachments/assets/5b6d5256-46f8-4339-9332-4878b3836598)
![image](https://github.com/user-attachments/assets/79b11178-ef13-4d88-8325-55e6eee8a922)

También se muestra en el evento de “Pago electrónico verificado”, el método de pago utilizado.

![image](https://github.com/user-attachments/assets/3f08663d-8dd4-44df-91f9-0fc7b297dddd)

Además, se capturan errores de PIB para mostrarlos en STH.

![image](https://github.com/user-attachments/assets/fe2793cd-3702-4c4f-9600-864fbe88040f)
![image](https://github.com/user-attachments/assets/4d5dfd88-d1aa-4a95-8b3b-5fc3c00f3888)
![image](https://github.com/user-attachments/assets/93242498-d73d-4c9f-9a8b-016387aa300e)
