### ISSUE TITLE
Canviar "sessions ok" per "Sessions finalitzades" al QC

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#837]
Proposaria  al QC canviar "sessions ok" per "Sessions finalitzades", atès que el contrari es diu "Sessions no finalitzades",  entenent que ok=finalitzat.

**Comment by jparedes-indra** [comment]
Se cambia el literal.

![image](https://github.com/user-attachments/assets/2527d779-5e08-4fff-be66-19ec890c2f93)

**Comment by avillen-dgtic** [comment]
👍🏼
