### ISSUE TITLE
Normalització de nom de fitxers annexats 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#839]
S'ha detectat que si l'usuari annexa fitxers amb noms que contenen ., a més del que separa el nom de l'extensió, es produeix un error a RW3.

**Comment by jparedes-indra** [comment]
Se puede registrar con anexos con nombres largos y con caracteres poco comunes.

![image](https://github.com/user-attachments/assets/0dcddec0-c00c-4985-95a2-68d81f76b897)
![image](https://github.com/user-attachments/assets/6ff60b3f-b8fa-4a83-a5ae-27e2a19d2eaf)
![image](https://github.com/user-attachments/assets/6ebc0eb6-aebf-46bf-848d-eb6e0166b979)

**Comment by jsastre-dgtic** [comment]
Annexat i registrat un document amb nom "Dosier-mi-primer-jardin-de-permacultura.,´Dosier-mi-primer-jardin-de-permacultura¿+" com a  FIRMA-ANNEX-2-1-99999999R.pdf.
