### ISSUE TITLE
STT: Autenticació des de Carpeta Ciutadana en base al tiquet generat a l'API externa

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#84]
En anteriores ciclos se implementó el API externa de STT para poder consultar los trámites en persistencia desde la Carpeta Ciudadana y posteriormente poder reanudarlos. Para reanudar un trámite se realizará un traspaso de sesión basado en un ticket de acceso de forma que se pasen los datos del usuario autenticado en la Carpeta Ciudadana y el identificador de sesión del trámite a retomar. Quedaba por implementar la modificación del proceso de login del STT para que funcionase a través del ticket generado mediante el API externa de STT. El proceso de autenticación se basa en primero generar un ticket mediante el API externa de STT (comunicación entre Carpeta Ciudadana y STT)  y luego una redirección desde el navegador del ciudadano con este ticket (en este punto es dónde hay que modificar el proceso de login del STT para pueda autenticarse a partir del ticket).

**Comment by rsanz-indra** [comment]
Por error se subieron los ficheros a otra issue. Se han modificado los ficheros implicados para poder asociarlos mediante el commit anterior a esta issue.

**Comment by jsastre-dgtic** [comment]
S'ha de crear UN NOU USUARI: $carpeta_sistramit amb el ROL STT_API_EXT. Comprovat funcionament
