### ISSUE TITLE
Avaluació de camps ocults

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#840]
S'ha detectat un problema a l'avaluació dels camps ocults. Com s'indica a l'script d'autoemplenament, quan la dependència és per camps d'una altra pàgina només s'executa quan els camps són de només lectura o és la primera vegada (1). El problema es produeix als camps ocults, ja que no es poden marcar com a només lectura i no es pinten en els PDF personalitzats en imprimir el formulari que els utilitza. Cal contemplar també que si és un camp ocult s'executi sempre.

![image](https://github.com/user-attachments/assets/6a27f094-725e-4df7-973d-866e62de39b2)

**Comment by jparedes-indra** [comment]
Se ha detectado que un campo oculto con un script de autorrelleno que tiene dependencias de otros campos situados en otra página, no se evaluaba. Con esta issue ya se evalúa correctamente.

En este xml el campo “CHECK” está en una página y el campo “OCULTO” en otra.

<\?xml version="1.0" encoding="UTF-8"?>
<urn:FORMULARIO accion="" xmlns:urn="urn:es:caib:sistra2:xml:formulario:v1:model"><CAMPO id=\"CHECK\" tipo=\"simple\">\<VALOR>S<\/VALOR><\/CAMPO>\<CAMPO id="OCULTO" tipo="simple">\<VALOR>S<\/VALOR><\/CAMPO><\/urn:FORMULARIO>
