### ISSUE TITLE
STG: Verificacions addicionals exportació versió tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#88]
Implementar millores sobre la verificació d'una versió de tràmit abans exportar per evitar errors posteriors: verificar si tots literals en els idiomes suportats, si s'empren camps / dominis no vàlids, si s'han configurat plantilles per als formularis, etc.

**Comment by rsanz-indra** [comment]
Se realizan las siguientes validaciones:
- Verificación literales obligatorios según configuración trámite
- Verificación sintáctica scripts
- Verificación dominios asociados al trámite usados desde PLUGIN_DOMINIOS
- Verificación dominios asociaddos al trámite usados desde selectores
- Verificación formateadores/plantillas asociados a formularios
- Verificación de parámetros registro cumplimentados

En un futuro se podrían ampliar las validaciones.

Como mejora interesante sería muy interesante que desde la pantalla de verificación se pudiese acceder al elemento en cuestión para modificarlo.

**Comment by jsastre-dgtic** [comment]
Ok, passam la millora a https://github.com/GovernIB/sistra2/issues/114#issue-419434943

**Comment by jsastre-dgtic** [comment]
No valida els scripts i versió. Comprovar-ho...
