### ISSUE TITLE
STG: Generació contingut ajudes vista Administrador Entitat / Desenvolupador

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#89]
**IMPORTANT:** Aquesta ajuda online ha d'anar a un directori del servidor en format html i fora del ear per tal de poder mantenir-la sense haver de desplegar l'ear cada vegada que es produeixi un petit canvi.

- Pantalla "Configuració entitat"
- Pantalla llista "formatador formulari"
- Fitxa "formatador formulari"
- Pantalla llista "Fonts de dades entitat"
- Fitxa "Fonts de dades entitat"
- Pantalla llista "Missatges d'avís entitat"
- Fitxa "Missatges d'avís entitat"
- Pantalla llista "Rols i permisos"
- Fitxa "Rols i permisos"
- Pantalla "Tràmits"
- Fitxa "Control d'accés"
- Fitxa "històric"
- Pantalla "Propietats" de versió de tràmit
- Pantalla "Dominis empleats" de versió de tràmit
- Pantalla "Cal Saber" de versió de tràmit
- Pantalla pas "Omplir formulari" de versió de tràmit
- Pantalla document formulari
- Pantalla de disseny de formulari
- Fitxa "Propietats del formulari"
- Pantalla pas "Annexar document"
- Pantalla document annex
- Pantalla pas "Pagar taxa"
- Pantalla document taxa
- Pantalla pas "Registrar formulari"

**Comment by jsastre-dgtic** [comment]
**S'han implementat:**

* Pantalla "Configuració entitat"
* Pantalla llista "formatador formulari"
* Fitxa "formatador formulari"
* Pantalla llista "Fonts de dades entitat"
* Fitxa "Fonts de dades entitat"
* Pantalla llista "Missatges d'avís entitat"
* Fitxa "Missatges d'avís entitat"
* Pantalla llista "Rols i permisos"
* Fitxa "Rols i permisos"

**Resten per implementar:**

* Pantalla "Tràmits"
* Fitxa "Control d'accés"
* Fitxa "històric"
* Pantalla "Propietats" de versió de tràmit
* Pantalla "Dominis empleats" de versió de tràmit
* Pantalla "Cal Saber" de versió de tràmit
* Pantalla pas "Omplir formulari" de versió de tràmit
* Pantalla document formulari
* Pantalla de disseny de formulari
* Fitxa "Propietats del formulari"
* Pantalla pas "Annexar document"
* Pantalla document annex
* Pantalla pas "Pagar taxa"
* Pantalla document taxa
* Pantalla pas "Registrar formulari"

**Comment by jsastre-dgtic** [comment]
Ok, només dos descuits:

![image](https://user-images.githubusercontent.com/18436867/53563236-b23a4b80-3b53-11e9-8cb1-03496554a29d.png)

![image](https://user-images.githubusercontent.com/18436867/53563356-165d0f80-3b54-11e9-9204-95dbf6f0b16a.png)

**Comment by jsastre-dgtic** [comment]
1.- Havíem demanat substituir “Caché” per “Memòria cau”, no per “Cau” ...
![image](https://user-images.githubusercontent.com/18436867/53876760-cbd20c00-4007-11e9-8be7-fc88ec36858b.png)
![image](https://user-images.githubusercontent.com/18436867/53876864-063ba900-4008-11e9-98f0-131a828e2e60.png)

2.-Si trobau llarg "Memòria Cau per un botó, posau només "Refrescar"", però Cau no té sentit tot sol.
![image](https://user-images.githubusercontent.com/18436867/53876811-ea380780-4007-11e9-8c4c-2b4d99a8057b.png)

**Comment by jsastre-dgtic** [comment]
No trobam l'ajuda de: 
b. Ficha de Control de acceso
A "e. Dominios":
![image](https://user-images.githubusercontent.com/18436867/53878680-cc20d600-400c-11e9-9459-4bded8e13ecd.png)

Al Cal Saber, manca el botó d'ajuda en mode consulta:
![image](https://user-images.githubusercontent.com/18436867/53878827-29b52280-400d-11e9-9ccd-52850d373f20.png)

![image](https://user-images.githubusercontent.com/18436867/53878812-1dc96080-400d-11e9-99d3-1fef22bcd186.png)

A j. Pantalla de documento anexo no hi trobam l'ajuda.

**Comment by jsastre-dgtic** [comment]
Comentaris a la resta d'ajudes que hem vist:
[comentaris_ajudes.pdf](https://github.com/GovernIB/sistra2/files/2936195/comentaris_ajudes.pdf)

**Comment by rsanz-indra** [comment]
Respecto a la tarea de poder acceder a las propiedades del trámite del catálogo de procedimientos a través del plugin de sesión quedaría adaptar la ayuda del plugin en el STG

**Comment by jsastre-dgtic** [comment]
Segueix incorrecte l'Ajuda:
![image](https://user-images.githubusercontent.com/18436867/54263881-28867700-4572-11e9-8b26-a4ab0034aeb9.png)
![image](https://user-images.githubusercontent.com/18436867/54263884-2d4b2b00-4572-11e9-932b-9cf99d1a3fa0.png)

**Comment by jsastre-dgtic** [comment]
Dominis Àrea:
![image](https://user-images.githubusercontent.com/18436867/54264347-2670e800-4573-11e9-928c-0704e1b558d3.png)

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/54599450-f629bd80-4a3a-11e9-858d-20e891b9a7bd.png)

**Comment by jsastre-dgtic** [comment]
Tot comprovat
