### ISSUE TITLE
STH: Anàlisi funcional de pantalles 

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#9]
Definir document d'anàlisi funcional amb els mockups de les pantalles del mòdul de HelpDesk. En concret es definiran els següents mockups de pantalla:
- Auditoria d'esdeveniments.
- Pèrdua  de clau de tramitació.
- Informació sobre pagaments.
- Informació de persistència.

**Comment by amaciam-indra** [comment]
S'han afegit els mockups de pantalles del STH al document de mockups. Aquesta versió està vinculada al commit 8b9cdf47a881de17cddd74b16da22af18da2f584

**Comment by rsanz-indra** [comment]
Queda pendiente revisión con DGDT de los mockups.

**Comment by sgelabert-dgtic** [comment]
Comentaris sobre la revisió del document de mockups:
- Avaluar la comoditat de les pestanyes en front del menú. 
L'accés al Helpdesk és molt freqüent i a priori no es preveuen un increment del número d'opcions. En qualsevol cas, no ho consideram imprescindible. Si complica i acursa el temps de desenvolupament, ho deixam estar.   
- En general no queden clars els camps obligatoris dels filtres. Cal revisar el document i marcar els camps obligatoris.
- En general trobam a faltar la "data/hora fi"  en les pàg 44, 46, 47 i 48 del document
- Pàg. 45, 48 : ens interessa poder exportar el resultat de la recerca a csv. Ho veiem útil en les pantalles d'esdeveniment (pàg.45) i la de detall de pagament (pàg. 48).  
- Pàg. 46: A la pantalla "Pèrdua clau tramitació" sabem de quin tràmit ens parlen sempre? Si no ho sabem, no sabrem el formulari associat... Quan es diu "qualsevol camp del formulari" vol dir que els filtres són dinàmics segons el tràmit que cerquem?
- Es decideix mantenir la clau de tramitació per als tràmits amb accés anònim amb persistència (cas Serveis Administratius no autenticats)
