### ISSUE TITLE
STT: Anàlisi convivència SISTRA1 i SISTRA2

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#90]

**Comment by rsanz-indra** [comment]
Se ha realizado documento estimación para la integración entre Carpeta ciudadana y Sistra1

**Comment by jsastre-dgtic** [comment]
I on és el document?

**Comment by jsastre-dgtic** [comment]
Pendents de que ens enviïn (de nou) un correu amb el doc....
