### ISSUE TITLE
STT: Anàlisi adaptació procés registre i lliurament presencial

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#91]

**Comment by jsastre-dgtic** [comment]
1.-  Quan s’ha registrat convendria llevar el literal Atenció i posar-hi la frase en la mateixa mida de l’”Atenció” de “S’ha realitzat el registre correctament”
![image](https://user-images.githubusercontent.com/18436867/64103440-8dc56300-cd72-11e9-9d7e-276a5e09a4b7.png)

2.- Acceptar hauria d’anar a mà reta sempre...

![image](https://user-images.githubusercontent.com/18436867/64103411-7b4b2980-cd72-11e9-8505-77e28db5725c.png)

**Comment by rsanz-indra** [comment]
Se pasan mejoras de presentación a la tarea del rediseño (#131).
El análisis como tal de la adaptación se puede dar como finalizado.

**Comment by jsastre-dgtic** [comment]
Mantenim oberta la tasca com a referència a :
https://github.com/GovernIB/sistra2/issues/91#issuecomment-531181824
